Smart Contract development with thirdweb
LiskHQ/lisk-docs pull request #108
Opened 2024-04-03 16:12 UTC by TalhaMaliktz

### What was the problem?

This PR resolves #44 & #103

2024-04-04 12:06 UTC, Tschakki requested changes

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Build](https://portal.thirdweb.com/contracts/build/overview): Write custom smart contracts.
```suggestion
- [Build (Solidity SDK)](https://portal.thirdweb.com/contracts/build/overview): Write custom smart contracts.
```

Would add this to inform that the build feature is actually the Solidity SDK, as we mention it in the title below.

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +## via thirdweb Explore
```suggestion
## Deploying pre-built contracts via thirdweb Explore
```

As the guide is about deploying smart contracts in general, I think we should mention that is option is only for pre-built contracts

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +thirdweb provides an excellent tutorial on the following:
```suggestion
In case you want to deploy a pre-built contract without any customization, thirdweb offers a convenient way to do so with **Explore**.
Check out the following video for a quick introduction into Explore:
```

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +### Deploying pre-built contracts via Explore
```suggestion
### Deploying pre-built contracts via Explore

The following videos describe step-by-step, how to deploy different tokens with pre-built contracts on Lisk.
```

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +### Interacting with deployed contracts via Explore
```suggestion
### Interacting with deployed contracts via Explore

The following videos describe step-by-step, how to interact with different token contracts on Lisk.
```

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +### Deploying pre-built contracts via Explore
Please add notes for things people need to adjust for deploying the contract successfully on Lisk Sepolia.

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +## Creating a project
```suggestion
### Creating a project
```

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +2. To install thirdweb run the following command:
```suggestion
### Prerequisites
#### Node.js v18+

Download and install [Node v18+](https://nodejs.org/en/download/).

If you are using nvm to manage your node versions, you can just run `nvm install 18`.

#### Installing and Configuring thirdweb

To develop custom contracts, it is required to download and configure thirdweb.

1. To install thirdweb run the following command:
```

Please adjust th eother bullet points accordingly

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +The project creation steps are similar for both Foundry and Hardhat.
If there are only a few differences between Foundry and Hardhat as mentioned here, maybe we can add notes, about what would be different if Hardhat is used, where it fits the context?

2024-04-04 12:06 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Once the contract is deployed, you can interact with it as explained in the [Interacting with deployed contracts via Explore](#interacting-with-deployed-contracts-via-explore) section.
If process for both is the same, please move the interact content from Explore section here, and remove the content form Explore section.

2024-04-08 14:41 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +## Creating a project
Since Creating a project is a bigger category as compared to creating a smart contract, it should stay as an L2 heading.

2024-04-09 08:52 UTC, Tschakki requested changes
Looking good already, just some small remarks :)

2024-04-09 08:52 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +## Creating a project
As far as I see, this is part of `via Solidity SDK` section, so it should be lower level

2024-04-09 08:52 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +### Deploying pre-built contracts via Explore
```suggestion
```

Very similar to the parent section name, would remove

2024-04-09 17:14 UTC, Tschakki approved these changes
LGTM 🎉

2024-04-10 09:51 UTC, merged