Add new page: Data Indexer
LiskHQ/lisk-docs pull request #111
Opened 2024-04-04 10:51 UTC by TalhaMaliktz

### What was the problem?

This PR resolves #28

2024-04-04 12:20 UTC, Tschakki requested changes

2024-04-04 12:20 UTC, Tschakki commented on docs/lisk-tools/indexers.md
> +    "smart contract development"
keywords do not fit the content

2024-04-08 07:46 UTC, TalhaMaliktz commented on docs/lisk-tools/indexers.md
> +    "smart contract development"
```suggestion
    "indexers",
    "data indexers",
    "Lisk",
    "Lisk test network",
    "Lisk testnet",
    "Goldsky",
    "Solidity",
    "Mirror",
    "Subgraph"
```

2024-04-09 06:22 UTC, Tschakki approved these changes
LGTM!

2024-04-09 17:14 UTC, merged