Add Governance page
LiskHQ/lisk-docs pull request #118
Opened 2024-04-23 13:36 UTC by Tschakki

### What was the problem?

This PR resolves #117 

### How was it tested?

https://liskhq.github.io/lisk-documentation/governance

2024-04-25 12:36 UTC, AndreasKendziorra requested changes

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +At the moment, the security of the Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) m
> individuals of the Onchain Foundation

Jan and Shu are also members of the group but do not belong to the Foundation.

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +  The [Lisk Governance Forum](https://forum.lisk.com/) is the place for the community to discuss the Lisk gonvernance and draft proposals, before they are submitted on Tally.
```suggestion
  The [Lisk Governance Forum](https://forum.lisk.com/) is the place for the community to discuss the Lisk governance and draft proposals, before they are submitted on Tally.
```

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +  The `#lisk-dao` channel in the [Lisk Chat](https://lisk.chat) Discord server is a comunity chat dedicated to discuss topics all around the Lisk DAO, share news and updates, or share ideas for new p
```suggestion
  The `#lisk-dao` channel in the [Lisk Chat](https://lisk.chat) Discord server is a community chat dedicated to discuss topics all around the Lisk DAO, share news and updates, or share ideas for new proposals.
```

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +The Lisk DAO has an associated treasury, which resides in the [TimeLock contract](https://sepolia-blockscout.lisk.com/address/0x4b727D3f74DD4c124Ced030335DebD5e7EBB8366).
```suggestion
The Lisk DAO has an associated treasury, which resides in the [TimelockController contract](https://sepolia-blockscout.lisk.com/address/0x4b727D3f74DD4c124Ced030335DebD5e7EBB8366).
```

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +In short, users get rewards for locking/staking tokens for governance participation.
this might be a bit confusing for readers as it wasn't explained yet that one actually has to stake to participate. I would propose to move the _staking rewards_ section to after _Delegation_ or _Administrative role of the Onchain Foundation_.

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +- Users can modify their locking positions (increase amount, pause locking duration) at any time they want.
they can also extend the duration

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +Note that this results in **higher staking rewards**, since the weight remains fixed, as opposed to a weight daily decreasing when the countdown is active.
> opposed to a weight daily decreasing

it was not clearly explained before that the weight is decreasing. This could be done by changing line 77 to:

> The further the end of the locking duration is in the future, the more rewards they get. This also implies that the rewards decrease every day.

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +{/* TODO: Add Blockscout link to address of the Staking contract */}
the address of the Reward contract might be more meaningful in this case

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +Rewards are taken from the balance of the `Staking` constract and calculated on a daily basis, based on the amount locked and the remaining locking duration.
```suggestion
Rewards are taken from the balance of the `Reward` contract and calculated on a daily basis, based on the amount locked and the remaining locking duration.
```

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +- **Proposal threshold**: For creating a proposal, the voting power of the proposer must be at least 300,000 vpLSK, i.e., the value corresponding to 100,000 LSK locked for 2 years where the countdown
this may also not be completely clear without reading the "voting power" section before. I would propose to move the "Proposals" section to after "Delegation" (but before "Staking rewards" as this one is the least important one on this page in my opinion).

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +But this requires custom integration from Tally.
It's good to have this information on confluence for us internally, but not for the public. I would therefore remove this section.

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +#### Boosting the voting power
I would make it a subsection of "Voting power calculation"

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +### Staking rewards
capitalization of headers is not consistent in this document. E.g., we have "Proposal Evaluation" below.

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +#### Voting power calculation:
```suggestion
#### Voting power calculation
```

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +### Capture resistance
I'm not sure I would keep this section as we do not really achieve it.

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +1. onchain governance processes to upgrade Lisk contracts and tune the economic parameters of the system, and
> onchain governance processes to upgrade Lisk contracts and tune the economic parameters of the system

This might be misleading. We do have onchain voting for it, but in a binding way. For instance, we could have a proposal to upgrade the staking contract to a new version. But the proposal would not be binding the founndation could ignore it.

2024-04-25 12:36 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +### Iteration
Is it really the idea to reduce the role of the foundation over time? I'm not sure what's the plan, but I also never heard that this is the goal.

2024-04-25 14:42 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +Rewards are taken from the balance of the `Staking` constract and calculated on a daily basis, based on the amount locked and the remaining locking duration.
Was this renamed? It is mentioned as Staking contract [here](https://onchaincollective.atlassian.net/wiki/spaces/Lisk/pages/84574238/Specification+of+the+Lisk+DAO+Contracts)

2024-04-25 14:44 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +At the moment, the security of the Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) m
Should we mention the Security council instead? If yes, do you have a good explanation how to explain it to the public?

2024-04-25 14:49 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +{/* TODO: Add Blockscout link to address of the Staking contract */}
what is the reward contract? it dont see it in the DAO contract specs

2024-04-25 14:54 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +### Capture resistance
Currently not, but wouldn't this be a goal we want to achieve, even if it is in far future?

2024-04-25 15:01 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +1. onchain governance processes to upgrade Lisk contracts and tune the economic parameters of the system, and
True. I tried to formulate it clearer, please check.

2024-04-25 15:05 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +### Iteration
I took this from the OP governance design principles. I am also not fully aware if this is a design principle we have for the Lisk DAO, but imho this should be a goal for every DAO to become more decentralized over time.
Who should we ask to clarify this ?

2024-04-27 04:30 UTC, TalhaMaliktz requested changes
Looking good already! Just minor remarks

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +Every LSK token holder who participates in the DAO is rewared with [staking rewards](#staking-rewards), to incentivize participation in the Lisk governance.
```suggestion
Every LSK token holder who participates in the DAO is rewarded with [staking rewards](#staking-rewards), to incentivize participation in the Lisk governance.
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +  The [Lisk DAO Tally instance](https://www.tally.xyz/gov/3rd-testing) is the place where users can vote on proposals or delegate their voting power.
What is 3rd-testing?

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +Delegation happens on [Tally](#tally).
Hyperlink doesn't work!

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +Proposals are created on [Tally](#tally).
Hyperlink doesn't work!

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +Funding proposals are **binding**, which means that no-one, not even the Onchain Foundation, can prevent the transfer, if the proposal passed.
```suggestion
Funding proposals are **binding**, which means that no one, not even the Onchain Foundation, can prevent the transfer if the proposal passes.
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +Staking rewards incentivize users to participate in governance, making the decision making more decentralized and community-driven.
```suggestion
Staking rewards incentivizes users to participate in governance, making the decision-making more decentralized and community-driven.  
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +Rewards are taken from the balance of the `Staking` constract and calculated on a daily basis, based on the amount locked and the remaining locking duration.
```suggestion
Rewards are taken from the balance of the `Staking` contract and calculated daily, based on the amount locked and the remaining locking duration.
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +3. the profit of the Onchain Foundation from sequencing rewards.
```suggestion
1. The unclaimed LSK tokens (such tokens will be moved to the Lisk DAO treasury after the 2-year claim window).
2. The staking rewards of the Onchain Foundation, which would be provided to the ecosystem.
3. The profit of the Onchain Foundation from sequencing rewards. 
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +There are two primary goals of Lisks governance system:
```suggestion
There are two primary goals of the Lisk's governance system:
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +This isn’t just about vibes: in crypto, where credible commitments not to extract are what makes decentralized platforms valuable, this is a competitive advantage.
I don't understand the statement, maybe re-word it?

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +| 2026 | 15,000,000 | LSK are linearly released over the year. |
```suggestion
| 2025 | 15,000,000 | LSKs are linearly released over the year. |
| 2026 | 15,000,000 | LSKs are linearly released over the year. |
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +The DAO fund may be increased further in the future by additional 100,000,000 LSK over the following 7 years, if the DAO members approve the corresponding proposals.
```suggestion
The DAO fund may be increased further in the future by an additional 100,000,000 LSK over the following 7 years if the DAO members approve the corresponding proposals.
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +But it is possible to [boost the voting power](#boosting-the-voting-power) by up to 200% where the boost is proportional to remaining locking duration.
```suggestion
But it is possible to [boost the voting power](#boosting-the-voting-power) by up to 200% where the boost is proportional to the remaining locking duration.
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +The Governor framework requires to **delegate the voting power** in order to use it.
```suggestion
The Governor framework requires **delegating the voting power** in order to use it.
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +  - Gain reputation by being a delegate.
```suggestion
  - Gain a reputation by being a delegate.
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +After the end of this 3 year span, we expect that developments in the Optimism Superchain Ecosystem (shared, decentralized sequencers)  would lead us to a new staking mechanism.
```suggestion
After the end of this 3-year span, we expect that developments in the Optimism Superchain Ecosystem (shared, decentralized sequencers) will lead us to a new staking mechanism.
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +Design decisions for Lisks governance system should be made in line with three key principles:
```suggestion
Design decisions for Lisk's governance system should be made in line with three key principles:
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +Lisk is decentralizing iteratively to increase the chances of building a healthy system that lasts for the long-term.
```suggestion
Lisk is decentralizing iteratively to increase the chances of building a healthy system that lasts for the long term.
```

2024-04-27 04:30 UTC, TalhaMaliktz commented on docs/about-lisk/governance.mdx
> +This means the Foundation will play a role in establishing processes, help the DAO through its first few rapid feedback loops in improving those processes, then reduce its role over time.
```suggestion
This means the Foundation will play a role in establishing processes, help the DAO through its first few rapid feedback loops in improving those processes, and then reduce its role over time.
```

2024-04-29 09:14 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +  The [Lisk DAO Tally instance](https://www.tally.xyz/gov/3rd-testing) is the place where users can vote on proposals or delegate their voting power.
its a Tally instance Matjaz set up for testing. I added a TODO to update it with the link of the final Tally instance, once we have it

2024-04-29 09:49 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +3. the profit of the Onchain Foundation from sequencing rewards.
```suggestion
1. Unclaimed LSK tokens 
2. The staking rewards of the Onchain Foundation, which would be provided to the ecosystem and
3. The profit of the Onchain Foundation from sequencing rewards. 
```

2024-04-29 09:50 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +There are two primary goals of Lisks governance system:
adding `the` sounds wrong here

2024-04-29 09:53 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +This isn’t just about vibes: in crypto, where credible commitments not to extract are what makes decentralized platforms valuable, this is a competitive advantage.
Agree it sounds a little confusing, I removed the line

2024-04-29 09:53 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +This isn’t just about vibes: in crypto, where credible commitments not to extract are what makes decentralized platforms valuable, this is a competitive advantage.
```suggestion
```

2024-04-29 09:55 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +| 2026 | 15,000,000 | LSK are linearly released over the year. |
It is both LSK singular and plural

2024-04-29 09:57 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +Staking rewards incentivize users to participate in governance, making the decision making more decentralized and community-driven.
rewards are plural

2024-04-29 12:00 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +{/* TODO: Add Blockscout link to address of the Staking contract */}
this reminds me that I must update the confluence page. Sorry for this, I will do it very soon.
The staking functionality was eventually split into 3 different contracts: `LockingPositionContract`, `StakingContract` and `RewardContract`. Some up-to-date diagrams can be see here: https://github.com/LiskHQ/lisk-contracts-private/blob/main/documentation/staking-governance.md#contracts-overview
But for this documentation of the governance system, I would avoid explaining the separation of the different staking contracts. So, it might be fine if you just talk about the rewards contract without any further explanation. Otherwise, you could link to 
- the [implementation](https://github.com/LiskHQ/lisk-contracts-private/blob/main/src/L2/L2Reward.sol),
- the staking docs if there should be some, or
- [this section](https://github.com/LiskHQ/lisk-contracts-private/blob/1ef369eea1d0fe3554a9263bf60c6619f630c0ca/documentation/staking.md#l2reward-contract) from the documentation inside the contracts repository. This PR is, however, not merged yet.

2024-04-29 12:01 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +Rewards are taken from the balance of the `Staking` constract and calculated on a daily basis, based on the amount locked and the remaining locking duration.
yes, sorry. See my [answer from above](https://github.com/LiskHQ/lisk-documentation/pull/118#discussion_r1582977129).

2024-04-29 12:06 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +### Staking rewards
For headers of level 2 (`Governance Goals` and `Design Principles`), you still use capitalization. Is this intended?

2024-04-29 12:19 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +1. onchain governance processes([binding](#implementation-of-funding-proposals) and non-binding) to upgrade Lisk contracts or allocate funds, and
```suggestion
1. onchain governance processes ([binding](#implementation-of-funding-proposals) and non-binding) to upgrade Lisk contracts or allocate funds, and
```

2024-04-29 12:19 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +1. onchain governance processes to upgrade Lisk contracts and tune the economic parameters of the system, and
sounds good to me

2024-04-29 13:49 UTC, AndreasKendziorra requested changes

2024-04-29 13:49 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
>  To enable voting power proportional to the promised locking duration, users have the option to pause the countdown of the locking period.
> To enable voting power proportional to the promised locking duration

I would remove this part as the current version does not give any hint anymore that we ever aimed for linearly decreasing voting power.

2024-04-29 13:57 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +### Staking rewards
Yes, imho it looks nicer. What do you think?

2024-04-29 14:07 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +Delegation happens on [Tally](#tally).
fixed it

2024-04-29 14:41 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +At the moment, the security of the Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) m
@AndreasKendziorra I updated the section according to Jans feedback!

2024-04-29 16:03 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +{/* TODO: Add Blockscout link to address of the Staking contract */}
> the staking docs if there should be some

Why not link to [this section](https://github.com/LiskHQ/lisk-contracts-private/blob/main/documentation/staking-governance.md#contracts-overview)? Assuming we will make it public soon.

2024-04-30 07:10 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +At the moment, the security of the Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) m
should we rather use "key members" instead of "individuals" as Jan proposed? The current way sounds a bit like arbitrary community members are involved, and then readers might wonder how they could get a chance to become a member.

2024-04-30 07:15 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +{/* TODO: Add Blockscout link to address of the Staking contract */}
you could also link to this one if you prefer

2024-04-30 07:16 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +{/* TODO: Add Blockscout link to address of the Staking contract */}
I see that you did it already

2024-04-30 07:20 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +### Staking rewards
I think it's common to use capitalization for headers. Not only for certain levels, but for all. So, I would apply it to all headers. But I don't know how you handle it in general in the repository. Consistency over the repository is more important I would say.

2024-04-30 07:55 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +### Staking rewards
OK, I adjusted it now to lower case, as this is used currently in most cases.

2024-05-02 12:39 UTC, AndreasKendziorra requested changes

2024-05-02 12:39 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +Every account holding **LSK** is able **stake/lock** a specific amount of LSK tokens to get some voting power and [staking rewards](#staking-rewards).
```suggestion
Every account holding **LSK** is able to **stake/lock** a specific amount of LSK tokens to get some voting power and [staking rewards](#staking-rewards).
```

2024-05-02 12:39 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +Delegation is a key feature of the Lisk DAO, as it allows token holders to participate in the governance of the Lisk project passively by entrusting a representative to vote on proposals in a way tha
I think it must be "entrusting a representative with voting on ..."

2024-05-02 12:39 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +By delegating their voting power to a delegate of their choice, token holders can ensure that their interests are represented in the decision-making process.
> token holders can ensure that their interests are represented

This must not necessarily be true as the delegate may vote against the interest of the delegater. You could change the wording "ensure" to something softer (I don't have a good proposal that is short) or just remove the sentence.

2024-05-02 12:39 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +This is why it is important to choose a delegate that you trust and that you believe will act in the best interest of the Lisk project and the community.
> This is why

Due to this formulation, I would not start a new paragraph here. Up to you.

2024-05-02 12:39 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +2. Select the "delegate" button.
What's missing is that one must first go to the  "my voting power" page to see the "delegate" button. And then after selecting "Someone else", one must click on the slightly hidden button "Explore all Delegates" to see the overview. Therefore, we may just provide the link to the "delegates" page directly. Which is `https://www.tally.xyz/gov/<DAO name>/delegates`

2024-05-02 12:39 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +You can also proportionally delegate your voting power to multiple delegates.
No. This is not possible.

2024-05-02 12:39 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +  - Create proposals
I would remove "create proposal" as this sounds like it expected from every delegate which is not the case.

2024-05-02 12:39 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +  - Give feedback on other draft proposals
Also for this one I'm not sure we should formulate it as a requirement. Average delegates may be able to make well-informed voting decision for most proposal. But providing feedback on draft proposals is much harder and may only make sense in some cases.

2024-05-02 12:39 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +Basically anyone who owns some LSK tokens can become a delegate.
I find it a bit misleading, because one can also become a delegate without having any LSK or voting power.

2024-05-02 13:17 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +By delegating their voting power to a delegate of their choice, token holders can ensure that their interests are represented in the decision-making process.
replaced it with "influence" now

2024-05-02 13:32 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +You can also proportionally delegate your voting power to multiple delegates.
oh you are right. It was described like this in the Arbitrum docs. Maybe Tally had this feature in the past?

2024-05-02 13:38 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +  - Give feedback on other draft proposals
i added a new paragraph below

2024-05-02 13:40 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +Basically anyone who owns some LSK tokens can become a delegate.
rephrased it, please check

2024-05-03 09:38 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +You can also proportionally delegate your voting power to multiple delegates.
I don't think that Tally ever had this feature, because the underlying contracts do not allow it.

2024-05-03 09:56 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +Basically anyone who owns some LSK tokens can become a delegate.
I would shorten lines 89-95 to the following:

> Basically anyone can become a delegate. There are various ways to do this:

Reasons:
- self-delegation is not a requirement for becoming a delegate.
- reaching the proposal threshold is not the only (and probably also not the main) motivation to become a delegate

2024-05-03 10:26 UTC, AndreasKendziorra requested changes

2024-05-03 10:26 UTC, AndreasKendziorra commented on docs/governance/overview.mdx
> +# Governance Overview
```suggestion
# Governance overview
```

2024-05-03 10:26 UTC, AndreasKendziorra commented on docs/governance/overview.mdx
> +- Receive voting power and staking rewards proportional to the amount of locked tokens.
1. "Delegate the staked tokens" --> "Delegate the voting power"
2. I would swap the two points as other wise one might think that delegation is a requirement for rewards. Or I would even remove the delegation step as delegation is not a requirement for receiving voting power. it is only a requirement for receiving delegated voting which in turn is required for voting and creating proposal. But this is also explained in the "Delegation" section.

2024-05-03 10:26 UTC, AndreasKendziorra commented on docs/intro.md
> +For more information, check out the [Governance](/governance/overview)
"check out the Governance" --> "check out the Governance overview" or "check out the Governance page"?

Also the "." is missing at the end of the sentence.

2024-05-03 10:51 UTC, Tschakki commented on docs/governance/overview.mdx
> +- Receive voting power and staking rewards proportional to the amount of locked tokens.
I am not sure about that.
I think if you stake tokens without delegating them, you will have 0 vpLSK displayed on Tally. Only if you delegate them, you, or the user you are delegating to will have the voting power.
To say they have voting power right after staking might be misleading. Also, we really want all people to delegate after staking, this is what they are getting rewards for, at least intentionally

2024-05-03 11:35 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +Basically anyone who owns some LSK tokens can become a delegate.
I would disagree here.
First, is it a realistic/common scenario for people who have no own LSK to be delegate? I mean, I don't see how it is realistic for them to receive delegations from others. Why would I trust someone who doesn't have own stakes in the project? Additionally, I don't see any good motivation for someone not holding LSK to be in the DAO.
So yes, in fact I think the first logical step for every delegate is to stake and self-selegate their voting power. And then, depending ont heir motivations, they can decide to advocate for delegations from other users.

2024-05-03 11:57 UTC, AndreasKendziorra commented on docs/governance/overview.mdx
> +- Receive voting power and staking rewards proportional to the amount of locked tokens.
> I think if you stake tokens without delegating them, you will have 0 vpLSK displayed on Tally. Only if you delegate them, you, or the user you are delegating to will have the voting power.

It's true that Tally is not showing it, but it's common to call it "voting power" before delegation. This is also done in the docs of [Tally](https://docs.tally.xyz/knowledge-base/delegations-on-tally/delegating-voting-power) ("delegate your voting power") and in [OpenZeppelin's Governor docs](https://docs.openzeppelin.com/contracts/5.x/governance#cast_a_vote) ("by self-delegating their voting power").
And one cannot delegate staked tokens. Because when you stake LSK tokens, one receives some vpLSK tokens which come from a different ERC20 contract, the "Voting Power" contract. And you can only delegate the vpLSK tokens but not the LSK tokens (or a locking position or anything else that we have in the staking contracts).

> Also, we really want all people to delegate after staking, this is what they are getting rewards for, at least intentionally

I agree with the goal. But with the current order one might get the impression that delegation is a requirement for receiving rewards, which is not true.

2024-05-03 11:57 UTC, AndreasKendziorra reviewed
No new comments. I only replied to open comments.

2024-05-03 12:12 UTC, AndreasKendziorra commented on docs/about-lisk/governance.mdx
> +Basically anyone who owns some LSK tokens can become a delegate.
It's probably not very common, but it exists. [L2beat](https://www.tally.xyz/gov/arbitrum/delegate/l2beatcom.eth), for instance, has no ARB tokens but is one of the largest delegates in Arbitrum.
So, for some entities, it might be obvious that they vote for the best interest of the project without staking and therefore users may choose them as a delegate. This could, for example, also be some projects deploying on Lisk.

And even if L2Beat on Arbitrum is the only exception, I would not write something that is technically misleading.

2024-05-03 15:05 UTC, Tschakki commented on docs/about-lisk/governance.mdx
> +Basically anyone who owns some LSK tokens can become a delegate.
I adjusted the section, please check :)

2024-05-03 15:06 UTC, Tschakki commented on docs/governance/overview.mdx
> +- Receive voting power and staking rewards proportional to the amount of locked tokens.
I moved the delegate point below, so it shouldn't give the impression anymore that it is a requirement :)

2024-05-06 07:12 UTC, AndreasKendziorra approved these changes

2024-05-07 08:36 UTC, TalhaMaliktz commented on docs/governance/delegation.md
> +We recommend to choose a delegate that is active in the community, has a good reputation, and has a track record of making good decisions.
```suggestion
We recommend choosing a delegate who is active in the community, has a good reputation, and has a track record of making good decisions.
```

2024-05-07 08:36 UTC, TalhaMaliktz commented on docs/governance/delegation.md
> +- **Lisk DAO Tally instance**: Check the delegate's profile, voting history and activity on the Lisk DAO Tally instance.
```suggestion
- **Lisk DAO Tally instance**: Check the delegate's profile, voting history, and activity on the Lisk DAO Tally instance.
```

2024-05-07 08:36 UTC, TalhaMaliktz commented on docs/governance/delegation.md
> +- Engage activly with the Lisk community online and/or offline
```suggestion
- Engage actively with the Lisk community online and/or offline
```

2024-05-07 08:36 UTC, TalhaMaliktz commented on docs/governance/delegation.md
> +Basically anyone who is able to accumulate some voting power can become a delegate.
```suggestion
Anyone who can accumulate some voting power can become a delegate.
```

2024-05-07 08:36 UTC, TalhaMaliktz commented on docs/governance/delegation.md
> +If you wish to increase your voting power to be able to create your own proposals and/or to have more influence on votings, it is possible to get delegations from other users.
```suggestion
If you wish to increase your voting power to be able to create your own proposals and/or to have more influence on voting, it is possible to get delegations from other users.
```

2024-05-07 10:46 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2024-05-07 11:14 UTC, merged