Add proposal lifecycle
LiskHQ/lisk-docs pull request #121
Opened 2024-05-07 12:45 UTC by Tschakki

### What was the problem?

This PR resolves #119 
### How was it tested?

https://liskhq.github.io/lisk-documentation/governance/proposal-lifecycle

2024-05-08 06:51 UTC, matjazv requested changes

2024-05-08 06:51 UTC, matjazv commented on docs/governance/proposal-lifecycle.mdx
> +3. [Voting & Results](#3-voting--results)
```suggestion
3. [Voting & results](#3-voting--results)
```

2024-05-08 06:51 UTC, matjazv commented on docs/governance/proposal-lifecycle.mdx
> +3. [Voting & Results](#3-voting--results)
Below, where section 3. starts `results` is written in lower case.

2024-05-08 06:51 UTC, matjazv commented on docs/governance/proposal-lifecycle.mdx
> +- **Proposal threshold**: 300,000 vpLSK are required to create new proposals.
If account doesn't have enough voting power, it's possible to find a sponsor.
This is mentioned when you're creating a new proposal and don't have enough voting power.

```
You won't be able to submit this proposal onchain. You can still save your proposal
as a draft and share it with a sponsor.

Find a sponsor
```

Should this be mentioned here?

2024-05-08 08:19 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +- **Proposal threshold**: 300,000 vpLSK are required to create new proposals.
good point, will add it! Have you tried this feature already?

2024-05-08 08:29 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +- **Proposal threshold**: 300,000 vpLSK are required to create new proposals.
i tested it, it just opens the delegates page

2024-05-08 08:31 UTC, matjazv commented on docs/governance/proposal-lifecycle.mdx
> +- **Proposal threshold**: 300,000 vpLSK are required to create new proposals.
Yes, I think opening a delegates page is action here. So user may get it touch with some of delegates to get a sponsor.

2024-05-08 09:15 UTC, matjazv approved these changes

2024-05-13 20:41 UTC, AndreasKendziorra requested changes

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +Ideas for proposals can be discussed in the `#lisk-dao` channel on [Lisk Chat](https://lisk.chat) or on a new discussion thread on the [Governance Forum](https://forum.lisk.com).
I assume the link to lisk.chat will also be updated once the the channel was created?

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +Please fill out the provided **template** when you open a new thread in above categories.
```suggestion
Please fill out the provided **template** when you open a new thread in the above categories.
```

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +- **Account on Tally**: You need to be a registered delegate on the Lisk DAO Tally instance.
I would remove this line because it is more or less implied by the proposal threshold and because of the following reasons:

> need to be a registered delegate

it's technically correct as self-delegation is a requirement if one wants to vote themselves. But not because this is conceptually nice (the opposite is the case), but because the ERC20Votes contracts are more gas efficient this way when it comes to transfer transactions. The current formulation may distract users who just want to participate in the DAO without receiving delegations from others, as it could be interpreted like a burden.

> on the Lisk DAO Tally instance

I find it a bit misleading, because Tally is just a front-end. Technically, delegation happens in the contracts. And users could actually choose different font-ends to interact with our contracts.

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +- **Proposal threshold**: 300,000 vpLSK are required to create new proposals.
1. I would emphasize that this is about delegated voting power. For example: "Your delegated voting power must be at least 300,000 vpLSK." (I admit that my formulation on Confluence was also not precise enough; I fixed it now)
2. I would remove "to create new proposals" as it was already said in line 48.

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +- **Discussion time**: Minimum 2 weeks of discussion in the governance forum.
I would also remove this one as it was already said in line 40 and because we are mixing "hard" rules with "soft" rules.

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +If you don't have enough voting power, you can still create the proposal as a draft on Tally and ask a delegate to submit it.
> you can still create the proposal as a draft on Tally and ask a delegate to submit it

I think that's not possible. But one can ask in the forum if a delegate is willing to submit a proposal from the forum to Tally.

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +To get an overview about the existing delegates and their voting power, you can check the Delegates page on the Lisk DAO Tally instance.
Due to my comment for line 55, it may make more sense to check the delegate threads in the forum.

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +If all requirements are met, anyone who considers the proposal mature enough, can create a proposal on Tally:
Suggestion: "Anyone who considers the proposal mature enough and who fulfills the requirements from above, can create a proposal on Tally:"

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +2. At the bottom, add the following line to the proposal:
We agreed somewhere on slack to not enforce it as it may distract some users and it's also not very common. I would therefore add to the beginning: "Optional to prevent frontrunning:"

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +- **Quorum**: For a proposal to pass, the “yes” and “abstain” votes must sum up at least to **24,000,000 vpLSK**, i.e., the value that corresponds to 8,000,000 LSK locked for 2 years where the countd
```suggestion
- **Quorum**: For a proposal to pass, the “yes” and “abstain” votes must sum up to at least  **24,000,000 vpLSK**, i.e., the value that corresponds to 8,000,000 LSK locked for 2 years where the countdown is paused.
```

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +- **Quorum**: For a proposal to pass, the “yes” and “abstain” votes must sum up at least to **24,000,000 vpLSK**, i.e., the value that corresponds to 8,000,000 LSK locked for 2 years where the countd
> i.e., the value that corresponds to 8,000,000 LSK locked for 2 years where the countdown is paused.

I would remove this part. It was important for our internal calculations, but not for the public.

2024-05-13 20:41 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +- **Majority**: There must be strictly **more “yes” than “no”** votes.
after this line I would continue describing the following:

- what happens when a proposal passed
  - proposal with actions (binding proposal): one must first queue the proposal in Tally and then execute the proposal. Anyone can do this, but each step requires a transaction.
  - proposal without actions (non-binding): Foundation will evaluate if they implement it or not 
- what happens when a proposal did not passed: nothing

2024-05-14 08:03 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +Ideas for proposals can be discussed in the `#lisk-dao` channel on [Lisk Chat](https://lisk.chat) or on a new discussion thread on the [Governance Forum](https://forum.lisk.com).
No, lisk chat link will stay as is

2024-05-14 08:09 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +- **Account on Tally**: You need to be a registered delegate on the Lisk DAO Tally instance.
> The current formulation may distract users who just want to participate in the DAO without receiving delegations from others, as it could be interpreted like a burden.

To be honest, I am not following what you are trying to say here. I am just mentioning that they need to register as delegate to create proposals. Not sure how this could be understood as a high burden.

> I find it a bit misleading, because Tally is just a front-end. Technically, delegation happens in the contracts. And users could actually choose different font-ends to interact with our contracts.

I don't agree here, because in this docs we are outlining the way we want DAO members to use the DAO. Even if technically they could use other frontends, or interact with the smart contracts directly, this is not what we intend them to do. If the easiest and the official process is to use Tally, we can communicate it like that.

2024-05-14 08:20 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +If you don't have enough voting power, you can still create the proposal as a draft on Tally and ask a delegate to submit it.
If you submit a draft proposal on Tally, you have the "Find a sponsor" button, which will take you to the delegates pages, so i am under the impression that this is a built-in feature on Tally. We should double check this

2024-05-14 08:25 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +- **Discussion time**: Minimum 2 weeks of discussion in the governance forum.
I am not sure I agree here. We are not mentioning here only the technical hard rules. We are explaining a process that we want people to follow. And as far as I understood, 2 weeks discussion before opening the proposal is part of the process.

2024-05-14 08:31 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +- **Majority**: There must be strictly **more “yes” than “no”** votes.
didn't you mention before that general proposals (those without action) can be binding too? I think it makes more sense to differentiate between general and funding here

2024-05-14 08:33 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +- **Majority**: There must be strictly **more “yes” than “no”** votes.
for this we have already sections in the governance overview page: https://liskhq.github.io/lisk-documentation/governance/overview#implementation-of-funding-proposals

2024-05-14 20:57 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +Ideas for proposals can be discussed in the `#lisk-dao` channel on [Lisk Chat](https://lisk.chat) or on a new discussion thread on the [Governance Forum](https://forum.lisk.com).
ok

2024-05-14 21:11 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +- **Account on Tally**: You need to be a registered delegate on the Lisk DAO Tally instance.
> To be honest, I am not following what you are trying to say here. I am just mentioning that they need to register as delegate to create proposals. Not sure how this could be understood as a high burden.

It's about the formulation "you need to be a registered delegate". Typically, a delegate is someone who is entrusted with something by others. And this can be seen as a burden.
The fact that self-delegation does not really imply this on Tally may not be obvious for everyone.

> I don't agree here, because in this docs we are outlining the way we want DAO members to use the DAO. Even if technically they could use other frontends, or interact with the smart contracts directly, this is not what we intend them to do. If the easiest and the official process is to use Tally, we can communicate it like that.

Would changing "Lisk DAO Tally instance" to "Lisk DAO" be an option?

2024-05-14 21:16 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +- **Discussion time**: Minimum 2 weeks of discussion in the governance forum.
I agree it's part of the process. But in my opinion, it should either be part of step 1 or of step 2, but not of both.

2024-05-14 21:29 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +- **Majority**: There must be strictly **more “yes” than “no”** votes.
> didn't you mention before that general proposals (those without action) can be binding too? I think it makes more sense to differentiate between general and funding here

general proposal can have actions but they don't need to. And in the beginning of the Lisk DAO, there will probably very few proposals with an action. And a proposal is binding if and only if it has an execution. This holds for any kind of proposal.

2024-05-14 21:34 UTC, AndreasKendziorra requested changes

2024-05-14 21:34 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +See also [Implementation of proposals](overview#implementation-of-funding-proposals).
it only links to implementation of funding proposal, not to the implementation of proposal in general. could this maybe be improved by moving the two subsection under a section "Implementation of proposals"?

2024-05-15 07:16 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +- **Account on Tally**: You need to be a registered delegate on the Lisk DAO Tally instance.
I have removed the line now

2024-05-15 07:19 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +- **Discussion time**: Minimum 2 weeks of discussion in the governance forum.
removed the line..

2024-05-15 07:36 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +See also [Implementation of proposals](overview#implementation-of-funding-proposals).
i am not in favor of this as there are alrwady too many subsection on the page. Also, the Implementation of general proposals is literally right below

2024-05-15 07:38 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +To get an overview about the existing delegates and their voting power, you can check the Delegates page on the Lisk DAO Tally instance.
i do not agree

2024-05-15 09:49 UTC, Tschakki commented on docs/governance/proposal-lifecycle.mdx
> +To get an overview about the existing delegates and their voting power, you can check the Delegates page on the Lisk DAO Tally instance.
Following our discussion, I added a new sentence below, mentioning the forum as alternative, to find a sponsor

2024-05-15 12:27 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +To get an overview about the existing delegates and their voting power, you can check the Delegates page on the Lisk DAO Tally instance.
sounds good to me

2024-05-15 12:28 UTC, AndreasKendziorra commented on docs/governance/proposal-lifecycle.mdx
> +See also [Implementation of proposals](overview#implementation-of-funding-proposals).
ok

2024-05-15 12:29 UTC, AndreasKendziorra approved these changes

2024-05-15 23:30 UTC, merged