Add Lisk Mainnet information
LiskHQ/lisk-docs pull request #122
Opened 2024-05-09 08:48 UTC by TalhaMaliktz

### What was the problem?

This PR resolves #89

2024-05-13 15:27 UTC, Tschakki requested changes

2024-05-13 15:27 UTC, Tschakki commented on docs/building-on-lisk/connecting-to-a-wallet.mdx
> +    #### Adding Lisk with 1 click
The 1 click solutions for Lisk Mainnet and Lisk Sepolia are exactly the same currently. Please double check how the process works after migration in the Portal, for both Sepolia and Mainnet

2024-05-13 15:27 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> -| [**LegacyERC20ETH**](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md#legacyerc20eth)                | [0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000](https://sepolia-
Why is this removed?

2024-05-13 15:27 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-Foundry.md
>  In this guide, we discuss, the basics of the [Foundry](https://book.getfoundry.sh/) development toolchain and will describe how to create and deploy a smart contract with Foundry to the **Lisk Sepoli
```suggestion
In this guide, we discuss the basics of the [Foundry](https://book.getfoundry.sh/) development toolchain and will describe how to create and deploy a smart contract with Foundry to the **Lisk Sepolia** testnet.
```

2024-05-13 15:27 UTC, Tschakki commented on docs/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +    --chain 4202 \
```suggestion
    --chain 1135 \
```

2024-05-13 15:27 UTC, Tschakki commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +      chain: lisk,
shouldn't this be ethereum?

2024-05-14 07:09 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> -| [**LegacyERC20ETH**](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md#legacyerc20eth)                | [0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000](https://sepolia-
`LegacyERC20ETH` is a depreciated contract! and is not used anymore.

2024-05-14 07:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +      chain: lisk,
```suggestion
      chain: ethereum,
```

2024-05-14 07:20 UTC, TalhaMaliktz commented on docs/building-on-lisk/connecting-to-a-wallet.mdx
> +    #### Adding Lisk with 1 click
The process is the same! A minor step of ensuring the correct network selection has been added to enhance clarity.

2024-05-15 07:09 UTC, Tschakki submitted a review, later dismissed
LGTM 🎉

2024-05-15 07:34 UTC, nagdahimanshu commented on docs/about-lisk/network-info.md
> +
Do you think it is better to combine both tables into one, for example something like this:

| Name                   | Lisk Mainnet                                         | Lisk Sepolia Testnet                                                 |
| :--------------------- | :--------------------------------------------------- | -------------------------------------------------------------------- |
| **Network Name**       | Lisk                                                 | Lisk Sepolia Testnet                                                 |
| **HTTP RPC Endpoint**  | [https://rpc.api.lisk.com](https://rpc.api.lisk.com) | [https://rpc.sepolia-api.lisk.com](https://rpc.sepolia-api.lisk.com) |
| **WS RPC Endpoint**    | [wss://ws.api.lisk.com](wss://ws.api.lisk.com)       | [wss://ws.sepolia-api.lisk.com](wss://ws.sepolia-api.lisk.com)       |
| **Chain ID**           | 1135                                                 | 4202                                                                 |
| **Currency Symbol**    | ETH                                                  | ETH                                                                  |
| **Block Explorer**     | https://blockscout.lisk.com                          | https://sepolia-blockscout.lisk.com                                  |
| **Block Explorer API** | https://blockscout.lisk.com/api                      | https://sepolia-blockscout.lisk.com/api                              |
| **Lisk Bridge**        | https://bridge.lisk.com                              | https://sepolia-bridge.lisk.com                                      |
| **Lisk Faucet**        | NA                                                   | https://app.optimism.io/faucet                                       |

2024-05-15 07:38 UTC, TalhaMaliktz commented on docs/about-lisk/network-info.md
> +
Don't mind it either way but this separation allows linking to either mainnet or testnet info individually from other pages of the documentation which is not possible if both tables are combined.

2024-05-15 08:46 UTC, nagdahimanshu requested changes
Looks good overall, left minor comments.

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +In this tutorial you'll learn how to bridge a custom ERC-20 token from Ethereum or Sepolia to Lisk or Lisk Sepolia network, respectivley.
```suggestion
In this tutorial, you will learn how to bridge a custom ERC-20 token from Ethereum or Sepolia to the Lisk or Lisk Sepolia network, respectively.
```

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +If you already have an L1 ERC-20 token, you can skip this step.
Just for consistency
```suggestion
If you already have an L1 ERC-20 token deployed on Ethereum Mainnet or Sepolia, you can skip this step.
```

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/building-on-lisk/connecting-to-a-wallet.mdx
> +    | RPC Endpoint    | [	https://rpc.api.lisk.com](https://rpc.api.lisk.com)                       |
```suggestion
    | RPC Endpoint    | [ https://rpc.api.lisk.com](https://rpc.api.lisk.com)      |
```

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/governance/delegation.md
> +- Follow the processes outlined in the Governance documentation of the Lisk DAO
Should we link the `Governance documentation` here in case available?

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/governance/overview.mdx
> +Every account holding **LSK** is able to **stake/lock** a specific amount of LSK tokens to get some voting power  and [staking rewards](#staking-rewards).
```suggestion
Every account holding **LSK** is able to **stake/lock** a specific amount of LSK tokens to get some voting power and [staking rewards](#staking-rewards).
```

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/governance/overview.mdx
> +That means, the counting towards the end of the locking period is paused until the user decides to resume it.
Optional
```suggestion
This means that the counting towards the end of the locking period is paused until the user decides to resume it.
```

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/governance/overview.mdx
> +The following requirements must be fulfilled for a proposal to pass:
```suggestion
The following requirements must be fulfilled for a proposal to approve:
```

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/governance/overview.mdx
> +Funding proposals are **binding**, which means that no one, not even the Onchain Foundation, can prevent the transfer if the proposal passes.
```suggestion
Funding proposals are **binding**, which means that no one, not even the Onchain Foundation, can prevent the transfer if the proposal approves.
```

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/governance/overview.mdx
> +The foundation will have an administrative role and will take care of the following
```suggestion
The foundation will have an administrative role and will take care of the following:
```

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/lisk-tools/utilities.md
> +To create a Safe account with Lisk, [connect your wallet](https://safe.optimism.io/welcome?chain=lisksep) through the Superchain-Safe portal.
May be we can update it to connect to Lisk mainnet:
```suggestion
To create a Safe account with Lisk, [connect your wallet](https://safe.optimism.io/welcome?chain=lisk) through the Superchain-Safe portal.
```

2024-05-15 08:46 UTC, nagdahimanshu commented on docs/lisk-tools/bridges.mdx
> +After initiating your withdrawal, a 7-day [challenge period](https://docs.optimism.io/builders/dapp-developers/bridging/messaging#for-l2-to-l1-transactions) needs to be observed as a security measure
```suggestion
After initiating your withdrawal, a 7-day [challenge period](https://docs.optimism.io/builders/dapp-developers/bridging/messaging#for-l2-to-l1-transactions) needs to be observed as a security measure. Once the challenge period has passed, the withdrawal can be completed with a final transaction.
```

2024-05-15 09:17 UTC, TalhaMaliktz commented on docs/governance/delegation.md
> +- Follow the processes outlined in the Governance documentation of the Lisk DAO
The governance-related docs are hidden for now and are not available publicly. They will be released publically next week and then the appropriate links will be added.

2024-05-15 10:51 UTC, nagdahimanshu approved these changes
LGTM 👍

2024-05-15 10:52 UTC, merged