New guide: How to run a Lisk node
LiskHQ/lisk-docs pull request #127
Opened 2024-05-27 13:15 UTC by Tschakki

### What was the problem?

This PR resolves #125 

### How was it tested?

https://liskhq.github.io/lisk-documentation/building-on-lisk/run-a-lisk-node

2024-05-28 10:10 UTC, TalhaMaliktz requested changes
Please consider the following!

2024-05-28 10:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +cd lisk-node
Please separate them into two code snippets!

2024-05-28 10:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +```
Please align it with the list item.

2024-05-28 10:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +```
Please align it with the list item.

2024-05-28 10:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +Running a node is time consuming, resource expensive, and potentially costly. If you don't already know why you want to run your own node, you probably don't need to.
```suggestion
Running a node is time-consuming, resource-expensive, and potentially costly. You probably don't need to if you don't know why you want to run your own node.
```

2024-05-28 10:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +The following system requirements are recommended to run Lisk L2 node.
```suggestion
The following system requirements are recommended to run the Lisk L2 node.
```

2024-05-28 10:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +- Machines with a high performance SSD drive with at least 4 TB free
```suggestion
- Machines with a high-performing SSD drive with at least 4 TB free.
```

2024-05-28 10:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +- Machines with a minimum of 16 GB RAM (32 GB recommended)
```suggestion
- Modern multi-core CPU with good single-core performance.
- Machines with a minimum of 16 GB RAM (32 GB recommended).
```

2024-05-28 10:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +It is currently not possible to run the nodes with the `--op-network` flag until the configs for Lisk have been merged to the [superchain-registry](https://github.com/ethereum-optimism/superchain-reg
```suggestion
It is currently not possible to run the nodes with the `--op-network` flag until the configs for Lisk have been merged into the [superchain-registry](https://github.com/ethereum-optimism/superchain-registry).
```

2024-05-28 10:10 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +---
```suggestion
```

2024-05-28 10:52 UTC, Tschakki commented on docs/building-on-lisk/run-a-lisk-node.md
> +The following system requirements are recommended to run Lisk L2 node.
```suggestion
The following system requirements are recommended to run a Lisk L2 node.
```

2024-05-28 11:43 UTC, Tschakki commented on docs/building-on-lisk/run-a-lisk-node.md
> +```
i am not sure how to achieve that, and also, the alignment looks OK for me.  But if you have a suggestion please go ahead.

2024-05-28 12:28 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +```
```suggestion
    ```
    curl -s -d '{"id":0,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false]}' \
      -H "Content-Type: application/json" http://localhost:8545
    ```
```

2024-05-28 12:28 UTC, TalhaMaliktz commented on docs/building-on-lisk/run-a-lisk-node.md
> +```
```suggestion
    ```
    docker compose up --build --detach
    ```
```

2024-05-28 12:36 UTC, sameersubudhi approved these changes

2024-05-28 12:36 UTC, sameersubudhi commented on docs/building-on-lisk/run-a-lisk-node.md
> +- **Testnet (Sepolia)**: `https://rpc.sepolia-api.lisk.com`
Optional, since we already specify this information in our `partners` page linked below.

```suggestion
- **Mainnet**: `https://rpc.api.lisk.com`, `https://lisk.drpc.org`
- **Testnet (Sepolia)**: `https://rpc.sepolia-api.lisk.com`, `https://lisk-sepolia.drpc.org`
```

2024-05-29 09:11 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2024-05-29 09:49 UTC, merged