Add Fee page
LiskHQ/lisk-docs pull request #13
Opened 2024-01-16 12:21 UTC by Tschakki

Closes #8

2024-01-18 08:45 UTC, TalhaMaliktz requested changes
Please consider the following.

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +The low transaction fees can be provided, because Lisk is a [Layer 2 optimistic rollup](https://ethereum.org/en/developers/docs/scaling/optimistic-rollups) network.
```suggestion
The low transaction fees can be provided because Lisk is a [Layer 2 optimistic rollup](https://ethereum.org/en/developers/docs/scaling/optimistic-rollups) network.
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +The `transaction_gas_price_l2` is composed of two components: a `base fee` and a `priority fee`, because Lisk is [EIP 1559](https://eips.ethereum.org/EIPS/eip-1559) compliant (although with [differen
```suggestion
The `transaction_gas_price_l2` is composed of two components: a `base fee` and a `priority fee` because Lisk is [EIP 1559](https://eips.ethereum.org/EIPS/eip-1559) compliant (although with [different parameter values](https://docs.optimism.io/chain/differences#eip-1559-parameters) compared to Ethereum).
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +Also, which the cost of L1 gas could increase between steps 1 and 3, it is only updated every five minutes and it does not change by more than 25%.
```suggestion
Also, the cost of L1 gas could increase between steps 1 and 3, it is only updated every five minutes and it does not change by more than 25%.
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +So at most the user will pay 25% more than expected.
```suggestion
So at most, the user will pay 25% more than expected.
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +    - The gas price for L1 transactions (when the transaction was processed).
Maybe this?
```suggestion
    - The gas price for processing a transaction on L1.
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +    - The L1 fee scalar, which is at writing 1.
```suggestion
    - The L1 fee scalar at the time of writing this is **1**.
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +    Take the value provided by the contract and divide by a million.
```suggestion
    Take the value provided by the contract and divide it by a million.
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +## How do spikes in the Ethereum(L1) gas price affect transaction costs on Lisk(L2)?
```suggestion
## How do fluctuation in gas price on Ethereum (L1) affect transaction costs on Lisk (L2)?
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +If the timing of your transaction is flexible, you can save costs by submitting transactions during periods of lower gas on the L1 (for example, over the weekend).
```suggestion
If the timing of your transaction is flexible, you can save cost by submitting transactions during periods when gas prices are lower than usual for example, over the weekend.
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +4. The transaction is written to L1
```suggestion
1. The wallet figures out the cost of the transaction.
2. The user then submits the transaction.
3. The sequencer executes the transaction in two phases.
    - First, it processes the transaction.
    - Then, it deducts the gas cost, based on the L1 and L2 gas prices at that time.
4. After that, the transaction is written to L1.
```

2024-01-18 08:45 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +After step 3 the transaction is Lisks's responsibility.
```suggestion
After step 3, the finality of the transaction is Lisk's responsibility.
```

2024-01-18 09:10 UTC, Tschakki commented on docs/about-lisk/fees.md
> +    - The gas price for L1 transactions (when the transaction was processed).
```suggestion
    - The gas price for processing the transaction on L1.
```

2024-01-18 09:11 UTC, Tschakki commented on docs/about-lisk/fees.md
> +If the timing of your transaction is flexible, you can save costs by submitting transactions during periods of lower gas on the L1 (for example, over the weekend).
```suggestion
If the timing of your transaction is flexible, you can save cost by submitting transactions during periods when gas prices on L1 are lower than usual for example, over the weekend.
```

2024-01-18 09:13 UTC, Tschakki commented on docs/about-lisk/fees.md
> +4. The transaction is written to L1
```suggestion
1. The wallet estimates the cost of the transaction.
2. The user then submits the transaction.
3. The sequencer processes the transaction in two phases.
    - First, it processes the transaction.
    - Then, it deducts the gas cost, based on the L1 and L2 gas prices at that time.
4. After that, the transaction is written to L1.
```

2024-01-18 12:36 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2024-01-21 19:53 UTC, Incede requested changes
Although I understand the OP docs are not consistent, I think it'd make sense to follow a single version of OP docs that we link and align our docs with it, otherwise it could be confusing for the user to find different information in the Lisk and linked OP docs. 

Not a strong opinion but could also be nice to provide quick links to find the values of important params used in the specified formulas so that user can quickly check them out:
1. [L1 fee scalar(Dynamic overhead)](https://optimistic.etherscan.io/address/0x420000000000000000000000000000000000000F#readProxyContract) 
2. [Transaction gas price L1 & L2 (L1 & L2 base fees)](https://optimistic.grafana.net/public-dashboards/c84a5a9924fe4e14b270a42a8651ceb8?orgId=1&refresh=5m)

2024-01-21 19:53 UTC, Incede commented on docs/about-lisk/fees.md
> +At a high level, the L2 fee is the cost to execute your transaction in L2 and the L1 fee is the estimated cost to publish your transaction on L1 (in a rollup batch).
```suggestion
At a high level, the L2 fee is the cost to execute your transaction on L2 and the L1 fee is the estimated cost to publish your transaction on L1 (in a rollup batch).
```

2024-01-21 19:53 UTC, Incede commented on docs/about-lisk/fees.md
> +- **L1 Security Fee/L1 Data Fee**: is charged as `transaction_gas_price_l1 * gas_used * l1_fee_scalar`.
I think this formula doesn't match with the [formula](https://docs.optimism.io/stack/transactions/fees#formula) specified in the [link](https://docs.optimism.io/stack/transactions/fees) you provide below which is:
```
l1_data_fee = tx_total_gas * ethereum_base_fee 
or
l1_data_fee =  (tx_data_gas + fixed_overhead) * dynamic_overhead * ethereum_base_fee
```

considering `dynamic_overhead` is same as `l1_fee_scalar`, `tx_data_gas` is same as `gas_used` and `ethereum_base_fee` is same as `transaction_gas_price_l1` there is a difference of following amount in the L1 Security/Data Fee between the 2 formulas:
```
fixed_overhead * dynamic_overhead * ethereum_base_fee
```

2024-01-22 09:18 UTC, Tschakki commented
> Not a strong opinion but could also be nice to provide quick links to find the values of important params used in the specified formulas so that user can quickly check them out:
> 
> 1. [L1 fee scalar(Dynamic overhead)](https://optimistic.etherscan.io/address/0x420000000000000000000000000000000000000F#readProxyContract)
> 2. [Transaction gas price L1 & L2 (L1 & L2 base fees)](https://optimistic.grafana.net/public-dashboards/c84a5a9924fe4e14b270a42a8651ceb8?orgId=1&refresh=5m)

I agree these links provide useful information in this context, but I wouldn't link to the gas price tracker of Optimism, as it doesn't show Lisk gas prices. Same for the scalar, it shows the scalar Optimism uses, we should link to our own contract here. Maybe I can add TODOs, to add these links, once/if they are available?

2024-01-22 10:34 UTC, Tschakki commented on docs/about-lisk/fees.md
> +- **L1 Security Fee/L1 Data Fee**: is charged as `transaction_gas_price_l1 * gas_used * l1_fee_scalar`.
I removed all the formulas now, as discussed

2024-01-22 12:12 UTC, Incede approved these changes

2024-01-22 12:12 UTC, Incede commented on docs/about-lisk/fees.md
> +So at most, the user will pay 25% more than expected.
Assuming this info is coming from [here](https://help.optimism.io/hc/en-us/articles/4416677738907) which was updated 2 years ago, it'd make sense to check if this info is still accurate, as it can be outdated as we already saw, otherwise could also omit this.

2024-01-22 14:11 UTC, merged