Restructure docs, improve styling and asthetics
LiskHQ/lisk-docs pull request #137
Opened 2024-06-05 09:46 UTC by TalhaMaliktz

### What was the problem?

This PR resolves #134 and #135

### How was it tested?
https://liskhq.github.io/lisk-documentation/

2024-06-06 08:47 UTC, Tschakki requested changes

2024-06-06 08:47 UTC, Tschakki commented on docs/intro.mdx
> +
this is a very old graphic, and imho it doesn't add much value. In case you want to add it, please check with the Rita or someone from design, if it is still OK to use it.

2024-06-06 08:47 UTC, Tschakki commented on docusaurus.config.js
> +            label: 'User Guides',
Would call it "User Docs" and the other "Dev Docs".

Right now, only user docs are shown in the top nav, Please add a link to Dev Docs as well.

Apart from this, we need now a landing page, with links to both user and dev docs.

2024-06-06 08:47 UTC, Tschakki commented on static/img/lisk-icon-dark.svg
This is pretty long icon, and it doesn't look good on mobile.

2024-06-06 10:09 UTC, TalhaMaliktz commented on docs/intro.mdx
> +
The graphic adds a bit of a flare to the docs IMHO, which I think is needed. @ritaosok What do you think about it? Do we have a better graphic than the one attached? or does the existing one suffice?

2024-06-13 08:03 UTC, ritaosok commented on docs/intro.mdx
> +
@TalhaMaliktz @Tschakki, I think it's fine that it's there. I would only suggest making it 10% larger and shifting it slightly to the right. So, for now, it's fine.

2024-06-13 08:48 UTC, Tschakki requested changes

2024-06-13 08:48 UTC, Tschakki commented on docs-user/intro.md
Please think about more content for this page, or remove it

2024-06-13 08:48 UTC, Tschakki commented on docusaurus.config.js
> +  ],
It looks like you are using the `@docusaurus/plugin-content-docs` plugin. 

Docusaurus has a note in their docs regarding the plugin:

> This feature is only useful for [versioned documentation](https://docusaurus.io/docs/versioning). It is recommended to be familiar with docs versioning before reading this page. If you just want [multiple sidebars](https://docusaurus.io/docs/sidebar/multiple-sidebars), you can do so within one plugin.

Why are we not using multiple sidebars instead?

2024-06-13 08:48 UTC, Tschakki commented on src/components/HomepageFeatures/index.js
Please add buttons to the features, like in the base docs

2024-06-13 08:48 UTC, Tschakki commented on src/pages/index.js
> +          Welcome to Lisk Docs
```suggestion
          Welcome to the Lisk Documentation 🎉
```

2024-06-13 08:48 UTC, Tschakki commented on src/pages/index.js
> +          Welcome to Lisk Docs
Could look better if the content is centered

2024-06-13 08:48 UTC, Tschakki commented on src/pages/index.js
> +            Let's build with Lisk  🛠
Could look better if the content is centered

2024-06-13 08:48 UTC, Tschakki commented on src/pages/index.js
> +        <p className="hero__subtitle">We are thrilled to have you here. Explore this site for technical details and guides on creating and utilizing the Lisk L2 blockchain.</p>
```suggestion
        <p className="hero__subtitle">The knowledge base for developer- and user-oriented information and guides regarding the Lisk blockchain.</p>
```

2024-06-13 08:52 UTC, TalhaMaliktz commented on docusaurus.config.js
> +  ],
I haven't tried this approach but, since we have an entire section of docs, it is good to have separation everywhere.

2024-06-13 08:53 UTC, TalhaMaliktz commented on src/components/HomepageFeatures/index.js
What do you mean? 🤔

2024-06-13 08:54 UTC, TalhaMaliktz commented on src/pages/index.js
> +            Let's build with Lisk  🛠
Tried it with centered content, and liked this one more.

2024-06-13 08:56 UTC, Tschakki commented on src/components/HomepageFeatures/index.js
https://docs.base.org/

2024-06-13 08:56 UTC, Tschakki commented on src/components/HomepageFeatures/index.js
We discussed earlier we do not want to list Lisk features here, but instead we want to highlight the most important documentation content, like in the base docs

2024-06-13 08:58 UTC, TalhaMaliktz commented on src/components/HomepageFeatures/index.js
Ummmmm! Yeah, I did highlight governance, and building with the Lisk section. Base docs also highlight the grants, Base camp, and tutorials and I highlighted similar content as well.

2024-06-13 08:59 UTC, TalhaMaliktz commented on docs-user/intro.md
Ummmm! For now, I would leave it as is and would create a new issue to fill this up!

2024-06-13 09:07 UTC, TalhaMaliktz commented on src/pages/index.js
> +        <p className="hero__subtitle">We are thrilled to have you here. Explore this site for technical details and guides on creating and utilizing the Lisk L2 blockchain.</p>
```suggestion
        <p className="hero__subtitle">Explore our comprehensive knowledge base tailored for both developers and users! Find in-depth technical information and helpful guides all about the Lisk blockchain.</p>
```

2024-06-13 09:30 UTC, Tschakki commented on src/components/HomepageFeatures/index.js
Base docs have distinctive buttons to click, and imho it looks much better. This is what i am referring to

2024-06-13 09:31 UTC, TalhaMaliktz commented on src/components/HomepageFeatures/index.js
I agree, I am adding the buttons, will update soon :-)

2024-06-13 09:32 UTC, Tschakki commented on src/pages/index.js
> +            Let's build with Lisk  🛠
please try again, same for title 🙏

2024-06-13 09:34 UTC, Tschakki commented on docusaurus.config.js
> +  ],
We can also separate into different folders without using this plugin. If we do not have a specific reason to use it (e.g. versioned docs) I would not use it because of the warning

2024-06-13 09:35 UTC, Tschakki commented on docs-user/intro.md
In that case please remove it for now until you start with the issue 🙏

2024-06-13 09:36 UTC, TalhaMaliktz commented on docusaurus.config.js
> +  ],
There's more than one way to skin a cat :-). Changing this will undo a lot of effort. I would like to keep it as is.

2024-06-13 15:28 UTC, TalhaMaliktz commented on docs-user/intro.md
Since this is the landing page of the user docs, the navigation of the entire user docs kinda depends on it. I have added a few highlights to the existing page and have also created an issue to further improve it in the future. Please add your suggestions to the following issue.

https://github.com/LiskHQ/lisk-documentation/issues/150

2024-06-13 15:38 UTC, ritaosok approved these changes

2024-06-14 08:45 UTC, Tschakki commented on docusaurus.config.js
> +  ],
Sure, but I am just trying to understand if this approach brings any benefits over going with the more simple Multiple Sidebars solution... I mean they explicitly added a note saying it is only useful for versioned documentation. And we are currently not versioning the docs, and there is also an explicit warning in the docs saying

> Think about it before starting to version your documentation - it can become difficult for contributors to help improve it!

So I am a little concerned we might add unneeded complexity to our documentation structure here.

2024-06-14 08:45 UTC, Tschakki commented on src/components/HomepageFeatures/index.js
thank you, looks much better now imho 🎉

2024-06-14 08:52 UTC, TalhaMaliktz commented on docusaurus.config.js
> +  ],
There is no complexity as far as I see it. There are only separate folders and separate sidebars. We will be creating a file in `docs-users` and adding them into `userSidebar.js`. Same as we were doing earlier when we were creating a file in the `docs` folder and then adding it in the `sidebars.js`. If anything this is better in my opinion as it now allows us to have versioned docs, which we could need in the future. For now, there is no additional step or file creation required for our current workflow.

2024-06-14 08:54 UTC, Tschakki commented on docs-user/intro.md
Hmm, tbh I still don't think we should publish it like this, the page is missing a clear concept imho.
And it is a very prominent landing page, it should get some attention and purpose, if published.

I am not sure why removing it is such a problem, is it because we are using the plugin instead of more simple multiple sidebar solution?

2024-06-14 08:56 UTC, TalhaMaliktz commented on docs-user/intro.md
What page would you like to be the landing page for now?

2024-06-14 13:02 UTC, TalhaMaliktz commented on docusaurus.config.js
> +  ],
Removed `@docusaurus/plugin-content-docs`, created multiple sidebars, and set the user docs' landing page, updated broken links.

2024-06-14 13:03 UTC, TalhaMaliktz commented on docs-user/intro.md
Connecting to Wallet is the new landing page for the user docs for now!

2024-06-14 13:30 UTC, Tschakki approved these changes
LGTM, just one minor suggestion :)

2024-06-14 13:30 UTC, Tschakki commented on src/components/HomepageFeatures/index.js
> +          to="/user/connecting-to-a-wallet/">
Would change this link to point to the governance overview, as it fits more with the above content
```suggestion
          to="/governance/overview">
```

2024-06-14 13:31 UTC, Tschakki commented
Please resolve the conflicts before merging this PR

2024-06-14 13:38 UTC, merged