Add formulas for L1 fee
LiskHQ/lisk-docs pull request #138
Opened 2024-06-05 13:05 UTC by Tschakki

### What was the problem?

This PR resolves #132 

### How was it tested?

2024-06-25 14:04 UTC, gkoumout commented on docs/about-lisk/fees.md
Comment for line 55: We ended up using different parameters for EIP-1559 that OP Mainnet, so I guess the link to Optimism Docs should be removed. 

Perhaps we should create our own table here and show our chosen values.

2024-06-25 14:04 UTC, gkoumout commented on docs/about-lisk/fees.md
Comment for lines 39, 60: It might be better to use sub sections instead of bullet points for L2 Exec and L1 Data fee, since the text below them is not that small and contains formulas.

2024-06-25 14:04 UTC, gkoumout commented on docs/about-lisk/fees.md
But not really strong opinion here, you might judge depending on how it would finally look like in the webpage.

2024-06-25 14:04 UTC, gkoumout commented on docs/about-lisk/fees.md
> +This function uses the following parameters:
The new content is correct. I would just don't use the world "function" here, since it's not clear what do we mean by function. 

Perhaps we can rephrase somehow like that: "As we explain below, the actual amount of this fee depends on i) the signed trs... ii) the current ethereum base fee ... iii) the scalars...

And then in the para starting on line 71 use some bold letters "L1 Data fee calculation" or something like that.

2024-06-25 14:04 UTC, gkoumout commented on docs/about-lisk/fees.md
> +
Optional: Some info that could be added, but not sure what's the best way to do it, so just mentioning here and you can try to judge if and how should be incorporated here:

 1.  We could mention that `tx_compressed_size` is an estimation on the size that trs will occupy in blobs. The factor of 16 is the savings of using blobs vs calldata. 
 2. The "L1 Gas used by txn" field in blockcsout (see screenshot below) contains this quantity multiplied by 16 (i.e., the calldata size)

 
 
![image](https://github.com/LiskHQ/lisk-documentation/assets/48478060/f52b0b3a-b127-4029-8ef1-9162473f52cf)

2024-06-25 14:04 UTC, gkoumout commented on docs/about-lisk/fees.md
> +  ```
Perhaps mention that currently Lisk uses the following values: `base_fee_scalar = 0.786381` and `blob_base_fee_scalar = 0.01734` .

2024-06-27 11:57 UTC, Tschakki commented on docs/about-lisk/fees.md
I created a new section, can you please tell me the correct values for Lisk to enter here?

2024-06-27 14:09 UTC, gkoumout approved these changes
Good job! One minor comment, otherwise looks good to me

2024-06-27 14:09 UTC, gkoumout commented on docs/about-lisk/fees.md
> +  - `base_fee_scalar` = 0.786381
Perhaps we can move those values after line 105 and say something indicating that those values can be changed at any time subject to network conditions. 

So I would say something like: Current values are ... . Note that those values can be updated at any time depending on network conditions to guarantee that the fees charged to transactions are enough to cover the cost of posting batches to L1. (perhaps you can rephrase better than me)

2024-06-27 14:11 UTC, gkoumout commented on docs/about-lisk/fees.md
Perhaps you want to add the link to our gas tracker (https://blockscout.lisk.com/gas-tracker) somewhere in the L2 Execution fee page (or here, wherever it seems more appropriate)

2024-06-27 14:45 UTC, Tschakki commented on docs/about-lisk/fees.md
Good point, actually i added now an new section right at the beginning :)

2024-06-28 06:42 UTC, TalhaMaliktz requested changes
Please consider the following!

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +To track the current and past gas fees on Lisk, check the gas tracker for the respective network on blockscout:
```suggestion
To track the current and past gas fees on Lisk, check the gas tracker for the respective network on Blockscout:
```

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +The L1 data fee is claculated according to the following formula:
```suggestion
The L1 data fee is calculated according to the following formula:
```

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +1. The **signed transaction** serialized according to the standard Ethereum transaction RLP encoding.
```suggestion
1. The **signed transaction** is serialized according to the standard Ethereum transaction RLP encoding.
```

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +`tx_compressed_size` is an estimation on the size the transaction will occupy in blobs.
```suggestion
`tx_compressed_size` is an estimation of the size that a transaction will occupy in blobs.
```

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +The "L1 Gas used by txn" field of transaction details in [blockcsout](https://blockscout.lisk.com/) contains the `tx_compressed_size` multiplied by 16 (i.e., the calldata size).
```suggestion
The "L1 Gas used by txn" field of transaction details in [Blockscout](https://blockscout.lisk.com/) contains the `tx_compressed_size` multiplied by 16 (i.e., the `calldata` size).
```

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
>  ## How do fluctuation in gas price on Ethereum (L1) affect transaction costs on Lisk (L2)?
```suggestion
## How does fluctuation in gas price on Ethereum (L1) affect transaction cost on Lisk (L2)?
```

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
>  While the L1 Data Fee will be always cheaper compared to posting the transaction directly to Ethereum mainnet (due to the efficient encoding in batching transactions), it's value will vary depending
```suggestion
While the L1 Data Fee will be always cheaper compared to posting the transaction directly to the Ethereum mainnet (due to the efficient encoding in batching transactions), its value will vary depending on the amount of transactions on the L1.
```

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
>    ]
Line 164:
`See the [Optimism Docs > Transaction Fees](https://docs.optimism.io/stack/transactions/fees#mechanism) for more information about transaction fees.`

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
Line 159:
`In principle, between steps 1 and 3 the gas price might change. However, it can not increase by more than 12.5%, therefore the difference between the price shown to the user in step 1 and the actual one is bounded by 12.5%.  `

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +The divisor of 16 represents the storage savings of using blobs vs calldata.
```suggestion
The divisor of 16 represents the storage savings of using blobs vs `calldata`.
```

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +If a transaction costs 100,000 gas on Ethereum, it will cost 100,000 gas on Lisk Mainnet.
```suggestion
If a transaction costs 100,000 gas units on Ethereum, it will cost 100,000 gas units on Lisk Mainnet.
```

2024-06-28 06:42 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +  - `blob_base_fee_scalar` = 0.01734[^1]                              |
If it is the power of 1 why are we mentioning it?
```suggestion
  - `blob_base_fee_scalar` = 0.01734
```

2024-06-28 07:54 UTC, Tschakki commented on docs/about-lisk/fees.md
>  ## How do fluctuation in gas price on Ethereum (L1) affect transaction costs on Lisk (L2)?
```suggestion
## How do fluctuations in gas price on Ethereum (L1) affect transaction costs on Lisk (L2)?
```

2024-06-28 08:45 UTC, gkoumout commented on docs/about-lisk/fees.md
> +The default values for the scalars are:
I would still say "current" values instead of default, since we chose them based on expected traffic for the first few months.

2024-06-28 08:45 UTC, gkoumout commented on docs/about-lisk/fees.md
> +1. The **signed transaction** is serialized according to the standard Ethereum transaction RLP encoding.
This point refers to the fact that `tx_compressed_size` is calculated based on `tx_data` in the calculation below. 

So the previous formulation (without "is") was correct. 

```suggestion
1. The **signed transaction**  serialized according to the standard Ethereum transaction RLP encoding.
```

2024-06-28 08:45 UTC, gkoumout commented on docs/about-lisk/fees.md
> +`tx_compressed_size` is an estimation of the size that a transaction will occupy in blobs.
Perhaps here we can add to be more precise. `tx_data` is the byte representation of the serialized transaction.

2024-06-28 09:04 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +1. The **signed transaction** is serialized according to the standard Ethereum transaction RLP encoding.
IMO! The sentence is missing an article, another suggestion could be this!
```suggestion
1. A **signed transaction**: serialized according to the standard Ethereum transaction RLP encoding.
```

2024-06-28 09:08 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
> +The divisor of 16 represents the storage savings of using blobs vs calldata.
The `calldata` is mentioned as a variable in the ETH docs, and should be encapsulated in code.

2024-06-28 09:09 UTC, Tschakki commented on docs/about-lisk/fees.md
> +1. The **signed transaction** is serialized according to the standard Ethereum transaction RLP encoding.
```suggestion
1. The **signed transaction**, serialized according to the standard Ethereum transaction RLP encoding.
```

2024-06-28 09:20 UTC, Tschakki commented on docs/about-lisk/fees.md
> +The divisor of 16 represents the storage savings of using blobs vs calldata.
Calldata is also a general term, and so we are using it here.

2024-06-28 09:22 UTC, Tschakki commented on docs/about-lisk/fees.md
> +The divisor of 16 represents the storage savings of using blobs vs calldata.
https://ethereum.org/en/developers/docs/data-availability/blockchain-data-storage-strategies/#calldata

2024-06-28 09:27 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼!

2024-06-28 09:38 UTC, gkoumout approved these changes
Very nice work!

2024-06-28 09:42 UTC, merged