Add info about voting power calculation
LiskHQ/lisk-docs pull request #142
Opened 2024-06-11 13:31 UTC by Tschakki

### What was the problem?

This PR resolves #141 

It also includes small updates in the proposal creation section

### How was it tested?

2024-06-11 15:05 UTC, TalhaMaliktz requested changes

2024-06-11 15:05 UTC, TalhaMaliktz commented on docs/governance/proposal-lifecycle.mdx
> +    ```
Since it is part of the bullet point.
```suggestion
        ```
        My proposal text
        #proposer=0x???
        ```
```

2024-06-12 07:50 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2024-06-12 08:06 UTC, gkoumout requested changes
Left few comments

2024-06-12 08:06 UTC, gkoumout commented on docs/governance/overview.mdx
>  Locked tokens provide a voting power proportional to the amount of locked tokens.
Comment about line 65: I find the sentence "Tokens for the Lisk DAO fund are minted newly and added to the Lisk DAO according to the following vesting plan:" a bit confusing, I would try to rephrase.

2024-06-12 08:06 UTC, gkoumout commented on docs/governance/overview.mdx
>  Locked tokens provide a voting power proportional to the amount of locked tokens.
Comment about line 74: I would add specifically that 7 years mentioned are 2026-2033 to avoid confusion of the reader

2024-06-12 08:06 UTC, gkoumout commented on docs/governance/overview.mdx
>  Locked tokens provide a voting power proportional to the amount of locked tokens.
I think lines 90-91 could be mover to the next subsection "voting power calculation". Otherwise the discussion on voting power is all over the place.

2024-06-12 08:06 UTC, gkoumout commented on docs/governance/overview.mdx
>  Locked tokens provide a voting power proportional to the amount of locked tokens.
Or perhaps completely remove those two lines, since the voting power is quite well explained later.

2024-06-12 08:06 UTC, gkoumout commented on docs/governance/overview.mdx
>  This means that the counting towards the end of the locking period is paused until the user decides to resume it.
Comment about line 102: Perhaps say: "Hence, the voting power can be increased by up to 200%, which is achieved at the maximum locking duration of 2 years"

2024-06-12 08:06 UTC, gkoumout commented on docs/governance/overview.mdx
> +The voting power for each proposal is counted from a snapshot on the [creation of the proposal](proposal-lifecycle#2-proposal-creation).
I would add this after the "boosting voting power" paragraph with some bold letters such as NOTE: or something like that. 

Example (perhaps you can rephrase better): 

" **Note:** The voting power for each proposal is counted from a snapshot on the [creation of the proposal](proposal-lifecycle#2-proposal-creation). Therefore, pausing the locking duration after a proposal is created does not increase the voting power for this proposal but for the future ones."

2024-06-12 08:34 UTC, Tschakki commented on docs/governance/overview.mdx
>  Locked tokens provide a voting power proportional to the amount of locked tokens.
It is now split into two sentences - does it make it clearer?

2024-06-12 10:10 UTC, gkoumout commented on docs/governance/overview.mdx
>  Locked tokens provide a voting power proportional to the amount of locked tokens.
My bad, it's 2027 - 2033, sorry, plz update!

2024-06-12 10:13 UTC, gkoumout requested changes
Two open points left.

2024-06-12 10:13 UTC, gkoumout commented on docs/governance/overview.mdx
> +The voting power for each proposal is counted from a snapshot on the [creation of the proposal](proposal-lifecycle#2-proposal-creation).
Looks good, I would just move it after the "boosting the voting power" paragraph, so that readers understand the effect of pausing first

2024-06-25 13:41 UTC, gkoumout reviewed
Looks good! I left a few more comments/suggestions

2024-06-25 13:41 UTC, gkoumout commented on docs/governance/overview.mdx
Comment about line 47: I think it should be deleted, since Lisk DAO is launched already, isn't it?

2024-06-25 13:41 UTC, gkoumout commented on docs/governance/overview.mdx
>  {/* TODO: Uncomment once staking is implemented */}
Suggestion: On line 83, add the link to the lisk portal that was commented out here.

2024-06-25 13:41 UTC, gkoumout commented on docs/governance/overview.mdx
>  {/* TODO: Uncomment once staking is implemented */}
Also suggestion on line 86: Replace "redeem" by "unlock"

2024-06-25 13:41 UTC, gkoumout commented on docs/governance/overview.mdx
>  ##### Boosting the voting power
Looks good now. Minor comment: Since this is not live yet in the UI, should we add a "coming soon" comment here somehow?

2024-06-26 13:17 UTC, Tschakki commented on docs/governance/overview.mdx
>  ##### Boosting the voting power
good point, added "(coming soon)" to the title

2024-06-27 09:01 UTC, gkoumout requested changes
Looks good! Just a few more comments..

2024-06-27 09:01 UTC, gkoumout commented on docs/docs-user/governance/overview.mdx
> +  The [Lisk DAO Tally instance](https://www.tally.xyz/gov/3rd-testing) is the place where users can vote on proposals or delegate their voting power.
Why did you change the link here? I think the old one was the correct one. The new one just links to a particular test proposal I think.

2024-06-27 09:01 UTC, gkoumout commented on docs/docs-user/governance/overview.mdx
> +Staking happens on the [Lisk portal](https://portal.lisk.com/staking/stake).
This is now redundant I guess, right?

2024-06-27 09:01 UTC, gkoumout commented on docs/governance/overview.mdx
I just made an observation about the last subsection "Staking Rewards Distribution":

We first mention that daily rewards are 8M/365 and only in the next paragraph we explain that we allocate 24M for 3 years. I guess we should change the order here. 

Also, we might want to skip the last part of potential future staking rewards, not sure.

2024-06-27 09:01 UTC, gkoumout commented on docs/governance/overview.mdx
Suggestion:


A total of 24 million LSK tokens will be used over the course of 3 years for the LSK staking rewards program (8 million LSK per year).  This amount is provided to the Rewards contract. 

Rewards are taken from the balance of the [Rewards contract](https://github.com/LiskHQ/lisk-contracts/blob/main/documentation/staking-governance.md#contracts-overview) and calculated daily, based on the amount locked and the remaining locking duration. Concretely, the weight for a locked amount is given by lockedAmount * (remainingLockingDurationInDays + 150). The total daily amount of staking rewards, 8,000,000 / 365 LSK, is then shared by all users proportional to their weight. 

After the end of ..

2024-06-27 09:11 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +  The [Lisk DAO Tally instance](https://www.tally.xyz/gov/3rd-testing) is the place where users can vote on proposals or delegate their voting power.
Oh I think this happened when I erged the updated base branch... good catch!

2024-06-27 09:13 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +Staking happens on the [Lisk portal](https://portal.lisk.com/staking/stake).
true, removed the line

2024-06-27 10:13 UTC, gkoumout approved these changes
Nice work!

2024-06-27 10:15 UTC, merged