Add Tally links
LiskHQ/lisk-docs pull request #145
Opened 2024-06-12 10:10 UTC by Tschakki

### What was the problem?

This PR resolves #144 

### How was it tested?

2024-06-12 11:35 UTC, AndreasKendziorra approved these changes

2024-06-13 13:03 UTC, TalhaMaliktz requested changes

2024-06-13 13:03 UTC, TalhaMaliktz commented on docs/governance/overview.mdx
> +A total of 24 million LSK tokens are used over the course of 3 years for the LSK staking rewards program (8 million LSK per year).
```suggestion
A total of 24 million LSK tokens will be used over the course of 3 years for the LSK staking rewards program (8 million LSK per year).
```

2024-06-13 14:38 UTC, Tschakki commented on docs/governance/overview.mdx
> +A total of 24 million LSK tokens are used over the course of 3 years for the LSK staking rewards program (8 million LSK per year).
As the DAO is launched now, we should talk in present tense imho

2024-06-13 14:52 UTC, TalhaMaliktz commented on docs/governance/overview.mdx
> +A total of 24 million LSK tokens are used over the course of 3 years for the LSK staking rewards program (8 million LSK per year).
A total of 24 million LSK tokens will be used in the course of the next 3 years, which means that this activity will start now and end in the future. Hence, the suggestion.

2024-06-14 13:07 UTC, TalhaMaliktz approved these changes

2024-06-14 13:10 UTC, merged