Add exchanges page
LiskHQ/lisk-docs pull request #163
Opened 2024-07-01 12:22 UTC by Tschakki

### What was the problem?

This PR resolves #155 

### How was it tested?

2024-07-02 10:06 UTC, TalhaMaliktz requested changes

2024-07-02 10:06 UTC, TalhaMaliktz commented on docs/docs-user/exchanges.md
> +Lisk(LSK) is available for trading on a variety of <!-- decentralized and centralized --> exchanges.
```suggestion
Lisk (LSK) is available for trading on various <!-- decentralized and centralized --> exchanges.
```

2024-07-02 10:06 UTC, TalhaMaliktz commented on docs/docs-user/exchanges.md
> +| **Zonda**                | 🟡 Ethereum        | [LSK/USDT](https://zondacrypto.com/en/exchange-rate/lisk-price-usdt)<br />[LSK/EUR](https://zondacrypto.com/en/exchange-rate/lisk-price-eur)<br />[LSK
I think we should remove the emoticons from the table and divide the Supported Network columns into two columns such as **Lisk L2 Support** and **Eth L1 Support** to bring visibility. An example of such a table can be like this:

![image](https://github.com/LiskHQ/lisk-documentation/assets/13951043/722ceef3-2dcb-42df-acb2-95c481a963ae)

You can use an HTML table to layout the table in the `.mdx` file to achieve the aforementioned.

2024-07-02 11:10 UTC, Tschakki commented on docs/docs-user/exchanges.md
> +| **Zonda**                | 🟡 Ethereum        | [LSK/USDT](https://zondacrypto.com/en/exchange-rate/lisk-price-usdt)<br />[LSK/EUR](https://zondacrypto.com/en/exchange-rate/lisk-price-eur)<br />[LSK
I don't agree adding two separate columns will help users. The main info they need if they can trade via L2 or L1, and this can be easily provided via one column. Therefore I don't see the benefit of introducing more complex HTML tables.

2024-07-03 05:01 UTC, TalhaMaliktz commented on docs/docs-user/exchanges.md
> +| **Zonda**                | 🟡 Ethereum        | [LSK/USDT](https://zondacrypto.com/en/exchange-rate/lisk-price-usdt)<br />[LSK/EUR](https://zondacrypto.com/en/exchange-rate/lisk-price-eur)<br />[LSK
I still believe that the emoticons should be removed, if you want to add any visual aid, please add the logos for Lisk and Ethereum in place of the emoticons, otherwise remove the emoticons.

2024-07-03 05:02 UTC, TalhaMaliktz requested changes
Please remove emoticons.

2024-07-03 08:28 UTC, Tschakki commented on docs/docs-user/exchanges.md
> +| **Zonda**                | 🟡 Ethereum        | [LSK/USDT](https://zondacrypto.com/en/exchange-rate/lisk-price-usdt)<br />[LSK/EUR](https://zondacrypto.com/en/exchange-rate/lisk-price-eur)<br />[LSK
The visual aid here is that Lisk is the preferable network because of low transaction fees, this is why I added the emoticons, so I still would like to keep them

2024-07-05 05:01 UTC, TalhaMaliktz commented on docs/docs-user/exchanges.md
> +| **Bitget**               | 🟡 Ethereum        | [LSK/USD](https://crypto.com/exchange/trade/LSK_USD)          |
Incorrect URL!
```suggestion
| **Bitget**               | 🟡 Ethereum        | [LSK/USD](https://www.bitget.com/futures/usdt/LSKUSDT)          |
```

2024-07-05 07:01 UTC, TalhaMaliktz approved these changes
LGTM!

2024-07-05 07:38 UTC, merged