Add staking guides
LiskHQ/lisk-docs pull request #166
Opened 2024-07-03 14:18 UTC by Tschakki

### What was the problem?

This PR resolves #153 

### How was it tested?

https://liskhq.github.io/lisk-documentation/category/staking

2024-07-16 07:22 UTC, gkoumout reviewed
Looks good to me, left comments for improvement in several places. 

On another note, screenshots are nice, but I was wondering whether it's better to use from Lisk Mainnet and not from Lisk Sepolia. But this could be done at the end, after having the final text.

2024-07-16 07:22 UTC, gkoumout commented on sidebars.js
>      },
Not sure, but I think it might make more sense to have Governance first and staking afterwards. Reason is that the important thing should be Governance and staking just the medium to participate in it.

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +Lisk staking is rewarding LSK token holders based on their commitment duration with [staking rewards](#staking-rewards) and [voting power](docs-user/governance/overview.mdx#voting-power) in the [Lisk
Suggestion:

```suggestion
LSK staking is required for participating in the [Lisk DAO](https://www.tally.xyz/gov/lisk) and having therefore an active involvement in the project's decision making. Our staking system rewards LSK stakers for their participation with [staking rewards](#staking-rewards) based on their commitment duration . 
```

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +Lisk staking is rewarding LSK token holders based on their commitment duration with [staking rewards](#staking-rewards) and [voting power](docs-user/governance/overview.mdx#voting-power) in the [Lisk
Perhaps you can rephrase better than me, just showing the main idea here.

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +Every time you [stake](stake-unstake.mdx#how-to-stake-your-lsk-tokens) a certain amount of LSK for a specific timeframe, this will create a new **locking position**.
```suggestion
Every time you [stake](stake-unstake.mdx#how-to-stake-your-lsk-tokens) a certain amount of LSK for a specific locking duration, this will create a new **locking position**.
```

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +Every time you [stake](stake-unstake.mdx#how-to-stake-your-lsk-tokens) a certain amount of LSK for a specific timeframe, this will create a new **locking position**.
I would not use timeframe instead of locking duration, to avoid confusion.

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +lockedAmount * (remainingLockingDurationInDays + 150)
Perhaps
```suggestion
weight = lockedAmount * (remainingLockingDurationInDays + 150)
```

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +Rewards are taken from the balance of the Rewards contract and calculated daily, based on the amount locked and the remaining locking duration.
```suggestion
**Daily Reward Calculation:** Rewards are taken from the balance of the Rewards contract and calculated daily, based on the amount locked and the remaining locking duration.
```

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +Rewards are taken from the balance of the Rewards contract and calculated daily, based on the amount locked and the remaining locking duration.
Somehow to show that here the user will read how to compute their daily rewards

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +
I would then add here a little bit more of explanation to show how daily rewards for a user are calculated. 

Something like this:

"That means, the dailyRewards for a locking position are calculated as: weight/totalWeight * TotalDailyRewards"

Not sure but I would even add an example here, based on current contract situation, to show to users actual numbers.

E.g., assume someone stakes 100LSK for 1 year and make an assumption on totalWeight (just take the current contract value). Then we can show the actual number of dailyRewards.

And even then compare to the case that the locking duration is 2 years, to show the difference.

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +The penalty is proportional to the remaining days in the staking period.
```suggestion
The penalty is proportional to the remaining days in the staking period that will be skipped.
```

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +For example, unlocking 100 LSK after 147 days would incur a penalty of 10.068 LSK.
```suggestion
For example, if a user wants to fast unlock a position with 100 LSK and remaining locking duration of 150 days, then the penalty is calculated as follows:  [Add calculation]

Note that we multiply by 147 and not 150, since the user will still have to wait for 3 days, so the locking duration decreased by 147 overall. 
```

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +Penalty = 0.5 * Staked Amount * (Remaining Days / 730)
Perhaps explain that 730 is the maximum locking duration?

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +<div className="imageCaption">
I would suggest moving the image a bit below, so that the page starts with text and then the image is in the appropriate place.

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +<div className="imageCaption">
Example, after step 3?

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +After at least one day of staking, you should see an accumulated amount of your [staking rewards](staking#staking-rewards) you received until then.
received --> are eligible for

The point is rewards are not automatically sent to user.

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +3. **Connect your Lisk wallet** to the Lisk Portal, if you haven't already.
Perhaps add this at step 2?

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +3. **Connect your Lisk wallet** to the Lisk Portal, if you haven't already.
Perhaps add this on step 2?

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +2. **Click on the `Unstake` tab.**
Screenshot?

2024-07-16 07:22 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +2. **Click on the `Claim` tab.**
Screenshot?

2024-07-16 12:15 UTC, Tschakki commented on docs/docs-user/staking/stake-unstake.mdx
> +<div className="imageCaption">
this image shall give a general overview of the staking UI, for the detailed steps, I added specific images that zoom in on the relevant area, so i would prefer leaving the image at the beginning

2024-07-16 13:18 UTC, Tschakki commented on docs/docs-user/staking/stake-unstake.mdx
> +2. **Click on the `Claim` tab.**
I would only like screenshots where really necessary, but i updated the link to go directly to the correct tab, so there should be no confusion here.

2024-07-16 13:19 UTC, Tschakki commented on docs/docs-user/staking/stake-unstake.mdx
> +2. **Click on the `Unstake` tab.**
I would only like screenshots where really necessary, but i updated the link to go directly to the correct tab, so there should be no confusion here.

2024-07-17 14:21 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +
Perhaps add a paragraph title here e.g., "Example: Reward calculation for 1 vs 2 years" something like that.

2024-07-17 14:21 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +dailyRewards = 0.0905726657 LSK = 51500 / 12462098705 * 21917
```suggestion
dailyRewards = 51500 / 12462098705 * 21917 = 0.0905726657 LSK 
```

2024-07-17 14:21 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +dailyRewards = 0.15476494334 LSK = 88000 / 12462098705 * 21917
```suggestion
dailyRewards = 88000 / 12462098705 * 21917 = 0.15476494334 LSK 
```

2024-07-17 14:21 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +<div className="imageCaption">
Ok. It would be nice if you could add screenshot from Mainnet. I can provide you screenshots from my testing account if you don't want to share personal info.

2024-07-17 14:21 UTC, gkoumout commented on sidebars.js
>      },
This seems to have been addressed, so I am resolving the comment.

2024-07-17 14:24 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +After at least one day of staking, you should see an accumulated amount of your [staking rewards](staking#staking-rewards) you are eligible for until then.
```suggestion
After at least one day of staking, you should see the accumulated amount of [staking rewards](staking#staking-rewards) that you are eligible for until then.
```

2024-07-17 14:24 UTC, gkoumout commented on docs/docs-user/staking/stake-unstake.mdx
> +After at least one day of staking, you should see an accumulated amount of your [staking rewards](staking#staking-rewards) you are eligible for until then.
Optional, just looked a bit strange formulation.

2024-07-17 22:44 UTC, gkoumout reviewed
Looks good to me, just left one comment. 

Can be merged from my side, not sure if you want to add info about new features such as increase amount, pause, etc once they are available, but I guess it's not strictly necessary.

2024-07-17 22:44 UTC, gkoumout commented on docs/docs-user/staking/staking.md
> +dailyRewards = 51500 / 12462098705 * 21917 = 0.0905726657 LSK
Here we don't explain what the value 21917 is. Perhaps we can add the explanation above (e.g., line 77 saying that `totalDailyRewards` is the 8M/(3*365) = 21917.

2024-07-22 12:38 UTC, TalhaMaliktz requested changes
Please consider the following!

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/staking.md
> +LSK staking is required for participating in the [Lisk DAO](https://www.tally.xyz/gov/lisk) and having therefore an active involvement in the project's decision making. Our staking system rewards LSK
```suggestion
LSK staking is necessary to participate in the [Lisk DAO](https://www.tally.xyz/gov/lisk), ensuring active involvement in the project's decision-making. Our staking system rewards LSK stakers for participating with [staking rewards](#staking-rewards) based on their committed duration.
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/staking.md
> +- [How to stake, claim and unstake](stake-unstake.mdx)
```suggestion
- [How to stake, claim, and unstake](stake-unstake.mdx)
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/staking.md
> +Every time you [stake](stake-unstake.mdx#how-to-stake-your-lsk-tokens) a certain amount of LSK for a specific locking duration, this will create a new **locking position**.
```suggestion
Every time you [stake](stake-unstake.mdx#how-to-stake-your-lsk-tokens) a certain amount of LSK for a specific locking duration, a new **locking position** will be created.
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/staking.md
> +Staking rewards incentivize users to participate in governance, making the decision making more decentralized and community-driven.
```suggestion
Staking rewards incentivize users to participate in governance, making the decision-making more decentralized and community-driven.  
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/staking.md
> +In case you need to unlock your tokens earlier that the defined locking period, it is possible to unstake your tokens before the locking period expired by using the [early unlock](#early-unlock) opti
```suggestion
In case you need to unlock your tokens earlier than the defined locking period, it is possible to unstake your tokens before the locking period expires by using the [early unlock](#early-unlock) option.
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/staking.md
> +For example, if a user wants to fast unlock a position with 100 LSK and remaining locking duration of 150 days, then the penalty is calculated as follows:
```suggestion
For example, if a user wants to fast unlock a position with 100 LSK and a remaining locking duration of 150 days, then the penalty is calculated as follows:
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/stake-unstake.mdx
> +  <p>Image1: _Staking at the Lisk Portal_</p>
I think we can make the images look even better by adjusting the styling, especially the borders. I suggest we try using the [figcaption tag](https://www.w3schools.com/tags/tag_figcaption.asp) for the captions and remove the borders. This will give all the images a consistent and synced-up look.
```suggestion
  <p>Image 1: _Staking at the Lisk Portal_</p>
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/stake-unstake.mdx
> +    You may use the %-Buttons below to conveniently stake a certain percentage of your total LSK balance.
```suggestion
    You may use the `%` buttons above to conveniently stake a certain percentage of your total LSK balance.
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/stake-unstake.mdx
> +</div>
Same comment as above regarding the styling!

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/stake-unstake.mdx
> +4. **Verify your rewards ready to be claimed.**<br />
```suggestion
4. **Verify your rewards, ready to be claimed.**<br />
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/pause-position.mdx
> +This guide explains ste-by-step how to pause your [locking position](overview#locking-positions) countdown, in order to receive more [voting power](/governance/overview#voting-power) in the Lisk DAO.
```suggestion
This guide explains step-by-step how to pause your [locking position](overview#locking-positions) countdown, in order to receive more [voting power](/governance/overview#voting-power) in the Lisk DAO.
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/pause-position.mdx
> +5. Your locking position will now be paused, and you will see a confirmation message.
Bullet points are not displayed correctly! Please correct them.

![image](https://github.com/user-attachments/assets/6266845e-087c-417c-b5b4-0a8d501c61c2)

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/pause-position.mdx
> +If your reload the page, you should see the voting power displayed in the staking dashboard has increased accordingly.
Does pausing also have an impact on the rewards earned?

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/increase-stake.mdx
> +This guide explains ste-by-step how to increase the amount of LSK staked in a particular [locking position](overview#locking-positions).
```suggestion
This guide explains step-by-step how to increase the amount of LSK staked in a particular [locking position](overview#locking-positions).
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/extend-duration.mdx
> +This guide explains ste-by-step how to extend the duration of the countdown of a particular [locking position](overview#locking-positions).
```suggestion
This guide explains step-by-step how to extend the duration of the countdown of a particular [locking position](overview#locking-positions).
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/extend-duration.mdx
> +2. In the list of your locking positions, click on the locking position you wish to increase, to expand it.
```suggestion
2. In the list of your locking positions, click on the locking position you wish to extend, to expand it.
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/early-unlock.mdx
> +This guide explains ste-by-step how to unstake a [locking position](overview#locking-positions) before it has expired.
```suggestion
This guide explains step-by-step how to unstake a [locking position](overview#locking-positions) before it has expired.
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/early-unlock.mdx
> +6. A prompt will show up confirming the early unlock was successfull.
```suggestion
6. A prompt will show up confirming the early unlock was successful.
```

2024-07-22 12:38 UTC, TalhaMaliktz commented on docs/docs-user/staking/early-unlock.mdx
> +title: How to unstake early
I see various Metamask screen grabs in the PR, why not use them in the docs?

2024-07-22 14:52 UTC, Tschakki commented on docs/docs-user/staking/staking.md
> +LSK staking is required for participating in the [Lisk DAO](https://www.tally.xyz/gov/lisk) and having therefore an active involvement in the project's decision making. Our staking system rewards LSK
```suggestion
LSK staking is necessary to participate in the [Lisk DAO](https://www.tally.xyz/gov/lisk), enabling active involvement in the project's decision-making. Our staking system rewards LSK stakers for their participation with [staking rewards](#staking-rewards) based on their commitment duration.
```

2024-07-23 08:37 UTC, Tschakki commented on docs/docs-user/staking/early-unlock.mdx
> +title: How to unstake early
Imho they do not provide much value, and also they are specific for MetaMask wallet, users might use a different wallet

2024-07-23 08:39 UTC, Tschakki commented on docs/docs-user/staking/pause-position.mdx
> +If your reload the page, you should see the voting power displayed in the staking dashboard has increased accordingly.
yes, pausing will stop the staking rewards from declining over time.

2024-07-23 09:23 UTC, TalhaMaliktz commented on docs/docs-user/staking/early-unlock.mdx
> +title: How to unstake early
I see, please remove them from the PR then for a cleaner Git repo.

2024-07-23 09:25 UTC, Tschakki commented on docs/docs-user/staking/early-unlock.mdx
> +title: How to unstake early
done 👍

2024-07-23 09:33 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼!

2024-07-23 10:33 UTC, AndreasKendziorra requested changes

2024-07-23 10:33 UTC, AndreasKendziorra commented on docs/docs-user/staking/extend-duration.mdx
> +2. In the list of your locking positions, click on the locking position you wish to increase, to expand it.
```suggestion
2. In the list of your locking positions, click on the locking position you wish to extend, to expand it.
```

2024-07-23 10:33 UTC, AndreasKendziorra commented on docs/docs-user/staking/pause-position.mdx
> +This guide explains step-by-step how to pause your [locking position](overview#locking-positions) countdown, in order to receive more [voting power](/governance/overview#voting-power) in the Lisk DAO
Next to the higher voting power, one could also mention "to avoid that the rewards decrease daily". This may probably be of more interest for many users.

2024-07-23 10:33 UTC, AndreasKendziorra commented on docs/docs-user/staking/extend-duration.mdx
> +    <img src={extend} /><br />
The selected image displays something, which is in my opinion a bug. Because the field says "4 weeks", but the duration is actually extended by 31 days. If you a select a duration different from 4 weeks, then the result will be correct. So for example, take 5 weeks.

2024-07-23 10:33 UTC, AndreasKendziorra commented on docs/docs-user/staking/extend-duration.mdx
> +    Additionally, you can preview the amount of voting power you will gain by extending the locking position duration.
Optional: the voting power will only be increased for paused positions. To avoid confusion or even frustration for the reader, you could mention this.

2024-07-23 10:33 UTC, AndreasKendziorra commented on docs/docs-user/staking/extend-duration.mdx
> +4. Confirm the spending cap in your wallet.
This step is not required for extending.

2024-07-23 10:49 UTC, Tschakki commented on docs/docs-user/staking/extend-duration.mdx
> +    <img src={extend} /><br />
ok, i made a new one with 2 weeks

2024-07-23 11:46 UTC, AndreasKendziorra approved these changes

2024-07-23 11:47 UTC, merged