Add claiming docs
LiskHQ/lisk-docs pull request #169
Opened 2024-07-10 14:41 UTC by Tschakki

### What was the problem?

This PR resolves #154 

### How was it tested?

2024-07-11 12:40 UTC, AndreasKendziorra requested changes

2024-07-11 12:40 UTC, AndreasKendziorra commented on docs/docs-user/claiming.mdx
> +1. An account on the Lisk L1 legacy chain, with some LSK tokens.
It would be good to add that this account must hold some LSK tokens at the snapshot height `24,823,618`. And it should be made clear that the balance at this height is exactly the one that can be claimed.

2024-07-11 12:40 UTC, AndreasKendziorra commented on docs/docs-user/claiming.mdx
> +    If you haven't already connect your wallet with the portal on the top right corner.
```suggestion
    If you haven't already, connect your wallet with the portal on the top right corner.
```

2024-07-11 12:40 UTC, AndreasKendziorra commented on docs/docs-user/claiming.mdx
> +  This will open a MetaMask prompt, where you can verify the claim you are intending to make.
It will only be MetaMask if you connected with MetaMask before, but not if you connected with another wallet.

2024-07-11 12:40 UTC, AndreasKendziorra commented on static/img/docs/claiming/7-sign-prompt-confirm.png
this picture is not used

2024-07-11 12:40 UTC, AndreasKendziorra commented on static/img/docs/claiming/Screenshot 2024-07-10 at 15.32.46.png
This is also not used, right?

2024-07-11 14:11 UTC, Tschakki commented on static/img/docs/claiming/7-sign-prompt-confirm.png
yes, i removed it again, as i think it doesn't add much value, i can remove it

2024-07-11 14:11 UTC, Tschakki commented on static/img/docs/claiming/Screenshot 2024-07-10 at 15.32.46.png
yes, will remove

2024-07-11 14:37 UTC, Phanco commented on docs/docs-user/claiming.mdx
> +    This will open a WalleConnect prompt.
```suggestion
    This will open a WalletConnect prompt.
```

2024-07-11 14:37 UTC, Phanco commented on docs/docs-user/claiming.mdx
> +5. Open the [Lisk Migration Wallet](https://lisk.com/wallet) and sign in with the account you intend to migrate.
Although the gitbook is showing the number correctly. 4 is skipped here

2024-07-11 14:37 UTC, Phanco commented on docs/docs-user/claiming.mdx
> +Make sure you have the latest version of the Lisk Migration Wallet installed (3.0.3).
Do you think we need to teach them how to know the version of the Lisk Wallet?

2024-07-11 15:17 UTC, Tschakki commented on docs/docs-user/claiming.mdx
> +Make sure you have the latest version of the Lisk Migration Wallet installed (3.0.3).
good idea, added

2024-07-12 07:30 UTC, TalhaMaliktz requested changes
Please consider the following!

2024-07-12 07:30 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +1. Open [claiming page on the Lisk Portal](https://portal.lisk.com/claim/regular-account) in the browser. <br />
```suggestion
1. Open the [Claim Tokens page on the Lisk Portal](https://portal.lisk.com/claim/regular-account) in the browser. <br />
```

2024-07-12 07:30 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +2. On the **claiming page**, click `Connect Lisk account` button.
```suggestion
2. On the **Claim Tokens page**, click the `Connect Lisk account` button.
```

2024-07-12 07:30 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +    <img src={signMessage} />
Please upload a high-res image! the current is blurred out.

2024-07-12 07:30 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +  <img src={claimSubmit} />
Please upload a high-res image! the current is blurred out.

2024-07-12 07:30 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +  The account must hold some LSK tokens at the snapshot height `24,823,618`.
```suggestion
  The account must hold some LSK tokens at the snapshot height of `24,823,618`.
```

2024-07-12 07:30 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +    <img src={walletPrompt} width="40%"/>
The screenshot is of low quality and doesn't display the entire window! Please replace this with a higher-quality image that shows everything discussed in this bullet point.

2024-07-12 07:30 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +7. Paste the connection URI you just copied in step 3 an press `Connect`.
```suggestion
7. Paste the connection URI you just copied in step 3 and press `Connect`. 
```

2024-07-12 07:30 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +  This will open a wallet prompt, where you can verify the claim you are intending to make.
```suggestion
  This will open a wallet prompt, where you can verify the claim you intend to make.
```

2024-07-12 07:30 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +After you completed the claiming process, you can check the **transaction receipt** on the claiming page in the Lisk Portal, to verify that the claiming of the LSK tokens was executed successfully.
```suggestion
After you complete the claiming process, you can check the **transaction receipt** on the claiming page in the Lisk Portal, to verify that the claiming of the LSK tokens was executed successfully.
```

2024-07-12 07:55 UTC, Tschakki commented on docs/docs-user/claiming.mdx
> +    <img src={walletPrompt} width="40%"/>
entire window is too big, it is cut intentionally

2024-07-12 07:56 UTC, TalhaMaliktz commented on docs/docs-user/claiming.mdx
> +    <img src={walletPrompt} width="40%"/>
I mean just the connect account window, like the pop-up!

2024-07-12 08:10 UTC, Tschakki commented on docs/docs-user/claiming.mdx
> +    <img src={walletPrompt} width="40%"/>
yes, it is cut intentionally

2024-07-12 09:14 UTC, TalhaMaliktz approved these changes
LGTM! 👍🏼

2024-07-12 10:47 UTC, Phanco approved these changes

2024-07-15 06:19 UTC, AndreasKendziorra approved these changes

2024-07-15 09:59 UTC, merged