Create guide how to deploy contracts with Hardhat
LiskHQ/lisk-docs pull request #17
Opened 2024-01-18 13:28 UTC by Tschakki

Closes #11

2024-01-22 18:43 UTC, Phanco commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +    function mint(address recipient) public payable returns (uint256) {
Small suggestion: remove `payable` since no native currency/ETH is involved in this function

2024-01-22 18:46 UTC, Phanco commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +✔ Hardhat project root: · /Users/mona/git/hardhat-test
Do you want mona be shown here? :P

2024-01-22 18:59 UTC, Phanco commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +            apiURL: "https://lisk-sepolia.blockscout.com/api",
URL has been changed to `https://sepolia-blockscout.lisk.com/`

2024-01-22 18:59 UTC, Phanco commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +https://lisk-sepolia.blockscout.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D#code
and here too

2024-01-22 19:13 UTC, Phanco commented
Commented, other parts look great :D

2024-01-23 09:41 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +✔ Hardhat project root: · /Users/mona/git/hardhat-test
updated :)

2024-01-24 08:55 UTC, Phanco approved these changes

2024-01-24 12:07 UTC, TalhaMaliktz requested changes
Please consider the following.

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +In case your wallet doesn't hold enough `SepoliaETH`, use one of the available faucets for the Ethereum Sepolia Testnet, like [https://sepoliafaucet.com](https://sepoliafaucet.com/) to receive free T
```suggestion
In case your wallet doesn't hold enough `SepoliaETH`, use one of the available faucets for the **Ethereum Sepolia** Testnet like [https://sepoliafaucet.com](https://sepoliafaucet.com/) to receive free Testnet ETH.
Then, use the aforementioned Lisk Bridge to send tokens from the **Ethereum Sepolia Testnet** to the **Lisk Sepolia Testnet**.
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +You can view the deployment status and contract by using a block explorer and searching for the address returned by your deploy script.
Please add a TODO about linking it to the block explorer section. Will add the link once I am done with the Network Information page.

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +The above contract has already been verified, so you should be able to view your version on a block explorer already.
I think the above contract wasn't verified, otherwise, it wouldn't have shown the verified message that you are describing below. 
```suggestion
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> + },
```suggestion
const config: HardhatUserConfig = {
  // Add the following information after the "networks" configuration
  etherscan: {
     apiKey: {
      "lisk-sepolia": ""
     },
     customChains: [
      {
          network: "lisk-sepolia",
          chainId: 4202,
          urls: {
              apiURL: "https://sepolia-blockscout.lisk.com/api",
              browserURL: "https://sepolia-blockscout.lisk.com"
          }
       }
     ]
   },
   sourcify: {
    enabled: false
  },
};
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +Message: Already Verified
For me it didn't throw an error. I got the following reponse
```suggestion
If you attempt to do so, such as verifying the above contract, you'll get a message similar to:

```text                                                                      
The contract 0x5B814018c5a002895d0292365cC5a90f1f2d4dCb has already been verified on Etherscan.
https://sepolia-blockscout.lisk.com/address/0x5B814018c5a002895d0292365cC5a90f1f2d4dCb#code
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +View your contract on BlockScout, by following the [link](https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D?tab=contract) displayed in the output message, to conf
```suggestion
View your contract on BlockScout, by following the [link to the deployed contract](https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D?tab=contract) displayed in the previous steps output message.
The block explorer will confirm that the contract is verified.
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +After [the contract is verified](#verifying-the-smart-contract), you can use the `Read Contract` and `Write Contract` tabs to interact with the deployed contract via [BlockScout](https://sepolia-bloc
```suggestion
After [the contract is verified](#verifying-the-smart-contract), you can use the `Read Contract` and `Write Contract` tabs to interact with the deployed contract via [BlockScout](https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D?tab=contract).
Don't forget to update the `contract address` in the aforementioned URL.
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +You'll need to connect your wallet first, by clicking the `Connect Wallet` button.
```suggestion
You'll also need to connect your wallet first, by clicking the `Connect Wallet` button on the `Blockscout Contract Explorer Page`.
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +
There's a horizontal line at the end of this section, do you see it too? I am looking at the branch locally.

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +This guide requires you have Node version 18+ installed.
```suggestion
This guide requires you to have Node version 18+ installed.
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +Substite `<YOUR_PRIVATE_KEY>` with the private key for your wallet.
```suggestion
Substitute `<YOUR_PRIVATE_KEY>` with the private key for your wallet.
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +If you want to interact with your contract on the block explorer, you, or someone, needs to verify it first.
```suggestion
If you want to interact with your contract on the block explorer, you, or someone, else needs to verify it first.
```

2024-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +For the remainder of this guide, we'll walk through how to verify your contract on Lisk Sepolia testnet.
```suggestion
For the remainder of this guide, we'll walk through how to verify your contract on the Lisk Sepolia Testnet.
```

2024-01-24 12:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +
```suggestion
The `apiKey` is the private key of the account used to deploy the contract.

```

2024-01-24 12:28 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +---
Since we don't have a horizontal line on other pages.
```suggestion
```

2024-01-24 12:32 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +If you want to interact with your contract on the block explorer, you, or someone, needs to verify it first.
```suggestion
If you want to interact with your contract on the block explorer, you, or someone else needs to verify it first.
```

2024-01-24 12:34 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +The above contract has already been verified, so you should be able to view your version on a block explorer already.
Yes because I was doing it the first time, but if you deployed the same contract, you should see a message that it is already verified.

2024-01-24 12:37 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +
not true

2024-01-24 12:38 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +
Agreed, We should add something about the error that I got. If you encounter this error about `apiKey` try a random value like `123` or something.

2024-01-24 12:40 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +The above contract has already been verified, so you should be able to view your version on a block explorer already.
Output for already verified contracts is described below

2024-01-24 12:43 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +View your contract on BlockScout, by following the [link](https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D?tab=contract) displayed in the output message, to conf
```suggestion
View your contract on BlockScout, by following the [link to the deployed contract](https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D?tab=contract) displayed in the previous steps output message.
The block explorer will confirm that the contract is verified and allow you to [interact](#interacting-with-the-smart-contract) with it.
```

2024-01-24 12:47 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +After [the contract is verified](#verifying-the-smart-contract), you can use the `Read Contract` and `Write Contract` tabs to interact with the deployed contract via [BlockScout](https://sepolia-bloc
contract address should be the same if they deployed the same contract I think

2024-01-24 12:48 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +You'll need to connect your wallet first, by clicking the `Connect Wallet` button.
```suggestion
You'll also need to connect your wallet first, by clicking the `Connect Wallet` button.
```

2024-01-24 12:49 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +---
we can remove for now, but we can consider to add a section at the bottom of each page for feedback, like base

2024-01-24 13:24 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +
I updated the config 👍

2024-01-25 09:40 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +After [the contract is verified](#verifying-the-smart-contract), you can use the `Read Contract` and `Write Contract` tabs to interact with the deployed contract via [BlockScout](https://sepolia-bloc
For me, the contract address was different as I deployed it too. `0x5B814018c5a002895d0292365cC5a90f1f2d4dCb` and this is how it should be I think, since the contract that you deployed has already got a unique address and when I try to deploy the same contract again, it will be deployed on a different unique address. The purpose of this statement is to inform the reader that, if you want to see your contract on blockscout, use the same URL but change the contract address with the one that you got after deploying it.

2024-01-25 10:01 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +You can view the deployment status and contract by using a block explorer and searching for the address returned by your deploy script.
done 👍

2024-01-25 10:59 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +After [the contract is verified](#verifying-the-smart-contract), you can use the `Read Contract` and `Write Contract` tabs to interact with the deployed contract via [BlockScout](https://sepolia-bloc
```suggestion
After [the contract is verified](#verifying-the-smart-contract), you can use the `Read Contract` and `Write Contract` tabs to interact with the deployed contract via [BlockScout](https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D?tab=contract).
Don't forget to update the contract address in the Blockscout URL.
```

2024-01-25 13:44 UTC, TalhaMaliktz reviewed
Please update the `sidebar.js` to add the following item in the navbar!
`'building-on-lisk/deploying-a-smart-contract'`

2024-01-25 13:44 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +Next, you will need to install Hardhat and create a new Hardhat project.
```suggestion
Next, you will need to install [Hardhat](https://hardhat.org/tutorial) and create a new Hardhat project.
```

2024-01-25 13:44 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +https://sepolia-blockscout.lisk.com/address/0x5B814018c5a002895d0292365cC5a90f1f2d4dCb#code
To be in sync with **263-268**
```suggestion
The contract 0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D has already been verified on Etherscan.
https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D#code
```

2024-01-25 13:47 UTC, TalhaMaliktz commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +    // Use "123" as placeholder, because Blockscout doesn't need a real API key, and hardhat will complain if this property isn't set.
```suggestion
    // Use "123" as a placeholder, because Blockscout doesn't need a real API key, and Hardhat will complain if this property isn't set.
```

2024-01-26 08:59 UTC, TalhaMaliktz approved these changes
Thank you. LGTM 👍🏼

2024-01-26 09:26 UTC, merged