Update smart contract page
LiskHQ/lisk-docs pull request #179
Opened 2024-07-25 13:19 UTC by TalhaMaliktz

### What was the problem?

This PR resolves #157 

### How was it tested?

https://liskhq.github.io/lisk-documentation/contracts

2024-07-25 16:32 UTC, Tschakki requested changes

2024-07-25 16:32 UTC, Tschakki commented on docs/building-on-lisk/contracts.mdx
> +### Vesting Wallets (L1)
Vesting wallets should not be included here, please remove

2024-07-25 16:32 UTC, Tschakki commented on docs/building-on-lisk/contracts.mdx
> +### Vesting Wallets (L2)
Same as above, Vesting wallets should not be listed here

2024-07-26 06:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.mdx
> +### Vesting Wallets (L1)
Why? Aren't these smart contracts as well?

2024-07-26 08:47 UTC, Tschakki commented on docs/building-on-lisk/contracts.mdx
> +### Vesting Wallets (L1)
Technically yes, but this is not relevant for devs to know the vesting wallets of the team for example

2024-07-26 12:30 UTC, Tschakki approved these changes
LGTM, just left some small suggestions 👍

2024-07-26 12:30 UTC, Tschakki commented on docs/building-on-lisk/contracts.mdx
> +### ERC-20 tokens deployed on Lisk L2
```suggestion
### ERC-20 tokens deployed on Lisk
```

2024-07-26 12:30 UTC, Tschakki commented on docs/building-on-lisk/contracts.mdx
> +### Lisk features-specific contracts (L2)
```suggestion
### Lisk features-specific contracts
```

2024-07-26 12:30 UTC, Tschakki commented on docs/building-on-lisk/contracts.mdx
> +### Predeploys (L2)
```suggestion
### Predeploys on Lisk
```

2024-07-26 12:30 UTC, Tschakki commented on docs/building-on-lisk/contracts.mdx
> +### Lisk features-specific contracts (L2)
would remove the L2 because it is already mentioned in parent section

2024-07-29 13:30 UTC, nagdahimanshu commented on docs/building-on-lisk/contracts.mdx
> +      <td scope="row" rowSpan="2">Handles the sending and receiving of messages between L1 and L2.</td>
Isn't it handles the sending and receiving of ERC721 tokens from L1 to L2?

2024-07-29 13:49 UTC, nagdahimanshu commented on docs/building-on-lisk/contracts.mdx
> +       <td scope="row" rowSpan="2"> Proxy contract for claiming LSK tokens from Lisk Chain on L2.</td>
Isn't it is better to mention Lisk chain (L1 or v4) here?

2024-07-31 08:09 UTC, nagdahimanshu approved these changes
LGTM 👍

2024-08-01 08:19 UTC, merged