Create Lisk L2's Introduction page.
LiskHQ/lisk-docs pull request #18
Opened 2024-01-23 12:29 UTC by TalhaMaliktz

Closes #6

2024-01-23 15:15 UTC, Tschakki requested changes

2024-01-23 15:15 UTC, Tschakki commented on docs/intro.md
> +### Why Lisk L2? and Who is it for?
Would remove this heading
```suggestion
```

2024-01-23 15:15 UTC, Tschakki commented on docs/intro.md
> +Lisk is based on [Optimism's L2 rollup](https://docs.optimism.io/), and it is already contributing to [Optimism's Super chain's philosophy](https://docs.optimism.io/stack/explainer).
In the first paragraph, focus first on describing the general purpose/goal of Lisk, e.g.

```suggestion
Built on the [OP Stack](https://docs.optimism.io/), Lisk contributes to scaling Ethereum to a level where blockchain infrastructure is ready for mass adoption.
```

2024-01-23 15:15 UTC, Tschakki commented on docs/intro.md
> +By being part of the Superchain: Lisk offers a network of chains that share bridging, decentralized governance, regular upgrades, a communication layer, and more—all built on the OP Stack, and secure
I am not sure if we should to mention Gelato as a feature here, it's nothing the user directly sees/profits from afaik.
Please read the "Lisk Division Plan" document to find other things to mention, I added a suggestion below.
```suggestion
## Superchain contributor
The [Superchain](https://docs.optimism.io/stack/explainer) is a network of chains that share bridging, decentralized governance, regular upgrades, a communication layer, and more — all built on the [OP Stack](https://docs.optimism.io/), and secured by Ethereum.
With Optimism's Super chain initiative, Lisk is participating in building the future we always believed in, which is an interoperable, seamless base layer that provides a great user experience, shared liquidity, and cheap transactions to ensure that web3 revolutionizes peoples' lives just as web2 did.

## Focus on real-world use cases
At Lisk, we believe that blockchain technology can solve many existing problems regarding centralization and governance in the real world, if applied meaningfully. 
That's why Lisk aims to become a platform for real-world use-cases on Ethereum, featuring a variety of web3 apps, especially around the topics "Decentralized Physical Infrastructure Networks" (DePIN), and real world assets (RWAs).
```

2024-01-23 15:15 UTC, Tschakki commented on docs/intro.md
> +For more information, see [Optimism's roll-up protocol](https://docs.optimism.io/stack/protocol/overview) and the [How it ensures Fault Proof?](https://docs.optimism.io/stack/protocol/overview#fault-
You are talking here about a very specific aspect of secuirty, which is already explained in detail in the OP docs. Imho it would be better to give a highlevel overview about security in Lisk.

For example, the following pages can help with more context: 
- https://docs.optimism.io/chain/security/faq
- https://optimism.help/Token+House+Governance/Security+Council/Intro+to+Optimism's+Security+Council

2024-01-23 15:15 UTC, Tschakki commented on docs/intro.md
> +Lisk is an Optimism stack chain and it is designed to be EVM equivalent, however, there are a few differences between [Ethereum and Optimism stack chains](https://docs.optimism.io/stack/differences),
Would move this sentence above the first one.
```suggestion
Lisk is an Optimism stack chain and it is designed to be [EVM equivalent](https://web.archive.org/web/20231127160757/https://medium.com/ethereum-optimism/introducing-evm-equivalence-5c2021deb306), however, there are a few differences between [Ethereum and Optimism stack chains](https://docs.optimism.io/stack/differences), which developers should be aware of.
```

2024-01-23 15:15 UTC, Tschakki commented on docs/intro.md
> +Any L2 based on Optimism is designed so that users can send arbitrary messages between smart contracts on L2 (OP Mainnet, OP Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). Th
Why mention erc20 specifically? Is it not possible to transfer ERC721 tokens for example?

2024-01-23 15:15 UTC, Tschakki commented on docs/intro.md
> +Lisk is among the initial members joining Optimism's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and Optimism teams.
I am not sure what this section is about - title and content don't seem to match.

2024-01-24 06:54 UTC, TalhaMaliktz commented on docs/intro.md
> +Any L2 based on Optimism is designed so that users can send arbitrary messages between smart contracts on L2 (OP Mainnet, OP Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). Th
Ummmm! Read the Optimism docs and that's where I got this Info. Maybe it is also possible to move other tokens! Will look into it.

2024-01-24 06:55 UTC, TalhaMaliktz commented on docs/intro.md
> +Lisk is among the initial members joining Optimism's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and Optimism teams.
This is a brief intro about the team owning/working on the project. Similar to how base has it in their docs.

2024-01-24 06:59 UTC, TalhaMaliktz commented on docs/intro.md
> +By being part of the Superchain: Lisk offers a network of chains that share bridging, decentralized governance, regular upgrades, a communication layer, and more—all built on the OP Stack, and secure
I don't know if we want to publicize the focus, on RWA/DePIN from this moment, I read the document and got the impression that for starters we are just similar to Base and later we can elaborate more on the differences. I think we can discuss this to be sure about what we can publicize at this time.

I am moving this to a slack thread to get clarity.

2024-01-25 14:22 UTC, Tschakki requested changes

2024-01-25 14:22 UTC, Tschakki commented on docs/about-lisk/_category_.json
> +    "description": "Following are the most important topics, that aid in understanding Lisk."
imho the original description is clearer

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +With Optimism's Super chain initiative, Lisk is participating in building the future it always believed in, which is an interoperable, seamless base layer that provides a great user experience, share
From the perspective of a reader first discovering Lisk, it is confusing to talk about the benefits of participating superchain initiative, without mentioning that Lisk is built on the OP stack and also participates in the superchain initiative. This info should be provided before. Please also add the relevant links regarding Optimism and superchain.

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +With [Gelato](https://www.gelato.network/) as a professional Rollup-as-a-Service provider and the battle-tested [OP stack](https://docs.optimism.io/stack/getting-started), we operate a highly reliabl
I still think we should not mention Gelato as one of our main features. We can mention it along woth the info that Lisk is built on the OP stack, at the beginning of the introduction.

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +By being part of the Superchain: Lisk offers a network of chains that share bridging, decentralized governance, regular upgrades, a communication layer, and more—all built on the OP Stack, and secure
this should be merged with the above content about the superchain

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +Lisk L2 is part of the [Optimism collective](https://community.optimism.io/docs/governance/) and Optimism is seeking to establish a [Security Council](https://optimism.help/Token+House+Governance/Sec
Are we really part of this collective? 
Also, when skimming over the Security council page, it looks like a initiative which will be implemented fully in the future, together with the superchain. Currently, contracts are updated via a multisig wallet. For Lisk, we need to provide the Lisk-specific information about this topic.

Please double-check.

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +Furthermore, Optimism's mainnet continuously keeps it in sync with the Ethereum L1 to ensure the security and validity of its network.
Please verify that this is true for Lisk as well, and if, replace `Optimism` with `Lisk`

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +This means that apart from the measures taken to secure the Superchain and Optimism's mainnet, the L1 security of Ethereum is also available to users interacting with Lisk L2.
```suggestion
This means that apart from the measures taken to secure the Superchain and Lisk's mainnet, the L1 security of Ethereum is also available to users interacting with Lisk L2.
```

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +For more information, see [Optimism's roll-up protocol](https://docs.optimism.io/stack/protocol/overview) and the [How it ensures Fault Proof?](https://docs.optimism.io/stack/protocol/overview#fault-
```suggestion
For more information, see [Optimism's roll-up protocol](https://docs.optimism.io/stack/protocol/overview) and the [How it ensures Fault Proof?](https://docs.optimism.io/stack/protocol/overview#fault-proofs) section.
```

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +For more information on the tokens available on Optimism see, [Optimism Tokens](https://cryptorank.io/blockchains/optimism).
```suggestion
For more information on the tokens available on Lisk see, [Optimism Tokens](https://cryptorank.io/blockchains/optimism).
```

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +As a long-standing Web3 infrastructure project, Lisk has been democratizing blockchain accessibility for developers and end users globally since 2016.
Imho this can be removed.

```suggestion
```

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +Lisk L2 is built on the MIT-Licensed OP Stack, in collaboration with Optimism.
Would move this info to beginning of introduction.

2024-01-25 14:22 UTC, Tschakki commented on docs/intro.md
> +Lisk is among the initial members joining Optimism's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and Optimism teams.
Would merge with section about superchain

2024-01-25 15:05 UTC, Tschakki commented on docs/intro.md
> +Any L2 based on Optimism is designed so that users can send arbitrary messages between smart contracts on L2 (OP Mainnet, OP Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). Th
```suggestion
Any L2 based on Optimism is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). This makes it possible to transfer ETH or tokens such as ERC20, ERC721 tokens, etc. between the two networks.
```

2024-01-25 15:20 UTC, TalhaMaliktz commented on docs/intro.md
> +Furthermore, Optimism's mainnet continuously keeps it in sync with the Ethereum L1 to ensure the security and validity of its network.
AFAIK! It is! Every L2 has to continuously be in sync with ETH L1, otherwise there will be inconsistency in the network.

2024-01-26 09:09 UTC, Tschakki approved these changes
Looking great! 🎉

2024-01-26 09:55 UTC, Tschakki commented on docs/intro.md
> +For more information, see [OP's roll-up protocol](https://docs.optimism.io/stack/protocol/overview) and the [How it ensures Fault Proof?](https://docs.optimism.io/stack/protocol/overview#fault-proofs
I would put this info first before talking about governance (remove `Furthermore`, too)

2024-01-26 09:56 UTC, Tschakki commented on docs/intro.md
> +At the moment, it's important to understand that the security of Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-s
```suggestion
At the moment, the security of Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) managed by several anonymous individuals.
```

2024-01-26 09:57 UTC, Tschakki commented on docs/intro.md
> +Such measures will ensure that decisions like using distributed sequencers, proposers, challengers, etc. can be made unanimously with the agreement of all the members of the Super chain and the Secur
please double check this is true for Lisk as well

2024-01-26 10:04 UTC, TalhaMaliktz commented on docs/intro.md
> +Such measures will ensure that decisions like using distributed sequencers, proposers, challengers, etc. can be made unanimously with the agreement of all the members of the Super chain and the Secur
@shuse2 Can you please confirm this?

2024-01-26 10:58 UTC, Tschakki commented on docs/intro.md
> +This means that apart from the measures taken to secure the Superchain and Lisk's mainnet, the L1 security of Ethereum is also available to users interacting with Lisk L2.
Please move this before the first paragraph

2024-01-29 11:05 UTC, Tschakki commented on docs/building-on-lisk/deploying-a-smart-contract.md
> +title: Deploying a smart contract on Hardhat
```suggestion
title: Deploying a smart contract using Hardhat
```
or
```suggestion
title: Deploying a smart contract with Hardhat
```

2024-01-30 09:19 UTC, sameersubudhi requested changes

2024-01-30 09:19 UTC, sameersubudhi commented on docs/intro.md
> +With [OP's Super chain](https://docs.optimism.io/stack/explainer) initiative, Lisk is participating in building the future it always believed in, which is to develop an interoperable, seamless base l
As per Optimism's [documentation](https://docs.optimism.io/stack/explainer), `Superchain` must be a single word.
```suggestion
With [Optimism's Superchain](https://docs.optimism.io/stack/explainer) initiative, Lisk is participating in building the future it always believed in, which is to develop an interoperable, seamless base layer that provides a great user experience, shared liquidity, and cheap transactions to ensure that **web3** revolutionizes peoples' lives just as **web2** did.
```

2024-01-30 09:19 UTC, sameersubudhi commented on docs/intro.md
> +By being part of the Superchain: Lisk offers a network of chains that share bridging, decentralized governance, regular upgrades, a communication layer, and more—all built on the OP Stack, and secure
```suggestion
By being part of the Superchain, Lisk offers a network of chains that share bridging, decentralized governance, regular upgrades, a communication layer, and more—all built on the OP Stack while being secured by Ethereum.
```

2024-01-30 09:19 UTC, sameersubudhi commented on docs/intro.md
> +Lisk's mainnet continuously keeps it in sync with the Ethereum L1 to ensure the security and validity of its network.
`continuous` can be quite a vague term here. @shuse2 do we know how often will we sync with the Ethereum L1? If we don't yet know, we can leave a TODO to update it later?

2024-01-30 09:19 UTC, sameersubudhi commented on docs/intro.md
> +For more information, see [OP's roll-up protocol](https://docs.optimism.io/stack/protocol/overview) and its [Fault Proof?](https://docs.optimism.io/stack/protocol/overview#fault-proofs) section.
```suggestion
For more information, see [OP's rollup protocol](https://docs.optimism.io/stack/protocol/overview) and its [Fault Proof?](https://docs.optimism.io/stack/protocol/overview#fault-proofs) section.
```

2024-01-30 09:19 UTC, sameersubudhi commented on docs/intro.md
> +Lisk is among the initial members joining OP's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and OP teams.
Should we be using `OP` instead of `Optimism` throughout?
```suggestion
Lisk is among the initial members joining Optimism's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and Optimism teams.
```

2024-01-30 09:19 UTC, sameersubudhi commented on docs/intro.md
> +Such measures will ensure that decisions like using distributed sequencers, proposers, challengers, etc. can be made unanimously with the agreement of all the members of the Super chain and the Secur
```suggestion
Such measures will ensure that decisions like using distributed sequencers, proposers, challengers, etc. can be made unanimously with the agreement of all the members of the Superchain and the Security Council.
```

2024-01-30 09:19 UTC, sameersubudhi commented on docs/intro.md
> +However, Lisk L2 is part of the [Optimism collective](https://community.optimism.io/docs/governance/) and OP is seeking to establish a [Security Council](https://optimism.help/Token+House+Governance/
```suggestion
However, Lisk L2 is part of the [Optimism collective](https://community.optimism.io/docs/governance/) and Optimism is seeking to establish a [Security Council](https://optimism.help/Token+House+Governance/Security+Council/Intro+to+Optimism's+Security+Council), for distributed governance, and equal participation of all OP stack chains to the superchain.
```

2024-01-30 09:19 UTC, sameersubudhi commented on docs/intro.md
> +Any L2 based on OP is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). This
```suggestion
Any L2 based on Optimism is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). This makes it possible to transfer ETH or tokens such as ERC20, ERC721 tokens, etc. between the two networks.
```

2024-01-30 09:20 UTC, TalhaMaliktz commented on docs/intro.md
> +Lisk is among the initial members joining OP's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and OP teams.
Since we have abbreviated Optimism to OP at the start, we should use OP throughout.

2024-01-30 09:23 UTC, TalhaMaliktz commented on docs/intro.md
> +With [OP's Super chain](https://docs.optimism.io/stack/explainer) initiative, Lisk is participating in building the future it always believed in, which is to develop an interoperable, seamless base l
```suggestion
With [OP's Superchain](https://docs.optimism.io/stack/explainer) initiative, Lisk is participating in building the future it always believed in, which is to develop an interoperable, seamless base layer that provides a great user experience, shared liquidity, and cheap transactions to ensure that **web3** revolutionizes peoples' lives just as **web2** did.
```

2024-01-30 09:24 UTC, TalhaMaliktz commented on docs/intro.md
> +However, Lisk L2 is part of the [Optimism collective](https://community.optimism.io/docs/governance/) and OP is seeking to establish a [Security Council](https://optimism.help/Token+House+Governance/
```suggestion
However, Lisk L2 is part of the [Optimism collective](https://community.optimism.io/docs/governance/) and OP is seeking to establish a [Security Council](https://optimism.help/Token+House+Governance/Security+Council/Intro+to+Optimism's+Security+Council), for distributed governance, and equal participation of all OP stack chains to the superchain.
```

2024-01-30 09:25 UTC, TalhaMaliktz commented on docs/intro.md
> +Any L2 based on OP is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). This
The reason to use OP is mentioned earlier.

2024-01-30 09:30 UTC, TalhaMaliktz commented on docs/intro.md
> +Lisk's mainnet continuously keeps it in sync with the Ethereum L1 to ensure the security and validity of its network.
Yeah, I got this impression after reading this rollup protocol page! I don't remember the exact line TBH
https://docs.optimism.io/stack/protocol/overview. 

It makes sense that the network should be in sync with L1 regularly to avoid inconsistencies so we can change the terminology to say that L1 and L2 are kept in sync after regular intervals.

2024-01-30 11:58 UTC, sameersubudhi approved these changes
Looks good but please take the following recommendations into consideration.

2024-01-30 11:58 UTC, sameersubudhi commented on docs/intro.md
> +Built on the MIT-Licensed [OP Stack](https://docs.optimism.io/stack/getting-started) and partnered with [Gelato](https://www.gelato.network/) as a RaaS provider, Lisk contributes to scaling Ethereum
```suggestion
Built on the MIT-licensed [OP Stack](https://docs.optimism.io/stack/getting-started) and partnered with [Gelato](https://www.gelato.network/) as a RaaS provider, Lisk contributes to scaling Ethereum to a level where blockchain infrastructure is ready for mass adoption.
```

2024-01-30 11:58 UTC, sameersubudhi commented on docs/intro.md
> +Lisk is among the initial members joining OP's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and OP teams.
Since it's a claim, it'd be nice to hyperlink `initial members` text with some official Optimism resource, if available.

```suggestion
Lisk is among the initial members joining OP's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and OP teams.
```

2024-01-30 11:58 UTC, sameersubudhi commented on docs/intro.md
> +For more information, see [OP's rollup protocol](https://docs.optimism.io/stack/protocol/overview) and its [Fault Proof?](https://docs.optimism.io/stack/protocol/overview#fault-proofs) section.
```suggestion
For more information, see [OP's rollup protocol](https://docs.optimism.io/stack/protocol/overview) and its [Fault Proof](https://docs.optimism.io/stack/protocol/overview#fault-proofs) section.
```

2024-01-30 11:58 UTC, sameersubudhi commented on docs/intro.md
> +This multisig wallet can be used to upgrade core Lisk Mainnet smart contracts without upgrade delays.
For consistency across the document.
```suggestion
At the moment, the security of Lisk mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) managed by several anonymous individuals.
This multisig wallet can be used to upgrade core Lisk mainnet smart contracts without upgrade delays.
```

2024-01-30 11:58 UTC, sameersubudhi commented on docs/intro.md
> +Lisk is an OP stack chain and it is designed to be [EVM equivalent](https://web.archive.org/web/20231127160757/https://medium.com/ethereum-optimism/introducing-evm-equivalence-5c2021deb306), however,
```suggestion
Lisk is an OP stack chain and is designed to be [EVM equivalent](https://web.archive.org/web/20231127160757/https://medium.com/ethereum-optimism/introducing-evm-equivalence-5c2021deb306). However, there are a few differences between [Ethereum and OP stack chains](https://docs.optimism.io/stack/differences), which developers should be aware of.
```

2024-01-30 11:58 UTC, sameersubudhi commented on docs/intro.md
> +Any L2 based on OP is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). This
```suggestion
Any L2 based on OP is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). This makes it possible to transfer ETH or tokens such as ERC20, ERC721 tokens, etc. between the two networks.
```

2024-01-30 12:04 UTC, TalhaMaliktz commented on docs/intro.md
> +Lisk is among the initial members joining OP's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and OP teams.
As far as I researched, I couldn't find such a page where OP lists all their partners

2024-01-30 12:05 UTC, TalhaMaliktz commented on docs/intro.md
> +This multisig wallet can be used to upgrade core Lisk Mainnet smart contracts without upgrade delays.
To be aligned with OP, we are using `Mainnet` instead of `mainnet`.

2024-01-30 12:05 UTC, TalhaMaliktz commented on docs/intro.md
> +Any L2 based on OP is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum mainnet, Sepolia, etc.). This
Same comment as above

2024-01-30 12:12 UTC, TalhaMaliktz commented on docs/intro.md
> +Lisk's mainnet continuously keeps it in sync with the Ethereum L1 to ensure the security and validity of its network.
I have re-phrased the sentence!

2024-01-31 16:52 UTC, shuse2 requested changes

2024-01-31 16:52 UTC, shuse2 commented on docs/intro.md
> +## How secure is Lisk L2?
```suggestion
## How secure is Lisk?
```
i would avoid saying `Lisk L2` unless we are specifically talking about differentiation between L1 or L2 or something similar. same for other places

2024-01-31 16:52 UTC, shuse2 commented on docs/intro.md
> +Lisk is among the initial members joining OP's Superchain initiative, and the Lisk L2 will be scaled and built by the experienced Lisk and OP teams.
I'm not sure if we can say this. 
* Im not sure if we can classify as "Initial" members
* Avoid Lisk L2 with the reason above
* we are not part of "core" contributors yet

2024-01-31 16:52 UTC, shuse2 commented on docs/intro.md
> +However, Lisk L2 is part of the [Optimism collective](https://community.optimism.io/docs/governance/) and OP is seeking to establish a [Security Council](https://optimism.help/Token+House+Governance/
i would avoid abbreviation when mentioning Optimism

2024-01-31 16:52 UTC, shuse2 commented on docs/intro.md
> +Any L2 based on OP is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum Mainnet, Sepolia, etc.). This
OP => OP stack or op-stack (pls check with their documentation

2024-01-31 16:58 UTC, shuse2 commented on docs/intro.md
> +Such measures will ensure that decisions like using distributed sequencers, proposers, challengers, etc. can be made unanimously with the agreement of all the members of the Super chain and the Secur
Optimism collective is umbrella term including op-stack or ecosystem overall. Within that we are part of superchain which will be govern by the security council. not all op stack chains are superchain participants

2024-02-01 10:57 UTC, shuse2 commented on docs/intro.md
> +At the moment, the security of Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) manag
i dont think this is true. it is multi-sig but i don't think it's anonymous individuals. We should check who holds OP upgrade keys. Also, all updates need to be approved by governance in OP

2024-02-01 10:57 UTC, shuse2 commented on docs/intro.md
> +Any L2 based on Optimism is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum Mainnet, Sepolia, etc.)
here i think you mean Any L2 built using op-stack

2024-02-01 10:58 UTC, TalhaMaliktz commented on docs/intro.md
> +Any L2 based on Optimism is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum Mainnet, Sepolia, etc.)
```suggestion
Any L2 based on OP Stack is designed so that users can send arbitrary messages between smart contracts on L2 (Lisk Mainnet, Lisk Sepolia, etc.) and the underlying L1 (Ethereum Mainnet, Sepolia, etc.). This makes it possible to transfer ETH or tokens such as ERC20, ERC721 tokens, etc. between the two networks.
```

2024-02-01 11:00 UTC, TalhaMaliktz commented on docs/intro.md
> +At the moment, the security of Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) manag
This information is based on this [page](https://docs.optimism.io/chain/security/faq).

> OP Mainnet is a work in progress. Constant, iterative improvement of the security mechanisms that safeguard OP Mainnet users is a top priority. At the moment, it's important to understand that the security of OP Mainnet is dependent on a multisig wallet managed by several anonymous individuals. This multisig wallet can be used to upgrade core OP Mainnet smart contracts without upgrade delays. For more information, see Optimism's Security Council.

2024-02-01 11:05 UTC, shuse2 commented on docs/intro.md
> +At the moment, the security of Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) manag
ah ok, let's add that as a reference?

2024-02-01 11:09 UTC, TalhaMaliktz commented on docs/intro.md
> +At the moment, the security of Lisk Mainnet is dependent on a [multisig wallet](https://www.coindesk.com/tech/2020/11/10/multisignature-wallets-can-keep-your-coins-safer-if-you-use-them-right/) manag
Done ✔️

2024-02-01 17:22 UTC, shuse2 approved these changes

2024-02-02 07:56 UTC, merged