Move EOA from contracts page to governance overview
LiskHQ/lisk-docs pull request #184
Opened 2024-08-01 09:59 UTC by TalhaMaliktz

### What was the problem?

This PR resolves #177

2024-08-01 14:02 UTC, Tschakki requested changes

2024-08-01 14:02 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +      <th scope="row" rowSpan="2">Managed by Gelato</th>
What is the difference between "Managed by Gelato" and "The contract is owned by a multi-sig account that belongs to Gelato."?

2024-08-01 14:02 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +    <td>[0xF54791059df4a12BA461b881B4080Ae81a1d0AC0](https://etherscan.io/address/0xF54791059df4a12BA461b881B4080Ae81a1d0AC0)</td>
```suggestion
    <td>[0xF54791059df4a12BA461b881B4080Ae81a1d0AC0](https://sepolia.etherscan.io/address/0xF54791059df4a12BA461b881B4080Ae81a1d0AC0)</td>
```

2024-08-02 07:44 UTC, TalhaMaliktz commented on docs/docs-user/governance/overview.mdx
> +      <th scope="row" rowSpan="2">Managed by Gelato</th>
This is what Gelato had to say on this topic!

> The multi-sig account is in Gelato ownership. as part of the Superchain agreement, the ownership of the multisig will be transferred to a 2/2 multisig controlled by the Security Council and Optimism Foundation later on. The process for transfer the ownership isn't yet established.

2024-08-02 07:50 UTC, TalhaMaliktz commented on docs/docs-user/governance/overview.mdx
> +      <th scope="row" rowSpan="2">Managed by Gelato</th>
For more information, see here for [EOA vs Contract](https://blog.ambire.com/eoas-vs-smart-contract-accounts/) ownership

2024-08-02 08:43 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +      <th scope="row" rowSpan="2">Managed by Gelato</th>
hmm ok, so both are managed by gelato, but difference is that some or multi-sig and some not? 
Imho for users, it is most relevant who manages the account, so I would suggest to change the column "Type of Key" to "Controlled by" or "Owner". So currently we can simply write "Gelato" in this column for all the EOAs. Once Gelato updates the ownership, we can simply update the table accordingly

2024-08-02 09:30 UTC, Tschakki approved these changes
LGTM

2024-08-02 09:52 UTC, merged