Update token bridging guide
LiskHQ/lisk-docs pull request #188
Opened 2024-08-06 12:39 UTC by Tschakki

### What was the problem?

This PR resolves #180 

### How was it tested?

https://liskhq.github.io/lisk-documentation/building-on-lisk/add-token-to-lisk

2024-08-07 06:56 UTC, sameersubudhi approved these changes
LGTM!

2024-08-08 08:25 UTC, TalhaMaliktz requested changes

2024-08-08 08:25 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> -title: Deploying an ERC-20 Token to Lisk
While building the branch using `npm run build`, I encounter the following. Please rectify this:
![image](https://github.com/user-attachments/assets/77daf6ec-b8ca-4dc0-82f9-2d0b37cbec94)

2024-08-08 08:25 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +We recommend you use the framework provided by Lisk's [standard bridge](#the-standard-bridge) contracts, and furthermore deploy your token using the [OptimismMintableERC20Factory](https://docs.lisk.c
```suggestion
We recommend you use the framework provided by Lisk's [standard bridge](#the-standard-bridge) contracts and, furthermore, deploy your token using the [OptimismMintableERC20Factory](https://docs.lisk.com/contracts#lisk-network-l2). 
```

2024-08-08 08:25 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +For step by step instructions how to deploy ERC-20 tokens on Lisk, check the following guides:
```suggestion
For step-by-step instructions on how to deploy ERC-20 tokens on Lisk, check the following guides:
```

2024-08-08 08:25 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +The [Superchain Token List](https://github.com/ethereum-optimism/ethereum-optimism.github.io) exists to help users discover the right bridged token addresses for any given native token.
```suggestion
The [Superchain Token List](https://github.com/ethereum-optimism/ethereum-optimism.github.io) exists to help users discover the correct bridged token addresses for any given native token.
```

2024-08-08 08:25 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +Users must always specify which bridged token they wish to use when using the bridge, see [Superchain Token List](#superchain-token-list).
```suggestion
Users must always specify which bridged token they wish to use when using the bridge; see [Superchain Token List](#superchain-token-list).
```

2024-08-08 08:25 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +The Standard Bridge is a simple smart contract with the functionality to move ERC-20 tokens between Lisk and Ethereum.
```suggestion
The Standard Bridge is a simple smart contract, with the functionality to move ERC-20 tokens between Lisk and Ethereum.
```

2024-08-08 08:25 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +If you choose a different bridging framework, its interface must be compatible with that of the standard bridge, otherwise it may be difficult for us to support.
```suggestion
If you choose a different bridging framework, its interface must be compatible with that of the standard bridge.
Otherwise, it may be difficult for us to support them.
```

2024-08-08 10:38 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2024-08-08 10:48 UTC, merged