Add section about the security council
LiskHQ/lisk-docs pull request #190
Opened 2024-08-14 09:50 UTC by Tschakki

### What was the problem?

This PR resolves #187 

### How was it tested?

https://liskhq.github.io/lisk-documentation/governance/overview

2024-08-14 11:20 UTC, shuse2 requested changes

2024-08-14 11:20 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +<table >
```suggestion
<table>
```

2024-08-14 11:20 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
I don't think this is true. The security of Lisk Mainnet is mainly based on ethereum security, OP stack bridge security and sequencer. DAO and security council at this moment does not really contribute to the Network security

2024-08-14 11:20 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +- Airdrop contract
Airdrop contract is not upgradable

2024-08-14 11:20 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +Details of **Admin account** addresses on 🟢 **Ethereum Mainnet** and 🟡 **Sepolia Testnet** are as follows.
Good to mention those Gelato controlled account will be transfered to the OP security council in the near future

2024-08-14 13:32 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +- Airdrop contract
updated line 36 to 
>The security council controls the following contracts:

2024-08-14 13:34 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
True, I updated the statement

2024-08-14 14:55 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +- Airdrop contract
im not sure if `control` is a right word, but i also don't have other idea...

2024-08-14 14:55 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +<table>
table is still not working?

2024-08-15 06:43 UTC, TalhaMaliktz requested changes

2024-08-15 06:43 UTC, TalhaMaliktz commented on docs/docs-user/governance/overview.mdx
>  # Governance overview
The following link is not working!
![image](https://github.com/user-attachments/assets/c81a6800-2a99-4a35-856a-a7ea01fd3847)

2024-08-15 06:43 UTC, TalhaMaliktz commented on docs/docs-user/governance/overview.mdx
> +
Removing whitespaces between the `<tr>` tags will also rectify rendering issues on Markdown.
```suggestion
```

2024-08-15 06:43 UTC, TalhaMaliktz commented on docs/docs-user/governance/overview.mdx
> +
```suggestion
```

2024-08-15 06:43 UTC, TalhaMaliktz commented on docs/docs-user/governance/overview.mdx
> +
```suggestion
```

2024-08-15 06:43 UTC, TalhaMaliktz commented on docs/docs-user/governance/overview.mdx
> +- all Vesting contracts
```suggestion
- All Vesting contracts
```

2024-08-15 06:43 UTC, TalhaMaliktz commented on docs/docs-user/governance/overview.mdx
> +The Gelato controlled accounts will be transfered to the [OP security council](https://gov.optimism.io/t/intro-to-optimisms-security-council/6885) in the near future.
```suggestion
The Gelato-controlled accounts will be transferred to the [OP security council](https://gov.optimism.io/t/intro-to-optimisms-security-council/6885) in the near future.
```

2024-08-15 10:37 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +<table>
works for me: https://liskhq.github.io/lisk-documentation/governance/overview

2024-08-15 11:32 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +<table>
ah now it's working 👍

2024-08-15 13:34 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
I think it's still mixing several things.

Lisk project is managed by Lisk Ltd delegated by Onchain Foundation. (this needs to be checked with Legal team how we should phrase it)
Lisk DAO is managing the DAO funds allocated
Security council is managing the security of the mentioned contracts

2024-08-16 06:23 UTC, TalhaMaliktz approved these changes
LGTM!

2024-08-16 08:26 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
DAO is not only managing the funds, it is also possible to propose general proposals that go beyond DAO funds. 
Regarding Lisk Ltd I heard it is similar to Lightcurve and we shouldn't mention it publicly

2024-08-16 08:30 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
The admin role of the Onchain foundation is also mentioned on the page below. I am not sure if we should mention the Onchain Foundation as part of governance, as it is not clear was exact responsibilities the Foundation has

2024-08-19 08:46 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
> The Lisk project is governed mainly by the [Lisk security council](#lisk-security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governance of the Lisk project.

but from this sentence, it sounds like `Lisk Security Concncil` is responsible for the governance of the `Lisk Project` which is not true. 
Also, Lisk DAO can propose something to overall governance, but it's not main party of governance i would say.
For example, Lisk DAO cannot decide about the upgrade, protocol related stuff, only suggestion

2024-08-19 09:25 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
Ok, I updated the phrase to include Onchain foundation, please check.

2024-08-19 09:37 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
it looks good to me, but for this i think it's better to ask opinion from wider range. Let me quickly check others

2024-08-21 15:42 UTC, shuse2 commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
From @janhack, 
> I don't think the security council plays a role in the the decision-making for the Lisk Project and I would therefore not mention it when talking about governance. Unlike the OP Security Council and security councils for other L2s, we don't have any upgrade keys for our L2 and the security council therefore does not have any role in protocol updates. Rather, it only has upgrade keys to Claiming, Staking and Vesting Wallet. We don't have any intention to upgrade those and the only time the security council would intervene is in case of incident. Here it also only acts on behalf of the Onchain Foundation.
Moreover, I think we should be careful how we formulate things. The formulation above makes it sound like the Onchain Foundation has all power and the Lisk DAO is only "supporting", which sounds like it has no power at all. This is not the case (The Lisk DAO has full control over the DAO treasury, for instance) and I would therefore reformulate the statement.


```suggestion
The Lisk project is governed by the Lisk DAO and Onchain Foundation. The Onchain Foundation defines the vision and strategy for the project together with the Lisk team, funds its development and is a stakeholder in the Lisk DAO via the Lisk Team delegate. The Lisk DAO allows any LSK token holder that stakes their tokens to participate in onchain governance for the Lisk project. The Lisk DAO decides how to spend funds in its significant treasury and can pass general proposals about protocol parameters or the project direction.
```

Also, https://docs.lisk.com/governance/overview we already have good information already

2024-08-22 07:34 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +The Lisk project is governed by the [Onchain Foundation](https://onchain.org/foundation/), with support of the [Lisk security council](#lisk-security-council) and the [Lisk DAO](#lisk-dao), which all
```suggestion
The Lisk project is governed by the [Lisk DAO](#lisk-dao) and [Onchain Foundation](https://onchain.org/foundation/).
The Onchain Foundation defines the vision and strategy for the project together with the Lisk team, funds its development and is a stakeholder in the Lisk DAO via the Lisk Team delegate.
The Lisk DAO allows any LSK token holder that stakes their tokens to participate in onchain governance for the Lisk project.
The Lisk DAO decides how to spend funds in its significant treasury and can pass general proposals about protocol parameters or the project direction.
```

2024-08-22 07:36 UTC, Tschakki commented on docs/docs-user/governance/overview.mdx
> +The security of the Lisk Mainnet is mainly dependent on the [security council](#security-council) and the [Lisk DAO](#lisk-dao), which allows Lisk token holders to participate together in the governa
@shuse2 I accepted your suggestion 👍

2024-08-26 06:22 UTC, shuse2 approved these changes

2024-08-27 07:53 UTC, merged