Add Oku Trade to exchanges list
LiskHQ/lisk-docs pull request #192
Opened 2024-08-22 12:55 UTC by Tschakki

### What was the problem?

This PR resolves #191 

### How was it tested?

2024-08-27 06:38 UTC, TalhaMaliktz requested changes

2024-08-27 06:38 UTC, TalhaMaliktz commented on docs/docs-user/exchanges.md
> +| [Oku.Trade](https://oku.trade/app/lisk/trade/0xac485391eb2d7d88253a7f1ef18c37f4242d1a24?quoteToken=0x05D032ac25d322df992303dCa074EE7392C117b9) | LSK/USDT, LSK/USDC, LSK/ETH, ETH/USDT, etc. |
For ease and synchronicity, we should add hyperlinks to the coin pairs in a way similar to how they are done throughout the page.

2024-08-27 07:55 UTC, Tschakki commented on docs/docs-user/exchanges.md
> +| [Oku.Trade](https://oku.trade/app/lisk/trade/0xac485391eb2d7d88253a7f1ef18c37f4242d1a24?quoteToken=0x05D032ac25d322df992303dCa074EE7392C117b9) | LSK/USDT, LSK/USDC, LSK/ETH, ETH/USDT, etc. |
Didn't see them - If you can find these links, we can add them.

2024-08-28 05:49 UTC, TalhaMaliktz commented on docs/docs-user/exchanges.md
> +| [Oku.Trade](https://oku.trade/app/lisk/trade/0xac485391eb2d7d88253a7f1ef18c37f4242d1a24?quoteToken=0x05D032ac25d322df992303dCa074EE7392C117b9) | LSK/USDT, LSK/USDC, LSK/ETH, ETH/USDT, etc. |
Yeah, I couldn't find them either. All good 👍🏼

2024-08-28 05:51 UTC, TalhaMaliktz commented on docs/docs-user/exchanges.md
> +| [Oku.Trade](https://oku.trade/app/lisk/trade/0xac485391eb2d7d88253a7f1ef18c37f4242d1a24?quoteToken=0x05D032ac25d322df992303dCa074EE7392C117b9) | LSK/USDT, LSK/USDC, LSK/ETH, ETH/USDT, etc. |
There is no `LSK/USDC` pair, I think!
![image](https://github.com/user-attachments/assets/7b3a2358-c9ec-430b-a398-9417be20b781)

2024-08-28 08:13 UTC, Tschakki commented on docs/docs-user/exchanges.md
> +| [Oku.Trade](https://oku.trade/app/lisk/trade/0xac485391eb2d7d88253a7f1ef18c37f4242d1a24?quoteToken=0x05D032ac25d322df992303dCa074EE7392C117b9) | LSK/USDT, LSK/USDC, LSK/ETH, ETH/USDT, etc. |
updated 👍

2024-08-28 08:14 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼 !

2024-08-28 09:11 UTC, merged