Add bridged token adresses via remark plugin
LiskHQ/lisk-docs pull request #193
Opened 2024-08-23 14:32 UTC by Tschakki

### What was the problem?

This PR resolves #181

### How was it tested?

2024-08-27 15:09 UTC, matjazv requested changes

2024-08-27 15:09 UTC, matjazv commented on plugins/generated-bridged-token-adresses-docs.js
> +                          url: "https://sepolia.etherscan.io/address/" + token.ethAddress+ ")",
`+ ")"` makes link broken.

2024-08-27 15:09 UTC, matjazv commented on plugins/generated-bridged-token-adresses-docs.js
> +                          url: "https://sepolia-blockscout.lisk.com/address/" + token.address+ ")",
`+ ")"` makes link broken.

2024-08-28 06:54 UTC, matjazv approved these changes
LGTM!

The only question I have is if we want to have Lisk token at the top of both tables or not?

2024-08-28 09:13 UTC, Tschakki commented
> LGTM!
> 
> The only question I have is if we want to have Lisk token at the top of both tables or not?

It is currently on top because it is the only entry. I am not sure that it will be on top once more tokens are bridged to Lisk.

2024-08-28 09:30 UTC, matjazv commented
> > LGTM!
> > The only question I have is if we want to have Lisk token at the top of both tables or not?
> 
> It is currently on top because it is the only entry. I am not sure that it will be on top once more tokens are bridged to Lisk.

Yes, I was asking for the future when there'll be more tokens listed.
Probably they will be listed as how they're listed inside `.json` file so Lisk token surely won't be at the top inside those two tables.
Not sure if we want that Lisk token is always at the top of the table or not...

2024-08-28 09:42 UTC, Tschakki commented
> Not sure if we want that Lisk token is always at the top of the table or not...

I see... I think it is ok  like this for now. If the list gets longer, we can consider to just hardcode the Lisk addresses at the top of the table, and only add other tokens dynamically.

2024-08-29 07:16 UTC, TalhaMaliktz requested changes

2024-08-29 07:16 UTC, TalhaMaliktz commented on docusaurus.config.js
> +import { generatedDocs } from './plugins/generated-bridged-token-adresses-docs';
What are these about?
Saw them as a result of `npm run build` and `npm run start`
![image](https://github.com/user-attachments/assets/b5e83ff3-1727-49ee-99f3-3a9b82918699)

2024-08-29 07:16 UTC, TalhaMaliktz commented on plugins/generated-bridged-token-adresses-docs.js
> +                }
This `else` is getting executed, which shouldn't happen if a table row is being pushed!

2024-08-29 07:16 UTC, TalhaMaliktz commented on plugins/generated-bridged-token-adresses-docs.js
> +                  console.log("Error: chainId not found")
This `else` is getting executed, which shouldn't happen if a table row is being pushed!

2024-08-29 10:13 UTC, Tschakki commented on plugins/generated-bridged-token-adresses-docs.js
> +                }
log was in wrong place, removed it now

2024-08-29 10:13 UTC, Tschakki commented on plugins/generated-bridged-token-adresses-docs.js
> +                  console.log("Error: chainId not found")
log was in wrong place, removed it now

2024-08-29 10:14 UTC, Tschakki commented on docusaurus.config.js
> +import { generatedDocs } from './plugins/generated-bridged-token-adresses-docs';
I am not sure, but it looks like the plugin is imported anyway 🤔

2024-08-30 07:25 UTC, TalhaMaliktz commented on docusaurus.config.js
> +import { generatedDocs } from './plugins/generated-bridged-token-adresses-docs';
That seems to be the case! however, let's work on debugging this to keep our repository clean. I've already tried removing `node_modules` and the `.lock` file, but no luck. It seems like there's something going on with the `config` and the `generatedDocs` file. Let's figure this out together!

2024-09-06 06:46 UTC, TalhaMaliktz approved these changes

2024-09-06 14:36 UTC, merged