New Guide: How to get Redstone oracle data
LiskHQ/lisk-docs pull request #195
Opened 2024-08-29 14:03 UTC by Tschakki

### What was the problem?

This PR resolves #99 

### How was it tested?

2024-09-04 11:20 UTC, Phanco requested changes

2024-09-04 11:20 UTC, Phanco commented on docs/building-on-lisk/use-oracle-data.md
> +In case you want to use Foundry, check out the [Redstone docs](https://docs.redstone.finance/docs/get-started/models/redstone-core#foundry) for isntructions.
```suggestion
In case you want to use Foundry, check out the [Redstone docs](https://docs.redstone.finance/docs/get-started/models/redstone-core#foundry) for instructions.
```

2024-09-04 11:20 UTC, Phanco commented on docs/building-on-lisk/use-oracle-data.md
> +#### Get mutiple values
```suggestion
#### Get multiple values
```

2024-09-04 11:20 UTC, Phanco commented on docs/lisk-tools/oracles.md
> +*   [RedStone Core](https://docs.redstone.finance/docs/get-started/models/redstone-core) (pull oracle) - less than 10s update time, broad spectrum of feeds, best for most use cases. All [Core Price F
I know the above 3 lines are about indentation, but seems the links have been changed and they're now unreachable. Would you mind updating them as well?

2024-09-04 15:17 UTC, Tschakki commented on docs/lisk-tools/oracles.md
> +*   [RedStone Core](https://docs.redstone.finance/docs/get-started/models/redstone-core) (pull oracle) - less than 10s update time, broad spectrum of feeds, best for most use cases. All [Core Price F
Actually I was also updating the links, but it seems they have changed again :D Updated them again, they should all work now 🙏

2024-09-09 11:19 UTC, TalhaMaliktz requested changes
Looks good overall! A few minor comments

2024-09-09 11:19 UTC, TalhaMaliktz commented on docs/building-on-lisk/use-oracle-data.md
> +In case you want to use Foundry, check out the [Redstone docs](https://docs.redstone.finance/docs/get-started/models/redstone-core#foundry) for instructions.
The URL leads to a "Page Not Found"

2024-09-09 11:19 UTC, TalhaMaliktz commented on docs/building-on-lisk/use-oracle-data.md
> +RedStone is a data ecosystem that delivers frequently updated, reliable and diverse data for your dApp and smart contracts deployed on Lisk.
```suggestion
RedStone is a data ecosystem that delivers frequently updated, reliable, and diverse data for your dApp and smart contracts deployed on Lisk.
```

2024-09-09 11:19 UTC, TalhaMaliktz commented on docs/building-on-lisk/use-oracle-data.md
> +This guides uses the [Redstone Pull model](https://docs.redstone.finance/docs/get-started/models/redstone-pull) to fetch the data.
```suggestion
This guide uses the [Redstone Pull model](https://docs.redstone.finance/docs/get-started/models/redstone-pull) to fetch the data.
```

2024-09-09 11:19 UTC, TalhaMaliktz commented on docs/building-on-lisk/use-oracle-data.md
> +For an overview about the different modules Redstone offers to receive oracle data, go [Oracles > Redstone](../lisk-tools/oracles#redstone).
```suggestion
For an overview of the different modules that Redstone offers to receive oracle data, go to [Oracles > Redstone](../lisk-tools/oracles#redstone).
```

2024-09-09 11:19 UTC, TalhaMaliktz commented on docs/building-on-lisk/use-oracle-data.md
> +Get the oracle data by using the provided functions of the EVM connector.
```suggestion
Get the oracle data using the functions provided by the EVM connector.
```

2024-09-09 11:19 UTC, TalhaMaliktz commented on docs/building-on-lisk/use-oracle-data.md
> +To get a single price feed, use the function `getOracleNumericValueFromTxMsg()` and provide the data feed ID as parameter.
```suggestion
To get a single price feed, use the function `getOracleNumericValueFromTxMsg()` and provide the data feed ID as a parameter.
```

2024-09-09 11:19 UTC, TalhaMaliktz commented on docs/building-on-lisk/use-oracle-data.md
> +To get data from multiple price feeds, use the function `getOracleNumericValuesFromTxMsg()` and provide the data feed ID array as parameter.
```suggestion
To get data from multiple price feeds, use the function `getOracleNumericValuesFromTxMsg()` and provide the data feed ID array as a parameter.
```

2024-09-09 11:19 UTC, TalhaMaliktz commented on docs/building-on-lisk/use-oracle-data.md
> +To deploy the smart contract on Lisk Sepolia or Lisk Mainnet, follow the guide [Deploying a smart contract with Hardhat](deploying-smart-contract/with-Hardhat.md)
Please also add link to the Foundry guide as well.

2024-09-09 15:11 UTC, Phanco commented on docs/building-on-lisk/use-oracle-data.md
> +        const contract = await YourContract.deploy(1896456000);
The `YourContract` above doesn't seem to take argument

2024-09-09 15:22 UTC, Phanco commented on docs/building-on-lisk/use-oracle-data.md
> +function getLatestEthBtcPrices() public view returns (uint256) {
this function would result in compile error, change to
`returns (uint256[] memory)`

`ethPrice` and `btcPrice` are also unused.

2024-09-11 10:53 UTC, TalhaMaliktz approved these changes
LGTM!

2024-09-11 11:49 UTC, Phanco approved these changes

2024-09-11 13:32 UTC, merged