Create manual voting guide
LiskHQ/lisk-docs pull request #208
Opened 2024-09-12 13:36 UTC by Tschakki

### What was the problem?

This PR resolves #205 

### How was it tested?
https://liskhq.github.io/lisk-documentation/governance/delegation
https://liskhq.github.io/lisk-documentation/governance/voting

2024-09-16 10:26 UTC, AndreasKendziorra approved these changes
Two optional comments. Otherwise looks good.

2024-09-16 10:26 UTC, AndreasKendziorra commented on docs/docs-user/governance/delegation.mdx
> +[^1]: At the time of writing, there is an issue with connecting MetaMask to Blockscout on Firefox;
Optional: I would still link to the issue such that users could see if it got resolved or not: https://github.com/blockscout/frontend/issues/2059

2024-09-16 10:26 UTC, AndreasKendziorra commented on docs/docs-user/governance/voting.mdx
> +[^1]: At the time of writing, there is an issue with connecting MetaMask to Blockscout on Firefox;
same as above: one could link to the issue

2024-09-18 08:41 UTC, AndreasKendziorra requested changes

2024-09-18 08:41 UTC, AndreasKendziorra commented on docs/docs-user/governance/voting.mdx
> +The return value is an array of logs, and for each log one gets also the corresponding transaction hash.
```suggestion
The return value is an array of logs, where each log corresponds to one proposal (creation) and for each log one gets also the corresponding transaction hash.
```

2024-09-18 08:41 UTC, AndreasKendziorra commented on docs/docs-user/governance/voting.mdx
> +To see the proposal ID, click on the `Logs` tab and look for the `proposalId` field in the `ProposalCreated` event.
```suggestion
To see if the proposal is the one you are looking for, click on the `Logs` tab and look for the `ProposalCreated` event. If the values, in particular the ones for `description`, `voteStart` and `voteEnd`, match with the proposal you want to on, then it is the right one. To get the proposal ID, copy the value of the field `proposalId`.
```

2024-09-18 08:41 UTC, AndreasKendziorra commented on static/img/docs/governance/proposal-id.png
With the changes to the text, it may be nicer to rather (or also) point to `description`, `voteStart` and `voteEnd`?

2024-09-18 09:17 UTC, AndreasKendziorra requested changes

2024-09-18 09:17 UTC, AndreasKendziorra commented on docs/docs-user/governance/voting.mdx
> +To see if the proposal is the one you are looking for, click on the `Logs` tab and look for the `ProposalCreated` event. If the values, in particular the ones for `description`, `voteStart` and `vote
```suggestion
To see if the proposal is the one you are looking for, click on the `Logs` tab and look for the `ProposalCreated` event. If the values, in particular the ones for `description`, `voteStart` and `voteEnd`, match with the proposal you want to vote on, then it is the right one. To get the proposal ID, copy the value of the field `proposalId`.
```

2024-09-18 09:17 UTC, AndreasKendziorra commented on docs/docs-user/governance/voting.mdx
> +To see if the proposal is the one you are looking for, click on the `Logs` tab and look for the `ProposalCreated` event. If the values, in particular the ones for `description`, `voteStart` and `vote
sorry, it was introduced by me

2024-09-18 10:27 UTC, AndreasKendziorra approved these changes

2024-09-19 11:06 UTC, TalhaMaliktz requested changes
Looking good already!

2024-09-19 11:06 UTC, TalhaMaliktz commented on docs/docs-user/governance/delegation.mdx
>  Delegates play a crucial role in the governance of the Lisk project.
The following section has some unnecessary characters!
<img width="707" alt="image" src="https://github.com/user-attachments/assets/c73962ac-6db0-48fb-996d-4095e5c58b35">

2024-09-19 11:06 UTC, TalhaMaliktz commented on docs/docs-user/governance/delegation.mdx
> +For a guide how to vote manually, see the [Voting](voting) page.
```suggestion
For a guide on how to vote manually, see the [Voting](voting) page.
```

2024-09-19 11:06 UTC, TalhaMaliktz commented on docs/docs-user/governance/voting.mdx
> +The return value is an array of logs, where each log corresponds to one proposal (creation) and for each log one gets also the corresponding transaction hash.
```suggestion
The return value is an array of logs, where each log corresponds to one proposal (creation) and has the corresponding transaction hash.
```

2024-09-19 11:06 UTC, TalhaMaliktz commented on docs/docs-user/governance/voting.mdx
> +For a guide how to delegate your voting power manually, see the [Delegation](delegation) page.
```suggestion
For a guide on how to delegate your voting power manually, see the [Delegation](delegation) page.
```

2024-09-19 11:31 UTC, TalhaMaliktz approved these changes
LGTM!

2024-09-19 11:54 UTC, merged