Add docs about token standards
LiskHQ/lisk-docs pull request #212
Opened 2024-09-18 16:44 UTC by Tschakki

### What was the problem?

This PR resolves #182 

### How was it tested?

https://liskhq.github.io/lisk-documentation/token-development

2024-10-10 16:17 UTC, ikem-legend commented on docs/building-on-lisk/token-development/overview.md
> +It includes an explanation of ERCs, a summary of the most important token standards and examples how to deploy these tokens on Lisk.
```suggestion
It includes an explanation of ERCs, a summary of the most important token standards and examples of how to deploy these tokens on Lisk.
```

2024-10-10 16:17 UTC, ikem-legend commented on docs/building-on-lisk/token-development/overview.md
> +ERCs are a subcategory of **EIPs**(= Ethereum Inprovemnt Proposals).
```suggestion
ERCs are a subcategory of **EIPs**(= Ethereum Improvement Proposals).
```

2024-10-10 16:18 UTC, ikem-legend commented on docs/building-on-lisk/token-development/overview.md
> +In case you already have a token deployed on the Ethereum network, an wish to bridge it to Lisk, please refer to the guide [Bridging an L1 token to Lisk](../add-token-to-lisk/index.md).
```suggestion
In case you already have a token deployed on the Ethereum network, and wish to bridge it to Lisk, please refer to the guide [Bridging an L1 token to Lisk](../add-token-to-lisk/index.md).
```

2024-10-11 13:56 UTC, ikem-legend commented on docs/building-on-lisk/token-development/overview.md
> +- **High application compatibility:** Most applications only support the most popular ERC token standards. By following these standars you ensure your token will be compatible with most external appl
```suggestion
- **High application compatibility:** Most applications only support the most popular ERC token standards. By following these standards you ensure your token will be compatible with most external application like wallets or decentralized exchanges.
```

2024-10-11 13:56 UTC, ikem-legend commented on docs/building-on-lisk/token-development/overview.md
> +A summary of some interesting ERC tokens standars can be found below.
```suggestion
A summary of some interesting ERC tokens standards can be found below.
```

2024-10-11 14:01 UTC, ikem-legend commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +Then, select the `MyNFT` contract from the deployment dropdown and click the orange `Deploy` button to deploy the contract.
```suggestion
Then, select the `MyToken` contract from the deployment dropdown and click the orange `Deploy` button to deploy the contract.
```

2024-10-11 14:03 UTC, ikem-legend commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +3. Go to the contract tabe and click on the blue `Verify and Publish` button.
```suggestion
3. Go to the contract tab and click on the blue `Verify and Publish` button.
```

2024-10-11 14:03 UTC, ikem-legend commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +  - Go to the contract tabe and click on the blue `Verify and Publish` button
```suggestion
  - Go to the contract tab and click on the blue `Verify and Publish` button
```

2024-10-11 14:43 UTC, ikem-legend approved these changes

2024-10-15 10:36 UTC, TalhaMaliktz requested changes

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/overview.md
> +**ERCs**(= Ethereum Request for Comments) are a set of application-level standards and conventions, including contract standards such as token standards (ERC-20), name registries (ERC-137), URI schem
```suggestion
**ERCs**(Ethereum Request for Comments) are a set of application-level standards and conventions, including contract standards such as token standards (ERC-20), name registries (ERC-137), URI schemes, library/package formats, and wallet formats for the Ethereum blockchain.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/overview.md
> +ERCs are a subcategory of **EIPs**(= Ethereum Improvement Proposals).
```suggestion
ERCs are a subcategory of **EIPs**(Ethereum Improvement Proposals).
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/overview.md
> +The full list of [ERC proposals](https://eips.ethereum.org/erc).
```suggestion
Here's the full list of [ERC proposals](https://eips.ethereum.org/erc).
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/overview.md
> +It includes an explanation of ERCs, a summary of the most important token standards and examples of how to deploy these tokens on Lisk.
```suggestion
It includes an explanation of ERCs, a summary of the most important token standards, and examples of how to deploy these tokens on Lisk.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/overview.md
> +- **High application compatibility:** Most applications only support the most popular ERC token standards. By following these standards you ensure your token will be compatible with most external app
```suggestion
- **High application compatibility:** Most applications only support the most popular ERC token standards. By following these standards, you ensure your token will be compatible with most external applications like wallets or decentralized exchanges.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/overview.md
> +- **Great documentation:** Benefit from the vast amount of tutorials and guides that are available to develop ERC compliant tokens.
```suggestion
- **Great documentation:** Benefit from the vast number of tutorials and guides that are available to develop ERC-compliant tokens.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/overview.md
> +A summary of some interesting ERC tokens standards can be found below.
```suggestion
A summary of some interesting ERC token standards can be found below.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/overview.md
> +Non-fungible tokens(NFTs) are used to represent unique objects like real estate or collectibles, where some items are valued more than others, due to their usefulness, rarity, or other individual cha
```suggestion
Non-fungible tokens(NFTs) are used to represent unique objects like real estate or collectibles, where some items are valued more than others due to their usefulness, rarity, or other individual characteristics.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/overview.md
> +To represent these unique features on chain, the ERC-721 includes metadata properties that offer information about the token's specific features, such as the title, the creator, and an image preview.
```suggestion
To represent these unique features onchain, the ERC-721 includes metadata properties that offer information about the token's specific features, such as the title, the creator, and an image preview.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
```suggestion
In this guide, we will use Remix as an IDE for smart contract development, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) or any other IDE to implement your token contract.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +Click the 📄 ("Create new file") button to create a new empty Solidity file.
```suggestion
Inside the `contracts` folder, click the 📄 ("Create new file") button to create a new empty Solidity file.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +
Please add a note here about matching the compiler version of the Remix IDE with the compiler version mentioned in the smart contract: `pragma solidity ^0.8.28;`.

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +Open the deployment tab (this looks like an Ethereum logo with an arrow pointing right).
```suggestion
Open the `Deploy & run transactions` tab (this looks like an Ethereum logo with an arrow pointing right).
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +Then, select the `MyToken` contract from the deployment dropdown and click the orange `Deploy` button to deploy the contract.
```suggestion
Then, select the `MyToken` contract from the deployment dropdown.
Afterward, input details about your token, such as name, symbol, and initial supply, in the `Deploy` section and then click on the orange `transact` button to deploy the contract.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
```suggestion
In this guide, we will use Remix as an IDE for smart contract development, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) or any other IDE to implement your token contract.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +Click the 📄 ("Create new file") button to create a new empty Solidity file.
```suggestion
Inside the `contracts` folder, click the 📄 ("Create new file") button to create a new empty Solidity file.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +
Please add a note here about matching the compiler version of the Remix IDE with the compiler version mentioned in the smart contract: `pragma solidity ^0.8.28;`.

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +Open the deployment tab (this looks like an Ethereum logo with an arrow pointing right).
```suggestion
Open the `Deploy & run transactions` tab (this looks like an Ethereum logo with an arrow pointing right).
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
```suggestion
In this guide, we will use Remix as an IDE for smart contract development, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) or any other IDE to implement your token contract.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +Click the 📄 ("Create new file") button to create a new empty Solidity file.
```suggestion
Inside the `contracts` folder, click the 📄 ("Create new file") button to create a new empty Solidity file.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +
Please add a note here about matching the compiler version of the Remix IDE with the compiler version mentioned in the smart contract: `pragma solidity ^0.8.28;`.

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +Open the deployment tab (this looks like an Ethereum logo with an arrow pointing right).
```suggestion
Open the `Deploy & run transactions` tab (this looks like an Ethereum logo with an arrow pointing right).
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +Make sure that your environment is set to "Injected Provider", your wallet is connected to the Lisk Sepolia network, and Remix has access to your wallet.
```suggestion
Make sure that your environment is set to "Injected Provider", your wallet is connected to the Lisk or Lisk Sepolia network, and Remix has access to your wallet.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +Then, select the `MyNFT` contract from the deployment dropdown and click the orange `transact` button to deploy the contract and confirm the contract deployment in your connected wallet.
```suggestion
Then, select the `MyNFT` contract from the deployment dropdown and click the orange `Deploy` button to deploy the contract and confirm the contract deployment in your connected wallet.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +You can name this file whatever you'd like, e.g. `MyToken.sol`.
```suggestion
You can name this file whatever you'd like, e.g., `MyToken.sol`.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +    - Choose `Solidity (Single file)` as verification method.
```suggestion
    - Choose `Solidity (Single file)` as the verification method.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +  Once verified, the code tab will include the ✅ icon and source code will be viewable.
```suggestion
  Once verified, the code tab will include the ✅ icon, and the source code will be viewable.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +You can name this file whatever you'd like, e.g. `MyNFT.sol`.
```suggestion
You can name this file whatever you'd like, e.g., `MyNFT.sol`.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +  This will create a new file `MyNFT_flattened.sol`.
```suggestion
  This will create a new file: `MyNFT_flattened.sol`.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +  - Go to the contract tab and click on the blue `Verify and Publish` button
```suggestion
  - Go to the contract tab and click on the blue `Verify and Publish` button.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +    - Choose `Solidity (Single file)` as verification method.
```suggestion
    - Choose `Solidity (Single file)` as the verification method.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +  Once verified, the code tab will include the ✅ icon and source code will be viewable.
```suggestion
  Once verified, the code tab will include the ✅ icon, and the source code will be viewable.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +You can name this file whatever you'd like, e.g. `MyItems.sol`.
```suggestion
You can name this file whatever you'd like, e.g., `MyItems.sol`.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +For the remainder of this guide, we'll walk through how to verify your contract with Remix on the Lisk Sepolia Testnet.
```suggestion
For the remainder of this guide, we'll walk you through how to verify your contract with Remix on the Lisk Sepolia Testnet.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +  Once verified, the code tab will include the ✅ icon and source code will be viewable.
```suggestion
  Once verified, the code tab will include the ✅ icon, and the source code will be viewable.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +The URI can include the string `{id}` which clients must replace with the actual token ID, in lowercase hexadecimal (with no 0x prefix) and leading zero padded to 64 hex characters.
```suggestion
The URI can include the string `{id}`, which clients must replace with the actual token ID, in lowercase hexadecimal (with no 0x prefix) and leading zero-padded to 64 hex characters.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +Check the Remix log messages, it should include the contract address.
```suggestion
Check the Remix log messages; they should include the contract address.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +Check the Remix log messages, it should include the contract address.
```suggestion
Check the Remix log messages; they should include the contract address.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +Check the Remix log messages, it should include the contract address.
```suggestion
Check the Remix log messages; they should include the contract address.
```

2024-10-15 10:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +    - Choose `Solidity (Single file)` as verification method.
```suggestion
    - Choose `Solidity (Single file)` as the verification method.
```

2024-10-15 11:03 UTC, Tschakki commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
The other smart contract development frameworks are not IDEs

2024-10-15 11:05 UTC, Tschakki commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
As above, the other smart contract development frameworks are not IDEs

2024-10-15 11:06 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
Yes, you are right! However, the sentence should be altered to incorporate both cases, an IDE (as Remix is one), and various frameworks. Feel free to alter it accordingly.

2024-10-15 11:08 UTC, Tschakki commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
The other smart contract development frameworks are not IDEs

2024-10-15 11:11 UTC, Tschakki commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
Imho framework is a more general term and also fits for Remix, don't you think?

2024-10-15 11:13 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
Nope, framework and IDE are two different things.

2024-10-15 11:15 UTC, Tschakki commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +Then, select the `MyToken` contract from the deployment dropdown and click the orange `Deploy` button to deploy the contract.
```suggestion
Then, select the `MyToken` contract from the deployment dropdown and deploy it with the parameters of your choice, for example:

- Name: MyToken
- Symbol: MYT
- InitalSupply: 1000000000000000000000

Click on the orange `Deploy` button to deploy the contract.
```

2024-10-15 11:25 UTC, Tschakki commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
I would disagree here

2024-10-15 11:27 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
https://stackoverflow.com/questions/5255868/difference-between-ide-and-framework#:~:text=The%20IDE%20is%20the%20software,guidelines%20on%20how%20to%20develop.

https://shashvatshukla.medium.com/framework-vs-library-vs-platform-vs-api-vs-sdk-vs-toolkits-vs-ide-50a9473999db

2024-10-15 11:48 UTC, Tschakki commented on docs/building-on-lisk/token-development/deploy-erc-1155.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
My point is that in the context of smart contract development frameworks, Remix is often counted among them, as it is used for the exact same purpose. You can easily see this when googeling "smart contract development framework".

I adjusted the beginning of the sentence now anyway.

```suggestion
We will use Remix IDE for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of your choice to implement your token contract.
```

2024-10-15 11:49 UTC, Tschakki commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
```suggestion
We will use Remix IDE for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of your choice to implement your token contract.
```

2024-10-15 11:50 UTC, Tschakki commented on docs/building-on-lisk/token-development/deploy-erc-721.md
> +We will use Remix as framework for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of y
```suggestion
We will use Remix IDE for smart contract development in this guide, but feel free to choose a [smart contract development framework](/category/building-on-lisk/deploying-smart-contract) of your choice to implement your token contract.
```

2024-10-16 07:02 UTC, TalhaMaliktz reviewed
Looking good already! Just a small update

2024-10-16 07:02 UTC, TalhaMaliktz commented on docs/building-on-lisk/token-development/deploy-erc-20.md
> +Click on the orange `Deploy` button to deploy the contract.
When adding the details, I see a "transact" button instead of a "Deploy"
![image](https://github.com/user-attachments/assets/7facb6fd-9ddb-4983-9c2c-5c54bfd6d0f8)

```suggestion
Click on the orange `transact` button to deploy the contract.
```

2024-10-16 09:22 UTC, TalhaMaliktz approved these changes
LGTM! 👍🏼

2024-10-16 09:39 UTC, merged