Create page about network information, block explorers, faucets
LiskHQ/lisk-docs pull request #22
Opened 2024-01-26 15:25 UTC by TalhaMaliktz

Closes #7
Closes #31

2024-01-29 08:32 UTC, Tschakki requested changes

2024-01-29 08:32 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +For more information about funding a wallet, see the [Wallet funds](building-on-lisk/deploying-a-smart-contract#wallet-funds) section.
This is not really a Lisk Testnet faucet, as it gives you Ethereum Testnet tokens. Would remove this section until we have our own faucet.

2024-01-29 08:32 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +- [Lisk Blockscout Explorer](https://sepolia-blockscout.lisk.com/)
For a better overview, I would include this info in the table above, listing only our official explorer.
We will have a separate page for listing other explorers which support Lisk networks.

2024-01-29 08:32 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +- [Lisk Testnet Bridge](https://sepolia-bridge.lisk.com/bridge/lisk-sepolia-testnet)
For a better overview, I would include this info in the table above, listing only our official bridge.
We will have a separate page for listing other bridges which support Lisk networks.

2024-01-29 08:32 UTC, Tschakki commented on docs/intro.md
> +title: Introduction to Lisk
Looks like you used the branch adding the intro page as base branch, please update the base branch in the PR accordingly, it should remove unrelated changes from the PR overview.

2024-01-29 09:31 UTC, TalhaMaliktz commented on docs/about-lisk/network-info.md
> +For more information about funding a wallet, see the [Wallet funds](building-on-lisk/deploying-a-smart-contract#wallet-funds) section.
I think, instead of removing it. I can simply rename it to Sepolia Testnet Faucet. Since we are already referring to it in the Wallet Funds section, where we do discuss/suggest to use the Sepolia Testnet Faucet.

2024-01-29 09:32 UTC, TalhaMaliktz commented on docs/intro.md
> +title: Introduction to Lisk
The base branch is the main branch, I needed some pages for cross-referencing so I merged my Intro branch into this branch.

2024-01-29 12:05 UTC, Tschakki commented on docs/intro.md
> +title: Introduction to Lisk
I don't think it matters if you used it as base from the start or merged it later

2024-01-29 12:08 UTC, TalhaMaliktz commented on docs/intro.md
> +title: Introduction to Lisk
I think that the branch was based on `main` and will be merged into `main`.

2024-01-29 13:31 UTC, Tschakki requested changes

2024-01-29 13:31 UTC, Tschakki commented on docs/intro.md
> +title: Introduction to Lisk
When you create a branch based on another branch than main, or you merge another branch than main into it(which you should avoid generally), then it should be picked as base branch in the PR. The base branch will automatically update to `main` once the other PR which was used as base is merged into `main` so please change the base branch as requested.

2024-01-29 13:31 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +For more information about funding a wallet, see the [Wallet funds](building-on-lisk/deploying-a-smart-contract#wallet-funds) section.
On this particular page we should list Lisk networks specific info only, please remove.

2024-01-29 13:31 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +For more information about funding a wallet, see the [Wallet funds](building-on-lisk/deploying-a-smart-contract#wallet-funds) section.
We are only referring to it, to give one example how to aquire Testnet ETH, there are multiple other ways to achieve this. This page should only list Lisk related network info

2024-01-29 14:01 UTC, TalhaMaliktz commented on docs/intro.md
> +title: Introduction to Lisk
Done

2024-01-30 08:55 UTC, Tschakki requested changes

2024-01-30 08:55 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +:::
I dont think it is relevant here to explain to users how they can get Ethereum Testnet tokens
```suggestion
```

2024-01-30 08:55 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +For more information about funding a wallet, see the [Wallet funds](building-on-lisk/deploying-a-smart-contract#wallet-funds) section. -->
Would include the faucet info in the table as well, once it is available

2024-01-30 09:25 UTC, Tschakki approved these changes
LGTM, just one small suggestion :)

2024-01-30 09:25 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +| Lisk Testnet Bridge| https://sepolia-bridge.lisk.com/bridge/lisk-sepolia-testnet
```suggestion
| Lisk Testnet Bridge| https://sepolia-bridge.lisk.com
```

2024-01-30 09:25 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +| Lisk Testnet Bridge| https://sepolia-bridge.lisk.com/bridge/lisk-sepolia-testnet
Adding this suggestion should close [this](https://github.com/LiskHQ/lisk-documentation/issues/31) issue

2024-01-30 16:04 UTC, nagdahimanshu approved these changes
Looks good 👍

2024-02-02 08:05 UTC, merged