[LISKDOCS-10] Add indonesian localization
LiskHQ/lisk-docs pull request #227
Opened 2024-10-15 10:15 UTC by Tschakki

### What was the problem?

### How was it tested?

2024-11-14 11:47 UTC, TalhaMaliktz requested changes

2024-11-14 11:47 UTC, TalhaMaliktz commented on src/pages/index.js
>  import Heading from '@theme/Heading';
On the homepage, when I go from Indonesian to English, I get the following error:
<img width="961" alt="image" src="https://github.com/user-attachments/assets/af21df68-b2c9-49b8-a577-55a821bb749f">

The URL on the browser reduces just to `ind/`.

2024-11-14 11:47 UTC, TalhaMaliktz commented on src/components/HomepageFeatures/index.js
>            className="button button--secondary button--lg btn-custom"
The buttons lose alignment when in the Indonesian mode.
<img width="1718" alt="image" src="https://github.com/user-attachments/assets/2c969aa4-dd03-44e7-bd6f-c867d6ad8335">

2024-11-14 11:47 UTC, TalhaMaliktz commented on docusaurus.config.js
> +    locales: ['en', 'ind'],
On the navbar, the term should either be `Bahasa Indonesian` or just `Indonesian`.

2024-11-14 13:16 UTC, Tschakki commented on src/components/HomepageFeatures/index.js
>            className="button button--secondary button--lg btn-custom"
I think this should be solved in a separate issue, as it is UI related

2024-11-14 13:18 UTC, Tschakki commented on src/pages/index.js
>  import Heading from '@theme/Heading';
I cannot reproduce your error, it works fine for me: https://liskhq.github.io/lisk-documentation

2024-11-14 13:23 UTC, TalhaMaliktz commented on src/components/HomepageFeatures/index.js
>            className="button button--secondary button--lg btn-custom"
Sure, please create a separate issue for record keeping.

2024-11-14 13:24 UTC, TalhaMaliktz commented on src/pages/index.js
>  import Heading from '@theme/Heading';
I am testing it with `npm run build && npm run serve` to mimic the production server. Can you try it this way?

2024-11-14 13:53 UTC, Tschakki commented on src/pages/index.js
>  import Heading from '@theme/Heading';
Ok I could reproduce the error now. I think it is related to localhost, as it works fine on github pages. On localhost, it sometimes works and sometimes fails for me.

2024-11-15 08:36 UTC, TalhaMaliktz commented on src/pages/index.js
>  import Heading from '@theme/Heading';
If I run a simple `npm run start` and try to change the language from English to Indonesian, I get the following error.
![image](https://github.com/user-attachments/assets/cc223a29-8c8f-490a-b9b0-40fc99f0d5e7)

It seems like there is an issue with routing with localization, and it should be sorted out.

2024-11-15 08:38 UTC, TalhaMaliktz requested changes
If I run a simple `npm run start` and try to change the language from English to Indonesian, I get the following error.
![image](https://github.com/user-attachments/assets/cc223a29-8c8f-490a-b9b0-40fc99f0d5e7)

It seems like there is an issue with routing with localization, and it should be sorted out.

2024-11-15 08:48 UTC, Tschakki commented on src/pages/index.js
>  import Heading from '@theme/Heading';
As I said this error shows only on localhost. And even there, not always. Please check the staging docs to see if you can reproduce the error there, otherwise it is not relevant to fix in this PR.

2024-11-15 10:01 UTC, TalhaMaliktz commented on src/pages/index.js
>  import Heading from '@theme/Heading';
I shared my thoughts on the pull request because it's relevant. I've noticed both behaviors mentioned above consistently, and I wanted to highlight that the recommended way to test the docs site locally, according to [Docusaurus](https://docusaurus.io/docs/deployment#testing-build-locally), is by running `npm run build && npm run serve` before moving to production. From my experience, what you encounter during this local build usually reflects what you'll see on the production server.

GitHub Pages is a bit tricky for reliable testing, mainly due to its handling of URLs, especially given the issues we've seen with image URLs.

That said, if you still feel confident that this issue won't arise in production, I'd be happy to approve it so you can try it. Let me know what you think!

2024-11-19 13:12 UTC, Tschakki commented on src/pages/index.js
>  import Heading from '@theme/Heading';
The PR is now deployed on the new staging @TalhaMaliktz http://stg-docs.lisk.com.s3-website.eu-west-3.amazonaws.com/

2024-11-19 13:18 UTC, TalhaMaliktz commented on src/pages/index.js
>  import Heading from '@theme/Heading';
While interacting with the staging docs, On either the `Building with Lisk` or `Using Lisk` section, if I try to change language from English to Indonesian, I get the following error:
<img width="1721" alt="image" src="https://github.com/user-attachments/assets/ab393d9d-4384-4482-a1c6-0b2a61f7dc79">

2024-11-19 13:24 UTC, TalhaMaliktz commented on src/pages/index.js
>  import Heading from '@theme/Heading';
Also, if I try to switch back from Indonesian to English (If I selected Indonesia on the homepage), I briefly see the `Page Not Found` message; however, that disappears. I would also look into this behavior.

2024-11-19 14:08 UTC, Tschakki commented on src/pages/index.js
>  import Heading from '@theme/Heading';
I think it was connected to the github-pages related configs.
I commented them out now as we moved away from gh-pages, please check again!

2024-11-20 06:59 UTC, TalhaMaliktz approved these changes
LGTM!

2024-11-20 09:03 UTC, merged