[LISKDOCS-12] Add guide for redstone push
LiskHQ/lisk-docs pull request #252
Opened 2024-11-21 14:51 UTC by Tschakki

2024-11-22 13:56 UTC, matjazv commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +Every time a price feed is updated, it adds +1 to the round ID.
We're using data feed contracts without rounds, so round is always `1`:
Name of the contracts tells us this: `L2PriceFeedWithoutRounds`

2024-11-22 13:56 UTC, matjazv commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +  - address: `0xd2176Dd57D1e200c0A8ec9e575A129b511DBD3AD`
We've just recently deployed two new data feed contracts if you want to add them:
- [USDC/USD](https://blockscout.lisk.com/address/0xb4e6A7861067674AC398a26DD73A3c524C602184)
- [WBTC/USD](https://blockscout.lisk.com/address/0x13da43eA89fB692bdB6666F053FeE70aC61A53cd)

2024-11-22 14:06 UTC, matjazv commented on docs/building-on-lisk/using-oracle-data/redstone-pull.md
> -description: A guide on using Redstone Data Feeds to access real-world data such as asset prices, directly from your smart contracts on the Lisk testnet.
I think everywhere should be `Redstone` => `RedStone`.

2024-11-22 14:13 UTC, matjazv requested changes

2024-11-22 14:13 UTC, matjazv commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +Use the `AggregatorV3Interface()` function and pass the adress of the respective data feed contract as parameter.
```suggestion
Use the `AggregatorV3Interface()` function and pass the address of the respective data feed contract as parameter.
```

2024-11-22 14:13 UTC, matjazv commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +RedStone data feeds are compatible with Chainlinks [AggregatorV3Interface](https://docs.chain.link/data-feeds/using-data-feeds#solidity) and include the following components:
```suggestion
RedStone data feeds are compatible with Chainlink's [AggregatorV3Interface](https://docs.chain.link/data-feeds/using-data-feeds#solidity) and include the following components:
```

2024-11-22 15:29 UTC, matjazv approved these changes
LGTM!
Nice job! 🚀

2024-11-25 12:31 UTC, TalhaMaliktz requested changes

2024-11-25 12:31 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +```solidity
I would add a snippet title to both code snippets for legibility.

2024-11-25 12:31 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +These contracts are already deployed on the Lisk network and can be directly used by Consumers.
```suggestion
These contracts have already been deployed on the Lisk network and can be directly used by consumers.
```

2024-11-25 12:31 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +In this guide, we will develop a Consumer contract that will request the latest spot prices from the ETH, LSK and USDT data feeds.
```suggestion
In this guide, we will develop a Consumer contract that requests the latest spot prices from the ETH, LSK, and USDT data feeds.
```

2024-11-25 12:31 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +To use the RedStone data inside your contract, import the [AggregatorV3Interface](https://docs.chain.link/data-feeds/using-data-feeds#solidity) from Chainlink like shown in the example contract below
```suggestion
To use the RedStone data inside your contract, import the [AggregatorV3Interface](https://docs.chain.link/data-feeds/using-data-feeds#solidity) from Chainlink, as shown in the example contract below.
```

2024-11-25 12:31 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +For every data feed you like to store, create a new constant with type `AggregatorV3Interface`.
```suggestion
Create a new constant with the type `AggregatorV3Interface` for every data feed you want to store.
```

2024-11-25 12:31 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +In the constructor, set the above defined constants to point to the respective data feeds:
```suggestion
In the constructor, set the above-defined constants to point to the respective data feeds.
```

2024-11-25 12:31 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +Use the `AggregatorV3Interface()` function and pass the address of the respective data feed contract as parameter.
```suggestion
Use the `AggregatorV3Interface()` function and pass the address of the respective data feed contract as a parameter.
```

2024-11-25 12:31 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +Inside of the functions, call the [latestRoundData](https://docs.chain.link/data-feeds/api-reference#latestrounddata) on the respective data feeds to receive the latest spot prices for the respective
```suggestion
Inside the functions, call the [latestRoundData](https://docs.chain.link/data-feeds/api-reference#latestrounddata) on the respective data feeds to receive the latest spot prices for the respective token.
```

2024-11-25 12:31 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> + */
Please take this out and put it in a `caution` for better visibility.

2024-11-25 13:22 UTC, TalhaMaliktz approved these changes
All good!

2024-11-25 13:22 UTC, TalhaMaliktz commented on docs/building-on-lisk/using-oracle-data/redstone-push.md
> +DO NOT USE THIS CODE IN PRODUCTION.
Too pronounced! Just sentence case would be fine :-D

2024-11-25 13:33 UTC, merged