[LISKDOCS-19] Introduction to Web3 app development
LiskHQ/lisk-docs pull request #260
Opened 2024-12-05 12:52 UTC by Tschakki

2025-01-09 11:11 UTC, TalhaMaliktz requested changes
Please consider the following!

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +To describe important steps in this innovation, websites and apps are generally categorized into different Web "versions":
```suggestion
To describe important steps in this innovation, websites, and apps are generally categorized into different Web "versions":
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    Web 1.0 is the first "version" of the Web, i.e. the first generation of websites that occured when the internet became available to the broader public around 1990.
```suggestion
    Web 1.0 is the first "version" of the Web, i.e., the first generation of websites that occurred when the Internet became available to the broader public around 1990.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    However, some Web 2.0 capabilities were present in the days of Web 1.0, but were implemented differently.
```suggestion
    However, some Web 2.0 capabilities were present in the days of Web 1.0 but were implemented differently.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Concerning frontend app development, there aren't many differences between Web2 and Web3 apps, when it comes to programming languages.
```suggestion
Concerning frontend app development, there aren't many differences between Web2 and Web3 apps when it comes to programming languages.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +To support developers, many blockcain platforms offer their own SDKs and tools to interact with their blockchain, which can make development easier and more efficient.
```suggestion
To support developers, many blockchain platforms offer their own SDKs and tools to interact with their blockchain, which can make development easier and more efficient.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +In Web3 apps, some data is stored on the blockchain, i.e. a decentralized database.
```suggestion
In Web3 apps, some data is stored on the blockchain, i.e., a decentralized database.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +How the data is stored is defined inside of smart cotracts.
```suggestion
How the data is stored is defined inside of smart contracts.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +To interact with the blockchain, there are various libraries and frameworks available, like [viem](https://viem.sh/), [web3.js](https://web3js.readthedocs.io) or [ethers.js](https://docs.ethers.io).
```suggestion
To interact with the blockchain, there are various libraries and frameworks available, like [viem](https://viem.sh/), [web3.js](https://web3js.readthedocs.io), or [ethers.js](https://docs.ethers.io).
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +To get started with the actual development of a Web3 app, you need to be clear about the the right app **platform(s)** to build your Web3 app on.
```suggestion
To get started with the actual development of a Web3 app, you need to be clear about the right **platform(s)** to build your Web3 app on.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Additionally, they don't need to be installed by the user, and can be used directly in the browser.
```suggestion
Additionally, they don't need to be installed by the user and can be used directly in the browser.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +A Progressive Web App (= PWA) allows users to install your web app to their device.
```suggestion
A Progressive Web App (PWA) allows users to install a web app on their devices.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Additionally, PWAs allow a user to directly install the app through your web app, without need to visit an app store.
```suggestion
Additionally, PWAs allow a user to directly install the app through your web app without the need to visit an app store.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +[^1]: Only supported in PWA-compatible browsers (most Chromium based browsers should work).
```suggestion
[^1]: Only supported in PWA-compatible browsers (most Chromium-based browsers should work).
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    Web 2.0 is the era where social media, [web applications](https://en.wikipedia.org/wiki/Web_application), and mobile apps come to the rise.
```suggestion
    Web 2.0 is the era where social media, [web applications](https://en.wikipedia.org/wiki/Web_application), and mobile apps came to the rise.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    Some of the most popular examples for Web 2.0 applications are Facebook, Twitter/X, Amazon and YouTube.
```suggestion
    Some of the most popular examples of Web 2.0 applications are Facebook, X, Amazon, and YouTube.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    Many of these applications and services became important pillars of the internet and peoples life, and even society as a whole.
```suggestion
    Many of these applications and services became important pillars of the internet and people's lives, and even society as a whole.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    However, the more relevant these applications became, the more obvious and relevant became their limitations, as users had to trust the companies behind these applications with their data and pri
```suggestion
    However, the more relevant these applications became, the more obvious and relevant their limitations became, as users had to trust the companies behind them with their data and privacy.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    Though Web 2.0 revolutionized how people use the web in a positive way, it's characteristics lead to certain disadvantages, for users who interact with Web2 applications:
```suggestion
    Though Web 2.0 revolutionized how people positively used the web, a few of its characteristics led to certain disadvantages for users interacting with Web2 applications. For example:
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    Web3 is the idea of a decentralized internet, where users are in control over their data.
```suggestion
    Web3 is based on the idea of a decentralized internet, where users are in control over their data.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    2015, when Ethereum launched as the world's first programmable blockchain, marked the beginning of the Web3 era.
```suggestion
    2015 marked the beginning of the Web3 era when Ethereum launched as the world's first programmable blockchain.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    Often, Web3 apps combine other cutting edge technologies like AI to provide unique new user experiences.
```suggestion
    Often, Web3 apps combine other cutting-edge technologies like AI to provide unique and new user experiences.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +      - Decentralized crowdfunding and -investing platforms
```suggestion
      - Decentralized crowdfunding and investing platforms
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +    Web3 is a promise to bring back the original vision of the internet, where users are in control of their data and privacy, and where the internet is a place for free speech and innovation.
```suggestion
    Web3 promises to bring back the original vision of the internet, where users are in control of their data and privacy and where the internet is a place for free speech and innovation.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +- [Video tutorial: Build a web3 PWA](https://www.youtube.com/watch?v=VU8i-dn2_GE) *by thirdweb*
```suggestion
- [Video tutorial: Build a Web3 PWA](https://www.youtube.com/watch?v=VU8i-dn2_GE) *by thirdweb*
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +They appear as native apps on your desktop or mobile device and offer features like offline support and push notifications.
```suggestion
They appear as native apps on desktop or mobile devices and offer features like offline support and push notifications.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +This way, PWAs allow to develop an application that can be used via browser[^1], mobile, or desktop application alike.
```suggestion
This way, PWAs allow the development of an application that can be used via a browser[^1], mobile, or desktop application alike.
```

2025-01-09 11:11 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Therefore, PWAs are a great choice to reach users on different platforms simultaneously.
```suggestion
Therefore, PWAs are a great choice for reaching users on different platforms simultaneously.
```

2025-01-10 10:50 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2025-01-10 11:11 UTC, TalhaMaliktz requested changes
Broken anchor found!
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/d00fe16c-2553-438e-8794-5ed59d429cf6" />

2025-01-10 11:18 UTC, Tschakki commented
> Broken anchor found! <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/13951043/401963303-d00fe16c-2553-438e-8794-5ed59d429cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MDc4NjIsIm5iZiI6MTczNjUwNzU2MiwicGF0aCI6Ii8xMzk1MTA0My80MDE5NjMzMDMtZDAwZmUxNmMtMjU1My00MzhlLTg3OTQtNWVkNTlkNDI5Y2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDExMTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MGQ5NTczYTFjMWE5NTI0YTI2NzU2MTgxOWJiM2I0ODk1ODAwNmMzYjYyMWE1MTM4ZWM1Y2Q4YzAzODdhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pC_wQI27b2WsBF8fB3kyrFEqzVIS0qu6oSADZgji374">

this seems to be in the translation, which doesn't exist yet for this content... How did you get it?

2025-01-10 11:39 UTC, TalhaMaliktz commented
> > Broken anchor found! <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/13951043/401963303-d00fe16c-2553-438e-8794-5ed59d429cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MDc4NjIsIm5iZiI6MTczNjUwNzU2MiwicGF0aCI6Ii8xMzk1MTA0My80MDE5NjMzMDMtZDAwZmUxNmMtMjU1My00MzhlLTg3OTQtNWVkNTlkNDI5Y2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDExMTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MGQ5NTczYTFjMWE5NTI0YTI2NzU2MTgxOWJiM2I0ODk1ODAwNmMzYjYyMWE1MTM4ZWM1Y2Q4YzAzODdhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pC_wQI27b2WsBF8fB3kyrFEqzVIS0qu6oSADZgji374">
> 
> this seems to be in the translation `/ind/`, which doesn't exist yet for this content... How did you get the error?

I got it when I ran `npm run build && npm run serve`; if it is missing a file, I think we can make it part of our workflow to add a file in the `/ind` folder as well whenever we have the final and approved English version of the new file.

2025-01-10 16:20 UTC, matjazv approved these changes
Current documentation looks good to me!

Maybe consider extending it with below topics if you find them useful for this page:
- Security considerations in Web3 applications (smart contract audits, secure key management, handling user data, bug bounties)
- Testing and deployment (local development env, testnets, continuous integration, monitoring)
- Onboarding Web2 users (abstracting wallet setup, gas fee management, support and community)

2025-01-10 17:12 UTC, Tschakki commented
> > > Broken anchor found! <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/13951043/401963303-d00fe16c-2553-438e-8794-5ed59d429cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MDc4NjIsIm5iZiI6MTczNjUwNzU2MiwicGF0aCI6Ii8xMzk1MTA0My80MDE5NjMzMDMtZDAwZmUxNmMtMjU1My00MzhlLTg3OTQtNWVkNTlkNDI5Y2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDExMTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MGQ5NTczYTFjMWE5NTI0YTI2NzU2MTgxOWJiM2I0ODk1ODAwNmMzYjYyMWE1MTM4ZWM1Y2Q4YzAzODdhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pC_wQI27b2WsBF8fB3kyrFEqzVIS0qu6oSADZgji374">
> > 
> > 
> > this seems to be in the translation `/ind/`, which doesn't exist yet for this content... How did you get the error?
> 
> I got it when I ran `npm run build && npm run serve`; if it is missing a file, I think we can make it part of our workflow to add a file in the `/ind` folder as well whenever we have the final and approved English version of the new file.

I added the file, which did not resolve the error. Then I changed format of the heading, and it fixed it, so I changed it in the original file as well.. not sure why the error was showing up for the translation and not original file though 🤔

2025-01-13 08:24 UTC, TalhaMaliktz approved these changes
LGTM! 👍🏼

2025-01-21 14:30 UTC, matjazv commented on docs/building-on-lisk/web3-app-development.mdx
> +#### Data Storage
Perhaps add a few words regarding data privacy and visibility on-chain.
Any data on a public blockchain is also viewable by anyone. Developers need to be aware that:
- Once data is added to a public blockchain, it becomes virtually impossible to remove and is visible to everyone.
- Sensitive or personal data may require additional measures (for example, encryption or zero-knowledge techniques) to avoid unwanted exposure.

2025-01-21 15:55 UTC, matjazv commented on docs/building-on-lisk/web3-app-development.mdx
> +In addition, soring large amounts of data onchain is quite expensive and slow to store large amounts of data onchain.
```suggestion
In addition, storing large amounts of data onchain is both expensive and slow.
```

2025-01-21 16:04 UTC, matjazv approved these changes
LGTM!
Nice work!

2025-01-24 12:07 UTC, TalhaMaliktz requested changes
Looking good already!

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +### Further Regarding
```suggestion
### Further Reading
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +A major challenge of Web3 applications is to provide a seamless user experience for users, similar to what they are used to from Web2 applications.
```suggestion
A significant challenge for Web3 applications is delivering a user experience that is as seamless as what users expect from Web2 applications.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +To onboard Web2 users to Web3, apps need to simplify the way how users interact with the app, in a way that feels natural and intuitive to them, while still providing the benefits of Web3 in a secure
```suggestion
To onboard Web2 users to Web3, apps need to simplify user interaction so that it feels natural and intuitive to them while still providing the benefits of Web3 in a secure way.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +To aim for a smooth user experience, and to abstract the complexity of blockchain technology away from the user, it is highly recommended to include "account abstraction" (sometimes also referred to
```suggestion
To aim for a smooth user experience, and to abstract the complexity of blockchain technology away from the user, it is highly recommended to include [Account Abstraction](https://www.alchemy.com/overviews/what-is-account-abstraction) (sometimes also referred to as "smart accounts", "smart wallets" or "smart contract accounts") into your Web3 application.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +- **UserOperation**: a structure that describes a transaction to be sent on behalf of a user.
```suggestion
- **UserOperation**: A structure that describes a transaction to be sent on behalf of a user.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Like a transaction, it contains “sender”, “to”, “calldata”, “maxFeePerGas”, “maxPriorityFee”, “signature”, “nonce”.
```suggestion
Like a transaction, it contains `sender`, `to`, `calldata`, `maxFeePerGas`, `maxPriorityFee`, `signature`, `nonce`.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Unlike a transaction the “signature” field usage is not defined by the protocol, but by each account implementation.
```suggestion
Unlike a transaction, the use of the `signature` field is not defined by the protocol but by each account implementation.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +- **Account Contract**: the user's smart account sending a user operation.
```suggestion
- **Account Contract**: The user's smart account sending a user operation.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +- **EntryPoint**: a singleton contract to execute bundles of UserOperations.
```suggestion
- **EntryPoint**: A singleton contract to validate and execute bundles of UserOperations.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +- [Deploying a smart contract with Foundry](/building-on-lisk/deploying-smart-contract/with-Foundry.md)
```suggestion
- [Deploying a smart contract with Foundry](/building-on-lisk/deploying-smart-contract/with-Foundry#testing-the-smart-contract)
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +- [Deploying a smart contract with Remix](/building-on-lisk/deploying-smart-contract/with-Remix.mdx)
The links should be replaced with guides about testing with Hardhat and Remix.

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +- **Smart contract audits**:
Should this be removed?
```suggestion
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Virtual TestNets are easy to set up and configure, giving you full control and flexibility over your environments.
```suggestion
Virtual Testnets are easy to set up and configure, giving you full control and flexibility over your environments.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +To deal with stuff like wallets, and other Web3-specific things, you might want to use specialized Web3 E2E testing tools:
```suggestion
To deal with stuff like wallets, and other Web3-specific things, you might want to use specialized Web3 E2E testing tools.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +[Synpress](https://synpress.io/) is an E2E (End-to-End) testing library for Web3 dapps.
Already abbreviated
```suggestion
[Synpress](https://synpress.io/) is an E2E testing library for Web3 dapps. 
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Synpress can be used with two leading E2E testing frameworks out there, i.e., both [Playwright](https://playwright.dev/) and [Cypress](https://www.cypress.io/), with support for all of their its feat
```suggestion
Synpress can be used with two leading E2E testing frameworks out there, i.e., [Playwright](https://playwright.dev/) and [Cypress](https://www.cypress.io/), with support for all of their features.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +There are also SDKs for Web3 app development that provide a complete tech stack, like [thirdweb](https://thirdweb.com/) or [Alchemy](https://www.alchemy.com/), which take away most of the complexity
```suggestion
There are also SDKs for Web3 app development, like [thirdweb](https://thirdweb.com/) or [Alchemy](https://www.alchemy.com/), which take away most of the complexity of blockchain development and provide a smooth developer experience.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Especially sensistive and private user data should not be stored on the blockchain, except it is encrypted.
```suggestion
Especially sensitive and private user data should not be stored on the blockchain, except if it is encrypted.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Hardhat allows you to deploy your contracts, [run your tests](https://hardhat.org/tutorial/testing-contracts) and debug your code, all within the confines of your local machine.
```suggestion
Hardhat allows you to deploy your contracts, [run your tests](https://hardhat.org/tutorial/testing-contracts), and debug your code, all within the confines of your local machine.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +However, it should be noted that onchain data on a public blockchain is visible to everyone and therefore not suitable for all types of data.
```suggestion
However, it should be noted that onchain data on a public blockchain is visible to everyone and, therefore, not suitable for all types of data.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +The intrinsic vulnerabilities of smart contracts, the immutability of blockchain data and interacting with a decentralized network call for specific testing and security measures.
```suggestion
The intrinsic vulnerabilities of smart contracts, the immutability of blockchain data, and the interactions with a decentralized network, call for specific testing and security measures.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Gladly, there are already many tools available to help developers ensure the security and reliability of their Web3 apps.
```suggestion
Gladly, many tools are already available to help developers ensure the security and reliability of their Web3 apps.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +There are several tools available that help developers to analyze their smart contracts for common security issues and vulnerabilities, for example:
```suggestion
There are several tools available that help developers analyze their smart contracts for common security issues and vulnerabilities, for example:
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +This specifically includes testing the frontend of your application, ensuring that the user interface works as expected.
```suggestion
This specifically includes testing the frontend of your application and ensuring that the user interface works as expected.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +Measure and improve your apps performance, throughput, and resilience under different levels of traffic and transactions.
```suggestion
Measure and improve your app's performance, throughput, and resilience under different levels of traffic and transactions.
```

2025-01-24 12:07 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +## What are Web3 Applications?
I would wait for confirmation from marketing before choosing a capitalization style.

2025-01-27 10:38 UTC, Tschakki commented on docs/building-on-lisk/web3-app-development.mdx
> +To aim for a smooth user experience, and to abstract the complexity of blockchain technology away from the user, it is highly recommended to include "account abstraction" (sometimes also referred to
I wouldn't add a link to an external site here, as we explain below account abstraction ourselves to the reader. We could add it under the further reading section, if you consider this resource to be valuable.

2025-01-27 10:44 UTC, Tschakki commented on docs/building-on-lisk/web3-app-development.mdx
> +This specifically includes testing the frontend of your application, ensuring that the user interface works as expected.
```suggestion
This specifically includes testing the frontend of your application, which ensures that the user interface works as expected.
```

2025-01-27 13:20 UTC, TalhaMaliktz commented on docs/building-on-lisk/web3-app-development.mdx
> +To aim for a smooth user experience, and to abstract the complexity of blockchain technology away from the user, it is highly recommended to include "account abstraction" (sometimes also referred to
Sure, the further reading section sounds suitable as well! I would use this [Blog](https://www.alchemy.com/blog/account-abstraction), which I found very useful for understanding AA.

2025-01-27 16:27 UTC, Tschakki commented on docs/building-on-lisk/web3-app-development.mdx
> +- [Deploying a smart contract with Remix](/building-on-lisk/deploying-smart-contract/with-Remix.mdx)
Yes, we should extend the guides with examples how to test the smart contract, I created the corresponding issues now 👍

2025-01-29 15:17 UTC, Tschakki commented on docs/building-on-lisk/web3-app-development.mdx
> +To aim for a smooth user experience, and to abstract the complexity of blockchain technology away from the user, it is highly recommended to include "account abstraction" (sometimes also referred to
added the link below!

2025-02-10 15:01 UTC, Tschakki commented on docs/building-on-lisk/web3-app-development.mdx
> +## What are Web3 Applications?
I updated the headings now to be all sentence case 👍

2025-02-11 11:41 UTC, TalhaMaliktz approved these changes
LGTM! 👍🏼

2025-02-11 12:24 UTC, merged