docs translating into indonesia
LiskHQ/lisk-docs pull request #262
Opened 2024-12-11 02:10 UTC by fujianggara10

path i18n/ind/docusaurus-plugin-content-docs/current
├── about-lisk.mdx
├── docs-user.mdx
├── lisk-l1.mdx
├── lisk-tools.mdx
└── intro.mdx
```

This structure reflects the following:

1. about-lisk: A document about Lisk.
2. docs-user: A document for users of Lisk, likely detailing user-related content.
3. lisk-l1: A document focusing on Lisk Layer 1.
4. lisk-tools: A document about the tools available within the Lisk ecosystem.

intro.mdx: A general introduction file

2024-12-18 07:35 UTC, jasonyapri requested changes
I found lots of imperfect translations, and some incorrect English translation. I've submitted 38 comments on the Git Pull Request so far. Still reviewing the rest of the Indonesian translation now.

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/_category_.json
> +    "description": "Sebuah pengenalan singkat tentang Lisk."
It's better to use "Pengenalan singkat tentang Lisk" and omit the "Sebuah" so it's more natural while retaining the same meaning.

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +Anda dapat membaca lebih lanjut tentang cara kerja biaya gas di Ethereum di [Ethereum.org](https://ethereum.org/en/developers/docs/gas/).
"gas di Ethereum" -> "gas Ethereum"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +Biaya Data L1 dikenakan secara otomatis untuk setiap transaksi yang dimasukkan dalam blok Lisk Mainnet.
"dimasukkan dalam blok" -> "dimasukkan ke dalam blok"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +Biaya Data L1 dipengaruhi secara signifikan oleh base fee Ethereum yang diteruskan terus-menerus dan tanpa kepercayaan dari Ethereum ke Lisk Mainnet.
"diteruskan terus-menerus dan tanpa kepercayaan" -> "diteruskan secara terus-menerus dan tanpa kepercayaan (trustless)"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +2. **Base fee Ethereum saat ini** dan/atau blob base fee (dikirim tanpa kepercayaan dari Ethereum).
"dikirim tanpa kepercayaan dari Ethereum" -> "dikirim secara trustless dari Ethereum"

"Tanpa kepercayaan" will generally be understood by without faith. Many opt for just using the english word for this "trustless"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +Ini dihitung berdasarkan ukuran transaksi yang diserialisasi, menggunakan model regresi linier berdasarkan data OP Mainnet historis, dengan asumsi bahwa itu dikompresi dengan kompresi Brotli.
"berdasarkan data OP Mainnet historis" -> "berdasarkan data historis OP Mainnet"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +Selanjutnya, dua parameter skalar diterapkan pada base fee dan blob base fee untuk menghitung pengali harga gas berbobot.
"dua parameter skalar diterapkan pada base fee dan blob base fee" -> "dua skalar diterapkan pada parameter base fee dan blob base fee"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +Nilai saat ini untuk parameter skalar adalah:
"Nilai saat ini untuk parameter skalar adalah:" -> "Nilai saat ini untuk skalar adalah:"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +Saat ini **tidak** mungkin untuk membatasi biaya Data L1 maksimum yang bersedia dibayar oleh transaksi.
"Saat ini **tidak** mungkin untuk membatasi biaya Data L1 maksimum yang bersedia dibayar oleh transaksi." -> "Saat ini tidak memungkinkan untuk membatasi maksimum Biaya Data L1 yang bersedia dibayar oleh sebuah transaksi."

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> -While the L1 Data Fee will be always cheaper compared to posting the transaction directly to the Ethereum mainnet (due to the efficient encoding in batching transactions), its value will vary dependi
@TalhaMaliktz  English: "will be always cheaper" -> "will always be cheaper"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +1. Dompet memperkirakan biaya transaksi dan menunjukkan kepada pengguna.
"menunjukkan" -> "menunjukkannya"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/network-info.md
> +| **Lisk Testnet Bridge**                                | https://sepolia-bridge.lisk.com                                             |
"Lisk Testnet Bridge" -> "Bridge Lisk Testnet"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/network-info.md
> +| **Lisk Testnet Faucet** (Memberikan LSK)               | https://sepolia-faucet.lisk.com/                                            |
"Lisk Testnet Faucet" -> "Faucet Testnet Lisk"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/network-info.md
> +| **Superchain Testnet Faucet** (Memberikan ETH)         | https://app.optimism.io/faucet                                              |
"Superchain Testnet Faucet" -> "Faucet Superchain Testnet"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/bridges.mdx
> -description: Documentation for bridging assets to Lisk. This page covers how to bridge ETH and ERC-20s between Ethereum Sepolia and Lisk Sepoklia, with essential cautions and contract information.
@TalhaMaliktz "Lisk Sepoklia" -> "Lisk Sepolia"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/bridges.mdx
> +description: Dokumentasi untuk menjembatani aset ke Lisk. Halaman ini membahas cara menjembatani ETH dan ERC-20 antara Ethereum Sepolia dan Lisk Sepolia, dengan kewaspadaan dan informasi kontrak yang
"ETH dan ERC-20" -> "ETH dan token ERC-20"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/bridges.mdx
> +  Periksa status penarikan mainnet Anda di [Sejarah Penarikan](https://bridge.lisk.com/history?slug=lisk).
"Sejarah Penarikan" -> "Riwayat Penarikan".

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/bridges.mdx
> +  Periksa status penarikan testnet Anda di [Sejarah Penarikan](https://sepolia-bridge.lisk.com/history?slug=lisk-sepolia-testnet).
"Sejarah Penarikan" -> "Riwayat Penarikan".

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/claiming.mdx
> +Pemegang token Lisk memiliki **jendela waktu 2 tahun mulai 21 Mei 2024** untuk mengklaim dan memigrasikan token mereka ke Lisk L2.
"jendela waktu 2 tahun " -> "jangka waktu 2 tahun "

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/claiming.mdx
> +1. Akun di rantai Lisk L1, dengan beberapa token LSK.
"rantai Lisk L1" -> "Lisk L1"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/claiming.mdx
> +   Jumlah token LSK yang dapat Anda klaim di Lisk L2 adalah sama dengan jumlah yang Anda pegang di Lisk L1 pada tinggi snapshot.
"pada tinggi snapshot." -> "pada tinggi snapshot tersebut."

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/claiming.mdx
> +2. Versi terbaru dari [Lisk Migration Wallet](https://lisk.com/wallet) yang terpasang (3.0.3)
"yang terpasang." -> "telah terpasang."

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/connecting-to-a-wallet.mdx
> +    'Dompet kompatibel EVM',
"Dompet kompatibel EVM" -> "Dompet yang kompatibel dengan EVM"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/connecting-to-a-wallet.mdx
> +**Lisk Mainnet** dapat **ditambahkan** sebagai jaringan kustom ke **dompet kompatibel EVM** mana pun (misalnya [MetaMask](https://metamask.io/)).
"dompet kompatibel EVM" -> "dompet yang kompatibel dengan EVM"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/connecting-to-a-wallet.mdx
> +**Lisk Sepolia** dapat **ditambahkan** sebagai jaringan kustom ke **dompet kompatibel EVM** mana pun (misalnya [MetaMask](https://metamask.io/)).
"dompet kompatibel EVM" -> "dompet yang kompatibel dengan EVM"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/connecting-to-a-wallet.mdx
> +    6. Ketuk tombol `Save` untuk menyimpan Lisk sebagai jaringan.
"Ketuk" -> "Tekan"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/connecting-to-a-wallet.mdx
> +    6. Ketuk tombol `Save` untuk menyimpan Lisk sebagai jaringan.
"Ketuk" -> "Tekan"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/connecting-to-a-wallet.mdx
> +Sekarang Anda harus dapat terhubung ke Lisk dengan memilihnya dari menu dropdown pemilihan jaringan.
"harus dapat" -> "seharusnya dapat"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/connecting-to-a-wallet.mdx
> +    3. Plugin MetaMask akan terbuka dan otomatis mengisi semua informasi yang dibutuhkan untuk menambahkan jaringan.
"otomatis mengisi semua informasi yang dibutuhkan untuk menambahkan jaringan." -> "semua informasi yang dibutuhkan untuk menambahkan jaringan otomatis terisi."

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/connecting-to-a-wallet.mdx
> +    3. Plugin MetaMask akan terbuka dan otomatis mengisi semua informasi yang dibutuhkan untuk menambahkan jaringan.
"otomatis mengisi semua informasi yang dibutuhkan untuk menambahkan jaringan." -> "semua informasi yang dibutuhkan untuk menambahkan jaringan otomatis terisi."

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/exchanges.md
> -| **HTX** (formerly Houbi) | 🟣 Ethereum <br/>(Lisk support coming soon) | [LSK/USDT](https://www.htx.com.jm/trade/lsk_usdt/)            |
@TalhaMaliktz Should be "Huobi", not "Houbi"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/exchanges.md
> +| **HTX** (dulu Houbi)    | 🟣 Ethereum <br/>(Dukungan Lisk segera hadir) | [LSK/USDT](https://www.htx.com.jm/trade/lsk_usdt/)             |
"dulu Houbi" -> "sebelumnya Huobi"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/exchanges.md
> +Bidang "jaringan yang didukung" menunjukkan blockchain yang digunakan oleh bursa untuk setoran & penarikan LSK.
Bidang "jaringan yang didukung" -> Kolom "jaringan yang didukung"

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/delegation.mdx
> +[^1]: Pada saat penulisan, ada [masalah](https://github.com/blockscout/frontend/issues/2059) dengan menghubungkan MetaMask ke Blockscout di Firefox;
dengan menghubungkan -> saat menghubungkan

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +| 2024 | 15.000.000 | 6.250.000 LSK cair pada migrasi, 8.750.000 LSK dirilis secara linier pada 2024, dimulai dari migrasi. |
cair pada migrasi -> cair saat migrasi
dimulai dari migrasi -> dimulai sejak migrasi

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Lisk DAO memungkinkan setiap pemegang token LSK yang mempertaruhkan token mereka untuk berpartisipasi dalam tata kelola onchain untuk proyek Lisk.
mempertaruhkan token -> staking token

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +- Staking token untuk durasi penguncian tertentu (antara 2 minggu dan 2 tahun) di [Lisk Portal](https://portal.lisk.com).
antara 2 minggu dan 2 tahun -> antara 2 minggu hingga 2 tahun

2024-12-18 07:35 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Dalam kasus menjeda, pengguna mendapatkan peningkatan kekuatan voting.
Dalam kasus menjeda -> Dalam kasus jeda

2024-12-18 07:45 UTC, jasonyapri requested changes

2024-12-18 07:45 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Kerangka Governor mengharuskan **delegasi kekuatan voting** untuk menggunakannya.
```suggestion
Kerangka Governor mengharuskan **pendelegasian kekuatan voting** agar dapat digunakan.
```

2024-12-18 08:00 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx

2024-12-18 08:00 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +- **Ambang Proposal**: Untuk membuat proposal, kekuatan voting dari pembuat proposal harus minimal 300.000 vpLSK, yaitu nilai yang setara dengan 100.000 LSK yang dikunci selama 2 tahun dengan hitunga
```suggestion
- **Ambang Proposal**: Untuk membuat proposal, kekuatan suara dari pembuat proposal harus minimal 300.000 vpLSK, yaitu nilai yang setara dengan 100.000 LSK yang dikunci selama 2 tahun dengan jeda hitungan waktu.
```

2024-12-18 08:00 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +- **Kuorum**: Untuk proposal diterima, jumlah suara "ya" dan "abstain" harus mencapai minimal 24.000.000 vpLSK, yaitu nilai yang setara dengan 8.000.000 LSK yang dikunci selama 2 tahun dengan hitunga
```suggestion
- **Kuorum**: Untuk proposal diterima, jumlah suara "ya" dan "abstain" harus mencapai minimal 24.000.000 vpLSK, yaitu nilai yang setara dengan 8.000.000 LSK yang dikunci selama 2 tahun dengan jeda hitungan waktu.
```

2024-12-18 08:00 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Transfer dari [harta DAO Lisk](#treasury) dapat dilakukan oleh siapa saja, setelah proposal pendanaan disetujui.
```suggestion
Transfer dari [kas DAO Lisk](#treasury) dapat dilakukan oleh siapa saja, setelah proposal pendanaan disetujui.
```

2024-12-18 08:00 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +1. Penghapusan proposal draf yang dianggap wajar sebagai penipuan, spam, fitnah, kebencian, atau tidak pantas lainnya.
```suggestion
1. Penghapusan proposal draf yang secara wajar dianggap sebagai penipuan, spam, fitnah, kebencian, atau hal lain yang tidak pantas.
```

2024-12-18 08:11 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/proposal-lifecycle.mdx

2024-12-18 08:11 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/proposal-lifecycle.mdx
> +    Pemerintahan Lisk,
```suggestion
    Tata kelola Lisk,  
```

2024-12-18 08:11 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/proposal-lifecycle.mdx
> +Ide untuk proposal dapat didiskusikan di saluran `#lisk-dao` di [Lisk Chat](https://lisk.chat) atau di thread diskusi baru di [Forum Pemerintahan](https://forum.lisk.com).
```suggestion
Ide untuk proposal dapat didiskusikan di saluran `#lisk-dao` di [Lisk Chat](https://lisk.chat) atau di thread diskusi baru di [Forum Tata kelola](https://forum.lisk.com).  
```

2024-12-18 08:11 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/proposal-lifecycle.mdx
> +Setelah ide menghasilkan proposal yang konkret, buat thread **proposal draf** baru di forum:
```suggestion
Setelah sebuah ide menghasilkan proposal yang konkret, buatlah thread **proposal draf** baru di forum:
```

2024-12-18 08:11 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/proposal-lifecycle.mdx
> +Setelah proposal baru dibuat, komunitas memiliki waktu **1 minggu** tepat untuk memberikan suara di Tally.
```suggestion
Setelah proposal baru dibuat, komunitas memiliki waktu tepat **1 minggu** untuk memberikan suara di Tally.  
```

2024-12-18 08:22 UTC, jasonyapri requested changes
Unified "Voting Power" Indonesian translation into "Kekuatan suara" instead of "Kekuatan voting"

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +### Kekuatan Voting
```suggestion
### Kekuatan Suara
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Setiap akun yang memegang **LSK** dapat **staking/mengunci** sejumlah token LSK untuk mendapatkan kekuatan voting dan [hadiah staking](../user/staking/overview#staking-rewards).
```suggestion
Setiap akun yang memegang **LSK** dapat **staking/mengunci** sejumlah token LSK untuk mendapatkan kekuatan suara dan [hadiah staking](../user/staking/overview#staking-rewards).
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +- Menerima kekuatan voting dan hadiah staking yang sebanding dengan jumlah token yang dikunci.
```suggestion
- Menerima kekuatan suara dan hadiah staking yang sebanding dengan jumlah token yang dikunci.
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +- [Delegasikan](#delegation) kekuatan voting ke diri Anda sendiri atau delegasi lain untuk menggunakannya.
```suggestion
- [Delegasikan](#delegation) kekuatan suara ke diri Anda sendiri atau delegasi lain untuk menggunakannya.
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Token yang dikunci memberikan kekuatan voting yang sebanding dengan jumlah token yang dikunci.
```suggestion
Token yang dikunci memberikan kekuatan suara yang sebanding dengan jumlah token yang dikunci.
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +#### Perhitungan Kekuatan Voting
```suggestion
#### Perhitungan Kekuatan Suara
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Secara konkret, 1 LSK yang dikunci memberikan satu unit kekuatan voting (= 1 vpLSK).
```suggestion
Secara konkret, 1 LSK yang dikunci memberikan satu unit kekuatan suara (= 1 vpLSK).
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +##### Meningkatkan Kekuatan Voting
```suggestion
##### Meningkatkan Kekuatan Suara
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Dalam kasus menjeda, pengguna mendapatkan peningkatan kekuatan voting.
```suggestion
Dalam kasus menjeda, pengguna mendapatkan peningkatan kekuatan suara.
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Dengan demikian, kekuatan voting dapat meningkat hingga 200%, yang tercapai pada durasi penguncian maksimal 2 tahun.
```suggestion
Dengan demikian, kekuatan suara dapat meningkat hingga 200%, yang tercapai pada durasi penguncian maksimal 2 tahun.
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Kekuatan voting untuk setiap proposal dihitung dari snapshot saat [pembuatan proposal](proposal-lifecycle#2-proposal-creation).
```suggestion
Kekuatan suara untuk setiap proposal dihitung dari snapshot saat [pembuatan proposal](proposal-lifecycle#2-proposal-creation).
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Oleh karena itu, menjeda durasi penguncian setelah proposal dibuat tidak akan meningkatkan kekuatan voting untuk proposal ini, tetapi untuk proposal yang akan datang.
```suggestion
Oleh karena itu, menjeda durasi penguncian setelah proposal dibuat tidak akan meningkatkan kekuatan suara untuk proposal ini, tetapi untuk proposal yang akan datang.
```

2024-12-18 08:22 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +Kekuatan voting dapat didelegasikan ke pengguna lain atau ke diri Anda sendiri.
```suggestion
Kekuatan suara dapat didelegasikan ke pengguna lain atau ke diri Anda sendiri.
```

2024-12-18 08:30 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/voting.mdx

2024-12-18 08:30 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/voting.mdx
> +Sangat penting bagi anggota Lisk DAO untuk dapat berinteraksi dengan DAO kapan saja, bahkan ketika Tally, antarmuka standar untuk Lisk DAO, sedang tidak aktif.
```suggestion
Sangat penting bagi anggota Lisk DAO untuk dapat berinteraksi dengan DAO kapan saja, bahkan ketika Tally, frontend standar untuk Lisk DAO, sedang tidak aktif.
```

2024-12-18 08:30 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/voting.mdx
> +        topics:['0x7d84a6263ae0d98d3329bd7b46bb4e8d6f98cd35a7adb45c274c8b7fd5ebd5e0'] // tanda tangan acara `ProposalCreated`
```suggestion
        topics:['0x7d84a6263ae0d98d3329bd7b46bb4e8d6f98cd35a7adb45c274c8b7fd5ebd5e0'] // signature dari event `ProposalCreated`
```

2024-12-18 08:30 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/voting.mdx
> +Untuk memastikan proposal yang Anda cari, klik tab `Logs` dan cari acara `ProposalCreated`. Jika nilai-nilai, terutama untuk `description`, `voteStart`, dan `voteEnd`, cocok dengan proposal yang ingi
```suggestion
Untuk memastikan proposal yang Anda cari, klik tab `Logs` dan cari event `ProposalCreated`. Jika nilai-nilai, terutama untuk `description`, `voteStart`, dan `voteEnd`, cocok dengan proposal yang ingin Anda beri suara, maka itu adalah proposal yang benar. Untuk mendapatkan ID proposal, salin nilai dari kolom `proposalId`.
```

2024-12-18 08:30 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/voting.mdx
> +Untuk memverifikasi bahwa suara Anda telah dikirim dengan benar, Anda dapat memeriksa acara `VoteCast` dari transaksi Anda.
```suggestion
Untuk memverifikasi bahwa suara Anda telah dikirim dengan benar, Anda dapat memeriksa event `VoteCast` dari transaksi Anda.
```

2024-12-18 08:30 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/voting.mdx
> +[^1]: Pada saat penulisan, terdapat [masalah](https://github.com/blockscout/frontend/issues/2059) dengan menghubungkan MetaMask ke Blockscout di Firefox;
```suggestion
[^1]: Pada saat penulisan, terdapat [masalah](https://github.com/blockscout/frontend/issues/2059) saat menghubungkan MetaMask ke Blockscout di Firefox;
```

2024-12-18 09:26 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx

i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx

i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx
> +title: 'Ikhtisar'
```suggestion
title: 'Gambaran Umum'
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx
> +title: 'Ikhtisar'
@fujianggara10 "Gambaran Umum" translation from "Overview" is already used in previous files. Try to maintain a unified translation for all the documents and stick with one version.

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx
> +# Ikhtisar
```suggestion
# Gambaran Umum
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx
> +- Temukan [model pemerintahan Lisk](/governance/overview) dan ambil bagian dalam membentuk masa depan Lisk.
```suggestion
- Temukan [model tata kelola Lisk](/governance/overview) dan ambil bagian dalam membentuk masa depan Lisk.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'memperpanjang posisi kunci',
```suggestion
    'perpanjang posisi penguncian',
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'memperpanjang staking',
```suggestion
    'perpanjang staking',
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'memperpanjang durasi',
```suggestion
    'perpanjang durasi',
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'modifikasi posisi kunci',
```suggestion
    'modifikasi posisi penguncian',
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'update posisi kunci',
```suggestion
    'update posisi penguncian',
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +description: 'Cara memperpanjang durasi staking pada posisi kunci tertentu.'
```suggestion
description: 'Cara memperpanjang durasi staking pada posisi penguncian tertentu.'
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +Panduan ini menjelaskan langkah demi langkah cara memperpanjang durasi hitung mundur pada [posisi kunci](overview#locking-positions) tertentu.
```suggestion
Panduan ini menjelaskan langkah demi langkah cara memperpanjang durasi hitung mundur pada [posisi penguncian](overview#locking-positions) tertentu.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +2. Di daftar posisi kunci Anda, klik posisi kunci yang ingin Anda perpanjang untuk memperluasnya.
```suggestion
2. Di daftar posisi penguncian Anda, klik posisi penguncian yang ingin Anda perpanjang untuk memperluasnya.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +4. Tentukan jumlah minggu yang ingin Anda perpanjang durasi hitung mundur posisi kunci saat ini.
```suggestion
4. Tentukan jumlah minggu yang ingin Anda tambahkan untuk memperpanjang durasi hitung mundur dari posisi penguncian saat ini.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    Anda dapat meninjau tanggal akhir baru dari posisi kunci langsung di prompt.
```suggestion
    Anda dapat meninjau tanggal akhir baru dari posisi penguncian langsung di prompt.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    Selain itu, Anda juga dapat melihat preview jumlah voting power yang akan Anda peroleh dengan memperpanjang durasi posisi kunci (voting power hanya akan meningkat jika posisi dijeda, lihat [Menin
```suggestion
    Selain itu, Anda juga dapat melihat preview jumlah kekuatan suara yang akan Anda peroleh dengan memperpanjang durasi posisi penguncian (kekuatan suara hanya akan meningkat jika posisi dijeda, lihat [Meningkatkan Kekuatan Suara](/governance/overview#boosting-the-voting-power)).
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +6. Hitung mundur posisi kunci sekarang akan diperpanjang sesuai jumlah minggu yang telah ditentukan.
```suggestion
6. Hitung mundur posisi penguncian sekarang akan diperpanjang sesuai jumlah minggu yang telah ditentukan.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +title: Cara Meningkatkan Staking
```suggestion
title: Cara Meningkatkan Jumlah Staking
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +    'meningkatkan staking',
```suggestion
    'meningkatkan jumlah staking',
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +    'modifikasi staking',
```suggestion
    'modifikasi jumlah staking',
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +Panduan ini menjelaskan langkah demi langkah cara meningkatkan jumlah LSK yang dipertaruhkan pada [posisi kunci](overview#locking-positions) tertentu.
```suggestion
Panduan ini menjelaskan langkah demi langkah cara meningkatkan jumlah LSK yang distaking pada [posisi penguncian](overview#locking-positions) tertentu.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +    'meningkatkan posisi kunci',
```suggestion
    'meningkatkan posisi penguncian',
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +description: 'Cara meningkatkan jumlah staking pada posisi kunci tertentu.'
```suggestion
description: 'Cara meningkatkan jumlah staking pada posisi penguncian tertentu.'
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +    'modifikasi posisi kunci',
```suggestion
    'modifikasi posisi penguncian',
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +2. Di daftar posisi kunci Anda, klik posisi kunci yang ingin Anda tingkatkan untuk memperluasnya.
```suggestion
2. Di daftar posisi penguncian Anda, klik posisi penguncian yang ingin Anda tingkatkan untuk memperluasnya.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +4. Tentukan jumlah LSK yang ingin Anda tambahkan ke posisi kunci tersebut.
```suggestion
4. Tentukan jumlah LSK yang ingin Anda tambahkan ke posisi penguncian tersebut.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +8. Posisi kunci Anda sekarang akan meningkat dengan jumlah yang ditentukan.
```suggestion
8. Posisi penguncian Anda sekarang akan meningkat dengan jumlah yang ditentukan.
```

2024-12-18 09:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +Jika Anda memuat ulang halaman, Anda seharusnya melihat jumlah staking yang meningkat pada posisi kunci di dashboard staking.
```suggestion
Jika Anda memuat ulang halaman, Anda seharusnya melihat jumlah staking yang meningkat pada posisi penguncian di dashboard staking.
```

2024-12-18 09:54 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx

i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +title: Cara Menangguhkan Hitung Mundur Staking
```suggestion
title: Cara Menjeda Hitung Mundur Staking
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx
> +title: 'Ikhtisar'
```suggestion
title: 'Gambaran Umum'
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx
> +# Ikhtisar
```suggestion
# Gambaran Umum
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx
> +- Hubungkan dengan dompet pilihan Anda dengan mengikuti panduan [Menghubungkan ke Dompet](/user/connecting-to-a-wallet).
```suggestion
- Hubungkan dompet pilihan Anda dengan mengikuti panduan [Menghubungkan ke Dompet](/user/connecting-to-a-wallet).
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +description: 'Cara memperpanjang durasi staking pada posisi kunci tertentu.'
```suggestion
description: 'Cara memperpanjang durasi staking pada posisi penguncian tertentu.'
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'memperpanjang posisi kunci',
```suggestion
    'perpanjang posisi penguncian',
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'memperpanjang staking',
```suggestion
    'perpanjang staking',
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'memperpanjang durasi',
```suggestion
    'perpanjang durasi',
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'modifikasi posisi kunci',
```suggestion
    'modifikasi posisi penguncian',
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    'update posisi kunci',
```suggestion
    'update posisi penguncian',
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +Panduan ini menjelaskan langkah demi langkah cara memperpanjang durasi hitung mundur pada [posisi kunci](overview#locking-positions) tertentu.
```suggestion
Panduan ini menjelaskan langkah demi langkah cara memperpanjang durasi hitung mundur [posisi penguncian](overview#locking-positions) tertentu.
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +2. Di daftar posisi kunci Anda, klik posisi kunci yang ingin Anda perpanjang untuk memperluasnya.
```suggestion
2. Di daftar posisi penguncian Anda, klik posisi penguncian yang ingin Anda perpanjang untuk memperluasnya.
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +4. Tentukan jumlah minggu yang ingin Anda perpanjang durasi hitung mundur posisi kunci saat ini.
```suggestion
4. Tentukan jumlah minggu yang ingin Anda tambahkan untuk memperpanjang durasi hitung mundur dari posisi penguncian saat ini.
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    Anda dapat meninjau tanggal akhir baru dari posisi kunci langsung di prompt.
```suggestion
    Anda dapat meninjau tanggal akhir baru dari posisi penguncian langsung di prompt.
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +    Selain itu, Anda juga dapat melihat preview jumlah voting power yang akan Anda peroleh dengan memperpanjang durasi posisi kunci (voting power hanya akan meningkat jika posisi dijeda, lihat [Menin
```suggestion
    Selain itu, Anda juga dapat melihat preview jumlah kekuatan suara yang akan Anda peroleh dengan memperpanjang durasi posisi penguncian (kekuatan suara hanya akan meningkat jika posisi dijeda, lihat [Meningkatkan Kekuatan Suara](/governance/overview#boosting-the-voting-power)).
```

2024-12-18 09:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/extend-duration.mdx
> +6. Hitung mundur posisi kunci sekarang akan diperpanjang sesuai jumlah minggu yang telah ditentukan.
```suggestion
6. Hitung mundur posisi penguncian sekarang akan diperpanjang sesuai jumlah minggu yang telah ditentukan.
```

2024-12-18 14:52 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +description: 'Cara menangguhkan hitung mundur pada posisi kunci.'
```suggestion
description: 'Cara menjeda hitung mundur pada posisi penguncian.'
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +    'menangguhkan posisi',
```suggestion
    'jeda posisi',
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +    'menangguhkan posisi kunci',
```suggestion
    'jeda posisi penguncian',
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +    'menangguhkan periode kunci',
```suggestion
    'jeda periode penguncian',
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +    'meningkatkan kekuatan suara',
```suggestion
    'dorong kekuatan suara',
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +    'meningkatkan voting power',
```suggestion
    'tingkatkan kekuatan suara',
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +Panduan ini menjelaskan langkah demi langkah cara menangguhkan hitung mundur pada [posisi kunci](overview#locking-positions), untuk mendapatkan lebih banyak [kekuatan suara](/governance/overview#voti
```suggestion
Panduan ini menjelaskan langkah demi langkah cara menjeda hitung mundur pada [posisi penguncian](overview#locking-positions), untuk mendapatkan lebih banyak [kekuatan suara](/governance/overview#voting-power) di Lisk DAO dan menghindari penurunan [hadiah](overview#staking-rewards) harian.
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +Menangguhkan posisi kunci Anda dapat [meningkatkan kekuatan suara](/governance/overview#boosting-the-voting-power) hingga **200%**.
```suggestion
Menjeda posisi penguncian Anda dapat [meningkatkan kekuatan suara](/governance/overview#boosting-the-voting-power) hingga **200%**.
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +2. Di daftar posisi kunci Anda, klik posisi kunci yang ingin Anda tangguhkan untuk memperluasnya.
```suggestion
2. Di daftar posisi penguncian Anda, klik posisi penguncian yang ingin Anda jeda untuk memperluasnya.
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +5. Posisi kunci Anda sekarang akan ditangguhkan, dan Anda akan melihat pesan konfirmasi.
```suggestion
5. Posisi penguncian Anda sekarang akan dijeda, dan Anda akan melihat pesan konfirmasi.
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +    Sebuah prompt akan muncul, menginformasikan Anda tentang proses penangguhan.
```suggestion
    Sebuah prompt akan muncul, menginformasikan Anda tentang proses penjedaan.
```

2024-12-18 14:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +    Konfirmasi bahwa Anda memahami konsekuensi dari penangguhan posisi dengan mengklik tombol `Pause Countdown`.
```suggestion
    Konfirmasi bahwa Anda memahami konsekuensi dari penjedaan posisi dengan mengklik tombol `Pause Countdown`.
```

2024-12-18 14:58 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/legacy-chain-service.md

2024-12-18 14:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/legacy-chain-service.md
>      chain history,
```suggestion
    riwayat rantai,
```

2024-12-18 14:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/legacy-chain-service.md
>      account history
```suggestion
    riwayat akun
```

2024-12-19 03:34 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/using-lisk/import-lsk.mdx

i18n/ind/docusaurus-plugin-content-docs/current/intro.mdx

2024-12-19 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/using-lisk/import-lsk.mdx
> +    'Dompet kompatibel EVM',
```suggestion
    'Dompet yang kompatibel dengan EVM',
```

2024-12-19 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/using-lisk/import-lsk.mdx
> +Ini berarti pemegang LSK harus mengimpor token LSK secara manual ke dalam dompet untuk berbagai jaringan, agar dapat ditampilkan di dompet MetaMask.
```suggestion
Ini berarti pemegang LSK harus mengimpor token LSK secara manual ke dalam dompet di berbagai jaringan, agar dapat ditampilkan di dompet MetaMask.
```

2024-12-19 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/intro.mdx
> +# Pengenalan Lisk
```suggestion
# Pengenalan Lisk dalam Bahasa Indonesia
```

2024-12-19 04:26 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/indexers.md

i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/indexers.md
> +    "jaringan uji Lisk",
```suggestion
    "jaringan test Lisk",  
```

Because Lisk testnet is translated as testnet Lisk.

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/indexers.md
> +[Goldsky](https://goldsky.com/) adalah pengindeks data pilihan untuk pembangun web3, yang menawarkan hosting subgraph berkinerja tinggi dan saluran replikasi data waktu nyata.
```suggestion
[Goldsky](https://goldsky.com/) adalah pengindeks data pilihan untuk pembangun web3, yang menawarkan hosting subgraph berkinerja tinggi dan saluran replikasi data secara real-time.  
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/indexers.md
> +- [Mirror](https://docs.goldsky.com/introduction#mirror): Dengan hanya satu file definisi `.yaml`, Anda dapat menggunakan Mirror, teknologi saluran data tanpa server, untuk memperoleh data waktu nyat
```suggestion
- [Mirror](https://docs.goldsky.com/introduction#mirror): Dengan hanya satu file definisi `.yaml`, Anda dapat menggunakan Mirror, teknologi saluran data tanpa server, untuk memperoleh data secara real-time ke dalam basis data Anda.  
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/indexers.md
> +Data didorong ke antrean atau penyimpanan data Anda, di mana data tersebut dapat dipertanyakan tanpa batasan laju eksternal, bersama dengan data yang sudah ada.
```suggestion
Data didorong ke antrean atau penyimpanan data Anda, di mana data tersebut dapat dikueri tanpa rate limit eksternal, bersama dengan data yang sudah ada.  
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +description: Dokumentasi untuk berbagai orakel blockchain untuk Lisk.
Let's use oracle instead of orakel as there is not a single Bahasa Indonesia article on the internet that uses orakel, all of them uses oracle
```suggestion
description: Dokumentasi untuk berbagai oracle blockchain di Lisk.  
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +# Orakel
```suggestion
# Oracle
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +[Orakel](https://ethereum.org/en/developers/docs/oracles/) menyediakan data offchain ke onchain.
```suggestion
[Oracle](https://ethereum.org/en/developers/docs/oracles/) menyediakan data offchain ke onchain.  
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +Berikut ini adalah orakel yang sudah mendukung jaringan Lisk:
```suggestion
Berikut ini adalah oracle yang sudah mendukung jaringan Lisk:
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +*   [RedStone Push](https://docs.redstone.finance/docs/get-started/models/redstone-push) (push oracle) - untuk protokol yang dirancang untuk antarmuka orakel tradisional, detak jantung yang dapat dis
```suggestion
*   [RedStone Push](https://docs.redstone.finance/docs/get-started/models/redstone-push) (push oracle) - untuk protokol yang dirancang untuk antarmuka oracle tradisional, detak jantung yang dapat disesuaikan, dan ambang penyimpangan.
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +    "Lisk Mainnet",
Follow the translation from other pages:
```suggestion
    "Mainnet Lisk",  
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +    "Lisk Testnet",
```suggestion
    "Testnet Lisk",  
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +    "umpan harga",
I find no reference that price / data feed is translated as umpan harga / data at all in any article on the internet. The literal translation of umpan is "bait" / "lure". So it's better to retain the English wording for feed here.
```suggestion
    "feed harga",  
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +    "umpan data",
```suggestion
    "feed data",  
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +[RedStone](https://redstone.finance/) menawarkan Umpan Data fleksibel untuk Pasar Peminjaman, Perpetuals, Opsi, Stablecoins, Penggabungan Hasil, dan jenis protokol DeFi baru lainnya.
```suggestion
[RedStone](https://redstone.finance/) menawarkan Feed Data fleksibel untuk Pasar Peminjaman, Perpetuals, Opsi, Stablecoins, Yield Aggregator, dan jenis protokol DeFi baru lainnya.
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +*   [RedStone Pull](https://docs.redstone.finance/docs/get-started/models/redstone-pull) (pull oracle) - waktu pembaruan kurang dari 10 detik, spektrum umpan yang luas, terbaik untuk sebagian besar k
```suggestion
*   [RedStone Pull](https://docs.redstone.finance/docs/get-started/models/redstone-pull) (pull oracle) - waktu pembaruan kurang dari 10 detik, spektrum feed yang luas, terbaik untuk sebagian besar kasus penggunaan. Semua [Feed Harga](https://app.redstone.finance/#/app/tokens) tersedia untuk Lisk.
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> -*   [RedStone X](https://docs.redstone.finance/docs/get-started/models/redstone-x) - specifically for Perps and Options, highest update frequency, and front-running protection.
@TalhaMaliktz we may want to use the long form of "Perpetuals" wordingsinstead of "Perps" for the English translation. Note that I cannot use suggest change feature as this is deleted lines on this PR.

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +*   [RedStone X](https://docs.redstone.finance/docs/get-started/models/redstone-x) - khusus untuk Perps dan Opsi, frekuensi pembaruan tertinggi, dan perlindungan dari front-running.
```suggestion
*   [RedStone X](https://docs.redstone.finance/docs/get-started/models/redstone-x) - khusus untuk Perpetual dan Opsi, frekuensi pembaruan tertinggi, dan perlindungan dari front-running.
```

2024-12-19 04:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/oracles.md
> +Tertarik untuk berintegrasi? [Hubungi](https://discord.com/invite/PVxBZKFr46) tim RedStone!
```suggestion
Tertarik untuk mengintegrasi? [Hubungi](https://discord.com/invite/PVxBZKFr46) tim RedStone!
```

2024-12-19 15:12 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/faucets.md

2024-12-19 15:12 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/faucets.md
> -description: Summary of available ETH and LSK faucets on the Lisk Seolia Testnet. Get free testnet tokens on Lisk Sepolia.
@TalhaMaliktz Minor Typo. Seolia -> Sepolia

2024-12-19 15:12 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/faucets.md
> +description: Ringkasan faucet ETH dan LSK yang tersedia di Lisk Sepolia Testnet. Dapatkan token testnet gratis di Lisk Sepolia.
```suggestion
description: Ringkasan faucet ETH dan LSK yang tersedia di Testnet Lisk Sepolia. Dapatkan token testnet gratis di Lisk Sepolia.  
```

2024-12-19 15:12 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/faucets.md
>      Lisk Sepolia Testnet,
```suggestion
    Testnet Lisk Sepolia,
```

2024-12-20 05:34 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/api-providers.md

2024-12-20 05:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/api-providers.md
> +description: Dokumentasi untuk Penyedia Node untuk jaringan Lisk. Termasuk rincian tentang layanan mereka, jaringan yang didukung, dan rencana harga.
```suggestion
description: Dokumentasi untuk Penyedia Node untuk jaringan Lisk. Termasuk rincian tentang layanan mereka, jaringan yang didukung, dan paket harga.  
```

2024-12-20 05:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/api-providers.md
> +Jika Anda ingin memperkuat aplikasi Anda dan menghindari pembatasan laju untuk pengguna Anda, silakan lihat penyedia node RPC yang tersedia seperti [dRPC](#drpc).
```suggestion
Jika Anda ingin memperkuat aplikasi Anda dan menghindari rate-limit untuk pengguna Anda, silakan lihat penyedia node RPC yang tersedia seperti [dRPC](#drpc).
```

2024-12-20 07:19 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/utilities.md

2024-12-20 07:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/utilities.md
> +Gelato mengembangkan contoh kecil [aplikasi react](https://gelato-raas-aa.web.app/) dengan integrasi safe-web3auth.
```suggestion
Gelato meluncurkan sebuah contoh [aplikasi react](https://gelato-raas-aa.web.app/) sederhana dengan integrasi safe-web3auth.  
```

2024-12-20 07:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/utilities.md
> +## Automasi
```suggestion
## Otomasi
```

2024-12-20 07:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/utilities.md
> +[Web3 Functions](https://www.gelato.network/web3-functions) dari Gelato adalah sistem automasi yang kuat yang dirancang untuk menyederhanakan dan meningkatkan operasi Web3.
```suggestion
[Web3 Functions](https://www.gelato.network/web3-functions) dari Gelato adalah sistem otomasi yang kuat yang dirancang untuk menyederhanakan dan meningkatkan operasi Web3.  
```

2024-12-20 07:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/utilities.md
> -This allows for a variety of new web3 experiences, as the user can now pay by only signing a message, or their transaction costs can be sponsored by the developer.
@TalhaMaliktz I think we can improve the translation here into:
"This allows for a variety of new web3 experiences, as users can just sign a message and their transaction costs can be sponsored by the developer."

2024-12-20 07:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/utilities.md
> +Ini memungkinkan berbagai pengalaman Web3 baru, karena pengguna sekarang dapat membayar hanya dengan menandatangani pesan, atau biaya transaksi mereka dapat disponsori oleh pengembang.
```suggestion
Ini memungkinkan berbagai pengalaman Web3 baru, karena pengguna hanya perlu menandatangani pesan dan biaya transaksi mereka dapat disponsori oleh pengembang.
```

2024-12-20 07:48 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +title: Cara Membuka Staking Sebelum Waktu
```suggestion
title: Cara Membuka Staking Lebih Awal 
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +description: 'Cara membuka staking pada posisi tertentu sebelum waktu kedaluwarsa.'
```suggestion
description: 'Cara membuka staking pada posisi penguncian tertentu sebelum waktu kedaluwarsa.' 
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +    'modifikasi posisi kunci',
```suggestion
    'modifikasi posisi penguncian', 
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +    'update posisi kunci',
```suggestion
    'update posisi penguncian', 
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +Biaya penalti dihitung berdasarkan sisa durasi posisi kunci dan jumlah LSK yang akan dibuka stakingnya.
```suggestion
Biaya penalti dihitung berdasarkan sisa durasi posisi penguncian dan jumlah LSK yang akan dibuka stakingnya. 
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +2. Di daftar posisi kunci Anda, klik posisi kunci yang ingin Anda buka stakingnya lebih awal untuk memperluasnya.
```suggestion
2. Di daftar posisi penguncian Anda, klik posisi penguncian yang ingin Anda buka stakingnya lebih awal untuk memperluasnya. 
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +    Anda dapat membuka staking lebih awal untuk posisi kunci yang dijeda maupun yang tidak dijeda.
```suggestion
    Anda dapat membuka staking lebih awal untuk posisi penguncian yang dijeda maupun yang tidak dijeda. 
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +7. Sekarang, jika Anda kembali ke dashboard staking, Anda akan melihat bahwa posisi kunci tersebut akan kedaluwarsa dalam 3 hari.
```suggestion
7. Sekarang, jika Anda kembali ke dashboard staking, Anda akan melihat bahwa posisi penguncian tersebut akan kedaluwarsa dalam 3 hari. 
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +Panduan ini menjelaskan langkah demi langkah cara membuka staking pada [posisi kunci](overview#locking-positions) sebelum waktu kedaluwarsanya.
```suggestion
Panduan ini menjelaskan langkah demi langkah cara membuka staking pada [posisi penguncian](overview#locking-positions) sebelum waktu kedaluwarsanya.
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +Untuk informasi lebih lanjut, lihat [Early Unlock](overview#early-unlock).
```suggestion
Untuk informasi lebih lanjut, lihat [Buka Kunci Lebih Awal](overview#early-unlock).
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +   Hubungkan dompet Anda jika belum dilakukan.
```suggestion
   Hubungkan dompet Anda jika belum terhubung.
```

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> -    Review the amount of LSK you will receive after the penalty fee is deducted.
@TalhaMaliktz The translation can be corrected into: "Review the amount of LSK you will receive after deducting the penalty fee."

2024-12-20 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/early-unlock.mdx
> +   Tinjau jumlah LSK yang akan Anda terima setelah biaya penalti dipotong.
```suggestion
   Tinjau jumlah LSK yang akan Anda terima setelah dipotong biaya penalti. 
```

2024-12-20 09:21 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +description: 'Cara staking dan un-stake token LSK'
```suggestion
description: 'Cara staking dan membuka staking token LSK'
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
>      'unstaking',
```suggestion
    'membuka staking',
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +## Cara unstake token LSK Anda
```suggestion
## Cara membuka staking token LSK Anda
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +Jika Anda ingin unstake LSK yang telah di-stake untuk digunakan untuk tujuan lain, ikuti proses ini:
```suggestion
Jika Anda ingin membuka staking LSK yang telah di-stake untuk digunakan untuk tujuan lain, ikuti proses ini:
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +Token LSK hanya dapat di-unstake jika periode kunci dari token yang di-stake telah berakhir.
```suggestion
Token LSK hanya dapat dibuka stakingnya jika periode penguncian dari token yang di-stake telah berakhir.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +2. **Pilih jaringan tempat Anda ingin melakukan unstaking.**
```suggestion
2. **Pilih jaringan tempat Anda ingin membuka staking.** 
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +3. **Pilih posisi kunci yang telah berakhir** yang ingin Anda unstake dan ikuti proses yang dijelaskan.<br />
```suggestion
3. **Pilih posisi penguncian yang telah berakhir** yang ingin Anda buka stakingnya dan ikuti proses yang dijelaskan.<br />
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +4. Sebuah prompt akan muncul, menunggu Anda untuk mengonfirmasi proses unstaking di dompet Anda. <br />
```suggestion
4. Sebuah prompt akan muncul, menunggu Anda untuk mengonfirmasi proses pembukaan staking di dompet Anda. <br />
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +    **Setujui transaksi di dompet Anda** untuk menyelesaikan proses unstaking.
```suggestion
    **Setujui transaksi di dompet Anda** untuk menyelesaikan proses pembukaan staking.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +5. **Tetapkan periode kunci.** <br />
```suggestion
5. **Tetapkan periode penguncian.** <br />
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +    Dengan menetapkan periode kunci, Anda menentukan durasi di mana token LSK Anda akan dikunci.
```suggestion
    Dengan menetapkan periode penguncian, Anda menentukan durasi di mana token LSK Anda akan distaking.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +    Selama token tersebut dikunci, mereka tidak dapat digunakan untuk tujuan lain.
```suggestion
    Selama token tersebut distaking, mereka tidak dapat digunakan untuk tujuan lain.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +8. **Buat posisi kunci dengan mengklik tombol `Stake`.**<br />
```suggestion
8. **Buat posisi penguncian dengan mengklik tombol `Stake`.**<br />
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +Seperti yang dapat Anda lihat di [Dashboard Staking](https://portal.lisk.com/staking/dashboard), Anda menerima kekuatan suara di Lisk DAO dan reward staking, yang sebanding dengan jumlah dan durasi k
```suggestion
Seperti yang dapat Anda lihat di [Dashboard Staking](https://portal.lisk.com/staking/dashboard), Anda menerima kekuatan suara di Lisk DAO dan hadiah staking, yang sebanding dengan jumlah dan durasi penguncian yang Anda staking.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +Anda dapat melakukan staking dengan jumlah token LSK mulai dari minimal 0.01 LSK
```suggestion
Anda dapat melakukan staking dengan jumlah token LSK mulai dari minimal 0,01 LSK
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +2. **Hubungkan dompet Lisk Anda** ke Lisk Portal, jika belum dilakukan.
```suggestion
2. **Hubungkan dompet Lisk Anda** ke Lisk Portal, jika belum terhubung.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +    Anda dapat menggunakan tombol %-di bawah untuk dengan mudah melakukan staking sejumlah persentase dari saldo total LSK Anda.
```suggestion
    Anda dapat menggunakan tombol % di bawah untuk dengan mudah melakukan staking sejumlah persentase dari total saldo LSK Anda.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +## Cara mengklaim reward staking
```suggestion
## Cara mengklaim hadiah staking
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +Setelah setidaknya satu hari melakukan staking, Anda seharusnya melihat jumlah [reward staking](overview#staking-rewards) yang dapat Anda klaim hingga saat itu.
```suggestion
Setelah setidaknya satu hari melakukan staking, Anda seharusnya melihat jumlah [hadiah staking](overview#staking-rewards) yang dapat Anda klaim hingga saat itu.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +Reward staking dapat diklaim kapan saja.
```suggestion
Hadiah staking dapat diklaim kapan saja.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +Saat mengklaim, Anda dapat memilih untuk menerima reward tersebut atau men-stake ulang reward tersebut, sehingga meningkatkan jumlah yang terkunci dan meningkatkan kekuatan suara Anda dalam tata kelo
```suggestion
Saat mengklaim, Anda dapat memilih untuk menerima hadiah tersebut atau men-stake ulang hadiah tersebut, sehingga meningkatkan jumlah yang terkunci dan meningkatkan kekuatan suara Anda dalam tata kelola.
```

2024-12-20 09:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/stake-unstake.mdx
> +4. **Verifikasi reward Anda, siap untuk diklaim.**<br />
```suggestion
4. **Verifikasi hadiah Anda, siap untuk diklaim.**<br />
```

2024-12-20 10:07 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +title: Ikhtisar
```suggestion
title: Gambaran Umum
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +- [Cara menghentikan posisi kunci](pause-position.mdx)
```suggestion
- [Cara menghentikan posisi penguncian](pause-position.mdx)
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +## Posisi Kunci
```suggestion
## Posisi Penguncian
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Setiap kali Anda [stake](stake-unstake.mdx#how-to-stake-your-lsk-tokens) sejumlah LSK untuk durasi kunci tertentu, posisi **kunci** baru akan dibuat.
```suggestion
Setiap kali Anda melakukan [Staking](stake-unstake.mdx#how-to-stake-your-lsk-tokens) sejumlah LSK untuk durasi penguncian tertentu, posisi **penguncian** baru akan dibuat.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +**Durasi kunci minimum** untuk staking adalah **dua minggu**.
```suggestion
**Durasi penguncian minimum** untuk staking adalah **dua minggu**.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +**Durasi kunci maksimum** untuk staking adalah **dua tahun**.
```suggestion
**Durasi penguncian maksimum** untuk staking adalah **dua tahun**.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Posisi kunci diwakili sebagai **NFT** menggunakan standar ERC-721, mirip dengan posisi likuiditas Uniswap v3.
```suggestion
Posisi penguncian diwakili dengan **NFT** menggunakan standar ERC-721, mirip dengan posisi likuiditas Uniswap v3.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Semakin jauh akhir durasi kunci di masa depan, semakin banyak hadiah yang Anda dapatkan.
```suggestion
Semakin jauh akhir durasi penguncian di masa depan, semakin banyak hadiah yang Anda dapatkan.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +- Pengguna dapat memodifikasi posisi kunci mereka (menambah jumlah, memperpanjang durasi kunci) kapan saja.
```suggestion
- Pengguna dapat memodifikasi posisi penguncian mereka (menambah jumlah, memperpanjang durasi penguncian) kapan saja.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +- Pengguna memiliki opsi untuk **menghentikan** hitungan mundur durasi kunci mereka.
```suggestion
- Pengguna memiliki opsi untuk **menghentikan** hitungan mundur durasi penguncian mereka.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Ini berarti, durasi kunci yang tersisa tetap tetap sampai pengguna memutuskan untuk melanjutkannya.
```suggestion
Ini berarti, durasi penguncian yang tersisa tetap sama sampai pengguna memutuskan untuk melanjutkannya.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +**Perhitungan Hadiah Harian:** Hadiah diambil dari saldo kontrak Rewards dan dihitung setiap hari, berdasarkan jumlah yang dikunci dan durasi kunci yang tersisa.
```suggestion
**Perhitungan Hadiah Harian:** Hadiah diambil dari saldo kontrak hadiah dan dihitung setiap hari, berdasarkan jumlah yang dikunci dan durasi penguncian yang tersisa.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Artinya, hadiah harian untuk posisi kunci dihitung sebagai:
```suggestion
Artinya, hadiah harian untuk posisi penguncian dihitung sebagai:
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Setelah periode kunci dari sebuah [posisi kunci](#locking-positions) berakhir, Anda dapat membuka kembali token yang di-stake dengan cara [unstake](stake-unstake.mdx#how-to-unstake-your-lsk-tokens).
```suggestion
Setelah periode penguncian dari sebuah [posisi penguncian](#locking-positions) berakhir, Anda dapat membuka kembali token yang di-staking dengan cara [buka staking](stake-unstake.mdx#how-to-unstake-your-lsk-tokens).
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Jika Anda perlu membuka token Anda lebih awal dari periode kunci yang ditentukan, Anda dapat melakukan unstake token Anda sebelum periode kunci berakhir dengan menggunakan opsi [early unlock](#early-
```suggestion
Jika Anda perlu membuka token Anda lebih awal dari periode penguncian yang ditentukan, Anda dapat membuka staking token Anda sebelum periode penguncian berakhir dengan menggunakan opsi [buka kunci lebih awal](#early-unlock).
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Unlock cepat memungkinkan Anda untuk melakukan unstake token LSK sebelum periode kunci mereka berakhir.
```suggestion
Unlock cepat memungkinkan Anda untuk membuka staking token LSK sebelum periode penguncian mereka berakhir.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Misalnya, jika seorang pengguna ingin melakukan unlock cepat posisi dengan 100 LSK dan durasi kunci yang tersisa 150 hari, maka penalti dihitung sebagai berikut:
```suggestion
Misalnya, jika seorang pengguna ingin membuka kunci dengan cepat untuk posisi 100 LSK dan durasi penguncian yang tersisa 150 hari, maka penalti dihitung sebagai berikut:
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Perhatikan bahwa kami mengalikan dengan 147 dan bukan 150, karena pengguna masih harus menunggu selama 3 hari, jadi durasi kunci secara keseluruhan berkurang sebanyak 147.
```suggestion
Perhatikan bahwa kami mengalikan dengan 147 dan bukan 150, karena pengguna masih harus menunggu selama 3 hari, jadi durasi penguncian secara keseluruhan berkurang sebanyak 147.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +- [Cara menambah stake](../staking/increase-stake.mdx)
```suggestion
- [Cara menambah staking](../staking/increase-stake.mdx)
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +- [Cara unstake lebih awal](early-unlock.mdx)
```suggestion
- [Cara membuka staking lebih awal](early-unlock.mdx)
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Jika 100 LSK yang di-stake habis dalam *dua tahun*, ini akan menghasilkan hadiah berikut pada hari itu:
```suggestion
Jika 100 LSK yang di-staking habis dalam *dua tahun*, ini akan menghasilkan hadiah berikut pada hari itu:
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Setelah di-unstake, token LSK dapat digunakan seperti sebelumnya untuk tujuan lainnya.
```suggestion
Setelah dibuka stakingnya, token LSK dapat digunakan seperti sebelumnya untuk tujuan lainnya.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Penalti = 0.5 * Jumlah yang di-stake * (Hari Tersisa / 730)
```suggestion
Penalti = 0.5 * Jumlah yang di-staking * (Hari Tersisa / 730)
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Perhatikan bahwa ini menghasilkan **hadiah staking yang lebih tinggi**, karena bobot tetap tetap, dibandingkan dengan bobot yang menurun setiap hari saat hitungan mundur aktif.
```suggestion
Perhatikan bahwa ini menghasilkan **hadiah staking yang lebih tinggi**, karena bobot tetap sama, dibandingkan dengan bobot yang menurun setiap hari saat hitungan mundur aktif.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Jumlah ini diberikan ke dalam [kontrak Rewards](https://blockscout.lisk.com/address/0xD35ca9577a9DADa7624a35EC10C2F55031f0Ab1f).
```suggestion
Jumlah ini diberikan kepada [kontrak hadiah](https://blockscout.lisk.com/address/0xD35ca9577a9DADa7624a35EC10C2F55031f0Ab1f).
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +bobot = jumlahDikunci * (durasiKunciTersisaDalamHari + 150)
```suggestion
bobot = jumlahDikunci * (durasiPenguncianTersisaDalamHari + 150)
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Nilai saat ini dari `totalBobot` dapat dicek di [kontrak Rewards](https://blockscout.lisk.com/address/0xD35ca9577a9DADa7624a35EC10C2F55031f0Ab1f?tab=read_proxy).
```suggestion
Nilai saat ini dari `totalBobot` dapat dicek di [kontrak hadiah](https://blockscout.lisk.com/address/0xD35ca9577a9DADa7624a35EC10C2F55031f0Ab1f?tab=read_proxy).
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> -For example, if someone stakes 100LSK for *1 year*, this would result in the following reward for that day, assuming `totalWeight` is `12462098705` for this example:
@TalhaMaliktz "100LSK" -> "100 LSK"

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Misalnya, jika seseorang melakukan staking 100LSK selama *1 tahun*, ini akan menghasilkan hadiah berikut pada hari itu, dengan asumsi `totalBobot` adalah `12462098705` untuk contoh ini:
```suggestion
Misalnya, jika seseorang melakukan staking 100 LSK selama *1 tahun*, ini akan menghasilkan hadiah berikut pada hari itu, dengan asumsi `totalBobot` adalah `12462098705` untuk contoh ini:
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Menggunakan unlock cepat akan melibatkan penalti yang harus dibayar.
```suggestion
Membuka kunci dengan cepat akan melibatkan penalti yang harus dibayar.
```

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> -
@TalhaMaliktz "so the locking duration decreased by" -> "so the locking duration is decreased by"

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> -
@TalhaMaliktz are you sure it is "decreased by 147 overall", not "decreased by 3 overall"? 🤔

2024-12-20 10:07 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> -
@fujianggara10 may need to change the Indonesian translation, based on Talha's reply later.

2024-12-20 11:21 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan ERC 721/1155 (NFT) didukung.
```suggestion
- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan dukungan ERC 721/1155 (NFT).
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +Tersedia sebagai ekstensi browser dan aplikasi mobile, [MetaMask](https://metamask.io/) memberikan Anda vault kunci, login aman, dompet token, dan banyak lagi — semua yang Anda butuhkan untuk mengelo
```suggestion
Tersedia sebagai ekstensi browser dan aplikasi mobile, [MetaMask](https://metamask.io/) memberikan Anda brankas kunci, login yang aman, dompet token, dan masih banyak lagi — semua yang Anda butuhkan untuk mengelola aset digital Anda.
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan ERC 721 (NFT) didukung.
```suggestion
- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan dukungan ERC 721 (NFT).
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan ERC 721 (NFT) didukung.
```suggestion
- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan dukungan ERC 721 (NFT).
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan ERC 721 (NFT) didukung.
```suggestion
- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan dukungan ERC 721 (NFT).
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan ERC 721/1155 (NFT) didukung.
```suggestion
- **Dukungan Token**: ETH, ERC 20 (termasuk LSK), dan dukungan ERC 721/1155 (NFT).
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +[Xellar](https://xellar.co/) menawarkan dompet mobile dan devkit untuk dompet yang disematkan yang dapat diintegrasikan ke dalam aplikasi dan situs web.
```suggestion
[Xellar](https://xellar.co/) menawarkan dompet mobile dan devkit untuk dompet yang tertanam yang dapat diintegrasikan ke dalam aplikasi dan situs web.
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +- **Penyedia dompet tersemat**
```suggestion
- **Penyedia dompet yang tertanam**
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +[Rabby](https://rabby.io/) adalah dompet kripto open source untuk Ethereum dan rantai EVM.
```suggestion
[Rabby](https://rabby.io/) adalah dompet kripto open source untuk Ethereum dan rantai-rantai EVM lainnya.
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +[Safe](https://safe.optimism.io/welcome/accounts?chain=lisk) adalah dompet multisig yang dapat disesuaikan dan platform untuk menyimpan aset digital di Ethereum dan rantai EVM populer seperti Lisk un
```suggestion
[Safe](https://safe.optimism.io/welcome/accounts?chain=lisk) adalah dompet multisig yang dapat disesuaikan dan platform untuk menyimpan aset digital di Ethereum dan rantai-rantai EVM populer seperti Lisk untuk pengguna, perusahaan, dana, pengembang, DAO, dan investor.
```

2024-12-20 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md
> +- **Multisig**: Tanda tangan ganda untuk individu dan tim dari berbagai ukuran.
```suggestion
- **Multisig**: Tanda tangan ganda untuk individu dan tim berbagai ukuran.
```

2024-12-20 13:56 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Here is the translation of your text into Bahasa Indonesia:
```suggestion
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +
```suggestion
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +// versi kompiler harus lebih besar dari atau sama dengan 0.8.20 dan kurang dari 0.9.0
```suggestion
// versi compiler harus lebih besar dari atau sama dengan 0.8.20 dan kurang dari 0.9.0
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +    // versi kompiler harus lebih besar dari atau sama dengan 0.8.20 dan kurang dari 0.9.0
```suggestion
    // versi compiler harus lebih besar dari atau sama dengan 0.8.20 dan kurang dari 0.9.0  
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +    // versi kompiler harus lebih besar dari atau sama dengan 0.8.20 dan kurang dari 0.9.0
```suggestion
    // versi compiler harus lebih besar dari atau sama dengan 0.8.20 dan kurang dari 0.9.0
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +      /** Peristiwa */
```suggestion
      /** Event*/
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +      // Peristiwa untuk pesan Hello baru
```suggestion
      // Event untuk pesan Hello baru
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +### Peristiwa
```suggestion
### Event
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Migrasikan peristiwa blockchain dari modul dengan mengimplementasikan peristiwa yang sesuai dalam kontrak seperti yang ditunjukkan di bawah ini.
```suggestion
Migrasikan event blockchain dari modul dengan mengimplementasikan event yang sesuai dalam kontrak seperti yang ditunjukkan di bawah ini.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Selain itu, kita meningkatkan penghitung pesan Hello sebanyak `1` dan memancarkan acara `NewHello`, seperti yang dilakukan dalam metode `execute()` pada modul Lisk L1 Hello sebelumnya.
```suggestion
Selain itu, kita meningkatkan penghitung pesan Hello sebanyak `1` dan memancarkan event `NewHello`, seperti yang dilakukan dalam metode `execute()` pada modul Lisk L1 Hello sebelumnya.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +        // 7. Memancarkan acara "New Hello"
```suggestion
        // 7. Memancarkan event "New Hello"
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +        /** Acara */
```suggestion
        /** Event */
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +        // Acara untuk pesan Hello baru
```suggestion
        // Event untuk pesan Hello baru
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +| Penyimpanan data onchain | Stores (onchain)             |[Variabel status](https://solidity-by-example.org/variables/)|
```suggestion
| Penyimpanan data onchain | Stores (onchain)             |[Variabel state](https://solidity-by-example.org/variables/)|
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +      // Variabel status untuk penghitung pesan
```suggestion
      // Variabel state untuk penghitung pesan
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +      /** Variabel status */
```suggestion
      /** Variabel state */
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +      // Variabel status untuk pesan Hello
```suggestion
      // Variabel state untuk pesan Hello
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +      /** Variabel status */
```suggestion
      /** Variabel state */
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +      // Variabel status untuk pesan Hello
```suggestion
      // Variabel state untuk pesan Hello
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +      // Variabel status untuk penghitung pesan
```suggestion
      // Variabel state untuk penghitung pesan
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Untuk mengatur pemilik kontrak, kita menambahkan variabel status baru `owner`, dan sebuah konstruktor yang mengatur variabel `owner` ke alamat akun yang menyebarkan kontrak.
```suggestion
Untuk mengatur pemilik kontrak, kita menambahkan variabel state baru `owner`, dan sebuah konstruktor yang mengatur variabel `owner` ke alamat akun yang meluncurkan kontrak.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +        /** Variabel Status */
```suggestion
        /** Variabel state */
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +        // Variabel status untuk pesan Hello
```suggestion
        // Variabel state untuk pesan Hello
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +        // Variabel status untuk penghitung pesan
```suggestion
        // Variabel state untuk penghitung pesan
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +  Untuk getter sederhana, cukup tambahkan modifier visibilitas `public` pada variabel status (lihat [storage](#storage)).
```suggestion
  Untuk getter sederhana, cukup tambahkan modifier visibilitas `public` pada variabel state (lihat [storage](#storage)).
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +  Variabel status publik dapat diakses langsung oleh pihak eksternal, tanpa perlu mengimplementasikan view function yang sesuai.
```suggestion
  Variabel state publik dapat diakses langsung oleh pihak eksternal, tanpa perlu mengimplementasikan fungsi view yang sesuai.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Migrasikan penyimpanan onchain dari sebuah modul dengan mengimplementasikan variabel status yang sesuai dalam kontrak seperti yang ditunjukkan di bawah ini.
```suggestion
Migrasikan penyimpanan onchain dari sebuah modul dengan mengimplementasikan variabel state yang sesuai dalam kontrak seperti yang ditunjukkan di bawah ini.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Konfigurasi spesifik modul, yang sebelumnya berada di `config.json` pada Lisk L1, sekarang menjadi bagian dari kontrak pintar itu sendiri dan didefinisikan sebagai variabel status.
```suggestion
Konfigurasi spesifik modul, yang sebelumnya berada di `config.json` pada Lisk L1, sekarang menjadi bagian dari kontrak pintar itu sendiri dan didefinisikan sebagai variabel state.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +  Untuk getter sederhana, cukup tambahkan [visibility modifier](https://solidity-by-example.org/visibility/) `public` pada variabel status (lihat [storage](#storage)).
```suggestion
  Untuk getter sederhana, cukup tambahkan [visibility modifier](https://solidity-by-example.org/visibility/) `public` pada variabel state (lihat [storage](#storage)).
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +  Variabel status publik dapat diakses langsung dari pihak eksternal, tanpa mengimplementasikan fungsi view yang sesuai.
```suggestion
  Variabel state publik dapat diakses langsung dari pihak eksternal, tanpa mengimplementasikan fungsi view yang sesuai.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Selain itu, kita meningkatkan penghitung pesan Hello sebanyak `1` dan memancarkan acara `NewHello`, seperti yang dilakukan dalam metode `execute()` pada modul Lisk L1 Hello sebelumnya.
```suggestion
Selain itu, kita meningkatkan penghitung pesan Hello sebanyak `1` dan memancarkan event `NewHello`, seperti yang dilakukan dalam metode `execute()` pada modul Lisk L1 Hello sebelumnya.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +### Endpoints
```suggestion
### Endpoint
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Migrasikan endpoint modul dengan mengimplementasikan [view functions](https://solidity-by-example.org/view-and-pure-functions/) yang sesuai dalam kontrak seperti yang ditunjukkan di bawah ini.
```suggestion
Migrasikan endpoint modul dengan mengimplementasikan [fungsi view](https://solidity-by-example.org/view-and-pure-functions/) yang sesuai dalam kontrak seperti yang ditunjukkan di bawah ini.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Sekarang kita telah mengimplementasikan kembali modul Hello dari Lisk L1 sebagai kontrak pintar di Lisk L2, maka kita bisa langsung meng-deploy kontrak Hello ke Lisk L2 dan berinteraksi dengannya.
```suggestion
Sekarang kita telah mengimplementasikan kembali modul Hello dari Lisk L1 sebagai kontrak pintar di Lisk L2, maka kita bisa langsung meluncurkan kontrak Hello ke Lisk L2 dan berinteraksi dengannya.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Sebelum meng-deploy kontrak pintar ke Lisk, disarankan untuk [menguji secara lokal](#testing-the-smart-contract) dengan menulis uji yang sesuai untuk kontrak pintar yang baru dibuat.
```suggestion
Sebelum meluncurkan kontrak pintar ke Lisk, disarankan untuk [menguji secara lokal](#testing-the-smart-contract) dengan menulis uji yang sesuai untuk kontrak pintar yang baru dibuat.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Setelah kontrak pintar [di-deploy](#smart-contract-deployment) ke Lisk, Anda dapat berinteraksi dengannya dengan memanggil fungsi publiknya.
```suggestion
Setelah kontrak pintar [diluncurkan](#smart-contract-deployment) ke Lisk, Anda dapat berinteraksi dengannya dengan memanggil fungsi publiknya.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Dengan menguji kontrak pintar, Anda dapat memverifikasi bahwa kontrak pintar berfungsi seperti yang diharapkan dan bebas dari bug, sebelum meng-deploy-nya ke Lisk.
```suggestion
Dengan menguji kontrak pintar, Anda dapat memverifikasi bahwa kontrak pintar berfungsi seperti yang diharapkan dan bebas dari bug, sebelum meluncurkannya ke Lisk.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +### Penyebaran Kontrak Pintar
```suggestion
### Peluncuran Kontrak Pintar
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Sekarang Anda dapat menyebarkan kontrak pintar ke Lisk.
```suggestion
Sekarang Anda dapat meluncurkan kontrak pintar ke Lisk.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Untuk contoh ini, kami akan menggunakan jaringan Lisk Sepolia untuk menyebarkan kontrak Hello.
```suggestion
Untuk contoh ini, kami akan menggunakan jaringan Lisk Sepolia untuk meluncurkan kontrak Hello.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Jika penyebaran berhasil, keluaran seharusnya terlihat seperti ini:
```suggestion
Jika peluncuran berhasil, keluaran seharusnya terlihat seperti ini:
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Diterapkan ke: 0x0a5A1C81F278cAe80d340a4A97E2D7B1c3Ec511a
```suggestion
Deployed to: 0x0a5A1C81F278cAe80d340a4A97E2D7B1c3Ec511a
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Penyebar: 0x3C46A11471f285E36EE8d089473ce98269D1b081
```suggestion
Deployer: 0x3C46A11471f285E36EE8d089473ce98269D1b081
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Setelah kontrak pintar diterapkan, Anda dapat berinteraksi dengannya dengan memanggil fungsi publiknya.
```suggestion
Setelah kontrak pintar diluncurkan, Anda dapat berinteraksi dengannya dengan memanggil fungsi publiknya.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Menunggu blockscout untuk mendeteksi penerapan kontrak...
```suggestion
Waiting for blockscout to detect contract deployment...
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Mulai memverifikasi kontrak `0x0a5A1C81F278cAe80d340a4A97E2D7B1c3Ec511a` yang diterapkan di 4202
```suggestion
Start verifying contract `0x0a5A1C81F278cAe80d340a4A97E2D7B1c3Ec511a` deployed on 4202
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> -        string[] memory bl = new string[](3);
@fujianggara10 I think you accidentally deleted some parts in this line

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +        string ;
```suggestion
        string[] memory bl = new string[](3) ;
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +   bl[2] = "word4";
```suggestion
        bl[2] = "word4";
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +[⠢] Memasak...
```suggestion
[⠢] Compiling...
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +[⠢] Memasak...
@fujianggara10 As this is an output from the command line, this shouldn't be translated.

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Tidak ada file yang diubah, kompilasi dilewati
```suggestion
No files changed, compilation skipped
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Hash transaksi: 0x52bb6aab8ceeecef674253ecc0ccfe35baeac7db3cc8e889a9da1f7cf1ce0593
```suggestion
Transaction hash: 0x52bb6aab8ceeecef674253ecc0ccfe35baeac7db3cc8e889a9da1f7cf1ce0593
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Memulai verifikasi kontrak...
```suggestion
Starting contract verification...
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Mengirim verifikasi untuk [src/Hello.sol:Hello] 0x0a5A1C81F278cAe80d340a4A97E2D7B1c3Ec511a.
```suggestion
Submitting verification for [src/Hello.sol:Hello] 0x0a5A1C81F278cAe80d340a4A97E2D7B1c3Ec511a.
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Kontrak yang diajukan untuk verifikasi:
```suggestion
Submitted contract for verification:
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +    Respon: `OK`
```suggestion
    Response: `OK`
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Status verifikasi kontrak:
```suggestion
Contract verification status:
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +    Respon: `OK`
```suggestion
    Response: `OK`
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +    Detail: `Menunggu dalam antrean`
```suggestion
    Details: `Pending in queue`
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Status verifikasi kontrak:
```suggestion
Contract verification status:
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +    Respon: `OK`
```suggestion
    Response: `OK`
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +    Detail: `Lulus - Terverifikasi`
```suggestion
    Details: `Pass - Verified`
```

2024-12-20 13:56 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/migration-guide.mdx
> +Kontrak berhasil diverifikasi
```suggestion
Contract successfully verified
```

2025-01-01 09:20 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +Biaya Data L1 dipengaruhi secara signifikan oleh base fee Ethereum yang diteruskan terus-menerus dan tanpa kepercayaan dari Ethereum ke Lisk Mainnet.
@fujianggara10 Missed this part " (trustless)"

2025-01-02 03:34 UTC, jasonyapri requested changes
Unapplied / new changes

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +Biaya Data L1 dipengaruhi secara signifikan oleh base fee Ethereum yang diteruskan secara terus-menerus dan tanpa kepercayaan dari Ethereum ke Lisk Mainnet.
```suggestion
Biaya Data L1 dipengaruhi secara signifikan oleh base fee Ethereum yang diteruskan secara terus-menerus dan trustless dari Ethereum ke Lisk Mainnet.
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/bridges.mdx
> +description: Dokumentasi untuk menjembatani aset ke Lisk. Halaman ini membahas cara menjembatani ETH dan ERC-20 antara Ethereum Sepolia dan Lisk Sepolia, dengan kewaspadaan dan informasi kontrak yang
```suggestion
description: Dokumentasi untuk menjembatani aset ke Lisk. Halaman ini membahas cara menjembatani ETH dan token ERC-20 antara Ethereum Sepolia dan Lisk Sepolia, dengan kewaspadaan dan informasi kontrak yang penting.  
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Secara singkat, pengguna mendapatkan [kekuatan voting](docs-user/governance/overview.mdx#voting-power) dan hadiah untuk staking token selama periode waktu tertentu.
```suggestion
Secara singkat, pengguna mendapatkan [kekuatan suara](docs-user/governance/overview.mdx#voting-power) dan hadiah untuk staking token selama periode waktu tertentu.
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/increase-stake.mdx
> +Jika Anda memuat ulang halaman, Anda seharusnya melihat jumlah staking yang meningkat pada posisi kunci di dashboard staking.
```suggestion
Jika Anda memuat ulang halaman, Anda seharusnya melihat jumlah staking yang meningkat pada posisi penguncian di dashboard staking.
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/indexers.md
> +kata kunci: [
```suggestion
keywords: [  
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +title: Ikhtisar
```suggestion
title: Gambaran Umum
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/intro-user.mdx
> +- Hubungkan dengan dompet pilihan Anda dengan mengikuti panduan [Menghubungkan ke Dompet](/user/connecting-to-a-wallet).
```suggestion
- Hubungkan dompet pilihan Anda dengan mengikuti panduan [Menghubungkan ke Dompet](/user/connecting-to-a-wallet).
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/pause-position.mdx
> +2. Di daftar posisi penguncian Anda, klik posisi penguncian yang ingin Anda tangguhkan untuk memperluasnya.
```suggestion
2. Di daftar posisi penguncian Anda, klik posisi penguncian yang ingin Anda jedakan untuk memperluasnya.
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-tools/utilities.md
> +[Web3 Functions](https://www.gelato.network/web3-functions) dari Gelato adalah sistem automasi yang kuat yang dirancang untuk menyederhanakan dan meningkatkan operasi Web3.
```suggestion
[Web3 Functions](https://www.gelato.network/web3-functions) dari Gelato adalah sistem otomasi yang kuat yang dirancang untuk menyederhanakan dan meningkatkan operasi Web3.  
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +- [Cara staking, klaim, dan unstake](stake-unstake.mdx)
```suggestion
- [Cara staking, klaim, dan buka staking](stake-unstake.mdx)
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +- [Cara unstake lebih awal](early-unlock.mdx)
```suggestion
- [Cara membuka staking lebih awal](early-unlock.mdx)
```

2025-01-02 03:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Perhatikan bahwa ini menghasilkan **hadiah staking yang lebih tinggi**, karena bobot tetap tetap, dibandingkan dengan bobot yang menurun setiap hari saat hitungan mundur aktif.
```suggestion
Perhatikan bahwa ini menghasilkan **hadiah staking yang lebih tinggi**, karena bobot tetap sama, dibandingkan dengan bobot yang menurun setiap hari saat hitungan mundur aktif.
```

2025-01-02 04:02 UTC, jasonyapri requested changes
Unapplied and new changes

2025-01-02 04:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/staking/staking.md
> +Ini berarti, durasi penguncian yang tersisa tetap tetap sampai pengguna memutuskan untuk melanjutkannya.
```suggestion
Ini berarti, durasi penguncian yang tersisa tetap sama sampai pengguna memutuskan untuk melanjutkannya.
```

2025-01-02 04:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/lisk-l1/legacy-chain-service.md
>      chain history,
```suggestion
    riwayat rantai,
```
This comment has been resolved but not yet applied... @fujianggara10

2025-01-06 16:52 UTC, jasonyapri approved these changes
All good to go

2025-01-07 13:01 UTC, TalhaMaliktz requested changes

2025-01-07 13:01 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> -slug: /fees
Please don't translate the `slug` property. It breaks navigation!

2025-01-07 13:01 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +- Testnet Lisk Sepolia: https://sepolia-blockscout.lisk.com/gas-tracker
Why change the positions?

2025-01-07 13:01 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/_category_.json
>  {
Please see the following list and correct all the broken URLs. The URLs should match the translated headings, otherwise they will throw an error.
```
Exhaustive list of all broken anchors found:
- Broken anchor on source page path = /ind/biaya:
   -> linking to #eip-1559-parameters (resolved as: /ind/biaya#eip-1559-parameters)
- Broken anchor on source page path = /ind/building-on-lisk/migration-guide:
   -> linking to /ind/building-on-lisk/migration-guide#state-transition-logic
   -> linking to #storage (resolved as: /ind/building-on-lisk/migration-guide#storage)
   -> linking to #testing-the-smart-contract (resolved as: /ind/building-on-lisk/migration-guide#testing-the-smart-contract)
   -> linking to #smart-contract-deployment (resolved as: /ind/building-on-lisk/migration-guide#smart-contract-deployment)
- Broken anchor on source page path = /ind/governance/delegation:
   -> linking to overview#proposals (resolved as: /ind/governance/overview#proposals)
   -> linking to overview#voting-power (resolved as: /ind/governance/overview#voting-power)
- Broken anchor on source page path = /ind/governance/overview:
   -> linking to ../user/staking/overview#staking-rewards (resolved as: /ind/user/staking/overview#staking-rewards)
   -> linking to #proposals (resolved as: /ind/governance/overview#proposals)
   -> linking to #proposal-types (resolved as: /ind/governance/overview#proposal-types)
   -> linking to #delegation (resolved as: /ind/governance/overview#delegation)
   -> linking to proposal-lifecycle#2-proposal-creation (resolved as: /ind/governance/proposal-lifecycle#2-proposal-creation)
   -> linking to #tools (resolved as: /ind/governance/overview#tools)
   -> linking to #treasury (resolved as: /ind/governance/overview#treasury)
- Broken anchor on source page path = /ind/user/staking/early-unstake:
   -> linking to overview#locking-positions (resolved as: /ind/user/staking/overview#locking-positions)
   -> linking to stake-unstake#how-to-unstake-your-lsk-tokens (resolved as: /ind/user/staking/stake-unstake#how-to-unstake-your-lsk-tokens)
   -> linking to overview#early-unlock (resolved as: /ind/user/staking/overview#early-unlock)
- Broken anchor on source page path = /ind/user/staking/extend-duration:
   -> linking to overview#locking-positions (resolved as: /ind/user/staking/overview#locking-positions)
   -> linking to /ind/governance/overview#boosting-the-voting-power
- Broken anchor on source page path = /ind/user/staking/increase-stake:
   -> linking to overview#locking-positions (resolved as: /ind/user/staking/overview#locking-positions)
- Broken anchor on source page path = /ind/user/staking/overview:
   -> linking to #staking-rewards (resolved as: /ind/user/staking/overview#staking-rewards)
   -> linking to /ind/user/staking/stake-unstake#how-to-stake-your-lsk-tokens
   -> linking to /ind/governance/overview#voting-power
   -> linking to /ind/user/staking/stake-unstake#how-to-claim-staking-rewards
   -> linking to #locking-positions (resolved as: /ind/user/staking/overview#locking-positions)
   -> linking to /ind/user/staking/stake-unstake#how-to-unstake-your-lsk-tokens
   -> linking to #early-unlock (resolved as: /ind/user/staking/overview#early-unlock)
- Broken anchor on source page path = /ind/user/staking/pause-position:
   -> linking to overview#locking-positions (resolved as: /ind/user/staking/overview#locking-positions)
   -> linking to /ind/governance/overview#voting-power
   -> linking to overview#staking-rewards (resolved as: /ind/user/staking/overview#staking-rewards)
   -> linking to /ind/governance/overview#boosting-the-voting-power
   -> linking to /ind/governance/overview#delegation
- Broken anchor on source page path = /ind/user/staking/stake-unstake:
   -> linking to overview#staking-rewards (resolved as: /ind/user/staking/overview#staking-rewards)
```

2025-01-07 13:01 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/exchanges.md
>  | **Binance**              | 🟡 Ethereum        | [LSK/USDT](https://www.binance.com/en/trade/LSK_USDT?type=spot)<br />[LSK/BTC](https://www.binance.com/en/trade/LSK_BTC?type=spot)<br />[LSK/ETH](http
```suggestion
| **Binance**              | 🟡 Ethereum        | [LSK/USDT](https://www.binance.com/en/trade/LSK_USDT?type=spot)<br />[LSK/BTC](https://www.binance.com/en/trade/LSK_BTC?type=spot) |
```

2025-01-07 13:01 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/exchanges.md
>  ---
The English version of this page has been recently updated. Please match the content with it.

2025-01-07 13:01 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/overview.mdx
> +:::catatan
There is no need to translate this; Docusaurus will automatically translate this!
```suggestion
:::note
```

2025-01-07 13:01 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/proposal-lifecycle.mdx
> +- **Ambang Proposal**: Kekuatan suara yang didelegasikan harus setidaknya 300.000 vpLSK.
While mentioning numbers, do you use a `.` instead of `,` in Indonesian?

2025-01-07 13:30 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +- Testnet Lisk Sepolia: https://sepolia-blockscout.lisk.com/gas-tracker
@TalhaMaliktz to make it more natural and abide to the structure of Indonesian language.

2025-01-14 11:21 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/governance/proposal-lifecycle.mdx
> +- **Ambang Proposal**: Kekuatan suara yang didelegasikan harus setidaknya 300.000 vpLSK.
we use `.` for thousand separator and `,` for decimals in Indonesian language

2025-01-14 15:31 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> -slug: /fees
I've reverted 2 accidental slug translations to Indonesian language (in i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md and i18n/ind/docusaurus-plugin-content-docs/current/docs-user/wallets.md). The rest of the slugs are not changed.

Commit: https://github.com/LiskHQ/lisk-docs/pull/262/commits/d32ecb3207da017aa47141733fa8a911ef891f47

2025-01-14 16:26 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/docs-user/exchanges.md
>  ---
Adjusted `i18n/ind/docusaurus-plugin-content-docs/current/docs-user/exchanges.md` Indonesian translation page based on the most recent updated English version (docs/docs-user/exchanges.md).

2025-01-15 05:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/_category_.json
>  {
@TalhaMaliktz I've fixed all broken internal URLs. Double checked all the results found using regex `\((.*?)#(.*?)` (meaning: all the links with hashtag on it. Ex: `(fees#eip-1559-parameters)` )

Commit: https://github.com/LiskHQ/lisk-docs/pull/262/commits/5f3ea5c3422a5fcd77516e0af442ecaae024c951

2025-01-15 08:05 UTC, jasonyapri commented
Fyi, I've fixed several translations on Indonesian Lisk Docs home page

Commit: https://github.com/LiskHQ/lisk-docs/pull/262/commits/1edfb43f07ecf52f10664127db4844752d9a4a16

2025-01-28 11:49 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +| Block gas limit                        |   30.000.000 gas   |                 30.000.000 gas     |
```suggestion
| Block gas limit                        |   60.000.000 gas   |                 30.000.000 gas     |
```

2025-01-28 11:49 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/about-lisk/fees.md
> +| Block gas target                       |    1.500.000 gas   |                 15.000.000 gas     |
```suggestion
| Block gas target                       |    3.000.000 gas   |                 15.000.000 gas     |
```

2025-01-28 11:57 UTC, TalhaMaliktz approved these changes
Great work, guys! 👏🏼  Special Kudos to @jasonyapri for taking an in-depth and ensuring quality.

2025-01-29 14:27 UTC, merged