Translation of "Building on Lisk" into Indonesian
LiskHQ/lisk-docs pull request #264
Opened 2024-12-19 07:34 UTC by aldhosutra

### What was the problem?

This PR translates the "Building on Lisk" section of the Lisk documentation into Indonesian. Some technical terms, such as "smart contract", "feed", "wallet", "bridge", "explorer", etc., are not translated into literal Indonesian, but are instead italicized, to be more developer-friendly

### How was it tested?

1. running `npm run build`
2. running `npm run serve`
3. accessing `http://localhost:3000/ind`

2024-12-23 09:11 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/_category_.json

i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/bridged-tokens.md

2024-12-23 09:11 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/_category_.json
> +    "description": "Panduan untuk developer yang ingin membangun di Lisk L2."
```suggestion
    "description": "Panduan untuk pengembang yang ingin membangun di Lisk L2."
```

2024-12-23 09:11 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/bridged-tokens.md
> +keywords: ["Lisk", "Bridged tokens"]
```suggestion
keywords: ["Lisk", "token yang dipindahkan melalui bridge (bridged token)"]
```

2024-12-23 09:11 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/bridged-tokens.md
> +Halaman ini merangkum token-token yang telah ditinjau secara resmi dan dideploy di Lisk, beserta alamat L1 yang sesuai.
```suggestion
Halaman ini merangkum token-token yang telah ditinjau secara resmi dan diluncurkan di Lisk, beserta alamat L1 yang sesuai.
```

2024-12-23 09:11 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/bridged-tokens.md
> +| _Bridged Tokens_ di Mainnet | Simbol | Token L1 | Token L2 |
```suggestion
| _Bridged Token_ di Mainnet | Simbol | Token L1 | Token L2 |
```

2024-12-23 09:11 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/bridged-tokens.md
> +| _Bridged Tokens_ di Sepolia | Simbol | Token L1 | Token L2 |
```suggestion
| _Bridged Token_ di Sepolia | Simbol | Token L1 | Token L2 |
```

2024-12-23 10:29 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +description: Dokumentasi untuk menggunakan Viem, sebuah interface TypeScript untuk blockchain yang kompatibel dengan EVM. Halaman ini mencakup instalasi, pengaturan, serta berbagai fungsi seperti mem
```suggestion
description: Dokumentasi untuk menggunakan Viem, sebuah interface TypeScript untuk blockchain yang kompatibel dengan EVM. Halaman ini mencakup instalasi, pengaturan, serta berbagai fungsi seperti membaca dan menulis data blockchain, dan berinteraksi dengan kontrak pintar di Lisk.
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Anda dapat menggunakan viem untuk berinteraksi dengan _smart contract_ yang dideploy di Lisk.
```suggestion
Anda dapat menggunakan viem untuk berinteraksi dengan kontrak pintar yang diluncurkan di Lisk.  
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +## Berinteraksi dengan Smart Contract
```suggestion
## Berinteraksi dengan Kontrak Pintar
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Anda dapat menggunakan viem untuk berinteraksi dengan _smart contract_ di Lisk dengan membuat instance `Contract` menggunakan [`getContract`](https://viem.sh/docs/contract/getContract.html) dan membe
```suggestion
Anda dapat menggunakan viem untuk berinteraksi dengan kontrak pintar di Lisk dengan membuat instance `Contract` menggunakan [`getContract`](https://viem.sh/docs/contract/getContract.html) dan memberikan ABI kontrak, alamat kontrak, serta [Public](https://viem.sh/docs/clients/public.html) dan/atau [Wallet](https://viem.sh/docs/clients/wallet.html) Client:  
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +`CONTRACT_ADDRESS` adalah alamat dari kontrak yang telah dideploy.
```suggestion
`CONTRACT_ADDRESS` adalah alamat dari kontrak yang telah diluncurkan.
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Viem menyediakan dukungan penuh untuk _chain_ yang diimplementasikan pada OP stack, lihat [viem.sh > OP stack](https://viem.sh/op-stack).
```suggestion
Viem menyediakan dukungan penuh untuk rantai yang diimplementasikan pada OP stack, lihat [viem.sh > OP stack](https://viem.sh/op-stack).
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Sebelum mulai menggunakan viem, Anda perlu mengatur [Client](https://viem.sh/op-stack/client) dengan [Transport](https://viem.sh/docs/clients/intro.html#transports) dan [Chain](https://viem.sh/docs/c
```suggestion
Sebelum mulai menggunakan viem, Anda perlu mengatur [Client](https://viem.sh/op-stack/client) dengan [Transport](https://viem.sh/docs/clients/intro.html#transports) dan [Rantai](https://viem.sh/docs/chains/introduction) yang diinginkan.
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Dengan meng-_extend_ public client menggunakan `publicActionsL2` atau `publicActionsL1`, Anda akan mendapatkan akses ke metode tambahan untuk Lisk dan _chain_ lain yang dibangun di atas OP stack.
```suggestion
Dengan meng-_extend_ public client menggunakan `publicActionsL2` atau `publicActionsL1`, Anda akan mendapatkan akses ke metode tambahan untuk Lisk dan rantai lain yang dibangun di atas OP stack.
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Dengan meng-_extend_ wallet client menggunakan `walletActionsL1` atau `walletActionsL2`, Anda akan mendapatkan akses ke metode tambahan untuk Lisk dan _chain_ lain yang dibangun di atas OP stack.
```suggestion
Dengan meng-_extend_ wallet client menggunakan `walletActionsL1` atau `walletActionsL2`, Anda akan mendapatkan akses ke metode tambahan untuk Lisk dan rantai lain yang dibangun di atas OP stack.  
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Lihat [Layer 2 extensions](https://viem.sh/op-stack/client#layer-2-extensions) untuk informasi lebih lanjut.
```suggestion
Lihat [Ekstensi Layer 2](https://viem.sh/op-stack/client#layer-2-extensions) untuk informasi lebih lanjut.  
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Selain membuat permintaan JSON-RPC (`eth_requestAccounts`) untuk mendapatkan sebuah Akun, viem menyediakan berbagai metode bantu untuk membuat sebuah `Account`, termasuk: [`privateKeyToAccount`](http
```suggestion
Selain membuat permintaan JSON-RPC (`eth_requestAccounts`) untuk mendapatkan sebuah Akun, viem menyediakan berbagai metode pembantu untuk membuat sebuah `Account`, termasuk: [`privateKeyToAccount`](https://viem.sh/docs/accounts/privateKey.html), [`mnemonicToAccount`](https://viem.sh/docs/accounts/mnemonic.html), dan [`hdKeyToAccount`](https://viem.sh/docs/accounts/hd.html).  
```

2024-12-23 10:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +// 2. Panggil metode kontrak, ambil *events*, dengarkan *events*, dan lain-lain.
```suggestion
// 2. Panggil metode kontrak, ambil *event*, dengarkan *event*, dan lain-lain.
```

2024-12-23 10:42 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +title: "Mendeploy Token ERC-721 Baru di Lisk"
```suggestion
title: "Meluncurkan Token ERC-721 Baru di Lisk"
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +description: "Panduan Cara Mendeploy Token ERC-721 Baru di Lisk."
```suggestion
description: "Panduan Cara Meluncurkan Token ERC-721 Baru di Lisk."
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +  ["Lisk", "Token development", "Deploy token", "ERC", "EIP", "ERC-721", "NFT"]
```suggestion
  ["Lisk", "Token development", "Meluncurkan token", "ERC", "EIP", "ERC-721", "NFT"]
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +# Cara Mendeploy Token ERC-721 Baru di Lisk
```suggestion
# Cara Meluncurkan Token ERC-721 Baru di Lisk
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +## 5. Deploy Kontrak
```suggestion
## 5. Meluncurkan Kontrak
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +Kemudian, pilih kontrak `MyNFT` dari dropdown deployment dan klik tombol oranye `Deploy` untuk mendepoy kontrak, lalu konfirmasikan proses deployment kontrak di _wallet_ Anda yang terhubung.
```suggestion
Kemudian, pilih kontrak `MyNFT` dari dropdown deployment dan klik tombol `Deploy` berwarna oranye untuk meluncurkan kontrak, lalu konfirmasikan proses peluncuran kontrak di dompet Anda yang terhubung.
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +- Sekarang, buka [kontrak yang baru saja Anda deploy](https://sepolia-blockscout.lisk.com/address/0x73e7a94dD5760d862F6FD9f8ea5D4245Bb143446) di https://sepolia-blockscout.lisk.com.
```suggestion
- Sekarang, buka [kontrak yang baru saja Anda luncurkan](https://sepolia-blockscout.lisk.com/address/0x73e7a94dD5760d862F6FD9f8ea5D4245Bb143446) di https://sepolia-blockscout.lisk.com.
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +Panduan ini menggunakan Remix IDE untuk pengembangan _smart contract_, tetapi Anda bebas memilih [framework pengembangan smart contract](/category/building-on-lisk/deploying-smart-contract) lain sesu
```suggestion
Panduan ini menggunakan Remix IDE untuk pengembangan kontrak pintar, tetapi Anda bebas memilih [framework pengembangan kontrak pintar](/category/building-on-lisk/deploying-smart-contract) lain sesuai preferensi Anda untuk mengimplementasikan kontrak token Anda.
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +Pastikan bahwa versi compiler di Remix IDE sesuai dengan versi compiler yang disebutkan di _smart contract_: `pragma solidity ^0.8.28;`.
```suggestion
Pastikan bahwa versi compiler di Remix IDE sesuai dengan versi compiler yang disebutkan di kontrak pintar: `pragma solidity ^0.8.28;`.
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +Tekan tombol hijau play di bagian atas untuk mengompilasi kontrak.
```suggestion
Tekan tombol _play_ berwarna hijau di bagian atas untuk mengompilasi kontrak.
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +Buka tab `Deploy & run transactions` (ikon ini terlihat seperti logo Ethereum dengan panah mengarah ke kanan). Pastikan bahwa _environment_ Anda diatur ke "Injected Provider", _wallet_ Anda terhubung
```suggestion
Buka tab `Deploy & run transactions` (ikon ini terlihat seperti logo Ethereum dengan panah mengarah ke kanan). Pastikan bahwa _environment_ Anda diatur ke "Injected Provider", dompet Anda terhubung ke jaringan Lisk atau Lisk Sepolia, dan Remix memiliki akses ke dompet Anda.
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +_Paste_ alamat ini di BlockScout untuk melihat kontrak di _explorer_ blockchain Lisk:
```suggestion
Tempel alamat ini di BlockScout untuk melihat kontrak di _explorer_ blockchain Lisk:  
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +Jika Anda memilih untuk mendepoy di Lisk Mainnet, _paste_-kan alamat tersebut di https://blockscout.lisk.com
```suggestion
Jika Anda memilih untuk meluncurkan di Lisk Mainnet, tempelkan alamat tersebut di https://blockscout.lisk.com
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +Anda dapat menerapkan langkah yang sama untuk memverifikasi kontrak di Lisk Mainnet, jika jaringan itu yang Anda gunakan pada proses diatas, cukup gunakan https://blockscout.lisk.com untuk menggantik
```suggestion
Anda dapat menerapkan langkah yang sama untuk memverifikasi kontrak di Lisk Mainnet, jika kamu meluncurkannya di jaringan itu di langkah sebelumnya, cukup gunakan https://blockscout.lisk.com dari pada https://sepolia-blockscout.lisk.com pada langkah 2 dibawah ini.
```

2024-12-23 10:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-721.md
> +- Buka tab kontrak dan klik tombol biru `Verify and Publish`.
```suggestion
- Buka tab kontrak dan klik tombol `Verify and Publish` berwarna biru.
```

2024-12-24 04:59 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-pull.md

2024-12-24 04:59 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-pull.md
> +RedStone adalah ekosistem data yang menyediakan data yang sering diperbarui, dapat diandalkan, dan beragam untuk dApp dan _smart contract_ Anda yang dideploy di Lisk.
```suggestion
RedStone adalah ekosistem data yang menyediakan data yang sering diperbarui, dapat diandalkan, dan beragam untuk dApp dan kontrak pintar Anda yang diluncurkan di Lisk.
```

2024-12-24 04:59 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-pull.md
> +Untuk membuat _smart contract_ yang secara langsung mengambil data terbaru dari RedStone oracle, ikuti panduan ini.
```suggestion
Untuk membuat kontrak pintar yang secara langsung mengambil data terbaru dari RedStone oracle, ikuti panduan ini.
```

2024-12-24 04:59 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-pull.md
> +Panduan ini menggunakan [Hardhat](https://hardhat.org/) untuk membuat _smart contract_.
```suggestion
Panduan ini menggunakan [Hardhat](https://hardhat.org/) untuk membuat kontrak pintar.
```

2024-12-24 04:59 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-pull.md
> +Untuk mendeploy _smart contract_ di Lisk Sepolia atau Lisk Mainnet, ikuti panduan berikut:
```suggestion
Untuk meluncurkan kontrak pintar di Lisk Sepolia atau Lisk Mainnet, ikuti panduan berikut:
```

2024-12-24 04:59 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-pull.md
> +- [Mendeploy smart contract dengan Hardhat](../deploying-smart-contract/with-Hardhat), atau
```suggestion
- [Meluncurkan kontrak pintar dengan Hardhat](../deploying-smart-contract/with-Hardhat), atau
```

2024-12-24 04:59 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-pull.md
> +- [Mendeploy smart contract dengan Foundry](../deploying-smart-contract/with-Foundry)
```suggestion
- [Meluncurkan kontrak pintar dengan Foundry](../deploying-smart-contract/with-Foundry)
```

2024-12-24 04:59 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-pull.md
> +## Mendeploy di Lisk
```suggestion
## Meluncurkan kontrak pintar di Lisk
```

2024-12-24 06:03 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md

2024-12-24 06:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
> +description: Tutorial yang mengajarkan cara mengatur dan menjalankan Node Lisk.
```suggestion
description: Tutorial yang mengajarkan cara memasang dan menjalankan Node Lisk.
```

2024-12-24 06:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
>      node deployment,
```suggestion
    peluncuran node,
```

2024-12-24 06:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
>      Lisk Node setup,
```suggestion
    pemasangan node Lisk,
```

2024-12-24 06:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
> +tags: ["nodes"]
```suggestion
tags: ["node"]
```

2024-12-24 06:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
> +- Mendeploy dan menyinkronkan node Lisk
```suggestion
- Meluncurkan dan menyinkronkan node Lisk
```

2024-12-24 06:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
> +**Catatan:** RPC kami memiliki batasan tingkat (rate-limited), sehingga tidak cocok untuk aplikasi produksi.
```suggestion
**Catatan:** RPC kami memiliki _rate limit_, sehingga tidak cocok untuk aplikasi produksi.
```

2024-12-24 06:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
> +Jika Anda ingin memperkuat aplikasi Anda dan menghindari pembatasan tingkat untuk pengguna Anda, silakan cek salah satu [mitra kami].
```suggestion
Jika Anda ingin memperkuat aplikasi Anda dan menghindari _rate limit_ untuk pengguna Anda, silakan cek salah satu [mitra kami].
```

2024-12-24 07:02 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +title: "Mendeploy Token ERC-20 Baru di Lisk"
```suggestion
title: "Meluncurkan Token ERC-20 Baru di Lisk"
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +description: "Panduan untuk Mendeploy Token ERC-20 Baru di Lisk"
```suggestion
description: "Panduan untuk Meluncurkan Token ERC-20 Baru di Lisk"
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +    "Deploy token",
```suggestion
    "Meluncurkan token",
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +# Cara Mendeploy Token ERC-20 Baru di Lisk
```suggestion
# Cara Meluncurkan Token ERC-20 Baru di Lisk
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +Panduan ini menjelaskan cara mendeploy token ERC-20 baru ke Lisk. Jika Anda ingin menjembatani (_bridge_) token yang sudah ada dari Ethereum, silakan merujuk ke panduan [Menjembatani Token L1 ke Lisk
```suggestion
Panduan ini menjelaskan cara meluncurkan token ERC-20 baru ke Lisk. Jika Anda ingin menjembatani (_bridge_) token yang sudah ada dari Ethereum, silakan merujuk ke panduan [Menjembatani Token L1 ke Lisk](../add-token-to-lisk).
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +## 5. Deploy Kontrak
```suggestion
## 5. Meluncurkan Kontrak
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +Kemudian, pilih kontrak `MyToken` dari dropdown deployment dan deploy dengan parameter pilihan Anda, misalnya:
```suggestion
Kemudian, pilih kontrak `MyToken` dari dropdown deployment dan luncurkan dengan parameter pilihan Anda, misalnya:
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +Akhirnya, konfirmasi deployment kontrak di _wallet_ Anda yang terhubung.
```suggestion
Akhirnya, konfirmasi peluncuran kontrak di _wallet_ Anda yang terhubung.
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +Klik tombol oranye `transact` untuk mendepoy kontrak.
```suggestion
Klik tombol `transact` berwarna oranye untuk meluncurkan kontrak.
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +Jika Anda memilih untuk mendepoy di Lisk Mainnet, _paste_-kan alamat tersebut di https://blockscout.lisk.com
```suggestion
Jika Anda memilih untuk meluncurkan di Lisk Mainnet, tempelkan alamat tersebut di https://blockscout.lisk.com
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +2. Sekarang, buka [kontrak yang baru saja Anda deploy](https://sepolia-blockscout.lisk.com/address/0x6e8fF2E042c1637a2Da9563763c62362a3bbD712) di https://sepolia-blockscout.lisk.com.
```suggestion
2. Sekarang, buka [kontrak yang baru saja Anda luncurkan](https://sepolia-blockscout.lisk.com/address/0x6e8fF2E042c1637a2Da9563763c62362a3bbD712) di https://sepolia-blockscout.lisk.com.
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +Dalam panduan ini, kita akan menggunakan Remix IDE untuk pengembangan _smart contract_, tetapi Anda bebas memilih [framework pengembangan smart contract](/category/building-on-lisk/deploying-smart-co
```suggestion
Dalam panduan ini, kita akan menggunakan Remix IDE untuk pengembangan kontrak pintar, tetapi Anda bebas memilih [framework pengembangan kontrak pintar](/category/building-on-lisk/deploying-smart-contract) lainnya untuk mengimplementasikan kontrak token Anda.
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +Pastikan bahwa versi compiler di Remix IDE sesuai dengan versi compiler yang disebutkan di _smart contract_: `pragma solidity ^0.8.28;`.
```suggestion
Pastikan bahwa versi compiler di Remix IDE sesuai dengan versi compiler yang disebutkan di kontrak pintar: `pragma solidity ^0.8.28;`.
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +    "Token development",
```suggestion
    "Pengembangan token",
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +Tekan tombol hijau play di bagian atas untuk mengompilasi kontrak.
```suggestion
Tekan tombol play berwarna hijau di bagian atas untuk mengompilasi kontrak.
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +_Paste_ alamat ini di BlockScout untuk melihat kontrak di _explorer_ blockchain Lisk:
```suggestion
Tempel alamat ini di BlockScout untuk melihat kontrak di _explorer_ blockchain Lisk:  
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +3. Buka tab kontrak dan klik tombol biru `Verify and Publish`.
```suggestion
3. Buka tab kontrak dan klik tombol `Verify and Publish` berwarna biru.
```

2024-12-24 07:02 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-20.md
> +   - Salin _source code_ yang telah diflatkan dari Remix dan tempelkan di bidang `Enter the Solidity Contract Code`.
```suggestion
   - Salin _source code_ yang telah diflatkan dari Remix dan tempelkan di kolom `Enter the Solidity Contract Code`.
```

2024-12-26 04:52 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +description: Dokumentasi untuk menggunakan ethers.js, sebuah library JavaScript untuk interaksi dengan blockchain yang kompatibel dengan EVM. Halaman ini mencakup instalasi, pengaturan, koneksi ke ja
```suggestion
description: Dokumentasi untuk menggunakan ethers.js, sebuah library JavaScript untuk interaksi dengan blockchain yang kompatibel dengan EVM. Halaman ini mencakup instalasi, pengaturan, koneksi ke jaringan Lisk, membaca dan menulis data blockchain, serta berinteraksi dengan kontrak pintar.
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +Anda dapat menggunakan ethers.js untuk berinteraksi dengan _smart contract_ yang telah dideploy di jaringan Lisk.
```suggestion
Anda dapat menggunakan ethers.js untuk berinteraksi dengan kontrak pintar yang telah diluncurkan di jaringan Lisk.
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +## Berinteraksi dengan smart contract
```suggestion
## Berinteraksi dengan kontrak pintar
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +Anda dapat menggunakan ethers.js untuk berinteraksi dengan _smart contract_ di Lisk dengan menginisialisasi objek `Contract` menggunakan ABI dan alamat dari kontrak yang telah dideploy:
```suggestion
Anda dapat menggunakan ethers.js untuk berinteraksi dengan kontrak pintar di Lisk dengan menginisialisasi objek `Contract` menggunakan ABI dan alamat dari kontrak yang telah diluncurkan:
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +Setelah Anda membuat objek `Contract`, Anda dapat menggunakannya untuk memanggil metode yang diinginkan pada _smart contract_:
```suggestion
Setelah Anda membuat objek `Contract`, Anda dapat menggunakannya untuk memanggil metode yang diinginkan pada kontrak pintar:
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +Sebagai contoh, Anda dapat menggunakan ABI untuk [Hello contract](https://sepolia-blockscout.lisk.com/address/0xb18eb752813c2fbedfdf2be6e5e842a85a3b8539?tab=contact_code). Cukup _scroll_ ke bagian `C
```suggestion
Sebagai contoh, Anda dapat menggunakan ABI untuk [Kontrak Hello](https://sepolia-blockscout.lisk.com/address/0xb18eb752813c2fbedfdf2be6e5e842a85a3b8539?tab=contact_code). Cukup _scroll_ ke bagian `Contract ABI` dan salin ABI dari kontrak yang telah diluncurkan.
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +… // ABI dari kontrak yang telah dideploy.
```suggestion
… // ABI dari kontrak yang telah diluncurkan.
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +`CONTRACT_ADDRESS` adalah alamat dari kontrak yang telah dideploy.
```suggestion
`CONTRACT_ADDRESS` adalah alamat dari kontrak yang telah diluncurkan.
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +Anda dapat terhubung ke Lisk dengan menginisialisasi objek `JsonRpcProvider` baru dari ethers.js menggunakan URL RPC dari jaringan Lisk:
```suggestion
Anda dapat terhubung ke Lisk dengan menginisialisasi objek `JsonRpcProvider` baru dari ethers.js menggunakan URL RPC jaringan Lisk:
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +// Kirim 0.01 ether ke alamat yang diberikan.
```suggestion
// Kirim 0,01 ether ke alamat yang diberikan.
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +````
```suggestion
```
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +Saldo akun penerima akan bertambah sebanyak `0.01` ETH setelah eksekusi transaksi berhasil.
```suggestion
Saldo akun penerima akan bertambah sebanyak `0,01` ETH setelah eksekusi transaksi berhasil.
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +// Kirim 0.01 ether ke alamat yang diberikan.
```suggestion
// Kirim 0,01 ether ke alamat yang diberikan.
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +````
```suggestion
```
```

2024-12-26 04:52 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +````
```suggestion
```
```

2024-12-26 06:36 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +description: Panduan menggunakan RedStone Push untuk mengakses data dunia nyata seperti harga aset, langsung dari smart contract Anda di blockchain Lisk.
```suggestion
description: Panduan menggunakan RedStone Push untuk mengakses data dunia nyata seperti harga aset, langsung dari kontrak pintar Anda di blockchain Lisk.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +RedStone adalah ekosistem data yang menyediakan data yang sering diperbarui, dapat diandalkan, dan beragam untuk dApp dan _smart contract_ Anda yang dideploy di Lisk.
```suggestion
RedStone adalah ekosistem data yang menyediakan data yang sering diperbarui, dapat diandalkan, dan beragam untuk dApp dan kontrak pintar Anda yang diluncurkan di Lisk.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +Untuk mendeploy smart contract di Lisk, ikuti panduan berikut:
```suggestion
Untuk meluncurkan kontrak pintar di Lisk, ikuti panduan berikut:
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +- [Mendeploy smart contract dengan Hardhat](../deploying-smart-contract/with-Hardhat), atau
```suggestion
- [Meluncurkan kontrak pintar dengan Hardhat](../deploying-smart-contract/with-Hardhat), atau
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +- [Mendeploy smart contract dengan Foundry](../deploying-smart-contract/with-Foundry)
```suggestion
- [Meluncurkan kontrak pintar dengan Foundry](../deploying-smart-contract/with-Foundry)
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +  Kontrak-kontrak ini sudah dideploy di jaringan Lisk dan dapat langsung digunakan oleh _konsumen_.
```suggestion
  Kontrak-kontrak ini sudah diluncurkan di jaringan Lisk dan dapat langsung digunakan oleh konsumen.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +RedStone Push hanya sepenuhnya tersedia di Lisk Mainnet, jadi pastikan untuk mendeploy kontrak _Consumer_ Anda di Lisk Mainnet juga.
```suggestion
RedStone Push hanya sepenuhnya tersedia di Lisk Mainnet, jadi pastikan untuk meluncurkan kontrak konsumen Anda di Lisk Mainnet juga.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +Jika Anda ingin mendeploy di Lisk Sepolia Testnet, periksa panduan [Tellor](./tellor.md), yang tersedia untuk kedua jaringan.
```suggestion
Jika Anda ingin meluncurkan di Lisk Sepolia Testnet, periksa panduan [Tellor](./tellor.md), yang tersedia untuk kedua jaringan.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +## Mendeploy di Lisk
```suggestion
## Meluncurkan di Lisk
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +RedStone Push hanya tersedia di Lisk Mainnet, jadi pastikan Anda mendeploy kontrak _Consumer_ di Lisk Mainnet.
```suggestion
RedStone Push hanya tersedia di Lisk Mainnet, jadi pastikan Anda meluncurkan kontrak konsumen di Lisk Mainnet.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +Jika Anda ingin mendeploy di Lisk Sepolia Testnet, silakan cek panduan [Tellor](./tellor.md), yang tersedia untuk kedua jaringan.
```suggestion
Jika Anda ingin meluncurkan di Lisk Sepolia Testnet, silakan cek panduan [Tellor](./tellor.md), yang tersedia untuk kedua jaringan.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +  Aggregator menyimpan data yang telah digabungkan di onchain sehingga _konsumen_ dapat mengambilnya dan menggunakannya dalam transaksi yang sama.
```suggestion
  Agregator menyimpan data yang telah digabungkan di onchain sehingga konsumen dapat mengambilnya dan menggunakannya dalam transaksi yang sama.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +- **Konsumen (Consumer)**: _Konsumen_ adalah aplikasi onchain atau offchain yang menggunakan data _feed_.
```suggestion
- **Konsumen (Consumer)**: Konsumen adalah aplikasi onchain atau offchain yang menggunakan data _feed_.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +  Kontrak _konsumen_ menggunakan `AggregatorV3Interface` untuk memanggil fungsi pada kontrak proxy[^1] dari Aggregator untuk mengambil data oracle.
```suggestion
  Kontrak konsumen menggunakan `AggregatorV3Interface` untuk memanggil fungsi pada kontrak proxy[^1] dari Agregator untuk mengambil data oracle.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +- **Kontrak Aggregator**: Aggregator adalah kontrak yang menerima pembaruan data berkala dari jaringan oracle.
```suggestion
- **Kontrak Agregator**: Agregator adalah kontrak yang menerima pembaruan data berkala dari jaringan oracle.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +    Kontrak proxy adalah proxy onchain yang menunjuk ke aggregator untuk data feed tertentu.
```suggestion
    Kontrak proxy adalah proxy onchain yang menunjuk ke agregator untuk data feed tertentu.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +    Penggunaan proxy memungkinkan aggregator dasar untuk ditingkatkan tanpa mengganggu layanan bagi kontrak yang mengonsumsinya.
```suggestion
    Penggunaan proxy memungkinkan agregator dasar untuk ditingkatkan tanpa mengganggu layanan bagi kontrak yang mengonsumsinya.
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +Aggregator berikut tersedia di Lisk Mainnet untuk RedStone Push:
```suggestion
Agregator berikut tersedia di Lisk Mainnet untuk RedStone Push:
```

2024-12-26 06:36 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/redstone-push.md
> +Dalam panduan ini, kita akan mengembangkan kontrak _Consumer_ yang akan meminta harga spot terbaru dari data feed ETH, LSK, dan USDT.
```suggestion
Dalam panduan ini, kita akan mengembangkan kontrak konsumen yang akan meminta harga spot terbaru dari data feed ETH, LSK, dan USDT.
```

2024-12-26 07:16 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +description: Panduan tentang menggunakan Tellor Data Feeds untuk mengakses data dunia nyata seperti harga aset, langsung dari smart contract Anda di blockchain Lisk.
```suggestion
description: Panduan tentang menggunakan Data Feed Tellor untuk mengakses data dunia nyata seperti harga aset, langsung dari kontrak pintar Anda di blockchain Lisk.
```

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +Untuk mendeploy _smart contract_ di Lisk Sepolia atau Lisk Mainnet, ikuti panduan berikut:
```suggestion
Untuk meluncurkan kontrak pintar di Lisk Sepolia atau Lisk Mainnet, ikuti panduan berikut:
```

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +- [Mendeploy smart contract dengan Hardhat](../deploying-smart-contract/with-Hardhat), atau
```suggestion
- [Meluncurkan kontrak pintar dengan Hardhat](../deploying-smart-contract/with-Hardhat), atau
```

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +- [Mendeploy smart contract dengan Foundry](../deploying-smart-contract/with-Foundry)
```suggestion
- [Meluncurkan kontrak pintar dengan Foundry](../deploying-smart-contract/with-Foundry)
```

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +## Mendeploy di Lisk
```suggestion
## Meluncurkan di Lisk
```

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +Untuk mendeploy _smart contract_ di Lisk Sepolia atau Lisk Mainnet, ikuti panduan berikut:
```suggestion
Untuk meluncurkan kontrak pintar di Lisk Sepolia atau Lisk Mainnet, ikuti panduan berikut:
```

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +[Tellor](https://tellor.io/) adalah protokol oracle terdesentralisasi yang _immutable_, di mana pihak-pihak dapat meminta nilai data dari luar blockchain (misalnya, ETH/USD, LSK/USD), dan _reporters_
```suggestion
[Tellor](https://tellor.io/) adalah protokol oracle terdesentralisasi yang _immutable_, di mana pihak-pihak dapat meminta nilai data dari luar blockchain (misalnya ETH/USD, LSK/USD), dan _reporters_ bersaing untuk menambahkan nilai ini ke dalam bank data onchain.
Input ke dalam bank data ini dijamin oleh jaringan _reporters_ yang melakukan staking terhadap token mereka.
```

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +Selain itu, contoh ini juga berusaha mengurangi serangan _back-in-time dispute attacks_ dengan menyimpan nilai dan timestamp terbaru dalam cache.
```suggestion
Selain itu, contoh ini juga berusaha mengurangi serangan disput _back-in-time_ dengan menyimpan nilai dan timestamp terbaru dalam cache.
```

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +Untuk gambaran umum _best-practice_ menggunakan Tellor, kunjungi [Checklists Pengguna](https://docs.tellor.io/tellor/getting-data/user-checklists) dalam dokumentasi Tellor.
```suggestion
Untuk gambaran umum _best-practice_ menggunakan Tellor, kunjungi [Checklist Pengguna](https://docs.tellor.io/tellor/getting-data/user-checklists) dalam dokumentasi Tellor.
```

2024-12-26 07:16 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/using-oracle-data/tellor.md
> +- Untuk implementasi yang lebih kuat dari oracle Tellor, lihat daftar lengkap fungsi yang tersedia [di sini](https://github.com/tellor-io/usingtellor/blob/master/README.md).
```suggestion
- Untuk implementasi yang lebih andal dari oracle Tellor, lihat daftar lengkap fungsi yang tersedia [di sini](https://github.com/tellor-io/usingtellor/blob/master/README.md).
```

2024-12-26 11:46 UTC, jasonyapri requested changes
Unified `smart contract` and all forms of `deploy` translations in all files

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Bridge Standar adalah smart contract sederhana dengan fungsionalitas untuk memindahkan token ERC-20 antara Lisk dan Ethereum.
```suggestion
Bridge Standar adalah kontrak pintar sederhana dengan fungsionalitas untuk memindahkan token ERC-20 antara Lisk dan Ethereum.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +Panduan ini menggunakan Remix IDE untuk pengembangan _smart contract_, tetapi Anda bebas memilih [framework pengembangan smart contract](/category/building-on-lisk/deploying-smart-contract) lain sesu
```suggestion
Panduan ini menggunakan Remix IDE untuk pengembangan kontrak pintar, tetapi Anda bebas memilih [framework pengembangan kontrak pintar](/category/building-on-lisk/deploying-smart-contract) lain sesuai preferensi Anda untuk mengimplementasikan kontrak token Anda.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +Pastikan bahwa versi compiler di Remix IDE sesuai dengan versi compiler yang disebutkan di _smart contract_: `pragma solidity ^0.8.28;`.
```suggestion
Pastikan bahwa versi compiler di Remix IDE sesuai dengan versi compiler yang disebutkan di kontrak pintar: `pragma solidity ^0.8.28;`.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +- [Memahami smart contract token ERC-20](https://ethereum.org/en/developers/tutorials/understand-the-erc-20-token-smart-contract/)
```suggestion
- [Memahami kontrak pintar token ERC-20](https://ethereum.org/en/developers/tutorials/understand-the-erc-20-token-smart-contract/)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +title: Mendeploy Token Sendiri
```suggestion
title: Meluncurkan Token Sendiri
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +# Mendeploy Token ERC-20 Anda Sendiri ke Lisk
```suggestion
# Meluncurkan Token ERC-20 Anda Sendiri ke Lisk
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Jika Anda tidak memerlukan fungsionalitas tambahan ini, pertimbangkan untuk mengikuti tutorial [Mendeploy Token ERC-20 Standar ke Lisk](./standard-token).
```suggestion
Jika Anda tidak memerlukan fungsionalitas tambahan ini, pertimbangkan untuk mengikuti tutorial [Meluncurkan Token ERC-20 Standar ke Lisk](./standard-token).
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Anda dapat mendeploy **Token ERC-20 Anda Sendiri** di Lisk Mainnet dengan menggunakan proses yang sama.
```suggestion
Anda dapat meluncurkan **Token ERC-20 Anda Sendiri** di Lisk Mainnet dengan menggunakan proses yang sama.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Untuk mendeploy ke mainnet, pastikan dompet (_wallet_) Anda memiliki ETH yang cukup.
```suggestion
Untuk meluncurkan ke mainnet, pastikan dompet (_wallet_) Anda memiliki ETH yang cukup.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Tutorial ini menggunakan [Remix](https://remix.ethereum.org) untuk mendeploy kontrak.
```suggestion
Tutorial ini menggunakan [Remix](https://remix.ethereum.org) untuk meluncurkan kontrak.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Jika Anda sudah memiliki token ERC-20 L1 yang dideploy di Ethereum Mainnet atau Sepolia, Anda dapat melewati langkah ini.
```suggestion
Jika Anda sudah memiliki token ERC-20 L1 yang diluncurkan di Ethereum Mainnet atau Sepolia, Anda dapat melewati langkah ini.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Tutorial ini menggunakan [Remix](https://remix.ethereum.org), sehingga Anda dapat dengan mudah mendeploy token tanpa _framework_ seperti [Hardhat](https://hardhat.org) atau [Foundry](https://getfound
```suggestion
Tutorial ini menggunakan [Remix](https://remix.ethereum.org), sehingga Anda dapat dengan mudah meluncurkan token tanpa _framework_ seperti [Hardhat](https://hardhat.org) atau [Foundry](https://getfoundry.sh).
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +### 6. Mendeploy Kontrak
```suggestion
### 6. Meluncurkan Kontrak
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Kemudian, pilih kontrak `MyCustomL2Token` dari dropdown deployment dan deploy dengan parameter berikut:
```suggestion
Kemudian, pilih kontrak `MyCustomL2Token` dari dropdown deployment dan luncurkan dengan parameter berikut:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +description: "Panduan menambahkan kontrak ERC-20 eksternal yang telah dideploy di Ethereum ke jaringan Lisk."
```suggestion
description: "Panduan menambahkan kontrak ERC-20 eksternal yang telah diluncurkan di Ethereum ke jaringan Lisk."
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Halaman ini ditujukan untuk penerbit token yang sudah memiliki kontrak ERC-20 yang dideploy di Ethereum dan ingin men-_submit_ token mereka untuk dipindahkan (_bridging_) antara Ethereum dan Lisk.
```suggestion
Halaman ini ditujukan untuk penerbit token yang sudah memiliki kontrak ERC-20 yang diluncurkan di Ethereum dan ingin men-_submit_ token mereka untuk dipindahkan (_bridging_) antara Ethereum dan Lisk.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Lisk menggunakan _Superchain Token List_ sebagai referensi untuk token-token yang telah dideploy di Lisk.
```suggestion
Lisk menggunakan _Superchain Token List_ sebagai referensi untuk token-token yang telah diluncurkan di Lisk.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +- Kontrak _bridge_ yang dideploy di **Ethereum**, disebut [L1StandardBridge](https://etherscan.io/address/0x2658723Bf70c7667De6B25F99fcce13A16D25d08).
```suggestion
- Kontrak _bridge_ yang diluncurkan di **Ethereum**, disebut [L1StandardBridge](https://etherscan.io/address/0x2658723Bf70c7667De6B25F99fcce13A16D25d08).
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +- Kontrak _bridge_ yang dideploy di **Lisk**, disebut [L2StandardBridge](https://blockscout.lisk.com/address/0x4200000000000000000000000000000000000010).
```suggestion
- Kontrak _bridge_ yang diluncurkan di **Lisk**, disebut [L2StandardBridge](https://blockscout.lisk.com/address/0x4200000000000000000000000000000000000010).
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Lisk menggunakan [Superchain Token List](https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/optimism.tokenlist.json) sebagai referensi untuk token-token yang telah dideploy
```suggestion
Lisk menggunakan [Superchain Token List](https://github.com/ethereum-optimism/ethereum-optimism.github.io/blob/master/optimism.tokenlist.json) sebagai referensi untuk token-token yang telah diluncurkan di Lisk.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +### Langkah 1: Deploy Token Anda di Lisk
```suggestion
### Langkah 1: Luncurkan Token Anda di Lisk
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Pilih framework _bridging_ yang Anda inginkan, dan gunakan untuk mendeploy ERC-20 token Anda di Lisk.
```suggestion
Pilih framework _bridging_ yang Anda inginkan, dan gunakan untuk meluncurkan ERC-20 token Anda di Lisk.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Kami merekomendasikan Anda menggunakan framework yang disediakan oleh kontrak [bridge standar](#bridge-standar) milik Lisk dan melakukan deploy token Anda menggunakan [OptimismMintableERC20Factory](h
```suggestion
Kami merekomendasikan Anda menggunakan framework yang disediakan oleh kontrak [bridge standar](#bridge-standar) milik Lisk dan meluncurkan token Anda menggunakan [OptimismMintableERC20Factory](https://docs.lisk.com/contracts#jaringan-lisk-l2).  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Mendeploy token Anda di Lisk dengan cara ini memberikan jaminan tambahan yang akan memperlancar proses persetujuan.
```suggestion
Meluncurkan token Anda di Lisk dengan cara ini memberikan jaminan tambahan yang akan memperlancar proses persetujuan.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Untuk instruksi langkah demi langkah tentang cara mendeploy token ERC-20 di Lisk, silakan lihat panduan berikut:
```suggestion
Untuk instruksi langkah demi langkah tentang cara meluncurkan token ERC-20 di Lisk, silakan lihat panduan berikut:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +- [Mendeploy Token ERC-20 Standar](./standard-token.md)
```suggestion
- [Meluncurkan Token ERC-20 Standar](./standard-token.md)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +- [Mendeploy Token ERC-20 Sendiri](./custom-token.mdx)
```suggestion
- [Meluncurkan Token ERC-20 Sendiri](./custom-token.mdx)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +title: Mendeploy Token Standar
```suggestion
title: Meluncurkan Token Standar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +# Mendeploy Token ERC-20 Standar Anda ke Lisk
```suggestion
# Meluncurkan Token ERC-20 Standar Anda ke Lisk
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +Tutorial ini menjelaskan cara menggunakan [`OptimismMintableERC20Factory`](https://github.com/ethereum-optimism/optimism/blob/186e46a47647a51a658e699e9ff047d39444c2de/packages/contracts-bedrock/contr
```suggestion
Tutorial ini menjelaskan cara menggunakan [`OptimismMintableERC20Factory`](https://github.com/ethereum-optimism/optimism/blob/186e46a47647a51a658e699e9ff047d39444c2de/packages/contracts-bedrock/contracts/universal/OptimismMintableERC20Factory.sol) untuk meluncurkan token ERC-20 standar di jaringan Lisk atau Lisk Sepolia.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +Anda dapat mendeploy **token ERC-20 Standar** Anda di Lisk Mainnet dengan menggunakan proses yang sama.
```suggestion
Anda dapat meluncurkan **token ERC-20 Standar** Anda di Lisk Mainnet dengan menggunakan proses yang sama.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +Untuk mendeploy ke mainnet, pastikan dompet Anda memiliki cukup ETH.
```suggestion
Untuk meluncurkan ke mainnet, pastikan dompet Anda memiliki ETH yang cukup.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +Jika Anda sudah memiliki token ERC-20 L1 yang dideploy di Ethereum Mainnet atau Sepolia, Anda dapat melewati langkah ini.
```suggestion
Jika Anda sudah memiliki token ERC-20 L1 yang diluncurkan di Ethereum Mainnet atau Sepolia, Anda dapat melewati langkah ini.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +### 4. Deploy token ERC-20 L2 Anda
```suggestion
### 4. Luncurkan token ERC-20 L2 Anda
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +Anda sekarang dapat mendeploy token ERC-20 L2 Anda menggunakan [`OptimismMintableERC20Factory`](https://github.com/ethereum-optimism/optimism/blob/186e46a47647a51a658e699e9ff047d39444c2de/packages/co
```suggestion
Anda sekarang dapat meluncurkan token ERC-20 L2 Anda menggunakan [`OptimismMintableERC20Factory`](https://github.com/ethereum-optimism/optimism/blob/186e46a47647a51a658e699e9ff047d39444c2de/packages/contracts-bedrock/contracts/universal/OptimismMintableERC20Factory.sol).  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +Gunakan perintah `cast` untuk memicu fungsi deployment pada kontrak factory.
```suggestion
Gunakan perintah `cast` untuk memicu fungsi peluncuran pada kontrak factory.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +Jika semua berjalan lancar, Anda akan menerima respons berisi alamat kontrak yang baru saja dideploy:
```suggestion
Jika semua berjalan dengan lancar, Anda akan menerima respons berisi alamat kontrak yang baru saja diluncurkan:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +_Factory_ memudahkan proses deploy kontrak secara instan.
```suggestion
_Factory_ memudahkan proses peluncuran kontrak secara instan.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +Namun, kelemahannya adalah Anda tidak memiliki kendali atas _source code_ dari kontrak yang akan dideploy karena proses ini dilakukan oleh _factory_.
```suggestion
Namun, kelemahannya adalah Anda tidak memiliki kendali atas _source code_ dari kontrak yang akan diluncurkan karena proses ini dilakukan oleh _factory_.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +[Superchain Token List](https://github.com/ethereum-optimism/ethereum-optimism.github.io#readme) adalah daftar umum token yang telah dideploy di chain dalam Optimism Superchain.
```suggestion
[Superchain Token List](https://github.com/ethereum-optimism/ethereum-optimism.github.io#readme) adalah daftar umum token yang telah diluncurkan di chain dalam Optimism Superchain.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +description: "Panduan tentang Cara Mendeploy Token ERC-1155 Baru di Lisk"
```suggestion
description: "Panduan tentang Cara Meluncurkan Token ERC-1155 Baru di Lisk"
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +    "Deploy token",
```suggestion
    "Meluncurkan token",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +# Cara Mendeploy Token ERC-721 Baru di Lisk
```suggestion
# Cara Meluncurkan Token ERC-721 Baru di Lisk
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +## 5. Deploy Kontrak
```suggestion
## 5. Luncurkan Kontrak
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +Jika Anda memilih untuk mendepoy di Lisk Mainnet, _paste_-kan alamat tersebut di https://blockscout.lisk.com
```suggestion
Jika Anda memilih untuk meluncurkan di Lisk Mainnet, tempelkan alamat tersebut di https://blockscout.lisk.com
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +2. Sekarang, buka [kontrak yang baru saja Anda deploy](https://sepolia-blockscout.lisk.com/address/0x8b2f45e810F539647e70fBCd6441B73d332Ef1A0) di https://sepolia-blockscout.lisk.com.
```suggestion
2. Sekarang, buka [kontrak yang baru saja Anda luncurkan](https://sepolia-blockscout.lisk.com/address/0x8b2f45e810F539647e70fBCd6441B73d332Ef1A0) di https://sepolia-blockscout.lisk.com.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +    "Deploy token",
```suggestion
    "Luncurkan token",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +Halaman ini mencakup penjelasan tentang ERC, ringkasan standar token terpenting, dan contoh cara mendeploy token tersebut di Lisk.
```suggestion
Halaman ini mencakup penjelasan tentang ERC, ringkasan standar token terpenting, dan contoh cara meluncurkan token tersebut di Lisk.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +Jika Anda sudah memiliki token yang dideploy di jaringan Ethereum dan ingin memindahkan (_bridge_) token tersebut ke Lisk, silakan merujuk ke panduan [Memindahkan Token L1 ke Lisk](../add-token-to-li
```suggestion
Jika Anda sudah memiliki token yang diluncurkan di jaringan Ethereum dan ingin memindahkan (_bridge_) token tersebut ke Lisk, silakan merujuk ke panduan [Memindahkan Token L1 ke Lisk](../add-token-to-lisk/index.md).
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +[Bagaimana cara mendeploy token ERC-20 baru di Lisk](deploy-erc-20.md)
```suggestion
[Bagaimana cara meluncurkan token ERC-20 baru di Lisk](deploy-erc-20.md)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +[Bagaimana cara mendeploy token ERC-721 baru di Lisk](deploy-erc-721.md)
```suggestion
[Bagaimana cara meluncurkan token ERC-721 baru di Lisk](deploy-erc-721.md)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +Kemudian, pilih kontrak `MyItems` dari dropdown deployment dan klik tombol oranye `Deploy` untuk mendepoy kontrak.
```suggestion
Kemudian, pilih kontrak `MyItems` dari dropdown deployment dan klik tombol `Deploy` berwarna oranye untuk meluncurkan kontrak.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +Detail smart contract yang dideploy di 🟢 **Ethereum Mainnet** dan 🟡 **Sepolia Testnet** adalah sebagai berikut.
```suggestion
Detail kontrak pintar yang diluncurkan di 🟢 **Ethereum Mainnet** dan 🟡 **Sepolia Testnet** adalah sebagai berikut.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +description: "Panduan untuk mendeploy smart contract di jaringan test Lisk menggunakan Foundry. Termasuk instruksi untuk mengatur environment, mengompilasi, dan mendeploy smart contract."
```suggestion
description: "Panduan untuk meluncurkan kontrak pintar di jaringan test Lisk menggunakan Foundry. Termasuk instruksi untuk mengatur environment, mengompilasi, dan meluncurkan kontrak pintar."
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
>      "smart contract",
```suggestion
    "kontrak pintar",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
>      "deploying smart contracts",
```suggestion
    "meluncurkan kontrak pintar",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
>      "write smart contract",
```suggestion
    "menulis ke kontrak pintar",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +    "smart contract development",
```suggestion
    "pengembangan kontrak pintar",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +# Mendeploy Smart Contract dengan Foundry
```suggestion
# Meluncurkan kontrak pintar dengan Foundry
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Panduan ini membahas dasar-dasar _toolchain_ [Foundry](https://book.getfoundry.sh/) dan menjelaskan cara membuat serta mendeploy _smart contract_ dengan Foundry ke testnet **Lisk Sepolia**.
```suggestion
Panduan ini membahas dasar-dasar _toolchain_ pengembangan [Foundry](https://book.getfoundry.sh/) dan menjelaskan cara membuat serta meluncurkan kontrak pintar dengan Foundry ke testnet **Lisk Sepolia**.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Foundry adalah rangkaian _tools_ yang mumpuni untuk mengembangkan, menguji, dan men-_debug_ _smart contract_ Anda.
```suggestion
Foundry adalah rangkaian _tools_ yang mumpuni untuk mengembangkan, menguji, dan men-_debug_ kontrak pintar Anda.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +- [`forge`](https://book.getfoundry.sh/forge/): _tools_ berbasis _command-line_ yang disertakan dengan Foundry. _Forge_ digunakan untuk menguji, membangun, dan mendeploy _smart contract_ Anda.
```suggestion
- [`forge`](https://book.getfoundry.sh/forge/): _tools_ berbasis _command-line_ yang disertakan dengan Foundry. _Forge_ digunakan untuk menguji, membangun, dan meluncurkan kontrak pintar Anda.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Langkah pertama dalam mendeploy _smart contract_ ke Lisk adalah menyiapkan _environment_ pengembangan Anda dengan membuat proyek Foundry.
```suggestion
Langkah pertama dalam meluncurkan kontrak pintar ke Lisk adalah menyiapkan _environment_ pengembangan Anda dengan membuat proyek Foundry.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +### **Membuat** Smart Contract
```suggestion
### **Membuat** Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Untuk kemudahan dan keamanan, kita akan menggunakan kontrak `ERC721` yang disediakan oleh [OpenZeppelin Contracts library](https://docs.openzeppelin.com/contracts/5.x/erc721) untuk membuat _smart con
```suggestion
Untuk kemudahan dan keamanan, kita akan menggunakan kontrak `ERC721` yang disediakan oleh [OpenZeppelin Contracts library](https://docs.openzeppelin.com/contracts/5.x/erc721) untuk membuat kontrak pintar ERC-721 sederhana.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Di dalam folder `src`, buat sebuah smart contract bernama `NFT.sol` dan tambahkan kode berikut ke dalam file yang baru dibuat.
```suggestion
Di dalam folder `src`, buat sebuah kontrak pintar bernama `NFT.sol` dan tambahkan kode berikut ke dalam file yang baru dibuat.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +### **Meng-_compile_** Smart Contract
```suggestion
### Mengompilasi Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Setelah kode _smart contract_ siap, Anda harus mengompilasinya menggunakan Foundry.
```suggestion
Setelah kode kontrak pintar siap, Anda harus mengompilasinya menggunakan Foundry.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Jika _smart contract_ tidak memiliki _error_, Anda akan melihat output berikut di terminal:
```suggestion
Jika kontrak pintar tidak memiliki eror, Anda akan melihat output berikut di terminal:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +### **Menge-_test_** Smart Contract
```suggestion
### **Menguji** Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Dengan melakukan _testing_ pada _smart contract_, Anda dapat memastikan bahwa _smart contract_ berperilaku sesuai harapan dan tidak ada _bug_ sebelum mendeploy-nya ke Lisk.
```suggestion
Dengan menguji kontrak pintar, Anda dapat memastikan bahwa kontrak pintar berperilaku sesuai harapan dan tidak ada _bug_ sebelum meluncurkannya ke Lisk.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Foundry menyediakan banyak _framework testing_ untuk mendukung Anda dalam menulis _tests_ untuk _smart contract_.
```suggestion
Foundry menyediakan banyak _framework testing_ untuk mendukung Anda dalam menulis _test_ untuk kontrak pintar.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Untuk melakukan _testing_ pada _smart contract_ `NFT`, buat file baru bernama `NFT.t.sol` di dalam direktori `test/`, dan tambahkan konten berikut:
```suggestion
Untuk melakukan _testing_ pada kontrak pintar `NFT`, buat file baru bernama `NFT.t.sol` di dalam direktori `test/`, dan tambahkan konten berikut:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +### **Mendeploy** Smart Contract
```suggestion
### Meluncurkan Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Setelah berhasil membangun _smart contract_, Anda sekarang dapat mendeploy-nya ke jaringan Lisk.
```suggestion
Setelah berhasil membangun kontrak pintar, Anda sekarang dapat meluncurkannya ke jaringan Lisk.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Tambahkan flag `--verify`, `--verifier`, `--verifier-url`, dan `--private-key` dari akun pengirim ke perintah `forge create` untuk langsung memverifikasi _smart contract_ di BlockScout.
```suggestion
Tambahkan flag `--verify`, `--verifier`, `--verifier-url`, dan `--private-key` dari akun pengirim ke perintah `forge create` untuk langsung memverifikasi kontrak pintar di BlockScout.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Setelah _smart contract_ berhasil dideploy dan diverifikasi, Anda dapat berinteraksi dengan memanggil fungsi-fungsi publiknya.
```suggestion
Setelah kontrak pintar berhasil diluncurkan dan diverifikasi, Anda dapat berinteraksi dengan memanggil fungsi-fungsi publiknya.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +### **Memverifikasi** Smart Contract
```suggestion
### **Memverifikasi** Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Jika _smart contract_ Anda belum diverifikasi, ambil alamat kontrak yang sudah dideploy dan jalankan:
```suggestion
Jika kontrak pintar Anda belum diverifikasi, ambil alamat kontrak yang sudah diluncurkan dan jalankan:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +## Berinteraksi dengan Smart Contract
```suggestion
## Berinteraksi dengan Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Seperti yang disebutkan sebelumnya, jika Anda telah memverifikasi _smart contract_ di Blockscout, Anda dapat menggunakan bagian `Read contract` dan `Write contract` di bawah tab `Contract` untuk beri
```suggestion
Seperti yang disebutkan sebelumnya, jika Anda telah memverifikasi kontrak pintar di Blockscout, Anda dapat menggunakan bagian `Read contract` dan `Write contract` di bawah tab `Contract` untuk berinteraksi dengan kontrak yang telah diluncurkan.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Hal ini tidak diperlukan untuk perintah `cast call`, karena perintah tersebut hanya mengambil data yang sudah dipublikasikan dari _smart contract_.
```suggestion
Hal ini tidak diperlukan untuk perintah `cast call`, karena perintah tersebut hanya mengambil data yang sudah dipublikasikan dari kontrak pintar.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +description: "Panduan untuk mendeploy smart contract di jaringan test Lisk menggunakan Hardhat. Termasuk instruksi untuk mengatur environment, mengompilasi, dan mendeploy smart contract."
```suggestion
description: "Panduan untuk meluncurkan kontrak pintar di jaringan test Lisk menggunakan Hardhat. Termasuk instruksi untuk mengatur environment, mengompilasi, dan meluncurkan kontrak pintar."
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
>      "smart contract",
```suggestion
    "kontrak pintar",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
>      "deploying smart contracts",
```suggestion
    "meluncurkan kontrak pintar",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
>      "write smart contract",
```suggestion
    "menulis ke kontrak pintar",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +    "smart contract development",
```suggestion
    "pengembangan kontrak pintar",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +# Mendeploy Smart Contract dengan Hardhat
```suggestion
# Meluncurkan Kontrak Pintar dengan Hardhat
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Sebelum Anda dapat mulai mendeploy _smart contract_ ke Lisk, Anda perlu menyiapkan _environment_ pengembangan dengan membuat proyek Node.js.
```suggestion
Sebelum Anda dapat mulai meluncurkan kontrak pintar ke Lisk, Anda perlu menyiapkan _environment_ pengembangan dengan membuat proyek Node.js.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Untuk mendeploy _smart contract_ ke jaringan Lisk, Anda perlu mengonfigurasi proyek Hardhat Anda dan menambahkan jaringan Lisk.
```suggestion
Untuk meluncurkan kontrak pintar ke jaringan Lisk, Anda perlu mengonfigurasi proyek Hardhat Anda dan menambahkan jaringan Lisk.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Untuk kemudahan dan keamanan, kita akan menggunakan _interface_ `ERC721` yang disediakan oleh [OpenZeppelin Contracts library](https://docs.openzeppelin.com/contracts/5.x/) untuk membuat _smart contr
```suggestion
Untuk kemudahan dan keamanan, kita akan menggunakan _interface_ `ERC721` yang disediakan oleh [OpenZeppelin Contracts library](https://docs.openzeppelin.com/contracts/5.x/) untuk membuat kontrak pintar NFT.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +## Meng-_compile_ Smart Contract
```suggestion
## Mengompilasi Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +## Mendeploy Smart Contract
```suggestion
## Meluncurkan Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +## Memverifikasi Smart Contract
```suggestion
## Memverifikasi Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +## Berinteraksi dengan Smart Contract
```suggestion
## Berinteraksi dengan Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +description: "Panduan untuk mendeploy smart contract di jaringan test Lisk menggunakan thirdweb. Termasuk instruksi untuk mengatur environment, mengompilasi, dan mendeploy smart contract."
```suggestion
description: "Panduan untuk meluncurkan kontrak pintar di jaringan test Lisk menggunakan thirdweb. Termasuk instruksi untuk mengatur environment, mengompilasi, dan meluncurkan kontrak pintar."
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
>      "smart contract",
```suggestion
    "kontrak pintar",
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +# Mendeploy Smart Contract dengan thirdweb
```suggestion
# Meluncurkan Kontrak Pintar dengan thirdweb
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +[thirdweb](https://thirdweb.com/) adalah _framework_ end-to-end untuk pengembangan dan deployment _smart contract_.
```suggestion
[thirdweb](https://thirdweb.com/) adalah _framework_ end-to-end untuk pengembangan dan peluncuran kontrak pintar.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Selain itu, developer yang ingin mengembangkan dan mendeploy _smart contract_ kustom dapat menggunakan [Solidity SDK](https://portal.thirdweb.com/contracts/build/overview) yang disediakan oleh thirdw
```suggestion
Selain itu, developer yang ingin mengembangkan dan meluncurkan kontrak pintar kustom dapat menggunakan [Solidity SDK](https://portal.thirdweb.com/contracts/build/overview) yang disediakan oleh thirdweb, serta opsi lainnya seperti [TypeScript SDK](https://portal.thirdweb.com/typescript/v5) dan [Unity SDK](https://portal.thirdweb.com/unity).  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Build (Solidity SDK)](https://portal.thirdweb.com/contracts/build/overview): Menulis _smart contract_ kustom.
```suggestion
- [Build (Solidity SDK)](https://portal.thirdweb.com/contracts/build/overview): Menulis kontrak pintar kustom.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Interact](https://portal.thirdweb.com/contracts/interact/overview): Berinteraksi dengan _smart contract_ dan mengintegrasikannya langsung ke dalam aplikasi Anda.
```suggestion
- [Interact](https://portal.thirdweb.com/contracts/interact/overview): Berinteraksi dengan kontrak pintar dan mengintegrasikannya langsung ke dalam aplikasi Anda.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Langkah pertama untuk mendeploy _smart contract_ ke Lisk adalah menyiapkan _environment_ pengembangan Anda dengan membuat sebuah proyek.
```suggestion
Langkah pertama untuk meluncurkan kontrak pintar ke Lisk adalah menyiapkan _environment_ pengembangan Anda dengan membuat sebuah proyek.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +thirdweb mendukung dua framework pengembangan _smart contract_ paling populer, yaitu [Foundry](https://book.getfoundry.sh/) dan [Hardhat](https://hardhat.org).
```suggestion
thirdweb mendukung dua framework pengembangan kontrak pintar paling populer, yaitu [Foundry](https://book.getfoundry.sh/) dan [Hardhat](https://hardhat.org).
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Dalam panduan ini, kami menggunakan Foundry untuk pengembangan _smart contract_.
```suggestion
Dalam panduan ini, kami menggunakan Foundry untuk pengembangan kontrak pintar.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +4. Selanjutnya, pilih `Forge` sebagai framework, `NFT` sebagai nama kontrak, `ERC721` sebagai jenis _smart contract_, dan `None` untuk opsi ekstensi.
```suggestion
4. Selanjutnya, pilih `Forge` sebagai framework, `NFT` sebagai nama kontrak, `ERC721` sebagai jenis kontrak pintar, dan `None` untuk opsi ekstensi.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +#### **Membuat** smart contract
```suggestion
#### **Membuat** Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +#### **Mem-build** smart contract
```suggestion
#### **Membangun** Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Setelah kode _smart contract_ siap, kontrak tersebut harus di-_build_ menggunakan thirdweb.
```suggestion
Setelah kode kontrak pintar siap, kontrak tersebut harus di-_build_ menggunakan thirdweb.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +2. Jika _smart contract_ tidak memiliki error, Anda akan melihat output berikut di terminal:
```suggestion
2. Jika kontrak pintar tidak memiliki error, Anda akan melihat output berikut di terminal:  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +#### **Mendeploy** smart contract
```suggestion
#### **Meluncurkan** Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Semua pemeriksaan berhasil dilewati, yang berarti _smart contract_ siap untuk dideploy menggunakan thirdweb.
```suggestion
Semua pemeriksaan berhasil dilewati, yang berarti kontrak pintar siap untuk diluncurkan menggunakan thirdweb.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +2. Jika _smart contract_ tidak memiliki error, Anda akan melihat output berikut di terminal:
```suggestion
2. Jika kontrak pintar tidak memiliki error, Anda akan melihat output berikut di terminal:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +5. Setelah Anda mengisi detail _smart contract_ ERC721, klik tombol `Deploy Now` dan kontrak tersebut akan dideploy ke jaringan yang dipilih dari _wallet_ Anda.
```suggestion
5. Setelah Anda mengisi detail kontrak pintar ERC721, klik tombol `Deploy Now` dan kontrak tersebut akan diluncurkan ke jaringan yang dipilih dari dompet Anda.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Jika Anda ingin mengetes kontrak berbasis Foundry Anda, ikuti langkah-langkah yang disebutkan dalam panduan [Testing the Smart Contract](/building-on-lisk/deploying-smart-contract/with-Foundry#menge-
```suggestion
Jika Anda ingin menguji kontrak berbasis Foundry Anda, ikuti langkah-langkah yang disebutkan dalam panduan [Menguji Kontrak Pintar](/building-on-lisk/deploying-smart-contract/with-Foundry#menge-test-smart-contract).
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +## Berinteraksi dengan Smart Contract
```suggestion
## Berinteraksi dengan Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +description: Dokumentasi untuk menggunakan web3.js, sebuah library JavaScript untuk interaksi blockchain yang kompatibel dengan EVM. Halaman ini mencakup instalasi, pengaturan, koneksi ke jaringan Li
```suggestion
description: Dokumentasi untuk menggunakan web3.js, sebuah library JavaScript untuk interaksi blockchain yang kompatibel dengan EVM. Halaman ini mencakup instalasi, pengaturan, koneksi ke jaringan Lisk, membaca dan menulis data blockchain, serta berinteraksi dengan kontrak pintar.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Anda juga dapat menggunakan web3.js untuk berinteraksi dengan _smart contract_ yang telah dideploy di jaringan Lisk.
```suggestion
Anda juga dapat menggunakan web3.js untuk berinteraksi dengan kontrak pintar yang telah diluncurkan di jaringan Lisk.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +## Berinteraksi dengan Smart Contract
```suggestion
## Berinteraksi dengan Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Anda dapat menggunakan web3.js untuk berinteraksi dengan sebuah _smart contract_ di Lisk dengan menginstansikan objek `Contract` dan memberikan `ABI` serta `address` dari _smart contract_ yang telah
```suggestion
Anda dapat menggunakan web3.js untuk berinteraksi dengan sebuah kontrak pintar di Lisk dengan menginstansikan objek `Contract` dan memberikan `ABI` serta `address` dari kontrak pintar yang telah diluncurkan.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +- Membaca data dari _smart contract_ yang telah dideploy, secara spesifik, kita akan mengambil **nama dari kontrak tersebut**.
```suggestion
- Membaca data dari kontrak pintar yang telah diluncurkan, secara spesifik, kita akan mengambil **nama dari kontrak tersebut**.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +- Selain itu, kita juga akan **mint token** melalui _smart contract_ yang sudah dideploy.
```suggestion
- Selain itu, kita juga akan **mint token** melalui kontrak pintar yang sudah diluncurkan.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +### Membaca dari Smart Contract
```suggestion
### Membaca dari Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Untuk membaca data dari sebuah _smart contract_, Anda perlu memberikan `address` dan `abi` dari _smart contract_ yang telah dideploy dan diverifikasi.
```suggestion
Untuk membaca data dari sebuah kontrak pintar, Anda perlu memberikan `address` dan `abi` dari kontrak pintar yang telah diluncurkan dan diverifikasi.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Setelah informasi tersebut diberikan, fungsi _read-only_ dari _smart contract_ dapat dipanggil, seperti yang dijelaskan di bawah ini:
```suggestion
Setelah informasi tersebut diberikan, fungsi _read-only_ dari kontrak pintar dapat dipanggil, seperti yang dijelaskan di bawah ini:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +### Menulis ke Smart Contract
```suggestion
### Menulis ke Kontrak Pintar
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +description: '**Halaman referensi yang mencantumkan semua kontrak yang dideploy terkait Lisk.**'
```suggestion
description: '**Halaman referensi yang mencantumkan semua kontrak yang diluncurkan terkait Lisk.**'
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +Halaman referensi yang mencakup informasi tentang semua kontrak yang dideploy pada berbagai jaringan.
```suggestion
Halaman referensi yang mencakup informasi tentang semua kontrak yang diluncurkan pada berbagai jaringan.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +### Predeploys pada Lisk
```suggestion
### Pra-Peluncuran pada Lisk
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +Kontrak predeployed disertakan dalam _state_ genesis L2, dan ada sejak awal blockchain.
```suggestion
Kontrak prapeluncuran disertakan dalam _state_ genesis L2, dan ada sejak awal blockchain.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +Untuk informasi lebih lanjut tentang _Predeploys_, lihat [README Predeploys](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
```suggestion
Untuk informasi lebih lanjut tentang Prapeluncuran, lihat [README Prapeluncuran](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +Detail kontrak **_predeployed_** yang dideploy pada 🔵 **Lisk Mainnet** dan 🟣 **Lisk Sepolia Testnet** adalah sebagai berikut.
```suggestion
Detail kontrak **prapeluncuran** yang diluncurkan pada 🔵 **Lisk Mainnet** dan 🟣 **Lisk Sepolia Testnet** adalah sebagai berikut.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +Detail kontrak **_features-specific_ Lisk** yang dideploy pada 🔵 **Lisk Mainnet** dan 🟣 **Lisk Sepolia Testnet** adalah sebagai berikut.
```suggestion
Detail kontrak **_features-specific_ Lisk** yang diluncurkan pada 🔵 **Lisk Mainnet** dan 🟣 **Lisk Sepolia Testnet** adalah sebagai berikut.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Anda dapat mendeploy kontrak di mainnet **Lisk** dengan menggunakan proses yang sama.
```suggestion
Anda dapat meluncurkan kontrak di mainnet **Lisk** dengan menggunakan proses yang sama.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Untuk mendeploy ke mainnet, pastikan _wallet_ Anda memiliki cukup ETH.
```suggestion
Untuk meluncurkan ke mainnet, pastikan _wallet_ Anda memiliki cukup ETH.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +**Mendeploy kontrak** ke blockchain memerlukan **biaya gas**.
```suggestion
**Meluncurkan kontrak** ke blockchain memerlukan **biaya gas**.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Dalam panduan ini, Anda akan mendeploy kontrak ke Lisk Sepolia Testnet.
```suggestion
Dalam panduan ini, Anda akan meluncurkan kontrak ke Lisk Sepolia Testnet.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Untuk contoh ini, kita akan menggunakan jaringan Lisk Sepolia untuk mendeploy kontrak `NFT`.
```suggestion
Untuk contoh ini, kita akan menggunakan jaringan Lisk Sepolia untuk meluncurkan kontrak `NFT`.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Jika deployment berhasil, outputnya akan terlihat seperti berikut:
```suggestion
Jika peluncuran berhasil, outputnya akan terlihat seperti berikut:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +# Perintah yang disebutkan di atas akan terlebih dahulu mendeploy kontrak dan menampilkan output berikut:
```suggestion
# Perintah yang disebutkan di atas akan terlebih dahulu meluncurkan kontrak dan menampilkan output berikut:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +# Setelah kontrak berhasil dideploy, perintah yang disebutkan di atas akan langsung memverifikasi kontrak tersebut!
```suggestion
# Setelah kontrak berhasil diluncurkan, perintah yang disebutkan di atas akan langsung memverifikasi kontrak tersebut!
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Setiap kontrak yang dideploy harus diverifikasi agar pengguna dan developer lainnya dapat memeriksa _source code_-nya dan memastikan bahwa _source code_ tersebut sesuai dengan _bytecode_ yang dideplo
```suggestion
Setiap kontrak yang diluncurkan harus diverifikasi agar pengguna dan developer lainnya dapat memeriksa _source code_-nya dan memastikan bahwa _source code_ tersebut sesuai dengan _bytecode_ yang diluncurkan di blockchain.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Dengan _tool_ command-line dari Foundry: [`cast`](https://book.getfoundry.sh/cast/), Anda dapat berinteraksi dengan kontrak yang telah dideploy, baik untuk membaca maupun menulis data di blockchain.
```suggestion
Dengan _tool_ command-line dari Foundry: [`cast`](https://book.getfoundry.sh/cast/), Anda dapat berinteraksi dengan kontrak yang telah diluncurkan, baik untuk membaca maupun menulis data di blockchain.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Mari kita lakukan panggilan tanpa mempublikasikan transaksi (_read_), lalu menandatangani (_sign_) dan mempublikasikan transaksi (_write_) ke kontrak yang telah dideploy.
```suggestion
Mari kita lakukan panggilan tanpa mempublikasikan transaksi (_read_), lalu menandatangani (_sign_) dan mempublikasikan transaksi (_write_) ke kontrak yang telah diluncurkan.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Hal ini masuk akal karena Anda baru saja mendeploy kontrak NFT, namun belum ada NFT yang dicetak (_minted_), sehingga saldo akun Anda adalah nol.
```suggestion
Hal ini masuk akal karena Anda baru saja meluncurkan kontrak NFT, namun belum ada NFT yang dicetak (_minted_), sehingga saldo akun Anda adalah nol.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Sekarang, mari kita tandatangani dan kirim transaksi dengan memanggil fungsi `mint(address)` pada kontrak `NFT` yang baru saja kita deploy.
```suggestion
Sekarang, mari kita tandatangani dan kirim transaksi dengan memanggil fungsi `mint(address)` pada kontrak `NFT` yang baru saja kita luncurkan.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Dan responsnya: `0x0000000000000000000000000000000000000000000000000000000000000001` (`1` dalam format heksadesimal) — selamat, Anda berhasil mendeploy kontrak dan mencetak NFT dengan Foundry!
```suggestion
Dan responsnya: `0x0000000000000000000000000000000000000000000000000000000000000001` (`1` dalam format heksadesimal) — selamat, Anda berhasil meluncurkan kontrak dan mencetak NFT dengan Foundry!
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +**Mendeploy kontrak** ke blockchain memerlukan **biaya gas**.
```suggestion
**Meluncurkan kontrak** ke blockchain memerlukan **biaya gas**.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Dalam panduan ini, Anda akan mendeploy kontrak ke Lisk Sepolia Testnet.
```suggestion
Dalam panduan ini, Anda akan meluncurkan kontrak ke Lisk Sepolia Testnet.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Anda dapat mendeploy kontrak di Lisk Mainnet dengan menggunakan proses yang sama.
```suggestion
Anda dapat meluncurkan kontrak di Lisk Mainnet dengan menggunakan proses yang sama.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Untuk mendeploy ke mainnet, pastikan _wallet_ Anda memiliki cukup ETH.
```suggestion
Untuk meluncurkan ke mainnet, pastikan _wallet_ Anda memiliki cukup ETH.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +`WALLET_KEY` adalah _private key_ dari _wallet_ yang akan digunakan saat mendeploy kontrak.
```suggestion
`WALLET_KEY` adalah _private key_ dari _wallet_ yang akan digunakan saat meluncurkan kontrak.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Setelah kontrak Anda berhasil dikompilasi, Anda dapat mendeploy kontrak ke jaringan test Lisk Sepolia.
```suggestion
Setelah kontrak Anda berhasil dikompilasi, Anda dapat meluncurkan kontrak ke jaringan test Lisk Sepolia.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Untuk mendeploy kontrak ke jaringan test Lisk Sepolia, Anda perlu memodifikasi file `scripts/deploy.ts` di proyek Anda:
```suggestion
Untuk meluncurkan kontrak ke jaringan test Lisk Sepolia, Anda perlu memodifikasi file `scripts/deploy.ts` di proyek Anda:
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Lihat bagian [Prasyarat](#prasyarat) jika Anda belum melakukannya. Jika tidak, upaya _deployment_ akan gagal.
```suggestion
Lihat bagian [Prasyarat](#prasyarat) jika Anda belum melakukannya. Jika tidak, upaya peluncuran akan gagal.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Kontrak akan dideploy di Lisk Sepolia Testnet.
```suggestion
Kontrak akan diluncurkan di Lisk Sepolia Testnet.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Anda dapat melihat status deployment dan kontrak dengan menggunakan _block explorer_ dan mencari alamat yang dikembalikan oleh skrip deploy Anda.
```suggestion
Anda dapat melihat status peluncuran dan kontrak dengan menggunakan _block explorer_ dan mencari alamat yang dikembalikan oleh skrip peluncuran Anda.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Jika Anda mendeploy kontrak baru atau yang dimodifikasi, Anda perlu memverifikasinya terlebih dahulu.
```suggestion
Jika Anda meluncurkan kontrak baru atau yang dimodifikasi, Anda perlu memverifikasinya terlebih dahulu.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Lihat kontrak Anda di BlockScout dengan mengikuti [link ke kontrak yang telah dideploy](https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D?tab=contract) yang ditam
```suggestion
Lihat kontrak Anda di BlockScout dengan mengikuti [link ke kontrak yang telah diluncurkan](https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D?tab=contract) yang ditampilkan dalam pesan output langkah sebelumnya.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Setelah [kontrak diverifikasi](#verifying-the-smart-contract), Anda dapat menggunakan tab `Read Contract` dan `Write Contract` untuk berinteraksi dengan kontrak yang telah dideploy melalui [BlockScou
```suggestion
Setelah [kontrak diverifikasi](#verifying-the-smart-contract), Anda dapat menggunakan tab `Read Contract` dan `Write Contract` untuk berinteraksi dengan kontrak yang telah diluncurkan melalui [BlockScout](https://sepolia-blockscout.lisk.com/address/0xC10710ac55C98f9AACdc9cD0A506411FBe0af71D?tab=contract).  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Kerangka ini memungkinkan developer untuk mendeploy kontrak standar seperti ERC-20, ERC-721, atau ERC-1155, tanpa menulis satu baris kode pun.
```suggestion
Kerangka ini memungkinkan developer untuk meluncurkan kontrak standar seperti ERC-20, ERC-721, atau ERC-1155, tanpa menulis satu baris kode pun.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Explore](https://portal.thirdweb.com/contracts/explore/overview): Mendeploy kontrak bawaan siap pakai.
```suggestion
- [Explore](https://portal.thirdweb.com/contracts/explore/overview): Meluncurkan kontrak bawaan siap pakai.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Deploy](https://portal.thirdweb.com/contracts/deploy/overview): Mendukung deployment kontrak untuk berbagai kasus penggunaan.
```suggestion
- [Deploy](https://portal.thirdweb.com/contracts/deploy/overview): Mendukung peluncuran kontrak untuk berbagai kasus penggunaan.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +## Mendeploy Kontrak Bawaan melalui thirdweb Explore
```suggestion
## Meluncurkan Kontrak Bawaan melalui thirdweb Explore
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Jika Anda ingin mendeploy kontrak bawaan tanpa kustomisasi, thirdweb menyediakan cara yang mudah untuk melakukannya menggunakan **Explore**.
```suggestion
Jika Anda ingin meluncurkan kontrak bawaan tanpa kustomisasi, thirdweb menyediakan cara yang mudah untuk melakukannya menggunakan **Explore**.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Cara mendeploy kontrak bawaan **ERC-20** melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=5776)
```suggestion
- [Cara meluncurkan kontrak bawaan **ERC-20** melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=5776)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Cara mendeploy kontrak bawaan **ERC-721** melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=6040)
```suggestion
- [Cara meluncurkan kontrak bawaan **ERC-721** melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=6040)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Cara mendeploy kontrak bawaan **ERC-1155** melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=6396)
```suggestion
- [Cara meluncurkan kontrak bawaan **ERC-1155** melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=6396)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Setelah kontrak dideploy, Anda dapat berinteraksi dengan kontrak tersebut melalui Explore.
```suggestion
Setelah kontrak diluncurkan, Anda dapat berinteraksi dengan kontrak tersebut melalui Explore.  
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Bagaimana cara berinteraksi dengan kontrak **ERC-20** yang telah dideploy melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=6823)
```suggestion
- [Bagaimana cara berinteraksi dengan kontrak **ERC-20** yang telah diluncurkan melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=6823)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Bagaimana cara berinteraksi dengan kontrak **ERC-721** yang telah dideploy melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=7581)
```suggestion
- [Bagaimana cara berinteraksi dengan kontrak **ERC-721** yang telah diluncurkan melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=7581)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Bagaimana cara berinteraksi dengan kontrak **ERC-1155** yang telah dideploy melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=8355)
```suggestion
- [Bagaimana cara berinteraksi dengan kontrak **ERC-1155** yang telah diluncurkan melalui Explore?](https://youtu.be/jYEqoIeAoBg?t=8355)
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Cukup scroll ke bagian `Contract ABI` dan salin ABI kontrak yang telah dideploy.
```suggestion
Cukup scroll ke bagian `Contract ABI` dan salin ABI kontrak yang telah diluncurkan.
```

2024-12-26 11:46 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Gunakan cuplikan kode berikut untuk berinteraksi dengan fungsi `mint()` dari [kontrak yang telah dideploy](https://sepolia-blockscout.lisk.com/address/0x108872F713A27bc22ca1db8CEefCAC8CbeDdF9E5?tab=w
```suggestion
Gunakan cuplikan kode berikut untuk berinteraksi dengan fungsi `mint()` dari [kontrak yang telah diluncurkan](https://sepolia-blockscout.lisk.com/address/0x108872F713A27bc22ca1db8CEefCAC8CbeDdF9E5?tab=write_contract).
```

2024-12-26 12:03 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx

2024-12-26 12:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Untuk informasi lebih lanjut, lihat [jaringan Lisk yang tersedia](/network-info) dan [cara menghubungkan _wallet_ ke jaringan tersebut](/user/connecting-to-a-wallet).
```suggestion
Untuk informasi lebih lanjut, lihat [jaringan Lisk yang tersedia](/network-info) dan [cara menghubungkan dompet ke jaringan tersebut](/user/connecting-to-a-wallet).
```

2024-12-26 12:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +### Menambahkan Lisk Sepolia ke _Wallet_ Anda
```suggestion
### Menambahkan Lisk Sepolia ke Dompet Anda
```

2024-12-26 12:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Anda perlu menambahkan jaringan Lisk atau Lisk Sepolia ke _wallet_ Anda untuk mengikuti tutorial ini.
```suggestion
Anda perlu menambahkan jaringan Lisk atau Lisk Sepolia ke dompet Anda untuk mengikuti tutorial ini.
```

2024-12-26 12:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Silakan ikuti panduan [Cara Menghubungkan Lisk ke _Wallet_](/user/connecting-to-a-wallet) untuk menghubungkan _wallet_ Anda ke jaringan Lisk atau Lisk Sepolia.
```suggestion
Silakan ikuti panduan [Cara Menghubungkan Lisk ke Dompet](/user/connecting-to-a-wallet) untuk menghubungkan dompet Anda ke jaringan Lisk atau Lisk Sepolia.
```

2024-12-26 12:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Pastikan bahwa _environment_ Anda diatur ke "Injected Provider", _wallet_ Anda terhubung ke jaringan Lisk atau Lisk Sepolia, dan Remix memiliki akses ke _wallet_ Anda.
```suggestion
Pastikan bahwa _environment_ Anda diatur ke "Injected Provider", dompet Anda terhubung ke jaringan Lisk atau Lisk Sepolia, dan Remix memiliki akses ke dompet Anda.
```

2024-12-26 12:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Jika Anda lebih suka, Anda dapat mengikuti proses umum yang sama dalam _framework_ pilihan Anda.
```suggestion
Anda juga dapat mengikuti proses umum yang sama dalam _framework_ pilihan Anda jika Anda mau.
```

2024-12-26 12:03 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +### 5. Meng-_compile_ Kontrak
```suggestion
### 5. Mengompilasi Kontrak
```

2024-12-26 12:19 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md

2024-12-26 12:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +    "ERC-20 contract",
```suggestion
    "Kontrak ERC-20",
```

2024-12-26 12:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +    "Lisk Testnet",
```suggestion
    "Testnet Lisk",
```

2024-12-26 12:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +    "Lisk Mainnet",
```suggestion
    "Mainnet Lisk",
```

2024-12-26 12:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +    "Optimism Superchain token list",
```suggestion
    "daftar token Optimism Superchain",
```

2024-12-26 12:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Token yang ada di _Superchain Token List_ akan otomatis muncul di beberapa _tools_ seperti [Superchain Bridges UI](https://app.optimism.io/bridge).
```suggestion
Token yang ada di _Superchain Token List_ akan otomatis muncul di beberapa _tool_ seperti [Superchain Bridges UI](https://app.optimism.io/bridge).  
```

2024-12-26 12:19 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Jika Anda memilih framework _bridging_ lain, interfacenya harus kompatibel dengan _bridge standar_. Jika tidak, kami mungkin akan kesulitan untuk men-_support_-nya.
```suggestion
Jika Anda memilih framework _bridging_ lain, interfacenya harus kompatibel dengan _bridge standar_. Jika tidak, kami mungkin akan kesulitan untuk mendukungnya.
```

2024-12-26 13:28 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md

2024-12-26 13:28 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +    "ERC-20 contract",
```suggestion
    "kontrak ERC-20",
```

2024-12-26 13:28 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +    "Standard token",
```suggestion
    "Token Standar",
```

2024-12-26 13:28 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +    "Lisk Testnet",
```suggestion
    "Testnet Lisk",
```

2024-12-26 13:28 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +    "Optimism Superchain token list",
```suggestion
    "Daftar Token Optimism Superchain",
```

2024-12-27 04:29 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +title: "Mendeploy Token ERC-1155 Baru di Lisk"
```suggestion
title: "Meluncurkan Token ERC-1155 Baru di Lisk"
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +    "Token development",
```suggestion
    "Pengembangan Token",
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +    "Hybrid token",
```suggestion
    "Token Hybrid",
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +Pada contoh diatas, _Gold_, _Silver_, _Sword_, dan _Shield_ adalah token yang dapat dipertukarkan (fungible tokens), sedangkan _Thor’s Hammer_ adalah token yang tidak dapat dipertukarkan (non-fungibl
```suggestion
Pada contoh diatas, _Gold_, _Silver_, _Sword_, dan _Shield_ adalah token yang dapat dipertukarkan (fungible token), sedangkan _Thor’s Hammer_ adalah token yang tidak dapat dipertukarkan (non-fungible token) karena kami hanya mencetak satu unit.
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +Tekan tombol hijau play di bagian atas untuk mengompilasi kontrak.
```suggestion
Tekan tombol play berwarna hijau di bagian atas untuk mengompilasi kontrak.
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +Buka tab `Deploy & run transactions` (ikon ini terlihat seperti logo Ethereum dengan panah mengarah ke kanan). Pastikan bahwa _environment_ Anda diatur ke "Injected Provider", _wallet_ Anda terhubung
```suggestion
Buka tab `Deploy & run transactions` (ikon ini terlihat seperti logo Ethereum dengan panah mengarah ke kanan). Pastikan bahwa _environment_ Anda diatur ke "Injected Provider", dompet Anda terhubung ke jaringan Lisk atau Lisk Sepolia, dan Remix memiliki akses ke dompet Anda.
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +Akhirnya, konfirmasi deployment kontrak di _wallet_ Anda yang terhubung.
```suggestion
Akhirnya, konfirmasi deployment kontrak di dompet Anda yang terhubung.
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +_Paste_ alamat ini di BlockScout untuk melihat kontrak di _explorer_ blockchain Lisk: https://sepolia-blockscout.lisk.com/address/0x8b2f45e810F539647e70fBCd6441B73d332Ef1A0
```suggestion
Tempelkan alamat ini di BlockScout untuk melihat kontrak di penjelajah blockchain Lisk: https://sepolia-blockscout.lisk.com/address/0x8b2f45e810F539647e70fBCd6441B73d332Ef1A0
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +Anda dapat menerapkan langkah yang sama untuk memverifikasi kontrak di Lisk Mainnet, jika jaringan itu yang Anda gunakan pada proses diatas, cukup gunakan https://blockscout.lisk.com untuk menggantik
```suggestion
Anda dapat menerapkan langkah yang sama untuk memverifikasi kontrak di Lisk Mainnet, jika kontrak diluncurkan di jaringan tersebut, cukup gunakan https://blockscout.lisk.com untuk menggantikan https://sepolia-blockscout.lisk.com pada langkah 2 dibawah ini.
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +3. Buka tab kontrak dan klik tombol biru `Verify and Publish`.
```suggestion
3. Buka tab kontrak dan klik tombol `Verify and Publish` berwarna biru.
```

2024-12-27 04:29 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/deploy-erc-1155.md
> +   - Salin _source code_ yang telah diflatkan dari Remix dan tempelkan di bidang `Enter the Solidity Contract Code`.
```suggestion
   - Salin _source code_ yang telah diflatkan dari Remix dan tempelkan di kolom `Enter the Solidity Contract Code`.
```

2024-12-27 04:40 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +title: Ikhtisar
```suggestion
title: Gambaran Umum
```

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +    "Token development",
```suggestion
    "Pengembangan Token",
```

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +    "Fungible token",
```suggestion
    "token Fungible",
```

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +    "Hybrid token",
```suggestion
    "token Hybrid",
```

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +_Interface_ standar memungkinkan token apa pun di Ethereum untuk digunakan kembali oleh aplikasi lain: mulai dari _wallet_ hingga _decentralized exchange_.
```suggestion
_Interface_ standar memungkinkan token apa pun di Ethereum untuk digunakan kembali oleh aplikasi lain: mulai dari dompet hingga _decentralized exchange_.
```

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +**ERCs** (_Ethereum Request for Comments_) adalah serangkaian standar dan konvensi di tingkat aplikasi, termasuk standar kontrak seperti standar token (ERC-20), registri nama (ERC-137), skema URI, fo
```suggestion
**ERCs** (_Ethereum Request for Comments_) adalah serangkaian standar dan konvensi di tingkat aplikasi, termasuk standar kontrak seperti standar token (ERC-20), registri nama (ERC-137), skema URI, format _library/package_, dan format dompet untuk blockchain Ethereum.
```

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +- **Kompatibilitas aplikasi tinggi:** Sebagian besar aplikasi hanya mendukung standar token ERC yang paling populer. Dengan mengikuti standar ini, Anda memastikan token Anda akan kompatibel dengan se
```suggestion
- **Kompatibilitas aplikasi tinggi:** Sebagian besar aplikasi hanya mendukung standar token ERC yang paling populer. Dengan mengikuti standar ini, Anda memastikan token Anda akan kompatibel dengan sebagian besar aplikasi eksternal seperti dompet atau _decentralized exchange_.
```

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +_Non-fungible tokens_ (NFTs) digunakan untuk merepresentasikan objek unik seperti real estate atau barang koleksi (_collectibles_), di mana beberapa item memiliki nilai lebih tinggi dibandingkan lain
```suggestion
_Non-fungible token_ (NFTs) digunakan untuk merepresentasikan objek unik seperti real estate atau barang koleksi (_collectibles_), di mana beberapa item memiliki nilai lebih tinggi dibandingkan lainnya karena kegunaan, kelangkaan, atau karakteristik individu lainnya.
```

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +Satu kontrak yang dideploy dapat mencakup kombinasi token _fungible_, _non-fungible_, atau konfigurasi lainnya (misalnya, token _semi-fungible_).
```suggestion
Satu kontrak yang dideploy dapat mencakup kombinasi token _fungible_, _non-fungible_, atau konfigurasi lainnya (misalnya token _semi-fungible_).
```

2024-12-27 04:40 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/token-development/overview.md
> +Alih-alih mendeploy kontrak baru untuk setiap jenis token, satu kontrak token ERC-1155 dapat menyimpan seluruh _state_ sistem, sehingga mengurangi biaya deployment dan kompleksitas.
```suggestion
Alih-alih mendeploy kontrak baru untuk setiap jenis token, satu kontrak token ERC-1155 dapat menyimpan seluruh _state_ sistem, sehingga mengurangi biaya peluncuran dan kompleksitas.
```

2024-12-27 04:58 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +      <td scope="row" rowSpan="2">Berisi daftar root _state_ yang diusulkan oleh Proposers yang mereka klaim sebagai hasil dari eksekusi blok.</td>
```suggestion
      <td scope="row" rowSpan="2">Berisi daftar root _state_ yang diusulkan oleh Proposer yang mereka klaim sebagai hasil dari eksekusi blok.</td>
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +      <td scope="row" rowSpan="2">Ini adalah _entry point_ utama untuk menyetor dana dari L1 ke L2. Selain itu, kontrak ini memungkinkan pembuktian dan penyelesaian _withdrawals_.</td>
```suggestion
      <td scope="row" rowSpan="2">Ini adalah titik masuk utama untuk menyetor dana dari L1 ke L2. Selain itu, kontrak ini memungkinkan pembuktian dan penyelesaian penarikan.</td>
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +      <td scope="row" rowSpan="2">Ini adalah _entry point_ utama untuk menyetor token ERC20 dari L1 ke L2. Kontrak ini dapat menyimpan token apa pun.</td>
```suggestion
      <td scope="row" rowSpan="2">Ini adalah titik masuk utama untuk menyetor token ERC20 dari L1 ke L2. Kontrak ini dapat menyimpan token apa pun.</td>
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +### Kontrak _features-specific_ Lisk
```suggestion
### Kontrak di Lisk yang _features-specific_
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +       <td scope="row" rowSpan="2">Kontrak proxy untuk mengklaim token LSK dari _chain_ Lisk _legacy_ dan menerima jumlah yang sesuai di Lisk L2.</td>
```suggestion
       <td scope="row" rowSpan="2">Kontrak proxy untuk mengklaim token LSK dari rantai legacy Lisk dan menerima jumlah yang sesuai di Lisk L2.</td>
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +       <td scope="row" rowSpan="2">Memungkinkan pengguna untuk mengklaim token LSK mereka dari _chain_ Lisk _legacy_ dan menerima jumlah yang sesuai di Lisk L2 menggunakan bukti _Merkle_, dengan duku
```suggestion
       <td scope="row" rowSpan="2">Memungkinkan pengguna untuk mengklaim token LSK mereka dari rantai legacy Lisk dan menerima jumlah yang sesuai di Lisk L2 menggunakan bukti _Merkle_, dengan dukungan untuk akun reguler maupun _multisig_.</td>
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +       <td scope="row" rowSpan="2">Kontrak proxy untuk operasi terkait _governance_ di Lisk L2.</td>
```suggestion
       <td scope="row" rowSpan="2">Kontrak proxy untuk operasi terkait tata kelola di Lisk L2.</td>
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +       <td scope="row" rowSpan="2">Mengelola operasi yang terkait dengan governance di Lisk L2.</td>
```suggestion
       <td scope="row" rowSpan="2">Mengelola operasi yang terkait dengan tata kelola di Lisk L2.</td>
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +       <td scope="row" rowSpan="2">Kontrak untuk mengunci posisi. Kontrak ini memungkinkan pembuatan, modifikasi, dan penghapusan posisi yang terkunci.</td>
```suggestion
       <td scope="row" rowSpan="2">Kontrak untuk mengunci posisi. Kontrak ini memungkinkan pembuatan, modifikasi, dan penghapusan posisi penguncian.</td>
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +       <td scope="row" rowSpan="2">Modul kontrak ini berfungsi sebagai pengontrol dengan penguncian waktu (time-locked controller).</td>
```suggestion
       <td scope="row" rowSpan="2">Modul kontrak ini berfungsi sebagai pengontrol penguncian waktu (time-locked controller).</td>
```

2024-12-27 04:58 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +       <td scope="row" rowSpan="2">Kontrak untuk menangani hak suara (_voting powers_), penguncian posisi, dan fungsi lainnya dari _staker_ di jaringan Lisk L2.</td>
```suggestion
       <td scope="row" rowSpan="2">Kontrak untuk menangani hak suara (_voting powers_), penguncian posisi, dan fungsi lainnya oleh _staker_ di jaringan Lisk L2.</td>
```

2024-12-27 05:42 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx

2024-12-27 05:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Sebelum mencoba panduan berikut, pastikan bahwa [wallet Anda terhubung ke Jaringan Lisk](/user/connecting-to-a-wallet) dan memiliki dana yang cukup.
```suggestion
Sebelum mencoba panduan berikut, pastikan bahwa [dompet Anda terhubung ke Jaringan Lisk](/user/connecting-to-a-wallet) dan memiliki dana yang cukup.  
```

2024-12-27 05:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Untuk informasi lebih lanjut, lihat bagian [Dana Wallet](/building-on-lisk/deploying-smart-contract/with-Foundry#dana-wallet).
```suggestion
Untuk informasi lebih lanjut, lihat bagian [Dana Dompet](/building-on-lisk/deploying-smart-contract/with-Foundry#dana-dompet).
```

2024-12-27 05:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Video-video berikut menjelaskan langkah-langkah untuk mendeploy berbagai token dengan kontrak bawaan di Lisk:
```suggestion
Video-video berikut menjelaskan langkah-langkah untuk meluncurkan berbagai token dengan kontrak bawaan di Lisk:
```

2024-12-27 05:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +Untuk mengembangkan kontrak kustom, Anda perlu mengunduh dan mengonfigurasi thirdweb.
```suggestion
Untuk mengembangkan kontrak kustom, Anda perlu men_download_ dan mengonfigurasi thirdweb.  
```

2024-12-27 06:10 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx

2024-12-27 06:10 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +    // Instansikan objek web3 dengan memberikan URL RPC dari Lisk Sepolia:
```suggestion
    // Instansikan objek web3 dengan memberikan URL RPC dari Lisk Sepolia.
```

2024-12-27 06:10 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +    // Instansikan objek web3 dengan memberikan URL RPC dari Lisk:
```suggestion
    // Instansikan objek web3 dengan memberikan URL RPC dari Lisk.
```

2024-12-27 06:10 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Untuk menulis data ke jaringan Lisk, Anda perlu membuat sebuah [`Wallet`](https://docs.web3js.org/guides/wallet/).
```suggestion
Untuk menulis data ke jaringan Lisk, Anda perlu membuat sebuah [`Dompet`](https://docs.web3js.org/guides/wallet/).
```

2024-12-27 06:10 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +`Wallet` pada web3.js adalah entry point utama Anda jika ingin menggunakan private key untuk melakukan operasi blockchain, seperti mengirim transaksi, dan lainnya.
```suggestion
`Dompet` pada web3.js adalah titik masuk utama Anda jika ingin menggunakan private key untuk melakukan operasi blockchain, seperti mengirim transaksi, dan lainnya.  
```

2024-12-27 06:10 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Anda dapat membuat sebuah `Wallet` dengan menginstansikan objek `Wallet` baru dari Web3 dan menambahkan private key ke dalamnya.
```suggestion
Anda dapat membuat sebuah `Dompet` dengan menginstansikan objek `Wallet` baru dari Web3 dan menambahkan private key ke dalamnya.  
```

2024-12-27 06:10 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +// Menambahkan akun ke wallet
```suggestion
// Menambahkan akun ke dompet
```

2024-12-27 06:10 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +    // Tambahkan sebuah akun ke wallet.
```suggestion
    // Tambahkan sebuah akun ke dompet.
```

2024-12-27 06:42 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
>      "Lisk test network",
```suggestion
    "jaringan test Lisk",
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
>      "Lisk testnet",
```suggestion
    "testnet Lisk",
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
>      "build on lisk",
```suggestion
    "membangun di lisk",
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +### Dana _Wallet_
```suggestion
### Dana Dompet
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Oleh karena itu, Anda perlu mendanai _wallet_ Anda dengan ETH untuk menutupi biaya gas tersebut.
```suggestion
Oleh karena itu, Anda perlu mendanai dompet Anda dengan ETH untuk menutupi biaya gas tersebut.
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Jika _wallet_ Anda tidak memiliki cukup `SepoliaETH`, gunakan salah satu faucet yang tersedia untuk **Ethereum Sepolia** Testnet, seperti [https://sepoliafaucet.com](https://sepoliafaucet.com/) untuk
```suggestion
Jika dompet Anda tidak memiliki `SepoliaETH` yang cukup, gunakan salah satu faucet yang tersedia untuk **Ethereum Sepolia** Testnet, seperti [https://sepoliafaucet.com](https://sepoliafaucet.com/) untuk menerima ETH Testnet secara gratis.  
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Untuk informasi lebih lanjut, lihat [jaringan Lisk yang tersedia](/network-info) dan [cara menghubungkan wallet ke jaringan tersebut](/user/connecting-to-a-wallet).
```suggestion
Untuk informasi lebih lanjut, lihat [jaringan Lisk yang tersedia](/network-info) dan [cara menghubungkan dompet ke jaringan tersebut](/user/connecting-to-a-wallet).
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Ganti `<YOUR_PRIVATE_KEY>` dengan _private key_ _wallet_ Anda.
```suggestion
Ganti `<YOUR_PRIVATE_KEY>` dengan _private key_ dompet Anda.
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Ikuti instruksi dari _wallet_ Anda untuk mendapatkan _private key_.
```suggestion
Ikuti instruksi dari dompet Anda untuk mendapatkan _private key_.  
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Anda juga memerlukan ETH Testnet di _wallet_ Anda.
```suggestion
Anda juga memerlukan ETH Testnet di dompet Anda.  
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Anda juga perlu menghubungkan _wallet_ Anda terlebih dahulu dengan mengklik tombol `Connect Wallet`.
```suggestion
Anda juga perlu menghubungkan dompet Anda terlebih dahulu dengan mengklik tombol `Connect Wallet`.
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Untuk menambahkan OpenZeppelin Contracts library ke proyek Anda, jalankan perintah berikut:
```suggestion
Untuk menambahkan library OpenZeppelin Contract ke proyek Anda, jalankan perintah berikut:
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +import { ethers } from "hardhat";
```suggestion
import { ethers } from 'hardhat';
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +  const nft = await ethers.deployContract("NFT");
```suggestion
  const nft = await ethers.deployContract('NFT');
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +  console.log("NFT Contract Deployed at " + nft.target);
```suggestion
  console.log('NFT Contract Deployed at ' + nft.target);
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Jika Anda ingin berinteraksi dengan kontrak Anda di _block explorer_, Anda atau orang lain perlu memverifikasinya terlebih dahulu.
```suggestion
Jika Anda ingin berinteraksi dengan kontrak Anda di penjelajah blockchain, Anda atau orang lain perlu memverifikasinya terlebih dahulu.  
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Kontrak di atas sudah diverifikasi, sehingga Anda seharusnya dapat melihat versi Anda di _block explorer_.
```suggestion
Kontrak di atas sudah diverifikasi, sehingga Anda seharusnya dapat melihat versi Anda di penjelajah blockchain.  
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +  // Tambahkan informasi berikut setelah konfigurasi "networks" di HardhatUserConfig:
```suggestion
  // Tambahkan informasi berikut setelah konfigurasi "networks" di HardhatUserConfig
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Anda akan melihat output yang serupa dengan berikut:
```suggestion
Anda akan melihat output yang serupa dengan:
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Jika Anda mencoba melakukannya, seperti memverifikasi kontrak di atas, Anda akan mendapatkan pesan yang seperti:
```suggestion
Jika Anda mencoba melakukannya, seperti memverifikasi kontrak di atas, Anda akan mendapatkan pesan yang serupa dengan:
```

2024-12-27 06:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Block explorer akan mengonfirmasi bahwa kontrak tersebut telah diverifikasi dan memungkinkan Anda untuk [berinteraksi](#berinteraksi-dengan-smart-contract) dengannya.
```suggestion
Penjelajah Blockchain akan mengonfirmasi bahwa kontrak tersebut telah diverifikasi dan memungkinkan Anda untuk [berinteraksi](#berinteraksi-dengan-smart-contract) dengannya.
```

2024-12-27 07:14 UTC, jasonyapri requested changes
i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md

2024-12-27 07:14 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Untuk informasi lebih lanjut, lihat [jaringan Lisk yang tersedia](/network-info) dan [cara menghubungkan wallet ke jaringan tersebut](/user/connecting-to-a-wallet).
```suggestion
Untuk informasi lebih lanjut, lihat [jaringan Lisk yang tersedia](/network-info) dan [cara menghubungkan dompet ke jaringan tersebut](/user/connecting-to-a-wallet).
```

2024-12-27 07:14 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +### Dana _Wallet_
```suggestion
### Dana Dompet
```

2024-12-27 07:14 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Oleh karena itu, Anda perlu mendanai _wallet_ Anda dengan ETH untuk menutupi biaya gas tersebut.
```suggestion
Oleh karena itu, Anda perlu mendanai dompet Anda dengan ETH untuk menutupi biaya gas tersebut.
```

2024-12-27 07:14 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Tab `Read contract` dapat digunakan tanpa menghubungkan _wallet_, namun, untuk menggunakan tab `Write contract`, Anda harus terlebih dahulu menghubungkan _wallet_ Anda.
```suggestion
Tab `Read contract` dapat digunakan tanpa menghubungkan dompet, namun, untuk menggunakan tab `Write contract`, Anda harus terlebih dahulu menghubungkan dompet Anda.  
```

2024-12-27 07:14 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
>      "build on lisk",
```suggestion
    "membangun di lisk",
```

2024-12-27 07:14 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Jika dompet Anda tidak memiliki cukup `SepoliaETH`, gunakan salah satu faucet yang tersedia untuk Ethereum Sepolia Testnet seperti [https://sepoliafaucet.com](https://sepoliafaucet.com/) untuk meneri
```suggestion
Jika dompet Anda tidak memiliki `SepoliaETH` yang cukup, gunakan salah satu faucet yang tersedia untuk Ethereum Sepolia Testnet seperti [https://sepoliafaucet.com](https://sepoliafaucet.com/) untuk menerima ETH Testnet secara gratis.  
```

2024-12-27 07:14 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +- [`anvil`](https://book.getfoundry.sh/anvil/): node testnet lokal, dirancang untuk menguji perilaku kontrak dari antarmuka depan atau melalui RPC dalam _environment_ pengembangan lokal.
```suggestion
- [`anvil`](https://book.getfoundry.sh/anvil/): node testnet lokal, dirancang untuk menguji perilaku kontrak dari frontend atau melalui RPC dalam _environment_ pengembangan lokal.
```

2024-12-27 07:14 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Selain itu, jika Anda ingin orang lain dapat berinteraksi dengan kontrak Anda melalui _block explorer_ seperti _interface_ [Read Contract](https://sepolia-blockscout.lisk.com/address/0x108872F713A27b
```suggestion
Selain itu, jika Anda ingin orang lain dapat berinteraksi dengan kontrak Anda melalui penjelajah blockchain seperti _interface_ [Read Contract](https://sepolia-blockscout.lisk.com/address/0x108872F713A27bc22ca1db8CEefCAC8CbeDdF9E5?tab=read_contract) dan [Write Contract](https://sepolia-blockscout.lisk.com/address/0x108872F713A27bc22ca1db8CEefCAC8CbeDdF9E5?tab=write_contract) di Blockscout, kontrak tersebut harus diverifikasi terlebih dahulu.
```

2024-12-27 07:14 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +Kontrak di atas **sudah diverifikasi**, sehingga Anda seharusnya dapat melihat versi Anda di _block explorer_, tetapi kami tetap akan menjelaskan langkah-langkah untuk memverifikasi kontrak di Lisk S
```suggestion
Kontrak di atas **sudah diverifikasi**, sehingga Anda seharusnya dapat melihat versi Anda di penjelajah blockchain, tetapi kami tetap akan menjelaskan langkah-langkah untuk memverifikasi kontrak di Lisk Sepolia testnet.
```

2025-01-01 12:59 UTC, TalhaMaliktz requested changes
Looking good already! 

Please remove the italic formatting on English terms from all the translated documents.  This includes removal of symbols such as `_` or `()`, unless they are also formatted in this way in the English version.

2025-01-02 03:19 UTC, jasonyapri commented
> Looking good already!
> 
> Please remove the italic formatting on English terms from all the translated documents. This includes removal of symbols such as `_` or `()`, unless they are also formatted in this way in the English version.

@aldhosutra Can you implement the changes requested by @TalhaMaliktz ?
I don't have access to your repo and I think it would be much easier and faster to implement it directly on VS Code using Search rather than me looking at it one by one on this Git `Files changed` page and suggest changes

2025-01-07 13:01 UTC, TalhaMaliktz requested changes

2025-01-07 13:01 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
>      'ERC-20 contract',
Where possible, please translate the keywords on all the pages as well.

2025-01-14 09:17 UTC, TalhaMaliktz requested changes
Looking good! I have left some additional feedback.

Regarding the comment about known terms in web3, you can use the [Optimism's Glossary](https://docs.optimism.io/connect/resources/glossary).

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Anda dapat menggunakan [Superchain Faucet](https://app.optimism.io/faucet?utm_source=docs) untuk mendapatkan ETH di Lisk Sepolia.
```suggestion
Anda dapat menggunakan [Superchain Faucet](https://app.optimism.io/faucet) untuk mendapatkan ETH di Lisk Sepolia.
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
>  <details>
The in-line comments in the following example should be translated as well. Beware of the keywords in the code snippet.

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +# Memindahkan Token L1 ke Lisk
Since Bridge/Bridging is a universal term in web3, I would keep it as is. This is also true for any widely used term in web3 that has been translated in this PR.

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
>  slug: /contracts
```suggestion
slug: /building-on-lisk/contracts
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Kami merekomendasikan Anda menggunakan framework yang disediakan oleh kontrak [bridge standar](#bridge-standar) milik Lisk dan meluncurkan token Anda menggunakan [OptimismMintableERC20Factory](https:
```suggestion
Kami merekomendasikan Anda menggunakan framework yang disediakan oleh kontrak [bridge standar](#bridge-standar) milik Lisk dan meluncurkan token Anda menggunakan [OptimismMintableERC20Factory](contracts#jaringan-lisk-l2).  
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
> +Anda dapat menggunakan [Superchain Faucet](https://app.optimism.io/faucet?utm_source=docs) untuk mendapatkan ETH di Lisk Sepolia.
```suggestion
Anda dapat menggunakan [Superchain Faucet](https://app.optimism.io/faucet) untuk mendapatkan ETH di Lisk Sepolia.
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
>  # Replace this with your L1 ERC-20 token if not using the testing token!
Should be translated to Indonesian.

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/bridged-tokens.md
> -title: Bridged Token Addresses
Same comment as above about the term "Bridged".

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +description: '**Halaman referensi yang mencantumkan semua kontrak yang diluncurkan terkait Lisk.**'
```suggestion
description: 'Halaman referensi yang mencantumkan semua kontrak yang diluncurkan terkait Lisk.'
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +### Pra-Peluncuran pada Lisk
Should be `Predeploys` as this is a type of contract.

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +Untuk informasi lebih lanjut tentang Prapeluncuran, lihat [README Prapeluncuran](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
Should be `Predeploys` as this is a type of contract.

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +Misalnya, untuk **MetaMask**, silakan ikuti [instruksi ini](https://support.metamask.io/hc/en-us/articles/360015289632-How-to-export-an-account-s-private-key).
```suggestion
Misalnya, untuk **MetaMask**, silakan ikuti [instruksi ini](https://support.metamask.io/configure/accounts/how-to-export-an-accounts-private-key/).  
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +import { ethers } from "hardhat";
It should be single quotes, as it is in the English version.

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +  const nft = await ethers.deployContract("NFT");
It should be single quotes, as it is in the English version.

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +  console.log("NFT Contract Deployed at " + nft.target);
It should be single quotes, as it is in the English version.

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- [Interact](https://portal.thirdweb.com/contracts/interact/overview): Berinteraksi dengan kontrak pintar dan mengintegrasikannya langsung ke dalam aplikasi Anda.
```suggestion
- Interact: Berinteraksi dengan kontrak pintar dan mengintegrasikannya langsung ke dalam aplikasi Anda.
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +const ethers = require("ethers");
```suggestion
const ethers = require('ethers');
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Sebelum mulai menggunakan viem, Anda perlu mengatur [Client](https://viem.sh/op-stack/client) dengan [Transport](https://viem.sh/docs/clients/intro.html#transports) dan [Rantai](https://viem.sh/docs/
Please don't translate keywords. This is applicable to the entire PR.
```suggestion
Sebelum mulai menggunakan viem, Anda perlu mengatur [Client](https://viem.sh/op-stack/client) dengan [Transport](https://viem.sh/docs/clients/intro.html#transports) dan [Chain](https://viem.sh/docs/chains/introduction) yang diinginkan.
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Selain membuat permintaan JSON-RPC (`eth_requestAccounts`) untuk mendapatkan sebuah Akun, viem menyediakan berbagai metode pembantu untuk membuat sebuah `Account`, termasuk: [`privateKeyToAccount`](h
```suggestion
Selain membuat permintaan JSON-RPC (`eth_requestAccounts`) untuk mendapatkan sebuah Akun, viem menyediakan berbagai metode pembantu untuk membuat sebuah `Account`, termasuk: [`privateKeyToAccount`](https://viem.sh/docs/accounts/local/privateKeyToAccount), [`mnemonicToAccount`](https://viem.sh/docs/accounts/local/mnemonicToAccount), dan [`hdKeyToAccount`](https://viem.sh/docs/accounts/local/hdKeyToAccount).  
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Untuk menulis data ke jaringan Lisk, Anda perlu membuat sebuah [`Dompet`](https://docs.web3js.org/guides/wallet/).
```suggestion
Untuk menulis data ke jaringan Lisk, Anda perlu membuat sebuah [`Wallet `](https://docs.web3js.org/guides/wallet/).
```

2025-01-14 09:17 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
> +tags: ["node"]
```suggestion
tags: ['nodes']
```

2025-01-16 07:33 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
> +tags: ["node"]
As for this one, Indonesian's plural word and singular word are the same (without the `s`).

2025-01-16 07:34 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/web3.mdx
> +Untuk menulis data ke jaringan Lisk, Anda perlu membuat sebuah [`Dompet`](https://docs.web3js.org/guides/wallet/).
I'll revert back all the `Wallet` translations from `Dompet` on Fuji and Aldo's PR

2025-01-16 07:38 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +Sebelum mulai menggunakan viem, Anda perlu mengatur [Client](https://viem.sh/op-stack/client) dengan [Transport](https://viem.sh/docs/clients/intro.html#transports) dan [Rantai](https://viem.sh/docs/
I'll revert back all the `Chain` translations from `Rantai` on Fuji and Aldo's PR

2025-01-16 07:42 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/interacting-with-the-blockchain/ethers.md
> +const ethers = require("ethers");
I'll revert " back to ' in all code snippets (like in the original English translations)

2025-01-16 07:44 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/contracts.mdx
> +Untuk informasi lebih lanjut tentang Prapeluncuran, lihat [README Prapeluncuran](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
I'll revert back all the `Pre-deploys` translations from `Pra-peluncuran` on Fuji and Aldo's PR

2025-01-16 07:47 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/bridged-tokens.md
> -title: Bridged Token Addresses
I'll revert back all the `Bridge` translations from `dipindahkan melalui bridge` on Fuji and Aldo's PR

2025-01-16 07:48 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/standard-token.md
>  # Replace this with your L1 ERC-20 token if not using the testing token!
Translate all the comments (started with // or #) in all code snippets

2025-01-16 07:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +# Memindahkan Token L1 ke Lisk
Noted. I'll revert back all the `Bridge` translations from `dipindahkan melalui bridge` on Fuji and Aldo's PR

2025-01-16 07:54 UTC, jasonyapri commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/custom-token.mdx
>  <details>
Noted. I'll translate all the in-line comments (started with // or #) in all code snippets

2025-01-16 12:12 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/run-a-lisk-node.md
> +tags: ["node"]
In that case, we can keep it as `node`.

2025-01-17 07:00 UTC, jasonyapri commented
I've revert back several known web3 terms, as follows:

Wallet (See Commit https://github.com/LiskHQ/lisk-docs/pull/264/commits/75984ecaa1564247f64232bd4e9c2261589163f0)
Chain (See Commit https://github.com/LiskHQ/lisk-docs/pull/264/commits/6d77d806d41e815d732d00df7b7760cc2fa70d87)
Bridge (See Commit https://github.com/LiskHQ/lisk-docs/pull/264/commits/98f3e148e1d1f2ff49a102f37d26b7be4d201528)

I've revert back " to '  (like in the original English version | See Commit https://github.com/LiskHQ/lisk-docs/pull/264/commits/3771257215fc9d2e8609c79e607b34760d901898)

Other changes on progress

2025-01-20 13:05 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/add-token-to-lisk/index.md
> +Kami merekomendasikan Anda menggunakan framework yang disediakan oleh kontrak [bridge standar](#bridge-standar) milik Lisk dan deploy token Anda menggunakan [OptimismMintableERC20Factory](../contract
```suggestion
Kami merekomendasikan Anda menggunakan framework yang disediakan oleh kontrak [bridge standar](#bridge-standar) milik Lisk dan deploy token Anda menggunakan [OptimismMintableERC20Factory](contracts#jaringan-lisk-l2).  
```

2025-02-04 13:39 UTC, TalhaMaliktz requested changes

2025-02-04 13:39 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +### Mengompilasi Smart Contract
```suggestion
### **Mengompilasi** Smart Contract
```

2025-02-04 13:39 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Foundry.md
> +### Deploy Smart Contract
```suggestion
### **Deploy** Smart Contract
```

2025-02-04 13:39 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-Hardhat.md
> +## Mengompilasi Smart Contract
There seems to be an inconsistency here; either use the term 'Contract' or 'Kontrak'. I would use Contract since that is widely known.

2025-02-04 13:39 UTC, TalhaMaliktz commented on i18n/ind/docusaurus-plugin-content-docs/current/building-on-lisk/deploying-smart-contract/with-thirdweb.mdx
> +- Interact: Berinteraksi dengan smart contract dan mengintegrasikannya langsung ke dalam aplikasi Anda.
```suggestion
```

2025-02-04 14:08 UTC, jasonyapri approved these changes
Added bold styling for headers as in the English version on building-on-lisk/deploying-smart-contract/with-Foundry.md and Removed a line as in the latest closed PR on building-on-lisk/deploying-smart-contract/with-thirdweb.mdx

2025-02-06 12:24 UTC, TalhaMaliktz approved these changes
Good work! 👏🏼

2025-02-14 13:50 UTC, merged