Update fee page
LiskHQ/lisk-docs pull request #30
Opened 2024-01-29 16:17 UTC by Tschakki

Closes #23

2024-01-30 12:41 UTC, TalhaMaliktz requested changes

2024-01-30 12:41 UTC, TalhaMaliktz commented on docs/about-lisk/fees.md
>    The total price per unit gas that a transaction pays is the sum of the [Base Fee](https://ethereum.org/en/developers/docs/gas/#base-fee) and the optional additional [Priority Fee](https://ethereum.
Since we are discussing L2 fees, we should be linking these fee definitions to OP docs rather than ETH. 

```suggestion
  The total price per unit of gas that a transaction pays is the sum of the [Base Fee](https://docs.optimism.io/stack/transactions/fees#base-fee) and the optional additional [Priority Fee](https://docs.optimism.io/stack/transactions/fees#priority-fee).
```

2024-01-30 12:56 UTC, Tschakki commented on docs/about-lisk/fees.md
>    The total price per unit gas that a transaction pays is the sum of the [Base Fee](https://ethereum.org/en/developers/docs/gas/#base-fee) and the optional additional [Priority Fee](https://ethereum.
I added the links to ethereum documentation on purpose, because it is exactly like in ethereum, as we state earlier. The ethereum docs are also the better resource here, as they go into much more detail about the base and priority fee, while OP docs only have general description and then also link to Ethereum docs as a reference. As we have the general description of the fee already in our docs, the link to OP docs doesn't provide any additional value imho.

2024-01-30 13:47 UTC, TalhaMaliktz approved these changes
LGTM 👍🏼

2024-01-31 14:29 UTC, gkoumout requested changes
Good job! I still left some comments for one last round of updates.

2024-01-31 14:29 UTC, gkoumout commented on docs/about-lisk/fees.md
>  Like Ethereum, Lisk Mainnet uses the [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559) mechanism to set the Base Fee for transactions (although with [different parameter values](https://docs.optimi
I would put this sentence after the equation of lines 51-53. So that the flow is more consistent.

2024-01-31 14:29 UTC, gkoumout commented on docs/about-lisk/fees.md
>    The total price per unit gas that a transaction pays is the sum of the [Base Fee](https://ethereum.org/en/developers/docs/gas/#base-fee) and the optional additional [Priority Fee](https://ethereum.
"total price per unit gas" is a bit confusing phrase IMO. Perhaps The "gas price" is cleaner. Or "The price the transaction pays for each gas unit is ..."

2024-01-31 14:29 UTC, gkoumout commented on docs/about-lisk/fees.md
>    **The only difference is that the gas price on Lisk Mainnet is much lower** than the gas price on Ethereum so you'll end up paying much less in ETH.
Comment for lines 72 - 78: I think this :::note is not displayed correctly, at least to me.

2024-01-31 14:29 UTC, gkoumout commented on docs/about-lisk/fees.md
Comment for line 82: Suggestion: Start this with a positive vibe, for example:

" While the L1 fee will be always cheaper compared to posting the transaction directly to Ethereum mainnet (due to the efficient encoding in batching transactions), still it's value will vary depending ... ".

2024-01-31 14:29 UTC, gkoumout commented on docs/about-lisk/fees.md
> +Also, the cost of L1 gas could increase between steps 1 and 3, it is only updated every five minutes and it does not change by more than 12.5%.
I think it is not true that it gets updated every five minutes, so I would remove this phrase completely. 

Suggestion:

```
In principle, between steps 1 and 3 the gas price might change. However, it can not increase by more than 12.5%, therefore the difference between the price shown to user in step 1 and the actual one is bounded by 12.5%.  

After step 3, the finality ... "
```

2024-01-31 14:29 UTC, gkoumout commented on docs/about-lisk/fees.md
Comment for line 89: Perhaps we want to say "The wallet estimates the cost of the transaction and shows it to the user", so that it is clear that the user gets informed on the amount they have to pay.

2024-01-31 14:44 UTC, Tschakki commented on docs/about-lisk/fees.md
>    **The only difference is that the gas price on Lisk Mainnet is much lower** than the gas price on Ethereum so you'll end up paying much less in ETH.
This note format is Docusaurus specific, see: https://docusaurus.io/docs/markdown-features/admonitions

2024-01-31 14:47 UTC, Tschakki commented on docs/about-lisk/fees.md
Good  point! 👍

2024-01-31 15:21 UTC, gkoumout approved these changes
Approved with an optional comment.

2024-01-31 15:21 UTC, gkoumout commented on docs/about-lisk/fees.md
>    **The only difference is that the gas price on Lisk Mainnet is much lower** than the gas price on Ethereum so you'll end up paying much less in ETH.
Ok I trust you, I just wanted to double check :-)

2024-01-31 15:21 UTC, gkoumout commented on docs/about-lisk/fees.md
>    **The only difference is that the gas price on Lisk Mainnet is much lower** than the gas price on Ethereum so you'll end up paying much less in ETH.
Perhaps add "as explained below", since this is exactly what we explain in the following lines

2024-01-31 15:34 UTC, merged