Add community links to footer and navigation bar
LiskHQ/lisk-docs pull request #33
Opened 2024-01-30 09:14 UTC by TalhaMaliktz

Closes #16

2024-01-30 09:41 UTC, Tschakki requested changes

2024-01-30 09:41 UTC, Tschakki commented on docusaurus.config.js
> +          },
In line 124, please update `Documentation` to `Lisk Documentation`

2024-01-30 09:41 UTC, Tschakki commented on docusaurus.config.js
> +              {
imho it would be nice to add the corresponding icons for Discord, Twitter, and GitHub in the Footer as well.

2024-01-30 09:41 UTC, Tschakki commented on docusaurus.config.js
>          ],
Please verify if copyright should be `Lisk` or `Onchain Foundation`

2024-01-30 14:31 UTC, Tschakki requested changes

2024-01-30 14:31 UTC, Tschakki commented on docusaurus.config.js
> +                    <a href="https://discord.com/invite/7EKWJ7b" target="_blank" aria-label="Discord">
```suggestion
                    <a href="https://lisk.chat" target="_blank" aria-label="Discord">
```

2024-01-30 14:31 UTC, Tschakki commented on docusaurus.config.js
> +                    </a>
Maybe it looks better with the name behind the icon?

Same for GitHub and Twitter links.

```suggestion
                    Discord
                    </a>
```

2024-01-30 14:31 UTC, Tschakki commented on docusaurus.config.js
> +                    <img src="img/twitter-x-white.svg" class="x-dark" />
Although I know Twitter officially rebranded, I have to say I personally still call it Twitter, and also favor the bird logo over the new X logo. I saw we also still use the bird on lisk.com, so maybe we want to keep using it? Just my 2 cents.

2024-01-30 14:32 UTC, TalhaMaliktz commented on docusaurus.config.js
> +                    </a>
Tried it, doesn't look good! I think it should be without icons altogether in the footer, like it was in the default setting.

2024-01-30 14:33 UTC, TalhaMaliktz commented on docusaurus.config.js
> +                    <img src="img/twitter-x-white.svg" class="x-dark" />
Ummmm! I think we should use the latest logo, not the old one! since the company rebranded!

2024-01-30 14:45 UTC, Tschakki commented on docusaurus.config.js
> +                    </a>
Imho it will make it clearer with text, like we had it in the footer of our [old docs](https://lisk.com/documentation/). What exactly do you mean by it doesn't look good?

2024-01-30 14:47 UTC, Tschakki commented on docusaurus.config.js
> +                    <img src="img/twitter-x-white.svg" class="x-dark" />
Yeah, as i said i am aware of this. I just know many people kind of ignore this and still call it Twitter (me included)

2024-01-30 14:54 UTC, TalhaMaliktz commented on docusaurus.config.js
> +                    </a>
<img width="170" alt="image" src="https://github.com/LiskHQ/lisk-documentation/assets/13951043/132dca21-7c65-4de1-adbd-4e260312dd0b">

I can align the text and the icon with styling but still, I prefer the default links over this one!

2024-01-30 14:55 UTC, TalhaMaliktz commented on docusaurus.config.js
> +                    <img src="img/twitter-x-white.svg" class="x-dark" />
I see your point, however, sooner or later we are going to redesign the current site and will use the latest icon so I would keep the X icon.

2024-01-30 15:07 UTC, Tschakki commented on docusaurus.config.js
> +                    </a>
Hmmm ok, then if you prefer only icons, maybe it looks better if they are in the same line

2024-01-30 15:36 UTC, TalhaMaliktz commented on docusaurus.config.js
> +                    </a>
I have now styled them to be on the same line!

2024-01-31 09:44 UTC, Tschakki approved these changes
Thank you, LGTM! 👍

2024-01-31 10:41 UTC, merged