Create Adding ERC-20 tokens to Lisk guide
LiskHQ/lisk-docs pull request #37
Opened 2024-02-05 10:04 UTC by TalhaMaliktz

### What was the problem?

This PR resolves #10

2024-02-05 10:20 UTC, matjazv requested changes

2024-02-05 10:20 UTC, matjazv commented on docs/about-lisk/network-info.md
> +| **Block Explorer** | https://sepolia-blockscout.lisk.com/                                        |
```suggestion
| **Block Explorer** | https://sepolia-blockscout.lisk.com                                        |
```

2024-02-05 10:20 UTC, matjazv commented on docs/building-on-lisk/contracts.md
> +The following contracts have been deployed by Lisk on the Lisk Sepolia Testnet.
Not all contracts were deployed on `Lisk Sepolia Testnet`. L1 contracts were deployed on `Ethereum Sepolia` network.

2024-02-05 10:20 UTC, matjazv commented on docs/building-on-lisk/contracts.md
> +A reference page containing information about all the contracts deployed by Lisk on different networks.
`deployed by Lisk` is somehow not correct.
Contracts were deployed by Gelato, our RaaS provider.

`different networks` => Ethereum Sepolia and Lisk Sepolia test networks

2024-02-05 10:20 UTC, matjazv commented on docs/building-on-lisk/add-token-to-lisk.md
> +Follow the instructions in the [ethereum-optimism.github.io repository's README](https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#superchain-token-list) and submit
As far as I know, we'll need to have our own repository for tokens which will be listed inside [Lisk Standard Bridge](https://sepolia-bridge.lisk.com/bridge/lisk-sepolia-testnet).

Inside Optimism repository, PRs opened there are used to list tokens here: https://app.optimism.io/bridge/deposit
I think each chain (Optimism, Base, Lisk) needs to have their own list of tokens...

2024-02-05 10:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +A reference page containing information about all the contracts deployed by Lisk on different networks.
Can you please name the contracts deployed on L1 and L2? I can add a column to differentiate between the contracts deployed on L1 and L2!

2024-02-05 10:34 UTC, matjazv commented on docs/building-on-lisk/contracts.md
> +A reference page containing information about all the contracts deployed by Lisk on different networks.
I think only those who have prefix `L1` were deployed on L1 network.

2024-02-05 10:42 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +Follow the instructions in the [ethereum-optimism.github.io repository's README](https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#superchain-token-list) and submit
From what I could understand [Base uses the same repo](https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#base-tokens) to upload the list of Tokens deployed to its network and so do [other chains based on OP Stack](https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/617/files). Maybe you can go through the [README](https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/617/files) and help me in clarifying this?

2024-02-05 10:42 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +A reference page containing information about all the contracts deployed by Lisk on different networks.
I have added a column and have re-arranged contracts accordingly.

2024-02-05 11:13 UTC, Tschakki requested changes

2024-02-05 11:13 UTC, Tschakki commented on docs/about-lisk/network-info.md
> +| **Lisk Testnet Faucet** | https://app.optimism.io/faucet                                              |
please adjust whitespace of the table, so columns are clear

2024-02-05 11:13 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +For more information about the purpose of each smart contract mentioned above, see [**OP Mainnet > Smart Contracts**](https://l2beat.com/scaling/projects/optimism#contracts) section.
This doesn't include descriptions for all contracts, and it is quite cumbersome to find the descriptions in general. Imho it wouldn't hurt to include a short description (max 1-2 sentences) in the table.

2024-02-05 11:13 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +| **L1ERC721Bridge**                | 0xb4E988CF1aD8C361D56118437502A8f11C7FaA01 | L1 |
Can you please add explorer links to the respective contracts?

2024-02-05 11:13 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +Tokens approved in the GitHub repository are not necessarily listed on the Lisk Bridge.
```suggestion
Tokens approved in the GitHub repository are not necessarily listed on the [Lisk Bridge](https://sepolia-bridge.lisk.com).
```

2024-02-05 11:13 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +Use the recommended framework provided by Lisk's [Standard Bridge](network-info#lisk-sepolia-testnet) to deploy an ERC-20 contract for your token on Lisk.
Why not link directly to the bridge?
```suggestion
Use the recommended framework provided by Lisk's [Standard Bridge](https://sepolia-bridge.lisk.com/) to deploy an ERC-20 contract for your token on Lisk.
```

Also, I don't understand this step. How can I use the bridge to deploy ERC-20? Afaik, we currently only support ETH on the bridge. What is meant with "recommended framework"?

2024-02-05 11:34 UTC, matjazv commented on docs/building-on-lisk/add-token-to-lisk.md
> +Follow the instructions in the [ethereum-optimism.github.io repository's README](https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#superchain-token-list) and submit
I'm not sure how this will work for Lisk Bridge.

This is actually a question for Gelato, which procedure they will use to list tokens inside Lisk Bridge.
They can use list inside Optimism repository but this doesn't strictly need to be true.

2024-02-05 15:27 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +Use the recommended framework provided by Lisk's [Standard Bridge](network-info#lisk-sepolia-testnet) to deploy an ERC-20 contract for your token on Lisk.
```suggestion
Use the recommended framework provided by Lisk's [Standard Bridge](https://sepolia-bridge.lisk.com) to deploy an ERC-20 contract for your token on Lisk.
```

2024-02-09 09:04 UTC, TalhaMaliktz commented
@Tschakki and @matjazv,  I have incorporated your feedback on the **contracts page** and have separated it from this PR. You can take a look at the updated version here: https://github.com/LiskHQ/lisk-documentation/pull/49

2024-02-09 09:12 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +For more information about the purpose of each smart contract mentioned above, see [**OP Mainnet > Smart Contracts**](https://l2beat.com/scaling/projects/optimism#contracts) section.
Feedback is applied in the PR mentioned below!

2024-02-09 09:13 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +| **L1ERC721Bridge**                | 0xb4E988CF1aD8C361D56118437502A8f11C7FaA01 | L1 |
Feedback is applied in the PR mentioned below!

2024-02-09 09:18 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +Follow the instructions in the [ethereum-optimism.github.io repository's README](https://github.com/ethereum-optimism/ethereum-optimism.github.io?tab=readme-ov-file#superchain-token-list) and submit
For now, this process is TBD so, according to Shu, we will only be able to roll out information about deploying an ERC-20 Contract on the Lisk network. I have aligned the content accordingly and have asked for your review.

2024-02-09 09:29 UTC, matjazv requested changes

2024-02-09 09:29 UTC, matjazv commented on docs/building-on-lisk/add-token-to-lisk.md
> +Tokens approved in the GitHub repository are not necessarily listed on the Lisk Bridge and are not guaranteed or automatic.
```suggestion
Tokens approved in the GitHub repository are not necessarily listed on the Lisk Bridge; their listing is neither guaranteed nor automatic.
```

2024-02-09 09:29 UTC, matjazv commented on docs/building-on-lisk/add-token-to-lisk.md
> +Use the recommended framework provided by Lisk's [Standard Bridge](https://sepolia-bridge.lisk.com) to deploy an ERC-20 contract for your token on Lisk.
I don't understand meaning of this statement.
Could you rephrase it?

2024-02-09 13:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +Use the recommended framework provided by Lisk's [Standard Bridge](https://sepolia-bridge.lisk.com) to deploy an ERC-20 contract for your token on Lisk.
Done

2024-02-09 15:57 UTC, Tschakki requested changes

2024-02-09 15:57 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +It is possible to deploy an ERC-20 contract for bridging with Lisk that has already been deployed on Ethereum.
```suggestion
This tutorial is meant for developers who already have an existing ERC-20 token on Ethereum and want to create a bridged representation of that token on Lisk. In this guide you'll learn how to deploy a custom ERC-20 token from Ethereum to Lisk, using the Standard Bridge system. 
```

Please give more context in the introduction

2024-02-09 15:57 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +To deploy a ERC-20 token by using the [OptimismMintableERC20Factory](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md#optimismmintableerc20factory), follow the steps
Afaik, `OptimismMintableERC20Factory` is used for deploying standard tokens, and `IOptimismMintableERC20` is used for custom tokens. Please do not mix that. Also, if both is already possible for Lisk (standard & custom token), then explain both options equally. Otherwise, only explain one option.

2024-02-09 15:57 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +- [Bridging ERC-20 Tokens to OP Mainnet With the Optimism SDK](https://docs.optimism.io/builders/dapp-developers/tutorials/cross-dom-bridge-erc20)
```suggestion
```

Would remove this

2024-02-09 15:57 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +- [Bridging Your Standard ERC-20 Token to OP Mainnet Using the Standard Bridge](https://docs.optimism.io/builders/dapp-developers/tutorials/standard-bridge-standard-token)
Currently I am afraid we should include the main steps in our docs, because we need to update `TUTORIAL_RPC_URL` for the users. 

But imho this is a perfect example, where it would be awesome it OP docs would include `TUTORIAL_RPC_URL` for Lisk as well, e.g. in form of a tab. We should ask them if they can include that in the OP docs, then we dont need to copy the steps.

2024-02-09 16:05 UTC, matjazv commented on docs/building-on-lisk/add-token-to-lisk.md
> +To deploy a ERC-20 token by using the [OptimismMintableERC20Factory](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md#optimismmintableerc20factory), follow the steps
`IOptimismMintableERC20` is interface which every ERC-20 token needs to implement if that token wants to be bridged token. So to deploy ERC-20 token to Lisk Network, it needs to implement `IOptimismMintableERC20` interface.

`OptimismMintableERC20Factory` is a smart contract which may be used to deploy ERC-20 tokens to LIsk Network.
It has two functions `createStandardL2Token(address _remoteToken, string memory _name, string memory symbol)` and `createOptimismMintableERC20(address _remoteToken, string memory _name, string memory _symbol)` which can be called to "automatically" create and deploy ERC-20 token on LIsk Network.
(second function deploys mintable ERC-20 token and first one not).

2024-02-10 09:22 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +It is possible to deploy an ERC-20 contract for bridging with Lisk that has already been deployed on Ethereum.
```suggestion
This tutorial is meant for developers with an existing ERC-20 token on Ethereum who want to deploy the same token on Lisk.
In this guide, you'll learn how to deploy a custom ERC-20 token from Ethereum to Lisk.
```

2024-02-10 09:34 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +- [Bridging ERC-20 Tokens to OP Mainnet With the Optimism SDK](https://docs.optimism.io/builders/dapp-developers/tutorials/cross-dom-bridge-erc20)
Why 🤔 ?

2024-02-10 09:36 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +- [Bridging Your Standard ERC-20 Token to OP Mainnet Using the Standard Bridge](https://docs.optimism.io/builders/dapp-developers/tutorials/standard-bridge-standard-token)
We can mention that whilst following the mentioned guide, update the `TUTORIAL_RPC_URL` to `https://rpc.sepolia-api.lisk.com/` the rest of the steps are the same for everyone. What do you say?

2024-02-12 10:53 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +- [Bridging Your Standard ERC-20 Token to OP Mainnet Using the Standard Bridge](https://docs.optimism.io/builders/dapp-developers/tutorials/standard-bridge-standard-token)
yes, that would be an option

2024-02-12 11:01 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +To deploy a ERC-20 token by using the [OptimismMintableERC20Factory](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md#optimismmintableerc20factory), follow the steps
@TalhaMaliktz Just to clarify, I am referring to the fact that you mention `OptimismMintableERC20Factory` and then link to the guide explaining how to bridge custom tokens, although this is the contract used for bridging standard tokens. Please adjust the content accordingly

2024-02-12 11:02 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +- [Bridging ERC-20 Tokens to OP Mainnet With the Optimism SDK](https://docs.optimism.io/builders/dapp-developers/tutorials/cross-dom-bridge-erc20)
This guide is for bridging existing tokens, it is not relevant in this context.

2024-02-13 08:29 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +To deploy a ERC-20 token by using the [OptimismMintableERC20Factory](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md#optimismmintableerc20factory), follow the steps
@matjazv and @Tschakki, I have re-aligned the text based on the discussed feedback and now it has details for deploying a standard and a custom ERC-20 token. Please take another look.

2024-02-13 08:48 UTC, matjazv approved these changes
One small change suggested.

2024-02-13 08:48 UTC, matjazv commented on docs/building-on-lisk/add-token-to-lisk.md
> +To deploy a Custom ERC-20 token, one needs to implement all the functions defined by the [IOptimismMintableERC20](https://github.com/ethereum-optimism/optimism/blob/v1.1.4/packages/contracts-bedrock/
`mint`, `burn`, `remoteToken` and `bridge`

2024-02-13 08:58 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +To deploy a Custom ERC-20 token, one needs to implement all the functions defined by the [IOptimismMintableERC20](https://github.com/ethereum-optimism/optimism/blob/v1.1.4/packages/contracts-bedrock/
```suggestion
To deploy a Custom ERC-20 token, one needs to implement all the functions defined by the [IOptimismMintableERC20](https://github.com/ethereum-optimism/optimism/blob/v1.1.4/packages/contracts-bedrock/src/universal/IOptimismMintableERC20.sol) interface such as the logic for the `mint`, `burn`, `remoteToken` and `bridge`, functions of the `IOptimismMintableERC20` interface.
```

2024-02-13 10:47 UTC, Tschakki requested changes

2024-02-13 10:47 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +To do the aforementioned, follow the steps mentioned in the [Bridging Your Custom ERC-20 Token to OP Mainnet Using the Standard Bridge](https://docs.optimism.io/builders/dapp-developers/tutorials/sta
```suggestion
To do the aforementioned, follow the steps mentioned in the [Bridging Your Custom ERC-20 Token to OP Mainnet Using the Standard Bridge](https://docs.optimism.io/builders/dapp-developers/tutorials/standard-bridge-custom-token#create-an-l2-erc-20-token) guide.
```

2024-02-13 10:47 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +
```suggestion
:::important
While following the aforementioned guide, ensure your wallet is connected to Lisk Sepolia in step 6.
The rest of the steps are the same for Lisk as they are for Optimism.
:::
```

2024-02-13 10:47 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +title: Adding ERC-20 Token to Lisk
```suggestion
title: How to add your ERC-20 Token to Lisk
```

2024-02-13 11:37 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk.md
> +title: Adding ERC-20 Token to Lisk
The existing title suits more and is in sync with the titles of other pages so I would like to keep it as it is.

2024-02-13 17:15 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +title: Adding ERC-20 Token to Lisk
hmm imho it is ok to use "How to..." sometimes, and here it sounds better to me personally.

But anyway i don't have a strong opinion. If we go for your version, I think it should be updated to

```suggestion
title: Adding ERC-20 Tokens to Lisk
```

or

```suggestion
title: Adding an ERC-20 Token to Lisk
```

2024-02-14 08:22 UTC, Tschakki approved these changes
LGTM 🎉

2024-02-14 08:22 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk.md
> +# Adding ERC-20 Token to Lisk
```suggestion
# Adding an ERC-20 Token to Lisk
```

2024-02-14 13:00 UTC, merged