Add Contract Page
LiskHQ/lisk-docs pull request #49
Opened 2024-02-08 14:07 UTC by TalhaMaliktz

### What was the problem?

This PR resolves #24 

### How was it tested?

https://liskhq.github.io/lisk-documentation/contracts

2024-02-09 09:24 UTC, matjazv requested changes

2024-02-09 09:24 UTC, matjazv commented on docs/building-on-lisk/contracts.md
> +| **ProtocolVersions**              | [0x1Bb17EB31bDdFd30F63D4FAe6c8Eb85D9e9b1f48](https://sepolia.etherscan.io/address/0x1Bb17EB31bDdFd30F63D4FAe6c8Eb85D9e9b1f48) |  |
`The ProtocolVersions contract is used to manage superchain protocol version information.`

2024-02-09 09:25 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +| **ProtocolVersions**              | [0x1Bb17EB31bDdFd30F63D4FAe6c8Eb85D9e9b1f48](https://sepolia.etherscan.io/address/0x1Bb17EB31bDdFd30F63D4FAe6c8Eb85D9e9b1f48) |  |
```suggestion
| **ProtocolVersions**              | [0x1Bb17EB31bDdFd30F63D4FAe6c8Eb85D9e9b1f48](https://sepolia.etherscan.io/address/0x1Bb17EB31bDdFd30F63D4FAe6c8Eb85D9e9b1f48) | It is used to manage superchain protocol version information. |
```

2024-02-09 09:27 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +| **ProtocolVersions**              | [0x1Bb17EB31bDdFd30F63D4FAe6c8Eb85D9e9b1f48](https://sepolia.etherscan.io/address/0x1Bb17EB31bDdFd30F63D4FAe6c8Eb85D9e9b1f48) |  |
Description added!

2024-02-09 09:39 UTC, Tschakki requested changes

2024-02-09 09:39 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +## Ethereum Sepolia Testnet
As all the contracts related to the Lisk Testnet, I woult group them under same section `Testnet`, and then separate in L1 & L2 contract adresses

```suggestion
## Testnet

### L1 contract adresses
```

2024-02-09 09:39 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +## Lisk Sepolia Testnet
```suggestion
### L2 contract addresses
```

2024-02-09 09:39 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
Does it mean there are no single contracts on L2? Is it possible to link to the predeployed contracts in the genesis block somehow?

2024-02-09 11:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
As per Gelato all these are contracts and are deployed as Predeploys. Regarding the links you mention. We can simply reference the [following link](https://docs.optimism.io/chain/addresses#op-sepolia-l2) since these are all Predeploys on OP Sepolia so the addresses are the same for us as they are for Optimism.

2024-02-09 13:12 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
Why not include the table directly in our docs, with links to our own contracts in the explorer?

2024-02-09 13:28 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
For maintenance reasons I would avoid duplicating this info, these two pages have already a lot more information that a reader needs and IMHO the references to these pages are enough rather than having an entire table for the same info. I feel then there will be a need to define everything as well as we have done for L1 and seems like duplicating info which might get updated without our notice.

2024-02-09 13:44 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
Reference added!

2024-02-09 13:57 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
Hmm, I wouldn't add this reference to OP docs: as far as i see it lists the exact same contracts which are explained in more details in the Ethereum reference that you already included. 

The only additional information in the OP docs are direct links to the respective OP contracts. These links should be replaced with links to our own explorer, as the page is about the contracts of Lisk and not OP.
That's why imho we should include such a table in our docs.

2024-02-09 14:03 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
From what I can understand, these `predeploys` are there in the genesis state with predefined addresses and the addresses remain the same for whoever is building on the OP Stack, and they can simply use them. There is no way to view these contracts on our Explorer. If you try searching one of the addresses mentioned in the aforementioned links in our explorer, you'll find that it is not a contract address.

2024-02-09 14:26 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
ok thanks for the clarification! In that case the original GitHub reference should be sufficient imho :)

Maybe we can consider to add a little info why these contracts cannot be found in the explorer, because users might actually wonder the same when they search for them.

2024-02-09 14:37 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
Text Updated!

2024-02-09 14:40 UTC, matjazv commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
Behind those addresses are smart contracts which were predeployed to Lisk Sepolia Network.

For example, `L2StandardBridge` (`0x4200000000000000000000000000000000000010`), it's the same contracts in [Lisk Sepolia Explorer](https://sepolia-blockscout.lisk.com/address/0x4200000000000000000000000000000000000010) as it is in [Optimism Sepolia Explorer](https://optimism-sepolia.blockscout.com/address/0x4200000000000000000000000000000000000010).

Probably the reason why you can't see it as a smart contract is that it is a predeployed contract and it was not verified (to see smart contract source code, you need to verify it). Because of both conditions.
If you deploy smart contract you'll see it as smart contract even if it's not verified. Probably different case is if it's predeployed and not verified at the same time.

Why all those predeployed contracts are not verified and not seen as smart contracts in Lisk Explorer, is a question for Gelato.

2024-02-09 14:55 UTC, matjazv requested changes

2024-02-09 14:55 UTC, matjazv commented on docs/building-on-lisk/contracts.md
> +Any L2 based on the OP Stack inherits these contracts and can consume them at will.
`Lisk Sepolia Network` and `Optimism Sepolia Network` are two independent networks. There's no `Superchain network` yet, that those two networks could communicate between each other.

All L2 network based on `OP Stack` must predeploy L2 smart contracts to its network. `Lisk Sepolia Network` can't use smart contracts (pre)deployed on `Optimism Sepolia Network`.

2024-02-09 14:58 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +Any L2 based on the OP Stack inherits these contracts and can consume them at will.
Should I remove this?

2024-02-09 15:03 UTC, matjazv commented on docs/building-on-lisk/contracts.md
> +Any L2 based on the OP Stack inherits these contracts and can consume them at will.
Maybe whole info could be something like this:

`
A predeployed contract is one that is included in the L2 genesis state, meaning it exists from the very beginning of the chain. On Lisk Network, these contracts are located at specific addresses that are determined in advance and are part of the genesis state.
`

2024-02-09 15:58 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
@matjazv Gelato clarified it is a bug in BlockScout, and they are working to fix it, see the discussion on Slack :)

2024-02-09 15:59 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
Actually, they just confirmed it is already fixed 🎉 https://sepolia-blockscout.lisk.com/address/0x4200000000000000000000000000000000000010?tab=contract

2024-02-09 16:03 UTC, Tschakki commented on docs/building-on-lisk/contracts.md
> +For more information on each contract, see [Predeploy's README](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/predeploys.md).
so we can add the links now @TalhaMaliktz  :)

2024-02-12 07:41 UTC, matjazv approved these changes
Just one small question, otherwise looks good.

2024-02-12 07:41 UTC, matjazv commented on docs/building-on-lisk/contracts.md
> +    'L1',
If `L1` is inside keywords, should then `L2` also be part of it?

2024-02-12 07:48 UTC, TalhaMaliktz commented on docs/building-on-lisk/contracts.md
> +    'L1',
```suggestion
    'L1',
    'L2'
```

2024-02-12 10:55 UTC, Tschakki approved these changes
Thank you! 🎉

2024-02-12 10:56 UTC, merged