Configure Theme, plugins, and presets
LiskHQ/lisk-docs pull request #5
Opened 2024-01-08 13:02 UTC by TalhaMaliktz

Closes #3

2024-01-10 14:04 UTC, TalhaMaliktz commented
I played around with a local installation and here are my thoughts:

- I have disabled blogs, updated the index page, and disabled the unnecessary code blocks.
- The Google Analytics isn't enabled by default so I didn't have to do anything.
- Since we don't have a design/branding so far, I used colors from Lisk's existing palette and changed the code snippet theme as well, please share your thoughts on that.
- Regarding the presets, and themes, I think after the initial discussion which we just had, we can probably use the default settings for presets, themes, and plugins as there might not be much content that would require a separation.

2024-01-10 17:15 UTC, Tschakki requested changes

2024-01-10 17:15 UTC, Tschakki commented on src/pages/index.js
I don't think we currently need this page, as our content is very limited at the beginning.

2024-01-10 17:15 UTC, Tschakki commented on docusaurus.config.js
>              label: 'Tutorial',
This should be renamed to "Documentation", please also rename the corresponding sidebar, to avoid confusion.
```suggestion
            label: 'Documentation',
```

2024-01-10 17:15 UTC, Tschakki commented on docusaurus.config.js
> +        // blog: {
Please use block comments when commenting out multiple lines, it makes it easier to hide them. :)

2024-01-11 07:41 UTC, TalhaMaliktz commented on src/pages/index.js
Done

2024-01-11 07:41 UTC, TalhaMaliktz commented on docusaurus.config.js
> +        // blog: {
Done

2024-01-11 09:17 UTC, Tschakki requested changes
Looks good, just left some minor comments.

2024-01-11 09:17 UTC, Tschakki commented on docusaurus.config.js
>              sidebarId: 'tutorialSidebar',
Maybe rename to `documentationSidebar`, to align with the new label

2024-01-11 09:17 UTC, Tschakki commented on src/pages/index.js
Is it possible to completely remove the page? I dont see it anymore in [base docs](https://github.com/base-org/web/tree/master/apps/base-docs/src) for example

2024-01-11 09:18 UTC, TalhaMaliktz commented on docusaurus.config.js
>              sidebarId: 'tutorialSidebar',
Tried this and it threw an error, that's why I didn't change this.

2024-01-11 09:21 UTC, TalhaMaliktz commented on src/pages/index.js
Ummmmmm! Not sure, how they are doing it but somehow the framework keeps looking at this page. I tried renaming the file to see what happens and it threw an error, also tried changing the `baseUrl` in the config and that also didn't work. I then simply used the redirection code and now whenever you run the application, it will lead to the documentation page.

2024-01-11 09:31 UTC, Tschakki commented on docusaurus.config.js
>              sidebarId: 'tutorialSidebar',
did you adjust the corresponding file as well?

2024-01-11 09:32 UTC, Tschakki commented on src/pages/index.js
Maybe this helps? https://stackoverflow.com/questions/61999271/how-to-set-docs-as-the-main-page

2024-01-11 09:41 UTC, TalhaMaliktz commented on docusaurus.config.js
>              sidebarId: 'tutorialSidebar',
Just did, and that did the trick! label updated.

2024-01-11 09:49 UTC, TalhaMaliktz commented on src/pages/index.js
This guide did the trick: https://docusaurus.io/docs/next/docs-introduction#home-page-docs

2024-01-11 09:59 UTC, Tschakki approved these changes
LGTM 🎉

2024-01-11 09:59 UTC, Tschakki commented on docusaurus.config.js
>            alt: 'My Site Logo',
```suggestion
          alt: 'Lisk Logo',
```

2024-01-17 14:19 UTC, Tschakki approved these changes
🎉

2024-01-17 14:23 UTC, ritaosok approved these changes

2024-01-17 14:30 UTC, merged