L1->L2 Migration guide
LiskHQ/lisk-docs pull request #55
Opened 2024-02-13 11:51 UTC by Tschakki

### What was the problem?

This PR resolves #53 

### How was ist tested?
https://liskhq.github.io/lisk-documentation/building-on-lisk/migration-guide

2024-02-19 13:50 UTC, Phanco commented on docs/building-on-lisk/migration-guide.mdx
> +    blacklist = _newWord;
`_newWord` -> `_newBlackList` sounds better

2024-02-19 14:13 UTC, Phanco requested changes

2024-02-19 14:13 UTC, Phanco commented on docs/building-on-lisk/migration-guide.mdx
> +    minlength = _newMin;
`minlength` -> `_newMinLength`
`maxLength` -> `_newMaxLength`

2024-02-19 14:13 UTC, Phanco commented on docs/building-on-lisk/migration-guide.mdx
> +forge install willitscale/solidity-util
This library looks pretty old, if we only need `.length` feature from the library, we can use `bytes(message).length` instead

2024-02-19 14:13 UTC, Phanco commented on docs/building-on-lisk/migration-guide.mdx
> +        return counter;
Although I understand that we're trying to compare implementation of L1 and L2, it's not necessary to make a getter for a public variable. We can instead state that 

> `uint32 public counter` can be accessed directly`

2024-02-19 14:13 UTC, Phanco commented on docs/building-on-lisk/migration-guide.mdx
> +        hoax(alice, 100 ether);
I think alice can be hoaxed in `setUp`

2024-02-19 14:13 UTC, Phanco commented on docs/building-on-lisk/migration-guide.mdx
> +        hello2 = new Hello();
why we need to deploy `hello2`

2024-02-19 16:03 UTC, Tschakki commented on docs/building-on-lisk/migration-guide.mdx
> +        hello2 = new Hello();
We deploy a second time with Alice, so that she is owner of the contract, so that she can change the configs successfully

2024-02-19 16:14 UTC, Tschakki commented on docs/building-on-lisk/migration-guide.mdx
> +        hoax(alice, 100 ether);
Do you have a working example for that?

2024-02-19 16:16 UTC, Tschakki commented on docs/building-on-lisk/migration-guide.mdx
> +        return counter;
yeah i realized the same after writing it, that's why i added the comment on line [601](https://github.com/LiskHQ/lisk-documentation/pull/55/files#diff-a21743a4c014e99cb9f6a2da09e34196264ab67f94d1d5557364a70adb116feaR601) :) Will update it accordingly 👍

2024-02-20 11:00 UTC, Phanco commented on docs/building-on-lisk/migration-guide.mdx
> +        hoax(alice, 100 ether);
I believe for some tests you don't need to hoax alice, or submit the transaction on behalf of alice and it will also achieve the same result, e.g. `test_MinLength`?

2024-02-20 11:00 UTC, Phanco commented on docs/building-on-lisk/migration-guide.mdx
> +        hello2 = new Hello();
Ah I see, I just realised `owner` cannot be changed, then it make sense

2024-02-20 11:00 UTC, Phanco commented on docs/building-on-lisk/migration-guide.mdx
> +        address public owner;
since owner cannot be changed, you can set
```
address public immutable owner;
```

2024-02-20 11:43 UTC, Tschakki commented on docs/building-on-lisk/migration-guide.mdx
> +        hoax(alice, 100 ether);
ah true, I have updated the tests now, please check :)

2024-02-20 12:28 UTC, Phanco approved these changes
LGTM :D

2024-02-21 14:04 UTC, TalhaMaliktz requested changes
Please consider the following!

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +uint32 public minlength = 3
```suggestion
uint32 public minlength = 3;
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +For updating the owner of the smart contract, you can imeplemnt a corresponding function `setOwner()` and use the `onlyOwner` modifier to ensure that only the current owner can call this function.
```suggestion
To update the smart contract owner, you can implement a corresponding function `setOwner()`, and use the `onlyOwner` modifier to ensure that only the current owner can call this function.
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +Additionally, we increment the Hello message counter by +1, and emit the `NewHello` event, like it was done in the `execute()` method of the Lisk L1 Hello module previously.
```suggestion
Additionally, we increment the Hello message counter by `1` and emit the `NewHello` event, like it was done in the `execute()` method of the Lisk L1 Hello module previously.
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +}
The snippet doesn't match with the code in the following full contract. Please re-confirm and align all snippets with the final `Hello.sol` file.

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +The `validMessage()` modifier the we defined above in the Verification section is used to check if the message is valid, before `createHello()` function is executed.
```suggestion
The `validMessage()` modifier that we defined above in the [Verification](/building-on-lisk/migration-guide#verification) section is used to check if the message is valid before the `createHello()` function is executed.
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +  For more complex endpoints, you can implement corresponding view functions in the contract.
```suggestion
For more complex endpoints, you can implement corresponding [view](https://solidity-by-example.org/view-and-pure-functions/) functions in the contract.
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +    ```
Shouldn't this snippet be removed? Seems redundant as it is already defined earlier

```suggestion
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +The module-specific configurations, which resided in the `config.json` on Lisk L1, are now part of the smart contract itself, and defined as state variables.
```suggestion
The module-specific configurations, which resided in the `config.json` on Lisk L1, are now part of the smart contract itself and are defined as state variables.
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +To set the owner of the contract, we add a new state variable `owner` and a constructor which sets the `owner` variable to the account address that deploys the contract.
```suggestion
To set the owner of the contract, we add a new state variable `owner`, and a constructor which sets the `owner` variable to the account address that deploys the contract.
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +Inside of the modifiers, we check the length of the message and if it contains any blacklisted words, like it was done in the `verify()` method of the Lisk L1 Hello module.
```suggestion
Inside the modifiers, we check the length of the message and if it contains any blacklisted words like it was done in the `verify()` method of the Lisk L1 Hello module.
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +Inside of this function, we save the message of the sender in the `message` mapping under the sender address.
```suggestion
Inside this function, we save the message of the sender in the `message` mapping under the sender address.
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +To test the Hello smart contract, create a new file `Hello.t.sol` under `test/` and add the following content:
```suggestion
To test the Hello smart contract, create a new file `Hello.t.sol` under `test/`, and add the following content:
```

2024-02-21 14:04 UTC, TalhaMaliktz commented on deploy-github.sh
> +export LISK_DOC_BASE_URL=/lisk-documentation/
Can we please add another similar file, with the following code?

```
export LISK_DOC_BASE_URL=/lisk-documentation/
GIT_USER=TalhaMaliktz yarn deploy
```

2024-02-21 15:14 UTC, Tschakki commented on docs/building-on-lisk/migration-guide.mdx
> +    ```
I removed the snippet and adjusted the text accordingly 👍

2024-02-21 15:18 UTC, Tschakki commented on docs/building-on-lisk/migration-guide.mdx
> +}
done 👍

2024-02-22 09:33 UTC, TalhaMaliktz commented on docs/building-on-lisk/migration-guide.mdx
> +Details: `Unknown UID`
Got some additional log messages as well!
```suggestion
Details: `Pending in queue`
Contract verification status:
Response: `OK`
Details: `Pass - Verified`
Contract successfully verified
```

2024-02-22 09:48 UTC, TalhaMaliktz approved these changes
Thank you! LGTM! 🎉

2024-02-22 10:00 UTC, merged