How to interact with the blockchain with ether.js
LiskHQ/lisk-docs pull request #72
Opened 2024-02-22 12:30 UTC by Tschakki

### What was the problem?

This PR resolves #39 

### How was it tested?

https://liskhq.github.io/lisk-documentation/building-on-lisk/interacting-with-the-blockchain

2024-02-23 07:55 UTC, has5aan commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +    value: ethers.utils.parseEther("1.0")
As per suggested installation using the command `npm install --save ethers` install version 6.11.*. In which the `utils` object have been removed and the functions are defined directly on `ether` object. If we intend to align the documentation on v6 of ethers, would have to replace `ethers.utils.parseEther("1.0")` with `ethers.parseEther("1.0")`.

[Migrating from v5](https://docs.ethers.org/v6/migrating/#migrate-utils)

2024-02-23 08:46 UTC, Tschakki commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +    value: ethers.utils.parseEther("1.0")
Good catch! It's updated now.

2024-02-23 09:00 UTC, has5aan commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +[ethers.js](https://docs.ethers.org/v5/) is a JavaScript library that allows developers to interact with EVM-compatible blockchain networks.
Sorry I missed to point it out with the previous comment, but would we also need to perhaps update the link to `ethers.js` to point to [v6](https://docs.ethers.org/v6/)?

2024-02-23 09:03 UTC, has5aan approved these changes
Besides the open comment, LGTM 🚀 !

2024-02-23 15:39 UTC, TalhaMaliktz requested changes
Please consider the following!

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +---
```suggestion
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +You can connect to Lisk by instantiating a new ethers.js `JsonRpcProvider` object with a RPC URL of the Lisk network:
```suggestion
You can connect to Lisk by instantiating a new ethers.js `JsonRpcProvider` object with an RPC URL of the Lisk network:
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +// read only
```suggestion
// read-only
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +A **Contract** (in ethers.js) is an abstraction which represents a connection to a specific contract on the Lisk Network, so that applications can use it like a normal JavaScript object.
```suggestion
A **Contract** (in ethers.js) is an abstraction that represents a connection to a specific contract on the Lisk Network, so that applications can use it like a normal JavaScript object.
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +For reading and writing to contracts, provide a `Signer` object instead of a `Provider` object:
```suggestion
For reading and writing contracts, provide a `Signer` object instead of a `Provider` object:
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +A **Provider** (in ethers.js) is a class which provides an abstraction for a connection to the Ethereum Network. It provides read-only access to the Blockchain and its status.
```suggestion
A **Provider** (in ethers.js) is a class that provides an abstraction for a connection to the Ethereum Network. It provides read-only access to the Blockchain and its status.
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +A **Signer** is a class which (usually) in some way directly or indirectly has access to a private key, which can sign messages and transactions to authorize the network to charge your account ether
```suggestion
A **Signer** is a class that (usually) in some way directly or indirectly has access to a private key, which can sign messages and transactions to authorize the network to charge your account ether to perform operations.
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +[ethers.js](https://docs.ethers.org/v6/) is a JavaScript library that allows developers to interact with EVM-compatible blockchain networks.
By default, it leads to v6.x so no need to mention it explicitly IMHO. We should let this be maintained automatically.
```suggestion
[ethers.js](https://docs.ethers.org/) is a JavaScript library that allows developers to interact with EVM-compatible blockchain networks.
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +}
```suggestion
async function getLatestBlock() {
    const latestBlock = await provider.getBlockNumber();
    console.log("The latest block's number is:", latestBlock);
}

getLatestBlock();
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +
```suggestion

```text title="Response"                                                                                                                                                                                                 
The latest block's number is: 1687577
```

```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +    value: ethers.parseEther("1.0")
was able to send ETH to my other testnet account
```suggestion
    to: "0x5e1A92F84cA1CE280B3Cb29d79C3368f45b41EBB",
    value: ethers.parseEther("0.01")
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +`PRIVATE_KEY` is the private key of the wallet to use when creating the signer.
```suggestion
`PRIVATE_KEY` is the private key of the account that is to be used when creating the `signer` object.
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +}
```suggestion
async function getHello() {
    const value = await contract.message("0x3C46A11471f285E36EE8d089473ce98269D1b081");
    console.log(value.toString());
}

getHello();
```

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +---
For each of the following sections, please add a collapsible dropdown containing the entire code for that particular example. For example, a snippet for each of the following:

- Reading data from the blockchain
- Writing data to the blockchain
- Interacting with smart contracts

I have shared the `index.js` file containing all the code with you on Slack.

2024-02-23 15:39 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +
```suggestion

The receiving account's balance will increment by `0.01` ETH once the transaction execution is successful.
```

2024-02-26 13:00 UTC, Tschakki commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +---
adjusted the code a little, and added it to the page as suggested, please check :)

2024-02-27 07:20 UTC, TalhaMaliktz requested changes
Looking good already!

2024-02-27 07:20 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +// Send 1 ether to an ens name.
```suggestion
// Send 0.01 ether to a given address.
```

2024-02-27 07:20 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +// Send 1 ether to an ens name.
```suggestion
// Send 0.01 ether to a given address.
```

2024-02-27 07:20 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +const privateKey = 'PRIVATE_KEY';
```suggestion
// Replace PRIVATE_KEY with the private key of your account.
const privateKey = 'PRIVATE_KEY';
```

2024-02-27 07:20 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +For example, you can find the ABI for the `Hello` contract [here](https://sepolia-blockscout.lisk.com/address/0xb18eb752813c2fbedfdf2be6e5e842a85a3b8539?tab=contact_code). Just scroll down to `Contra
```suggestion
For example, you can use the ABI for the [Hello contract](https://sepolia-blockscout.lisk.com/address/0xb18eb752813c2fbedfdf2be6e5e842a85a3b8539?tab=contact_code). Just scroll down to `Contract ABI` and copy the deployed contract's ABI.
```

2024-02-27 07:20 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +const contractAddress = "CONTRACT_ADDRESS"
Since we are referring to an existing working example, it is better to use the actual contract.
```suggestion
// Replace the contractAddress' value with the desired contract.
const contractAddress = "0xb18eb752813c2fbedfdf2be6e5e842a85a3b8539"
```

2024-02-27 09:06 UTC, Tschakki commented on docs/building-on-lisk/interacting-with-the-blockchain.md
> +const contractAddress = "CONTRACT_ADDRESS"
```suggestion
// Replace the contractAddress' value with the desired contract.
const contractAddress = "CONTRACT_ADDRESS"
```

2024-02-27 10:22 UTC, TalhaMaliktz approved these changes
Thank you! LGTM 👍🏼

2024-02-27 10:29 UTC, merged