How to interact with Lisk using viem
LiskHQ/lisk-docs pull request #85
Opened 2024-02-27 13:48 UTC by Tschakki

### What was the problem?

This PR resolves #40 

### How was it tested?

2024-03-04 12:33 UTC, TalhaMaliktz requested changes
Please consider the following!

2024-03-04 12:33 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +  transport: custom(window.ethereum!),
```suggestion
  transport: custom(window.ethereum),
```

2024-03-04 12:33 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +})
This code is only valid if running in the browser, I think. coz AFAIK, the `window` is available on the browser.

2024-03-04 12:33 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +import { EthereumProvider } from '@walletconnect/ethereum-provider'
Would require the following step to be done so I would mention that!

`npm install @walletconnect/ethereum-provider`

2024-03-04 12:33 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +] as const;
This abi is incomplete as it shows syntactical errors on VS CODE! I suggest we use the abi of the hello Contract. I tried it and worked for me and the relevant code did fetch the contract! However, I got an error as described below!

2024-03-04 12:33 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +})
I was able to fetch the contract via the following code!
```suggestion
import { publicClient, walletClientWC } from './client.js'

// 1. Create contract instance
const contract = getContract({
    address: '0xb18eb752813c2fbedfdf2be6e5e842a85a3b8539',
    abi: wagmiAbi,
    // 1a. Insert a single client
    client: publicClient,
    // 1b. Or public and/or wallet clients
    client: { public: publicClient, wallet: walletClientWC }
})
```

2024-03-04 12:33 UTC, TalhaMaliktz commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +console.log(hash);
I get the following error when I try by simply using the `walletClientWC` client to run this file. I use the `node wallet-client.js` command.
```
Error: To use QR modal, please install the @walletconnect/modal package
    at I.initialize (/Users/iamtalha/Lightcurve-Code/L2/interact-blockchain/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:7377)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async I.init (/Users/iamtalha/Lightcurve-Code/L2/interact-blockchain/node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:2743)
    at async file:///Users/iamtalha/Lightcurve-Code/L2/interact-blockchain/viem/wallet-client.js:28:18

Node.js v18.17.0
```

2024-03-04 13:08 UTC, Tschakki commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +console.log(hash);
this example only works together with walletconnect

2024-03-04 13:10 UTC, Tschakki commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +import { EthereumProvider } from '@walletconnect/ethereum-provider'
it is only an example for projects using walletconnect. So they should have this installed already

2024-03-04 13:15 UTC, Tschakki commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +] as const;
it is just an example for an ABI, shortened for readability. People should paste their specific ABI here.

2024-03-04 13:15 UTC, Tschakki commented on docs/building-on-lisk/interacting-with-the-blockchain/viem.mdx
> +})
why change to `walletClientWC`?

2024-03-05 07:52 UTC, TalhaMaliktz approved these changes
Thank you! LGTM 🎉

2024-03-05 08:25 UTC, merged