Update Add Token guides and add bridging guide
LiskHQ/lisk-docs pull request #92
Opened 2024-03-05 13:47 UTC by Tschakki

### What was the problem?

This PR resolves #90

### How was it tested?

https://liskhq.github.io/lisk-documentation/building-on-lisk/add-token-to-lisk

2024-04-09 08:32 UTC, TalhaMaliktz requested changes
Please consider the following.

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +import DocCardList from '@theme/DocCardList';
As we already link to the relevant guides, adding cards also seems redundant. Please remove them.
```suggestion
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +<DocCardList />
```suggestion
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +To deploy a Standard ERC-20 Token to Lisk Sepolia, follow the steps mentioned in the [Add a Standard ERC-20 Token to Lisk](./standard-token.md) guide.
```suggestion
To deploy a Standard ERC-20 Token to Lisk Sepolia, follow the steps mentioned in the [Deploying Your Standard ERC-20 Token to Lisk](./standard-token.md) guide.
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +Tokens created by this factory contract implement the `IOptimismMintableERC20` interface and include basic logic for deposits, transfers, and withdrawals.
```suggestion
Tokens created by this factory contract implement the `IOptimismMintableERC20` interface, including basic logic for deposits, transfers, and withdrawals.
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +## [Deploying a Standard ERC-20 Token](./standard-token.md)
```suggestion
## [Deploying a Standard ERC-20 token](./standard-token.md)
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/index.md
> +To deploy a custom ERC-20 token to Lisk Sepolia, follow the steps mentioned in the [Add a Custom ERC-20 Token to Lisk](./custom-token.mdx) guide.
```suggestion
To deploy a custom ERC-20 token to Lisk Sepolia, follow the steps mentioned in the [Deploying your Custom ERC-20 token to Lisk](./custom-token.mdx) guide.
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> + If you want to bridge existing tokens, you can skip to the tutorial on [Bridging ERC-20 tokens with the Optimism SDK](https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc2
```suggestion
 If you want to bridge existing tokens, you can follow the tutorial on [Bridging ERC-20 tokens with the Optimism SDK](https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc20).
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +# Deploying Your Standard ERC-20 Token to Lisk
```suggestion
# Deploying your Standard ERC-20 token to Lisk
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +If you want to bridge existing tokens, you can skip to the tutorial on [Bridging ERC-20 tokens with the Optimism SDK](https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc20
```suggestion
If you want to bridge existing tokens, you can follow the tutorial on [Bridging ERC-20 tokens with the Optimism SDK](https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc20).
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +All tokens created by the factory implement the `IOptimismMintableERC20` interface and are compatible with the Standard Bridge system.
```suggestion
All tokens created by the factory implement the `IOptimismMintableERC20` interface and are compatible with the Standard Bridge system.
To create an L2 ERC-20 token, do the following:
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +## Create an L2 ERC-20 Token
```suggestion
## Create an L2 ERC-20 token
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +### 2. Add an Lisk Sepolia RPC URL to your environment
```suggestion
### 2. Add the Lisk Sepolia RPC URL to your environment
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +You can now deploy our L2 ERC-20 token using the [`OptimismMintableERC20Factory`](https://github.com/ethereum-optimism/optimism/blob/186e46a47647a51a658e699e9ff047d39444c2de/packages/contracts-bedroc
```suggestion
You can now deploy your L2 ERC-20 token using the [`OptimismMintableERC20Factory`](https://github.com/ethereum-optimism/optimism/blob/186e46a47647a51a658e699e9ff047d39444c2de/packages/contracts-bedrock/contracts/universal/OptimismMintableERC20Factory.sol).
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +Check out the tutorial on [Bridging ERC-20 tokens with the Optimism SDK](https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc20) to learn how to bridge your L1 ERC-20 to L2
Please add a note to all the places where this guide is mentioned.
The note's contents should describe the basic alterations that a reader would need to make, such as RPC URL, L2Chain ID, and any other parameter that you think fits the context.

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +In this tutorial you'll learn how to bridge a standard ERC-20 token from Ethereum to Lisk using the [Standard Bridge system](https://docs.optimism.io/builders/dapp-developers/bridging/standard-bridge
```suggestion
In this tutorial, you'll learn how to bridge a standard ERC-20 token from Ethereum to Lisk using the [Standard Bridge system](https://docs.optimism.io/builders/dapp-developers/bridging/standard-bridge).
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +**This tutorial is for developers who want to bridge a new ERC-20 token to Lisk Sepolia.**
```suggestion
**This tutorial is for developers who want to bridge a new Standard ERC-20 token to Lisk Sepolia.**
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +**This tutorial is for developers who want to bridge a new ERC-20 token to Lisk Mainnet.**
```suggestion
**This tutorial is for developers who want to bridge a new Custom ERC-20 token to Lisk Mainnet.**
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +# Deploying Your Custom ERC-20 Token to Lisk
```suggestion
# Deploying your Custom ERC-20 token to Lisk
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +If you don't need extra functionality like this, consider following the tutorial on [Adding Your Standard ERC-20 Token to Lisk](./standard-token) instead.
```suggestion
If you don't need extra functionality like this, consider following the tutorial on [Deploying your Standard ERC-20 token to Lisk](./standard-token) instead.
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +You can use [this faucet](https://sepoliafaucet.com/) to get ETH on Sepolia.
```suggestion
You can use [ETH Sepolia Faucet](https://sepoliafaucet.com/) to get ETH on Sepolia.
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +You can use [this faucet](https://sepoliafaucet.com) to get ETH on Sepolia.
```suggestion
You can use [ETH Sepolia Faucet](https://sepoliafaucet.com/) to get ETH on Sepolia.
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +Please follow [this guide](../connecting-to-a-wallet.mdx) to connect your wallet to Lisk Sepolia.
```suggestion
Please follow the [How to connect Lisk to a wallet](../connecting-to-a-wallet.mdx) guide, to connect your wallet to Lisk Sepolia.
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/bridge-tokens-to-lisk.mdx
> +title: Bridging ERC-20 tokens to Lisk
Since the guide isn't ready yet! Please exclude it and the related code example files from the PR and stash them somewhere else, maybe in a new branch based on a new issue!

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +The `mint` function allows the bridge to mint tokens to users.
```suggestion
The `mint` function allows the bridge to mint tokens for users.
```

2024-04-09 08:32 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/custom-token.mdx
> +If you've disabled auto-compile, you'll need to manually compile the contract by clicking the "Solidity Compiler" tab (this looks like the letter "S") and press the blue "Compile" button.
```suggestion
If you've disabled auto-compile, you'll need to manually compile the contract by clicking the "Solidity Compiler" tab (this looks like the letter "S") and pressing the blue "Compile" button.
```

2024-04-09 16:33 UTC, Tschakki commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +Check out the tutorial on [Bridging ERC-20 tokens with the Optimism SDK](https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc20) to learn how to bridge your L1 ERC-20 to L2
I thought of adding more info, but  am not sure if we should mention custom parameters... Alternatively, I would probably prefer to completely remove a reference for the guide, as it could not be verified that it is working as described.

2024-04-15 08:15 UTC, TalhaMaliktz commented on docs/building-on-lisk/add-token-to-lisk/standard-token.md
> +Check out the tutorial on [Bridging ERC-20 tokens with the Optimism SDK](https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc20) to learn how to bridge your L1 ERC-20 to L2
I am okay with removing this content!

2024-04-15 13:13 UTC, TalhaMaliktz approved these changes
LGTM 🎉

2024-04-15 14:24 UTC, merged